package document;

import java.util.HashMap;

/**
 * Created by Matteo on 12/11/2015.
 */
@SuppressWarnings("serial")
public class CitiesCodes_C extends HashMap<String, String> {

    public CitiesCodes_C(){
        this.put("C001", "CASSANO");
        this.put("C001", "CASSANO ALBESE");
        this.put("C002", "CASSANO");
        this.put("C002", "CASSANO ALLO IONIO");
        this.put("C003", "CASSANO D'ADDA");
        this.put("C004", "CASSANO MAGNAGO");
        this.put("C005", "CASSANO SPINOLA");
        this.put("C006", "CASSARO");
        this.put("C007", "CASSIGLIO");
        this.put("C008", "CASSINA ALIPRANDI");
        this.put("C009", "CASSINA AMATA");
        this.put("C010", "CASSINA BARAGGIA");
        this.put("C011", "CASSINA DE' BRACCHI");
        this.put("C012", "CASSINA DE' GATTI");
        this.put("C013", "CASSINA DEL PERO");
        this.put("C013", "PERO");
        this.put("C014", "CASSINA DE' PECCHI");
        this.put("C015", "CASSINA FERRARA");
        this.put("C016", "CASSINA MARIAGA");
        this.put("C017", "CASSINA NUOVA");
        this.put("C018", "CASSINA PERTUSELLA");
        this.put("C019", "CASSINA POBBIA");
        this.put("C020", "CASSINA RIZZARDI");
        this.put("C021", "CASSINA SAVINA");
        this.put("C022", "CASSINASCO");
        this.put("C023", "CASSINA TRIULZA");
        this.put("C024", "CASSINA VALSASSINA");
        this.put("C024", "CASSINA VALSASSINA");
        this.put("C025", "CASSINA VERGHERA");
        this.put("C026", "CASCINE");
        this.put("C027", "CASSINE");
        this.put("C028", "CASSINE CALDERARI");
        this.put("C029", "CASCINE GANDINI");
        this.put("C030", "CASSINELLE");
        this.put("C031", "CASSINE SIRIGARI");
        this.put("C032", "CASSINE TOLENTINE");
        this.put("C033", "CASSINETTA DI LUGAGNANO");
        this.put("C033", "LUGAGNANO");
        this.put("C034", "CASSINO");
        this.put("C034", "SAN GERMANO");
        this.put("C035", "CASSINO");
        this.put("C035", "CASSINO PO");
        this.put("C036", "CASSINO D'ALBERI");
        this.put("C037", "CASSOLA");
        this.put("C038", "CASSOLNOVO");
        this.put("C039", "CASTAGNA");
        this.put("C040", "CASTAGNA");
        this.put("C040", "CASTEL CASTAGNA");
        this.put("C041", "CASTAGNARO");
        this.put("C042", "CASTAGNATE OLONA");
        this.put("C043", "CASTAGNE'");
        this.put("C044", "CASTAGNETO CARDUCCI");
        this.put("C044", "CASTAGNETO");
        this.put("C044", "CASTAGNETO MARITTIMO");
        this.put("C045", "CASTAGNETO");
        this.put("C045", "CASTAGNETO PO");
        this.put("C046", "CASTAGNITO");
        this.put("C047", "CASTAGNOLE");
        this.put("C047", "CASTAGNOLE MONFERRATO");
        this.put("C048", "CASTAGNOLE");
        this.put("C048", "CASTAGNOLE PIEMONTE");
        this.put("C049", "CASTAGNOLE DELLE LANZE");
        this.put("C050", "CASTANA");
        this.put("C051", "CASTANIA");
        this.put("C051", "CASTELL'UMBERTO");
        this.put("C052", "CASTANO");
        this.put("C052", "CASTANO PRIMO");
        this.put("C053", "CASTEGGIO");
        this.put("C054", "CASTEGNATE");
        this.put("C054", "CASTEGNATE OLONA");
        this.put("C055", "CASTEGNATO");
        this.put("C056", "CASTEGNERO");
        this.put("C057", "CASTELBALDO");
        this.put("C058", "CASTEL BARONIA");
        this.put("C059", "CASTELBELFORTE");
        this.put("C060", "CASTELBELLINO");
        this.put("C061", "CASTELBELLO * KASTELBELL");
        this.put("C062", "CASTELBELLO-CIARDES * KASTELBELL-TSCHARS");
        this.put("C063", "CASTELBIANCO");
        this.put("C064", "CASTELVERO");
        this.put("C064", "CASTEL BOGLIONE");
        this.put("C065", "CASTEL BOLOGNESE");
        this.put("C066", "CASTELBOTTACCIO");
        this.put("C067", "CASTELBUONO");
        this.put("C068", "CASTEL CELLESI");
        this.put("C069", "CASTELCIVITA");
        this.put("C069", "CASTELLUCCIA");
        this.put("C070", "CASTEL CLEMENTINO");
        this.put("C070", "SERVIGLIANO");
        this.put("C070", "SERVIGLIANO");
        this.put("C071", "CASTEL COLONNA");
        this.put("C071", "TOMBA DI SENIGALLIA");
        this.put("C072", "CASTELCOVATI");
        this.put("C073", "CASTELCUCCO");
        this.put("C074", "CASTELDACCIA");
        this.put("C075", "CASTEL D'AIANO");
        this.put("C076", "CASTEL D'ARIO");
        this.put("C076", "CASTELLARO");
        this.put("C077", "CASTELDARNE * EHRENBURG");
        this.put("C077", "CASTELLO DI PUSTERIA * EHRENBURG");
        this.put("C078", "CASTEL D'AZZANO");
        this.put("C079", "CASTEL DE' CONTI");
        this.put("C079", "CASTELLI CALEPIO");
        this.put("C080", "CASTELDELCI");
        this.put("C080", "CASTELDELCI");
        this.put("C081", "CASTELDELFINO");
        this.put("C082", "CASTEL DEL GIUDICE");
        this.put("C083", "CASTEL DEL MONTE");
        this.put("C084", "CASTEL DEL MONTE UDINESE");
        this.put("C085", "CASTEL DEL PIANO");
        this.put("C086", "CASTEL DEL RIO");
        this.put("C087", "CASTEL DE' RATTI");
        this.put("C088", "CASTEL DI CROCE");
        this.put("C089", "CASTELDIDONE");
        this.put("C090", "CASTEL DI IERI");
        this.put("C091", "CASTEL DI IUDICA");
        this.put("C092", "CASTEL DI LAGO");
        this.put("C093", "CASTEL DI LAMA");
        this.put("C093", "LAMA");
        this.put("C094", "CASTEL DI LUCIO");
        this.put("C094", "CASTELLUCCIO");
        this.put("C095", "CASTELDIMEZZO");
        this.put("C096", "CASTEL DI SANGRO");
        this.put("C097", "CASTEL DI SASSO");
        this.put("C097", "SASSO");
        this.put("C098", "CASTELVECCHIO");
        this.put("C098", "CASTEL DI TORA");
        this.put("C099", "CASTEL DOBRA");
        this.put("C099", "CASTEL DOBRA");
        this.put("C100", "CASTELFIDARDO");
        this.put("C101", "CASTELFIORENTINO");
        this.put("C102", "CASTEL FOCOGNANO");
        this.put("C103", "CASTELFONDO");
        this.put("C104", "CASTELFORTE");
        this.put("C105", "CASTELFRANCI");
        this.put("C106", "CASTELFRANCO");
        this.put("C106", "CASTELFRANCO IN MISCANO");
        this.put("C107", "CASTELFRANCO");
        this.put("C107", "CASTELFRANCO EMILIA");
        this.put("C107", "CASTELFRANCO NELL'EMILIA");
        this.put("C108", "CASTELFRANCO");
        this.put("C108", "CASTROLIBERO");
        this.put("C109", "CASTELFRANCO");
        this.put("C109", "CASTELFRANCO D'OGLIO");
        this.put("C110", "CASTELFRANCO");
        this.put("C110", "CASTEL VITTORIO");
        this.put("C111", "CASTELFRANCO");
        this.put("C111", "CASTELFRANCO VENETO");
        this.put("C112", "CASTELFRANCO DI SOPRA");
        this.put("C113", "CASTELFRANCO DI SOTTO");
        this.put("C114", "CASTEL FRENTANO");
        this.put("C114", "CASTELNUOVO");
        this.put("C114", "CASTEL TRENTANO");
        this.put("C115", "CASTEL GABBIANO");
        this.put("C115", "GABBIANO");
        this.put("C116", "CASTEL GANDOLFO");
        this.put("C117", "CASTEL GIORGIO");
        this.put("C118", "CASTEL GOFFREDO");
        this.put("C119", "CASTELGOMBERTO");
        this.put("C120", "CASTELGRANDE");
        this.put("C121", "CASTEL GUELFO");
        this.put("C121", "CASTEL GUELFO DI BOLOGNA");
        this.put("C122", "CASTELGUGLIELMO");
        this.put("C123", "CASTELGUIDONE");
        this.put("C124", "CASTEL IABLANIZZA");
        this.put("C125", "CASTELLABATE");
        this.put("C126", "CASTELLAFIUME");
        this.put("C127", "CASTELL'ALFERO");
        this.put("C128", "CASTELLALTO");
        this.put("C129", "CASTELLAMARE");
        this.put("C129", "CASTELLAMMARE DI STABIA");
        this.put("C130", "CASTELLAMMARE DEL GOLFO");
        this.put("C131", "CASTEL LAMBRO");
        this.put("C132", "CASTELLAMMARE");
        this.put("C132", "CASTELLAMMARE ADRIATICO");
        this.put("C133", "CASTELLAMONTE");
        this.put("C134", "CASTELLANA");
        this.put("C134", "CASTELLANA GROTTE");
        this.put("C135", "CASTELLANA SICULA");
        this.put("C136", "CASTELLANETA");
        this.put("C137", "CASTELLANIA");
        this.put("C137", "CASTELLANIA");
        this.put("C138", "CASTELLANO");
        this.put("C139", "CASTELLANZA");
        this.put("C140", "CASTELLAR");
        this.put("C141", "CASTELLARANO");
        this.put("C142", "CASTELLAR GUIDOBONO");
        this.put("C143", "CASTELLARO");
        this.put("C144", "CASTELLARO DE' GIORGI");
        this.put("C145", "CASTELL'ARQUATO");
        this.put("C146", "CASTELLAVAZZO");
        this.put("C147", "CASTELL'AZZARA");
        this.put("C148", "CASTELLAZZO");
        this.put("C148", "CASTELLAZZO BORMIDA");
        this.put("C149", "CASTELLAZZO");
        this.put("C149", "CASTELLAZZO NOVARESE");
        this.put("C150", "CASTELLAZZO DE' BARZI");
        this.put("C151", "CASTELLENGO");
        this.put("C152", "CASTELLEONE");
        this.put("C152", "CASTELLEONE DI SUASA");
        this.put("C153", "CASTELLEONE");
        this.put("C154", "CASTELLERO");
        this.put("C155", "CASTELLETTO CERVO");
        this.put("C155", "CASTELLETTO CERVO");
        this.put("C156", "CASTELLETTO D'ERRO");
        this.put("C157", "CASTELLETTO DI BRANDUZZO");
        this.put("C158", "CASTELLETTO D'ORBA");
        this.put("C159", "CASTELLETTO MENDOSIO");
        this.put("C160", "CASTELLETTO MERLI");
        this.put("C161", "CASTELLETTO MOLINA");
        this.put("C162", "CASTELLETTO MONFERRATO");
        this.put("C162", "CASTELLETTO SCAZZOSO");
        this.put("C163", "CASTELLETTO MONFORTE");
        this.put("C164", "CASTELLETTO");
        this.put("C164", "CASTELLETTO PO");
        this.put("C165", "CASTELLETTO STURA");
        this.put("C166", "CASTELLETTO SOPRA TICINO");
        this.put("C167", "CASTELLETTO UZZONE");
        this.put("C168", "CASTELLETTO VILLA");
        this.put("C169", "CASTELLI");
        this.put("C171", "CASTELLI CUSIANI");
        this.put("C171", "CASTELLI CUSIANI");
        this.put("C171", "CASTELLI CUSIANI");
        this.put("C172", "CASTELLINA IN CHIANTI");
        this.put("C173", "CASTELLINALDO");
        this.put("C174", "CASTELLINA MARITTIMA");
        this.put("C175", "CASTELLINO");
        this.put("C175", "CASTELLINO DEL BIFERNO");
        this.put("C176", "CASTELLINO");
        this.put("C176", "CASTELLINO TANARO");
        this.put("C177", "CASTELLUCCIO");
        this.put("C177", "CASTELLUCCIO DI SORA");
        this.put("C177", "CASTELLIRI");
        this.put("C178", "CASTELLO");
        this.put("C178", "CASTELLO D'ALIFE");
        this.put("C178", "CASTELLO DEL MATESE");
        this.put("C179", "CASTELLO");
        this.put("C179", "CASTELLO VALSOLDA");
        this.put("C180", "CASTELLO");
        this.put("C180", "CASTELLO SOPRA LECCO");
        this.put("C181", "CASTELLO");
        this.put("C181", "CASTELLO VALTRAVAGLIA");
        this.put("C181", "CASTELVECCANA");
        this.put("C182", "CASTELLO");
        this.put("C183", "CASTELLO");
        this.put("C183", "CASTEL CONDINO");
        this.put("C184", "CASTELLO D'AGOGNA");
        this.put("C185", "CASTELLO D'ARGILE");
        this.put("C186", "CASTELLO DELL'ACQUA");
        this.put("C187", "CASTELLO DI BRIANZA");
        this.put("C187", "CASTELLO DI BRIANZA");
        this.put("C188", "CASTELLO DI CISTERNA");
        this.put("C188", "CISTERNA");
        this.put("C189", "CASTELLO DI FIEMME");
        this.put("C189", "CASTELLO-MOLINA DI FIEMME");
        this.put("C190", "CASTELLO DI GODEGO");
        this.put("C190", "GODEGO");
        this.put("C191", "CASTELLO DI SERRAVALLE");
        this.put("C191", "SERRAVALLE");
        this.put("C192", "CASTELLONE AL VOLTURNO");
        this.put("C193", "CASTELLONORATO");
        this.put("C194", "CASTELLO TESINO");
        this.put("C195", "CASTELLUCCHIO");
        this.put("C196", "CASTELLUCCIO");
        this.put("C196", "CASTELLUCCIO");
        this.put("C197", "CASTELLUCCIO ACQUABORRANO");
        this.put("C197", "CASTELMAURO");
        this.put("C198", "CASTELLUCCIO DEI SAURI");
        this.put("C199", "CASTELLUCCIO INFERIORE");
        this.put("C200", "CASTELLUCCIO IN VERRINO");
        this.put("C200", "VERRINO");
        this.put("C200", "CASTELVERRINO");
        this.put("C201", "CASTELLUCCIO SUPERIORE");
        this.put("C202", "CASTELLUCCIO VALMAGGIORE");
        this.put("C203", "CASTEL MADAMA");
        this.put("C204", "CASTEL MAGGIORE");
        this.put("C205", "CASTELMAGNO");
        this.put("C206", "CASTELMARTE");
        this.put("C207", "CASTELMASSA");
        this.put("C208", "CASTEL MELLA");
        this.put("C208", "CASTELNUOVO");
        this.put("C209", "CASTELMEZZANO");
        this.put("C210", "CASTEL MOLA");
        this.put("C210", "CASTELMOLA");
        this.put("C210", "MOLA");
        this.put("C211", "CASTEL MORRONE");
        this.put("C211", "MORRONE");
        this.put("C212", "CASTELNOVATE");
        this.put("C213", "CASTELNOVETTO");
        this.put("C214", "CASTELNOVO");
        this.put("C214", "CASTELNUOVO DI CEVA");
        this.put("C215", "CASTELNOVO");
        this.put("C215", "CASTELNOVO BARIANO");
        this.put("C216", "CASTELNOVO");
        this.put("C216", "CASTELNUOVO");
        this.put("C217", "CASTELNOVO DEL FRIULI");
        this.put("C217", "CASTELNOVO");
        this.put("C218", "CASTELNOVO DI SOTTO");
        this.put("C219", "CASTELNOVO NE' MONTI");
        this.put("C220", "CASTELNUOVO");
        this.put("C220", "CASTELNUOVO BAZENTE");
        this.put("C220", "CASTELNUOVO BOZZENTE");
        this.put("C221", "CASTELNUOVO");
        this.put("C221", "CASTELNUOVO CREMASCO");
        this.put("C222", "CASTELNUOVO");
        this.put("C222", "CASTELNUOVO DELLA DAUNIA");
        this.put("C223", "CASTELNUOVO");
        this.put("C223", "CASTELNUOVO PARANO");
        this.put("C224", "CASTELNUOVO");
        this.put("C224", "CASTELNUOVO DI FARFA");
        this.put("C225", "CASTELNUOVO");
        this.put("C225", "CASTELNUOVO DEL GARDA");
        this.put("C225", "CASTELNUOVO DI VERONA");
        this.put("C226", "CASTELNUOVO BELBO");
        this.put("C227", "CASTELNUOVO BERARDENGA");
        this.put("C228", "CASTELNUOVO BOCCA D'ADDA");
        this.put("C228", "CASTELNUOVO BOCCA D'ADDA");
        this.put("C229", "CASTELNUOVO BORMIDA");
        this.put("C230", "CASTELNUOVO CALCEA");
        this.put("C231", "CASTELNUOVO CILENTO");
        this.put("C232", "CASTELNUOVO D'ASTI");
        this.put("C232", "CASTELNUOVO DON BOSCO");
        this.put("C233", "CASTELNUOVO DEL VESCOVO");
        this.put("C234", "CASTELNUOVO DEL ZAPPA");
        this.put("C235", "CASTELNUOVO DI CONZA");
        this.put("C236", "CASTELNUOVO DI GARFAGNANA");
        this.put("C237", "CASTELNUOVO DI PORTO");
        this.put("C238", "CASTELNUOVO D'ISTRIA");
        this.put("C239", "CASTELNUOVO GHERARDI");
        this.put("C240", "CASTELNUOVO MAGRA");
        this.put("C241", "CASTELNUOVO NIGRA");
        this.put("C242", "CASTELNUOVO RANGONE");
        this.put("C243", "CASTELNUOVO SCRIVIA");
        this.put("C244", "CASTELNUOVO VAL DI CECINA");
        this.put("C245", "CASTELPAGANO");
        this.put("C246", "CASTELPETROSO");
        this.put("C247", "CASTELPIZZUTO");
        this.put("C248", "CASTELPLANIO");
        this.put("C249", "CASTELPONZONE");
        this.put("C250", "CASTELPOTO");
        this.put("C251", "CASTELRAIMONDO");
        this.put("C252", "CASTEL RITALDI");
        this.put("C252", "CASTEL RITALDI E SAN GIOVANNI");
        this.put("C253", "CASTEL ROCCHERO");
        this.put("C254", "CASTELROTTO * KASTELRUTH");
        this.put("C255", "CASTEL ROZZONE");
        this.put("C256", "CASTEL RUGGERO");
        this.put("C257", "CASTEL SAN BENEDETTO REATINO");
        this.put("C257", "SAN BENEDETTO");
        this.put("C258", "CASTEL SAN FELICE");
        this.put("C259", "CASTEL SAN GIORGIO");
        this.put("C259", "SAN GIORGIO");
        this.put("C260", "CASTEL SAN GIOVANNI");
        this.put("C260", "CASTEL SAN GIOVANNI DI SPOLETO");
        this.put("C261", "CASTEL SAN GIOVANNI");
        this.put("C262", "CASTEL SAN LORENZO");
        this.put("C263", "CASTEL SAN NICCOLO'");
        this.put("C264", "CASTEL SAN PIETRO");
        this.put("C264", "CASTEL SAN PIETRO MONFERRATO");
        this.put("C265", "CASTEL SAN PIETRO");
        this.put("C265", "CASTEL SAN PIETRO NELL'EMILIA");
        this.put("C265", "CASTEL SAN PIETRO TERME");
        this.put("C266", "CASTEL SAN PIETRO");
        this.put("C266", "CASTEL SAN PIETRO ROMANO");
        this.put("C267", "CASTELSANTANGELO");
        this.put("C267", "CASTELSANTANGELO SUL NERA");
        this.put("C268", "CASTEL SANT'ANGELO");
        this.put("C269", "CASTEL SANT'ELIA");
        this.put("C270", "CASTEL SAN VINCENZO");
        this.put("C271", "CASTELSARACENO");
        this.put("C272", "CASTELSARDO");
        this.put("C273", "CASTELSEPRIO");
        this.put("C274", "CASTELSPINA");
        this.put("C274", "CASTELSPINA");
        this.put("C275", "CASTELTERMINI");
        this.put("C276", "CASTELVECCHIO");
        this.put("C276", "CASTELVECCHIO DI ROCCA BARBENA");
        this.put("C277", "CASTELVECCHIO");
        this.put("C277", "CASTELVECCHIO DI SANTA MARIA MAGGIORE");
        this.put("C278", "CASTELVECCHIO CALVISIO");
        this.put("C279", "CASTELVECCHIO SUBEQUO");
        this.put("C280", "CASTELVENERE");
        this.put("C281", "CASTELVERO");
        this.put("C281", "CASTELVERO D'ASTI");
        this.put("C282", "CASTEL VERRES");
        this.put("C282", "VERRES");
        this.put("C283", "CASTELVETERE");
        this.put("C283", "CASTELVETERE DI CALORE");
        this.put("C283", "CASTELVETERE SUL CALORE");
        this.put("C284", "CASTELVETERE");
        this.put("C284", "CASTELVETERE IN VAL FORTORE");
        this.put("C285", "CASTELVETERE");
        this.put("C285", "CAULONIA");
        this.put("C286", "CASTELVETRANO");
        this.put("C287", "CASTELVETRO");
        this.put("C287", "CASTELVETRO DI MODENA");
        this.put("C288", "CASTELVETRO");
        this.put("C288", "CASTELVETRO PIACENTINO");
        this.put("C289", "CASTEL VISCARDO");
        this.put("C290", "CASTELVISCONTI");
        this.put("C291", "CASTEL VOLTURNO");
        this.put("C292", "CASTENASO");
        this.put("C293", "CASTENEDOLO");
        this.put("C294", "CASTIGLION DORA");
        this.put("C294", "CHATILLON");
        this.put("C295", "CASTIGLIONE");
        this.put("C295", "CASTIGLIONE D'ASTI");
        this.put("C296", "CASTIGLIONE");
        this.put("C296", "CASTIGLIONE DEI PEPOLI");
        this.put("C297", "CASTIGLIONE");
        this.put("C297", "CASTIGLIONE DI SICILIA");
        this.put("C298", "CASTIGLIONE");
        this.put("C298", "CASTIGLIONE MESSER MARINO");
        this.put("C299", "CASTIGLIONE");
        this.put("C299", "CASTIGLIONE D'INTELVI");
        this.put("C300", "CASTIGLIONE");
        this.put("C300", "CASTIGLIONE OLONA");
        this.put("C301", "CASTIGLIONE");
        this.put("C301", "CASTIGLIONE COSENTINO");
        this.put("C302", "CASTIGLIONE");
        this.put("C302", "CASTIGLIONE CHIAVARESE");
        this.put("C303", "CASTIGLIONE DI GARFAGNANA");
        this.put("C303", "CASTIGLIONE");
        this.put("C304", "CASTIGLIONE D'ADDA");
        this.put("C304", "CASTIGLIONE");
        this.put("C304", "CASTIGLIONE D'ADDA");
        this.put("C305", "CASTIGLIONE");
        this.put("C305", "CASTIGLIONE D'OSSOLA");
        this.put("C306", "CASTIGLIONE");
        this.put("C306", "CASTIGLIONE DEL GENOVESI");
        this.put("C306", "CASTIGLIONE DEL GENOVESI");
        this.put("C307", "CASTIGLIONE");
        this.put("C307", "CASTIGLIONE TORINESE");
        this.put("C308", "CASTIGLIONE A CASAURIA");
        this.put("C308", "CASTIGLIONE ALLA PESCARA");
        this.put("C309", "CASTIGLIONE DEL LAGO");
        this.put("C310", "CASTIGLIONE DELLA PESCAIA");
        this.put("C311", "CASTIGLIONE DELLA VALLE");
        this.put("C311", "COLLEDARA");
        this.put("C312", "CASTIGLIONE DELLE STIVIERE");
        this.put("C313", "CASTIGLIONE D'ORCIA");
        this.put("C314", "CASTIGLIONE FALLETTO");
        this.put("C315", "CASTIGLIONE IN TEVERINA");
        this.put("C316", "CASTIGLIONE MESSER RAIMONDO");
        this.put("C317", "CASTIGLIONE TINELLA");
        this.put("C318", "CASTIGLION FIBOCCHI");
        this.put("C318", "DUE COMUNI DI LATERINA");
        this.put("C319", "CASTIGLION FIORENTINO");
        this.put("C320", "CASTIGLION UBERTINI");
        this.put("C321", "CASTIGNANO");
        this.put("C322", "CASTILENTI");
        this.put("C323", "CASTINO");
        this.put("C324", "CASTIONE");
        this.put("C324", "CASTIONE DELLA PRESOLANA");
        this.put("C325", "CASTIONE");
        this.put("C325", "CASTIONE ANDEVENNO");
        this.put("C326", "CASTIONE");
        this.put("C326", "CASTIONE VERONESE");
        this.put("C327", "CASTIONS DI STRADA");
        this.put("C328", "CASTIRAGA DA REGGIO");
        this.put("C329", "CASTIRAGA VIDARDO");
        this.put("C329", "CASTIRAGA VIDARDO");
        this.put("C330", "CASTO");
        this.put("C331", "CASTORANO");
        this.put("C332", "CASTREZZATO");
        this.put("C333", "CASTREZZONE");
        this.put("C334", "CASTRI DI LECCE");
        this.put("C334", "CASTRI FRANCONE");
        this.put("C335", "CASTRIGNANO DE' GRECI");
        this.put("C336", "CASTRIGNANO DEL CAPO");
        this.put("C337", "CASTRO");
        this.put("C338", "CASTRO DEI VOLSCI");
        this.put("C338", "CASTRO");
        this.put("C339", "CASTROCARO E TERRA DEL SOLE");
        this.put("C339", "CASTROCARO TERME E TERRA DEL SOLE");
        this.put("C339", "TERRA DEL SOLE E CASTROCARO");
        this.put("C339", "TERRA DEL SOLE");
        this.put("C340", "PALAZZOLO DI CASTROCIELO");
        this.put("C340", "CASTROCIELO");
        this.put("C340", "PALAZZOLO");
        this.put("C341", "CASTROFILIPPO");
        this.put("C342", "CASTROGIOVANNI");
        this.put("C342", "ENNA");
        this.put("C343", "CASTRONNO");
        this.put("C344", "CASTRONOVO");
        this.put("C344", "CASTRONOVO DI SICILIA");
        this.put("C345", "CASTRONUOVO");
        this.put("C345", "CASTRONUOVO DI SANT'ANDREA");
        this.put("C346", "CASTROPIGNANO");
        this.put("C347", "CASTROREALE");
        this.put("C348", "CASTROREGIO");
        this.put("C349", "CASTROVILLARI");
        this.put("C350", "CATAFORIO");
        this.put("C351", "CATANIA");
        this.put("C352", "CATANZARO");
        this.put("C353", "CATENANUOVA");
        this.put("C354", "CATIGNANO");
        this.put("C355", "CATONA");
        this.put("C356", "CATTOLICA");
        this.put("C356", "CATTOLICA ERACLEA");
        this.put("C357", "CATTOLICA");
        this.put("C357", "CATTOLICA");
        this.put("C358", "CAURIA * GFRILL");
        this.put("C359", "CAUTANO");
        this.put("C360", "CAVA");
        this.put("C360", "CAVA MANARA");
        this.put("C361", "CAVA");
        this.put("C361", "CAVA DE' TIRRENI");
        this.put("C362", "CAVACURTA");
        this.put("C362", "CAVACURTA");
        this.put("C363", "CAVAGLIA'");
        this.put("C363", "CAVAGLIA'");
        this.put("C364", "CAVAGLIETTO");
        this.put("C365", "CAVAGLIO");
        this.put("C365", "CAVAGLIO D'AGOGNA");
        this.put("C366", "CAVAGLIO");
        this.put("C366", "CAVAGLIO SAN DONNINO");
        this.put("C367", "CAVAGLIO-SPOCCIA");
        this.put("C367", "CAVAGLIO-SPOCCIA");
        this.put("C368", "CAVAGNERA");
        this.put("C369", "CAVAGNOLO");
        this.put("C370", "CAVAION");
        this.put("C370", "CAVAION VERONESE");
        this.put("C371", "CAVAIONE");
        this.put("C372", "CAVALESE");
        this.put("C373", "CAVALLARA");
        this.put("C374", "CAVALLASCA");
        this.put("C375", "CAVALLERLEONE");
        this.put("C376", "CAVALLERMAGGIORE");
        this.put("C377", "CAVALLINO");
        this.put("C378", "CAVALLIRIO");
        this.put("C379", "CAVANDONE");
        this.put("C380", "CAVARENO");
        this.put("C381", "CAVARGNA");
        this.put("C382", "CAVARIA ED UNITI");
        this.put("C382", "CAVARIA CON PREMEZZO");
        this.put("C382", "ORAGO");
        this.put("C383", "CAVARZERE");
        this.put("C384", "CAVASO");
        this.put("C384", "CAVASO DEL TOMBA");
        this.put("C385", "CAVASSO NUOVO");
        this.put("C385", "CAVASSO");
        this.put("C386", "CAVA TIGOZZI");
        this.put("C387", "CAVATORE");
        this.put("C388", "CAVAZUCCHERINA");
        this.put("C388", "JESOLO");
        this.put("C389", "CAVAZZO");
        this.put("C389", "CAVAZZO CARNICO");
        this.put("C390", "CAVE");
        this.put("C391", "CAVE AUREMIANE");
        this.put("C392", "CAVEDAGO");
        this.put("C393", "CAVEDINE");
        this.put("C394", "CAVENAGO D'ADDA");
        this.put("C394", "CAVENAGO");
        this.put("C394", "CAVENAGO D'ADDA");
        this.put("C395", "CAVENAGO");
        this.put("C395", "CAVENAGO DI BRIANZA");
        this.put("C395", "CAVENAGO DI BRIANZA");
        this.put("C396", "CAVERNAGO");
        this.put("C397", "CAVERSACCIO");
        this.put("C398", "CAVEZZO");
        this.put("C399", "CAVIAGA");
        this.put("C400", "CAVIZZANA");
        this.put("C401", "CAVOLANO * GOEFLAN");
        this.put("C401", "COVELANO * GOEFLAN");
        this.put("C402", "CAVONA");
        this.put("C403", "CAVORETTO");
        this.put("C404", "CAVOUR");
        this.put("C405", "CAVRIAGO");
        this.put("C406", "CAVRIANA");
        this.put("C407", "CAVRIGLIA");
        this.put("C408", "CAZZAGO");
        this.put("C408", "CAZZAGO SAN MARTINO");
        this.put("C409", "CAZZAGO");
        this.put("C409", "CAZZAGO BRABBIA");
        this.put("C410", "CAZZANO");
        this.put("C410", "CAZZANO SANT'ANDREA");
        this.put("C410", "CAZZANO SANT'ANDREA");
        this.put("C411", "CAZZANO");
        this.put("C411", "CAZZANO BEFANA");
        this.put("C411", "CAZZANO BESANA");
        this.put("C412", "CAZZANO");
        this.put("C412", "CAZZANO DI TRAMIGNA");
        this.put("C413", "CECCANO");
        this.put("C414", "CECIMA");
        this.put("C414", "CECIMA");
        this.put("C415", "CECINA");
        this.put("C415", "FITTO DI CECINA");
        this.put("C416", "CECONICO");
        this.put("C417", "CEDEGOLO");
        this.put("C417", "GREVO");
        this.put("C418", "CEDRASCO");
        this.put("C419", "CEDRATE");
        this.put("C420", "CEFALA' DIANA");
        this.put("C421", "CEFALU'");
        this.put("C422", "CEGGIA");
        this.put("C423", "CEGLIE");
        this.put("C423", "CEGLIE DEL CAMPO");
        this.put("C424", "CEGLIE");
        this.put("C424", "CEGLIE MESSAPICO");
        this.put("C424", "CEGLIE MESSAPICA");
        this.put("C425", "CEGLIE");
        this.put("C426", "CELANO");
        this.put("C427", "CELENTINO");
        this.put("C428", "CELENZA");
        this.put("C428", "CELENZA SUL FRIGNO");
        this.put("C428", "CELENZA SUL TRIGNO");
        this.put("C429", "CELENZA");
        this.put("C429", "CELENZA VALFORTORE");
        this.put("C430", "CELICO");
        this.put("C431", "CELINA");
        this.put("C432", "CELLA");
        this.put("C432", "CELLA MONTE");
        this.put("C433", "CELLA");
        this.put("C434", "CELLA");
        this.put("C434", "CELLA DI BOBBIO");
        this.put("C434", "CELLA DI BOBBIO");
        this.put("C435", "CELLA DATI");
        this.put("C435", "PUGNOLO");
        this.put("C436", "CELLAMARE");
        this.put("C437", "CELLARA");
        this.put("C438", "CELLARENGO");
        this.put("C439", "CELLATICA");
        this.put("C440", "CELLE");
        this.put("C440", "CELLE ENOMONDO");
        this.put("C441", "CELLE");
        this.put("C441", "CELLE DI MACRA");
        this.put("C442", "CELLE");
        this.put("C442", "CELLE SAN VITO");
        this.put("C443", "CELLE");
        this.put("C443", "CELLE LIGURE");
        this.put("C444", "CELLE");
        this.put("C444", "CELLE DI BULGHERIA");
        this.put("C445", "CELLEDIZZO");
        this.put("C446", "CELLENO");
        this.put("C447", "CELLERE");
        this.put("C448", "CELLINO");
        this.put("C448", "CELLINO SAN MARCO");
        this.put("C449", "CELLINO");
        this.put("C449", "CELLINO ATTANASIO");
        this.put("C450", "CELLIO");
        this.put("C451", "CELPENCHIO");
        this.put("C452", "CEMBRA");
        this.put("C453", "CENADI");
        this.put("C454", "CENATE");
        this.put("C455", "CENATE D'ARGON");
        this.put("C455", "CENATE D'ARGON");
        this.put("C455", "CENATE D'ARGON");
        this.put("C456", "CENATE DI SOPRA");
        this.put("C456", "CENATE SOPRA");
        this.put("C457", "CENATE DI SOTTO");
        this.put("C457", "CENATE SOTTO");
        this.put("C458", "CENCENIGHE");
        this.put("C458", "CENCENIGHE AGORDINO");
        this.put("C459", "CENE");
        this.put("C460", "CENEDA");
        this.put("C461", "CENESELLI");
        this.put("C462", "CENESI");
        this.put("C463", "CENGIO");
        this.put("C464", "CENGLES * TSCHENGLS");
        this.put("C465", "CENOVA");
        this.put("C466", "CENTALLO");
        this.put("C467", "CENTA SAN NICOLO'");
        this.put("C468", "CENTEMERO");
        this.put("C469", "CENTO");
        this.put("C470", "CENTOLA");
        this.put("C471", "CENTORBI");
        this.put("C471", "CENTURIPE");
        this.put("C471", "CENTURUPI");
        this.put("C472", "CENTRACHE");
        this.put("C473", "CENTRISOLA");
        this.put("C473", "CENTRISOLA");
        this.put("C474", "CEPAGATTI");
        this.put("C475", "CEPINO");
        this.put("C476", "CEPPALONI");
        this.put("C477", "CEPPEDA");
        this.put("C478", "CEPPO MORELLI");
        this.put("C478", "CEPPO MORELLI");
        this.put("C479", "CEPRANO");
        this.put("C480", "CERAMI");
        this.put("C481", "CERANESI");
        this.put("C482", "CERANO");
        this.put("C482", "CERANO D'INTELVI");
        this.put("C483", "CERANO");
        this.put("C484", "CERANOVA");
        this.put("C484", "CERANOVA");
        this.put("C485", "CERASO");
        this.put("C486", "CERCEMAGGIORE");
        this.put("C487", "CERCENASCO");
        this.put("C488", "CERCEPICCOLA");
        this.put("C489", "CERCHIARA");
        this.put("C489", "CERCHIARA DI CALABRIA");
        this.put("C490", "CERCHIARA");
        this.put("C490", "CERCHIARA DI SABINA");
        this.put("C491", "CERCHIATE");
        this.put("C492", "CERCHIO");
        this.put("C493", "CERCINO");
        this.put("C494", "CERCIVENTO");
        this.put("C495", "CERCOLA");
        this.put("C495", "MASSA DI SOMMA");
        this.put("C496", "CERDA");
        this.put("C497", "CERE");
        this.put("C497", "CERES");
        this.put("C498", "CEREA");
        this.put("C499", "CEREDA");
        this.put("C500", "CEREGNANO");
        this.put("C501", "CERENZIA");
        this.put("C501", "CERENZIA");
        this.put("C502", "CERESARA");
        this.put("C503", "CERESETO");
        this.put("C504", "CERESOLE");
        this.put("C504", "CERESOLE ALBA");
        this.put("C505", "CERESOLE");
        this.put("C505", "CERESOLE REALE");
        this.put("C506", "CERETE");
        this.put("C507", "CERETTO");
        this.put("C507", "CERETTO GRUE");
        this.put("C507", "CERRETO GRUE");
        this.put("C508", "CERETTO LOMELLINA");
        this.put("C508", "CERRETTO");
        this.put("C508", "CERRETTO LOMELLINO");
        this.put("C509", "CERGNAGO");
        this.put("C510", "CERIALE");
        this.put("C511", "CERIANA");
        this.put("C512", "CERIANO");
        this.put("C512", "CERIANO LAGHETTO");
        this.put("C512", "CERIANO LAGHETTO");
        this.put("C513", "CERIGNALE");
        this.put("C514", "CERIGNOLA");
        this.put("C515", "CERISANO");
        this.put("C516", "CERMENATE");
        this.put("C517", "CERMIGNANO");
        this.put("C518", "CERNETO");
        this.put("C518", "CERRETO");
        this.put("C518", "CERRETO LAZIALE");
        this.put("C518", "MONTERUFO");
        this.put("C519", "CERNIZZA GORIZIANA");
        this.put("C520", "CERNOBBIO");
        this.put("C521", "CERNUSCO LOMBARDONE");
        this.put("C521", "CERNUSCO LOMBARDONE");
        this.put("C521", "CERNUSCO LOMBARDONE");
        this.put("C522", "CERNUSCO MONTEVECCHIA");
        this.put("C523", "CERNUSCO ASINARIO");
        this.put("C523", "CERNUSCO SUL NAVIGLIO");
        this.put("C524", "CERRETO");
        this.put("C524", "CERRETO D'ESI");
        this.put("C525", "CERRETO");
        this.put("C525", "CERRETO SANNITA");
        this.put("C526", "CERRETO CASTELLO");
        this.put("C526", "CERRETO");
        this.put("C526", "CERRETO CASTELLO");
        this.put("C527", "CERRETO");
        this.put("C527", "CERRETO DI SPOLETO");
        this.put("C528", "CERRETTO");
        this.put("C528", "CERRETO D'ASTI");
        this.put("C529", "CERRETO GUIDI");
        this.put("C530", "CERRETTO");
        this.put("C530", "CERRETTO LANGHE");
        this.put("C531", "CERRINA");
        this.put("C532", "CERRIONE");
        this.put("C532", "CERRIONE");
        this.put("C533", "CERRO");
        this.put("C533", "CERRO TANARO");
        this.put("C534", "CERRO");
        this.put("C534", "CERRO AL VOLTURNO");
        this.put("C535", "CERRO");
        this.put("C535", "CERRO LAGO MAGGIORE");
        this.put("C536", "CERRO");
        this.put("C536", "CERRO AL LAMBRO");
        this.put("C537", "CERRO");
        this.put("C537", "CERRO MAGGIORE");
        this.put("C538", "CERRO");
        this.put("C538", "CERRO VERONESE");
        this.put("C539", "CERSOSIMO");
        this.put("C540", "CERTALDO");
        this.put("C541", "CERTOSA DI PAVIA");
        this.put("C542", "CERVA");
        this.put("C543", "CERVARA");
        this.put("C543", "CERVARA DI ROMA");
        this.put("C544", "CERVARESE SANTA CROCE");
        this.put("C545", "CERVARO");
        this.put("C546", "CERVAROLO");
        this.put("C547", "CERVASCA");
        this.put("C548", "CERVATTO");
        this.put("C549", "CERVENO");
        this.put("C550", "CERVERE");
        this.put("C551", "CERVESINA");
        this.put("C552", "CERVETERI");
        this.put("C553", "CERVIA");
        this.put("C554", "CERVICATI");
        this.put("C555", "CERVIGNANO D'ADDA");
        this.put("C555", "CERVIGNANO");
        this.put("C555", "CERVIGNANO D'ADDA");
        this.put("C556", "CERVIGNANO");
        this.put("C556", "CERVIGNANO DEL FRIULI");
        this.put("C557", "CERVINARA");
        this.put("C558", "CERVINO");
        this.put("C559", "CERVO");
        this.put("C560", "CERZETO");
        this.put("C561", "CESA");
        this.put("C562", "CESANA");
        this.put("C562", "LENTIAI");
        this.put("C563", "CESANA");
        this.put("C563", "CESANA BRIANZA");
        this.put("C563", "CESANA DI BRIANZA");
        this.put("C563", "CESANA BRIANZA");
        this.put("C564", "CESANA");
        this.put("C564", "CESANA TORINESE");
        this.put("C565", "CESANO BOSCONE");
        this.put("C566", "CESANO MADERNO");
        this.put("C566", "CESANO MADERNO");
        this.put("C567", "CESARA");
        this.put("C567", "CESARA");
        this.put("C568", "CESARO'");
        this.put("C569", "CESATE");
        this.put("C570", "CESCLANS");
        this.put("C571", "CESELLI");
        this.put("C572", "CESELLO BRIANZA");
        this.put("C572", "CESELLO BRIANZA");
        this.put("C573", "CESENA");
        this.put("C574", "CESENATICO");
        this.put("C575", "CESI");
        this.put("C576", "CESINALI");
        this.put("C577", "CESIO");
        this.put("C577", "CESIOMAGGIORE");
        this.put("C578", "CESIO");
        this.put("C579", "CESNOLA");
        this.put("C580", "CESSALTO");
        this.put("C581", "CESSANITI");
        this.put("C581", "CESSANITI");
        this.put("C582", "CESSAPALOMBO");
        this.put("C583", "CESSOLE");
        this.put("C584", "CETARA");
        this.put("C585", "CETO");
        this.put("C586", "CETO-CERVENO");
        this.put("C586", "CETO-CERVENO");
        this.put("C587", "CETONA");
        this.put("C588", "CETRARO");
        this.put("C589", "CEVA");
        this.put("C590", "CEVES * TSCHOEFS");
        this.put("C590", "ZEDES * TSCHOEFS");
        this.put("C591", "CEVO");
        this.put("C592", "CHALLANT");
        this.put("C592", "CHALLANT SAINT ANSELME ET CHALLANT SAINT VICTOR");
        this.put("C592", "CHALLANT SAINT ANSELME ET CHALLANT SAINT VICTOR");
        this.put("C592", "VILLA SANT'ANSELMO");
        this.put("C593", "CHALLAND-SAINT-ANSELME");
        this.put("C593", "CHALLANT SAINT ANSELME");
        this.put("C594", "CHALLAND-SAINT-VICTOR");
        this.put("C594", "CHALLANT SAINT VICTOR");
        this.put("C595", "CHAMBAVE");
        this.put("C595", "CIAMBAVE");
        this.put("C596", "CHAMPDEPRAZ");
        this.put("C597", "CHAMPLAS DU COL");
        this.put("C598", "CHARVENSOD");
        this.put("C599", "CHERASCO");
        this.put("C600", "CHEREMULE");
        this.put("C601", "CHERSO");
        this.put("C602", "CHIABRANO");
        this.put("C603", "CHIAIANO");
        this.put("C603", "CHIAIANO ED UNITI");
        this.put("C604", "CHIALAMBERTO");
        this.put("C605", "CHIAMPO");
        this.put("C606", "CHIANCHE");
        this.put("C607", "CHIANCHETELLE");
        this.put("C608", "CHIANCIANO");
        this.put("C608", "CHIANCIANO TERME");
        this.put("C609", "CHIANNI");
        this.put("C610", "CHIANOC");
        this.put("C610", "CHIANOCCO");
        this.put("C611", "CHIAPOVANO");
        this.put("C612", "CHIARAMONTE GULFI");
        this.put("C612", "CHIARAMONTE");
        this.put("C613", "CHIARAMONTI");
        this.put("C614", "CHIARANO");
        this.put("C615", "CHIARAVALLE");
        this.put("C616", "CHIARAVALLE");
        this.put("C616", "CHIARAVALLE CENTRALE");
        this.put("C617", "CHIARAVALLE");
        this.put("C617", "CHIARAVALLE MILANESE");
        this.put("C618", "CHIARI");
        this.put("C619", "CHIAROMONTE");
        this.put("C620", "CHIAUCI");
        this.put("C621", "CHIAVARI");
        this.put("C622", "CHIAVAZZA");
        this.put("C622", "CHIAVAZZA");
        this.put("C623", "CHIAVENNA");
        this.put("C624", "CHIAVERANO");
        this.put("C625", "CHIENES * KIENS");
        this.put("C626", "CHIENIS");
        this.put("C627", "CHIERI");
        this.put("C628", "CHIESA");
        this.put("C628", "CHIESA IN VALMALENCO");
        this.put("C629", "CHIESANOVA");
        this.put("C629", "CHIESANUOVA");
        this.put("C630", "CHIES D'ALPAGO");
        this.put("C631", "CHIESINA UZZANESE");
        this.put("C632", "CHIETI");
        this.put("C633", "CHIEUTI");
        this.put("C634", "CHIEVE");
        this.put("C635", "CHIGNOLO");
        this.put("C635", "CHIGNOLO D'ISOLA");
        this.put("C636", "CHIGNOLO");
        this.put("C636", "CHIGNOLO VERBANO");
        this.put("C637", "CHIGNOLO");
        this.put("C637", "CHIGNOLO PO");
        this.put("C638", "CHIOGGIA");
        this.put("C639", "CHIOMONTE");
        this.put("C640", "CHIONS");
        this.put("C641", "CHIOPRIS VISCONE");
        this.put("C642", "CHIOSI D'ADDA VIGADORE");
        this.put("C643", "CHIOSI DI PORTA D'ADDA");
        this.put("C644", "CHIOSI PORTA CREMONESE");
        this.put("C645", "CHIOSI PORTA REGALE");
        this.put("C646", "CHIOSI UNITI CON BOTTEDO");
        this.put("C647", "CHIRIGNAGO");
        this.put("C648", "CHITIGNANO");
        this.put("C649", "CHIUDUNO");
        this.put("C650", "CHIUPPANO");
        this.put("C651", "CHIURO");
        this.put("C652", "CHIUSA * KLAUSEN");
        this.put("C652", "CHIUSA ALL'ISARCO * KLAUSEN");
        this.put("C653", "CHIUSA");
        this.put("C653", "CHIUSA DI PESIO");
        this.put("C654", "CHIUSA");
        this.put("C654", "CHIUSA SCLAFANI");
        this.put("C655", "CHIUSA");
        this.put("C655", "CHIUSA DI SAN MICHELE");
        this.put("C656", "CHIUSA");
        this.put("C656", "CHIUSAFORTE");
        this.put("C657", "CHIUSANICO");
        this.put("C658", "CHIUSANO");
        this.put("C658", "CHIUSANO D'ASTI");
        this.put("C659", "CHIUSANO");
        this.put("C659", "CHIUSANO DI SAN DOMENICO");
        this.put("C660", "CHIUSAVECCHIA");
        this.put("C661", "CHIUSDINO");
        this.put("C662", "CHIUSI");
        this.put("C663", "CHIUSI DELLA VERNA");
        this.put("C663", "CHIUSI IN CASENTINO");
        this.put("C664", "CHIUSO");
        this.put("C665", "CHIVASSO");
        this.put("C666", "CHIZZOLA");
        this.put("C667", "CIAGO");
        this.put("C668", "CIANCIANA");
        this.put("C669", "CIANO");
        this.put("C669", "CIANO D'ENZA");
        this.put("C669", "CANOSSA");
        this.put("C670", "CIANO-NOGARE'");
        this.put("C670", "CROCETTA DEL MONTELLO");
        this.put("C670", "CROCETTA TREVIGIANA");
        this.put("C671", "CIARDES * TSCHARS");
        this.put("C671", "CIARS * TSCHARS");
        this.put("C672", "CIBIANA");
        this.put("C672", "CIBIANA DI CADORE");
        this.put("C673", "CICAGNA");
        this.put("C674", "CICALA");
        this.put("C675", "CICCIANO");
        this.put("C676", "CICERALE");
        this.put("C677", "CICILIANO");
        this.put("C678", "CICOGNOLO");
        this.put("C679", "CICONIO");
        this.put("C680", "CIGLIANO");
        this.put("C681", "CIGLIE'");
        this.put("C682", "CIGNANO");
        this.put("C683", "CIGNONE");
        this.put("C684", "CIGOGNOLA");
        this.put("C685", "CIGOLE");
        this.put("C686", "CILAVEGNA");
        this.put("C687", "CILIVERGHE");
        this.put("C688", "CIMA");
        this.put("C689", "CIMADOLMO");
        this.put("C690", "CIMAMULERA");
        this.put("C691", "CIMBERGO");
        this.put("C692", "CIMBERGO-PASPARDO");
        this.put("C692", "CIMBERGO-PASPARDO");
        this.put("C693", "CIMBRO");
        this.put("C694", "CIMEGO");
        this.put("C695", "CIMINA'");
        this.put("C696", "CIMINNA");
        this.put("C697", "CIMITILE");
        this.put("C698", "CIMMO");
        this.put("C698", "TAVERNOLE-CIMMO");
        this.put("C698", "TAVERNOLE SUL MELLA");
        this.put("C699", "CIMOLAIS");
        this.put("C700", "CIMONE");
        this.put("C701", "CINAGLIO");
        this.put("C702", "CINETO ROMANO");
        this.put("C702", "SCARPA");
        this.put("C703", "CINGIA DE' BOTTI");
        this.put("C704", "CINGOLI");
        this.put("C705", "CINIGIANO");
        this.put("C706", "CINISELLO");
        this.put("C707", "CINISELLO BALSAMO");
        this.put("C708", "CINISI");
        this.put("C709", "CINO");
        this.put("C710", "CINQUEFRONDI");
        this.put("C711", "CINTANO");
        this.put("C712", "CINTE TESINO");
        this.put("C713", "CINTO");
        this.put("C713", "CINTO EUGANEO");
        this.put("C714", "CINTO");
        this.put("C714", "CINTO CAOMAGGIORE");
        this.put("C715", "CINZANO");
        this.put("C716", "CIORLANO");
        this.put("C717", "CIPOLLINA");
        this.put("C717", "SANTA MARIA");
        this.put("C717", "SANTA MARIA DEL CEDRO");
        this.put("C718", "CIPRESSA");
        this.put("C719", "CIRCELLO");
        this.put("C720", "CIRCHINA");
        this.put("C721", "CIREGGIO");
        this.put("C722", "CIRIE'");
        this.put("C723", "CIRIGLIANO");
        this.put("C724", "CIRIMIDO");
        this.put("C725", "CIRO'");
        this.put("C725", "CIRO'");
        this.put("C726", "CIRO' MARINA");
        this.put("C726", "CIRO' MARINA");
        this.put("C727", "CIS");
        this.put("C728", "CISANO");
        this.put("C728", "CISANO BERGAMASCO");
        this.put("C729", "CISANO");
        this.put("C729", "CISANO SUL NEVA");
        this.put("C730", "CISERANO");
        this.put("C731", "CISERIIS");
        this.put("C732", "CISLAGO");
        this.put("C733", "CISLIANO");
        this.put("C734", "CISMON");
        this.put("C734", "CISMON DEL GRAPPA");
        this.put("C735", "CISON");
        this.put("C735", "CISON DI VALMARINO");
        this.put("C736", "CISORE");
        this.put("C737", "CISSICO * ISSING");
        this.put("C737", "ISSENGO * ISSING");
        this.put("C738", "CISSONE");
        this.put("C739", "CISTERNA");
        this.put("C739", "CISTERNA D'ASTI");
        this.put("C740", "CISTERNA DI LATINA");
        this.put("C740", "CISTERNA DI LITTORIA");
        this.put("C740", "CISTERNA DI ROMA");
        this.put("C740", "CISTERNA");
        this.put("C741", "CISTERNINO");
        this.put("C742", "CITERNA");
        this.put("C743", "CITTADELLA");
        this.put("C744", "CITTA' DELLA PIEVE");
        this.put("C745", "CITTA' DI CASTELLO");
        this.put("C746", "CITTADUCALE");
        this.put("C747", "CITTANOVA");
        this.put("C748", "CITTANOVA D'ISTRIA");
        this.put("C749", "CITTAREALE");
        this.put("C750", "CITTA' SANT'ANGELO");
        this.put("C751", "CITTIGLIO");
        this.put("C752", "CIVATE");
        this.put("C752", "CIVATE");
        this.put("C753", "CIVELLO");
        this.put("C754", "CIVENNA");
        this.put("C755", "CIVEZZA");
        this.put("C756", "CIVEZZANO");
        this.put("C757", "CIVIASCO");
        this.put("C758", "CIVIDALE DEL FRIULI");
        this.put("C759", "CIVIDATE");
        this.put("C759", "CIVIDATE AL PIANO");
        this.put("C760", "CIVIDATE CAMUNO");
        this.put("C760", "CIVITADE");
        this.put("C760", "CIVITADE ALPINO");
        this.put("C761", "CIVIDATE-MALEGNO");
        this.put("C761", "CIVIDATE-MALEGNO");
        this.put("C762", "CIVIGLIO");
        this.put("C763", "CIVITA");
        this.put("C764", "CIVITACAMPOMARANO");
        this.put("C765", "CIVITA CASTELLANA");
        this.put("C766", "CIVITA D'ANTINO");
        this.put("C767", "CIVITA LAVINIA");
        this.put("C767", "LANUVIO");
        this.put("C768", "CIVITALUPARELLA");
        this.put("C769", "CIVITANOVA");
        this.put("C769", "CIVITANOVA DEL SANNIO");
        this.put("C770", "CIVITANOVA");
        this.put("C770", "CIVITANOVA MARCHE");
        this.put("C771", "CIVITAQUANA");
        this.put("C772", "CIVITAVECCHIA");
        this.put("C772", "DURONIA");
        this.put("C773", "CIVITAVECCHIA");
        this.put("C774", "CIVITELLA");
        this.put("C774", "CIVITELLA IN VAL DI CHIANA");
        this.put("C775", "CIVITELLA");
        this.put("C775", "CIVITELLA LICINIO");
        this.put("C776", "CIVITELLA");
        this.put("C776", "CIVITELLA MESSER RAIMONDO");
        this.put("C777", "CIVITELLA");
        this.put("C777", "CIVITELLA DI ROMAGNA");
        this.put("C778", "CIVITELLA ALFEDENA");
        this.put("C779", "CIVITELLA CASANOVA");
        this.put("C780", "CIVITELLA D'AGLIANO");
        this.put("C781", "CIVITELLA DEL TRONTO");
        this.put("C782", "CIVITELLA PAGANICO");
        this.put("C782", "PAGANICO");
        this.put("C782", "PARI");
        this.put("C783", "CIVITELLA ROVETO");
        this.put("C784", "CIVITELLA SAN PAOLO");
        this.put("C785", "CIVO");
        this.put("C786", "CIZZAGO");
        this.put("C787", "CLAINO CON OSTENO");
        this.put("C788", "CLANA");
        this.put("C789", "CLANEZZO");
        this.put("C789", "UBIALE CLANEZZO");
        this.put("C790", "CLAUT");
        this.put("C791", "CLAUZETTO");
        this.put("C792", "CLAVESANA");
        this.put("C793", "CLAVIERE");
        this.put("C793", "CLAVIERES");
        this.put("C794", "CLES");
        this.put("C795", "CLETO");
        this.put("C795", "PIETRAMALA");
        this.put("C796", "CLIVIO");
        this.put("C797", "CLOZ");
        this.put("C798", "CLUSANE");
        this.put("C798", "CLUSANE SUL LAGO");
        this.put("C799", "CLUSIO * SCHLEIS");
        this.put("C800", "CLUSONE");
        this.put("C801", "COASSOLO");
        this.put("C801", "COASSOLO TORINESE");
        this.put("C802", "COAZZANO");
        this.put("C803", "COAZZE");
        this.put("C804", "COAZZOLO");
        this.put("C805", "COBBIA");
        this.put("C806", "COCCAGLIO");
        this.put("C807", "COCCONATO");
        this.put("C808", "COCCONITO");
        this.put("C809", "COCQUIO");
        this.put("C810", "COCQUIO-TREVISAGO");
        this.put("C811", "COCULLO");
        this.put("C812", "CODEVIGO");
        this.put("C813", "CODEVILLA");
        this.put("C814", "CODIGORO");
        this.put("C815", "CODOGNE'");
        this.put("C816", "CODOGNO");
        this.put("C816", "CODOGNO");
        this.put("C817", "CODROIPO");
        this.put("C818", "CODRONGIANUS");
        this.put("C819", "COGGIOLA");
        this.put("C819", "COGGIOLA");
        this.put("C820", "COGLIATE");
        this.put("C820", "COGLIATE");
        this.put("C821", "COGNE");
        this.put("C822", "COGNOLA");
        this.put("C823", "COGOLETO");
        this.put("C824", "COGOLLO");
        this.put("C824", "COGOLLO DEL CENGIO");
        this.put("C825", "COGOLO");
        this.put("C826", "COGORNO");
        this.put("C827", "COIMO");
        this.put("C828", "COIRO");
        this.put("C828", "COIROMONTE");
        this.put("C829", "COLAZZA");
        this.put("C830", "COLBORDOLO");
        this.put("C831", "COLCAVAGNO");
        this.put("C832", "COLCIAGO");
        this.put("C833", "COLDERANO * GOLDRAIN");
        this.put("C833", "COLDRANO * GOLDRAIN");
        this.put("C834", "COLDIRODI");
        this.put("C834", "COLLA");
        this.put("C835", "COLERE");
        this.put("C836", "COLFELICE");
        this.put("C837", "COLFOSCO * COLFUSCHG");
        this.put("C838", "COLI");
        this.put("C839", "COLICO");
        this.put("C839", "COLICO");
        this.put("C840", "COLLAGNA");
        this.put("C840", "CULAGNA");
        this.put("C841", "COLLALTO");
        this.put("C841", "COLLALTO SABINO");
        this.put("C842", "COLLALTO");
        this.put("C842", "COLLALTO DELLA SOIMA");
        this.put("C842", "SEGNACCO");
        this.put("C844", "COLLARMELE");
        this.put("C845", "COLLAZZONE");
        this.put("C846", "COLLE");
        this.put("C846", "COLLE SANNITA");
        this.put("C847", "COLLE");
        this.put("C847", "COLLE DI VAL D'ELSA");
        this.put("C848", "COLLE");
        this.put("C848", "COLLE UMBERTO");
        this.put("C849", "COLLEBACCARO");
        this.put("C850", "COLLEBEATO");
        this.put("C851", "COLLE BRIANZA");
        this.put("C851", "COLLE BRIANZA");
        this.put("C852", "COLLECCHIO");
        this.put("C853", "COLLECORVINO");
        this.put("C854", "COLLE D'ANCHISE");
        this.put("C855", "COLLEDIMACINE");
        this.put("C856", "COLLEDIMEZZO");
        this.put("C857", "COLLE DI TORA");
        this.put("C858", "COLLEFERRO");
        this.put("C859", "COLLEGIOVE");
        this.put("C860", "COLLEGNO");
        this.put("C861", "COLLE IN CASIES * PICHL IN GSIES");
        this.put("C862", "COLLELONGO");
        this.put("C863", "COLLEMANCIO");
        this.put("C864", "COLLEPARDO");
        this.put("C865", "COLLEPASSO");
        this.put("C866", "COLLEPIETRO");
        this.put("C867", "COLLERETTO CASTELNUOVO");
        this.put("C868", "COLLERETTO GIACOSA");
        this.put("C868", "COLLERETTO PARELLA");
        this.put("C869", "COLLESALVETTI");
        this.put("C870", "COLLE SAN MAGNO");
        this.put("C871", "COLLESANO");
        this.put("C872", "COLLE SANTA LUCIA");
        this.put("C873", "COLLESCIPOLI");
        this.put("C874", "COLLESTATTE");
        this.put("C875", "COLLETORTO");
        this.put("C876", "COLLEVECCHIO");
        this.put("C877", "COLLI");
        this.put("C877", "COLLI DEL TRONTO");
        this.put("C878", "COLLI");
        this.put("C878", "COLLI A VOLTURNO");
        this.put("C879", "COLLIANO");
        this.put("C880", "COLLI DI LABRO");
        this.put("C880", "COLLI SUL VELINO");
        this.put("C881", "COLLI IN PUSTERIA * PICHLERN");
        this.put("C882", "FORRU");
        this.put("C882", "COLLINAS");
        this.put("C882", "COLLINAS");
        this.put("C883", "COLLIO");
        this.put("C884", "COLLOBIANO");
        this.put("C885", "COLLOREDO DI MONTE ALBANO");
        this.put("C886", "COLMURANO");
        this.put("C887", "COLNAGO");
        this.put("C888", "COLOBRARO");
        this.put("C889", "COLOGNA");
        this.put("C890", "COLOGNA");
        this.put("C890", "COLOGNA VENETA");
        this.put("C891", "COLOGNA CAVAZZO");
        this.put("C892", "COLOGNA");
        this.put("C893", "COLOGNE");
        this.put("C894", "COLOGNO");
        this.put("C894", "COLOGNO AL SERIO");
        this.put("C895", "COLOGNO");
        this.put("C895", "COLOGNO MONZESE");
        this.put("C896", "COLOGNOLA");
        this.put("C896", "COLOGNOLA DEL PIANO");
        this.put("C897", "COLOGNOLA");
        this.put("C897", "COLOGNOLA AI COLLI");
        this.put("C898", "COLOMBARO");
        this.put("C899", "COLOMBAROLO");
        this.put("C900", "COLONNA");
        this.put("C901", "COLONNELLA");
        this.put("C902", "COLONNO");
        this.put("C903", "COLORINA");
        this.put("C904", "COLORNO");
        this.put("C905", "COLOSIMI");
        this.put("C906", "COL SAN GIOVANNI");
        this.put("C907", "COLSANO * GALSAUN");
        this.put("C908", "COLTURANO");
        this.put("C909", "COLZANO");
        this.put("C910", "COLZATE");
        this.put("C911", "COMABBIO");
        this.put("C912", "COMACCHIO");
        this.put("C913", "COMAIRANO");
        this.put("C914", "COMANO");
        this.put("C915", "COMANO");
        this.put("C916", "COMASINE");
        this.put("C917", "COMAZZO");
        this.put("C917", "COMAZZO");
        this.put("C918", "COMEGLIANS");
        this.put("C919", "COMELICO INFERIORE");
        this.put("C919", "SANTO STEFANO DI CADORE");
        this.put("C920", "COMELICO SUPERIORE");
        this.put("C921", "COMENO");
        this.put("C922", "COMERIO");
        this.put("C923", "COMERO");
        this.put("C924", "COMEZZANO");
        this.put("C925", "COMEZZANO-CIZZAGO");
        this.put("C926", "COMIGNAGO");
        this.put("C927", "COMISO");
        this.put("C928", "COMITINI");
        this.put("C929", "COMIZIANO");
        this.put("C929", "CUMIGNANO");
        this.put("C929", "CUMIGNANO E GALLO DI NOLA");
        this.put("C930", "COMMESSAGGIO");
        this.put("C931", "COMMEZZADURA");
        this.put("C932", "COMNAGO");
        this.put("C933", "COMO");
        this.put("C934", "COMPIANO");
        this.put("C935", "COMUNANZA");
        this.put("C935", "COMUNANZA DEL LITTORIO");
        this.put("C936", "COMUNE DELLA VALSOLDA");
        this.put("C936", "VALSOLDA");
        this.put("C937", "COMUN NUOVO");
        this.put("C938", "CONA");
        this.put("C939", "CONCA");
        this.put("C939", "CONCA DELLA CAMPANIA");
        this.put("C940", "CONCA");
        this.put("C940", "CONCA DEI MARINI");
        this.put("C940", "CONCA MARINI");
        this.put("C941", "CONCA CASALE");
        this.put("C942", "CONCADIRAME");
        this.put("C943", "CONCAMARISE");
        this.put("C944", "CONCEI");
        this.put("C945", "CONCENEDO");
        this.put("C946", "CONCERVIANO");
        this.put("C947", "CONCESA");
        this.put("C948", "CONCESIO");
        this.put("C949", "CONCO");
        this.put("C950", "CONCORDIA");
        this.put("C950", "CONCORDIA SAGITARIA");
        this.put("C950", "CONCORDIA SAGITTARIA");
        this.put("C951", "CONCORDIA SULLA SECCHIA");
        this.put("C952", "CONCOREZZO");
        this.put("C952", "CONCOREZZO");
        this.put("C953", "CONDINO");
        this.put("C954", "CONDOFURI");
        this.put("C955", "CONDOVE");
        this.put("C956", "CONDRO'");
        this.put("C957", "CONEGLIANO");
        this.put("C958", "CONFIENZA");
        this.put("C959", "CONFIGNI");
        this.put("C960", "CONFLENTI");
        this.put("C961", "CONIO");
        this.put("C962", "CONIOLO");
        this.put("C963", "CONSELICE");
        this.put("C964", "CONSELVE");
        this.put("C965", "CONSIGLIO DI RUMO");
        this.put("C966", "CONSONNO");
        this.put("C967", "CONTARINA");
        this.put("C968", "CONTESSA");
        this.put("C968", "CONTESSA ENTELLINA");
        this.put("C969", "CONTIGLIANO");
        this.put("C970", "CONTRA");
        this.put("C971", "CONTRADA");
        this.put("C972", "CONTROGUERRA");
        this.put("C973", "CONTRONE");
        this.put("C974", "CONTURSI TERME");
        this.put("C975", "CONVERSANO");
        this.put("C976", "CONZA DELLA CAMPANIA");
        this.put("C977", "CONZANO");
        this.put("C978", "COPERTINO");
        this.put("C979", "COPIANO");
        this.put("C980", "COPPARO");
        this.put("C981", "COPRENO");
        this.put("C982", "CORANA");
        this.put("C983", "CORATO");
        this.put("C984", "CORBARA");
        this.put("C985", "CORBESATE");
        this.put("C986", "CORBETTA");
        this.put("C987", "CORBOLA");
        this.put("C988", "CORCHIANO");
        this.put("C989", "CORCIAGO");
        this.put("C990", "CORCIANO");
        this.put("C991", "CORDENONS");
        this.put("C992", "CORDIGNANO");
        this.put("C993", "CORDOVADO");
        this.put("C994", "COREDO");
        this.put("C995", "COREGLIA");
        this.put("C995", "COREGLIA DI FONTANABUONA");
        this.put("C995", "COREGLIA LIGURE");
        this.put("C996", "COREGLIA");
        this.put("C996", "COREGLIA ANTELMINELLI");
        this.put("C997", "CORENNO");
        this.put("C997", "CORENNO PLINIO");
        this.put("C998", "CORENO");
        this.put("C998", "CORENO AUSONIO");
        this.put("C999", "CORFINIO");
        this.put("C999", "PENTIMA");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
