package document;

import java.util.HashMap;

/**
 * Created by Matteo on 12/11/2015.
 */
@SuppressWarnings("serial")
public class CitiesCodes_H extends HashMap<String, String> {

    public CitiesCodes_H(){
        this.put("H001", "PRATO");
        this.put("H001", "PRATO SESIA");
        this.put("H002", "PRATO");
        this.put("H002", "PRATO CARNICO");
        this.put("H003", "PRATO ALLA DRAVA * WINNEBACH");
        this.put("H004", "PRATO ALLO STELVIO * PRAD AM STILFSERJOCH");
        this.put("H004", "PRATO IN VENOSTA * PRAD");
        this.put("H004", "PRATO VENOSTA * PRAD");
        this.put("H006", "PRATOLA");
        this.put("H006", "PRATOLA SERRA");
        this.put("H007", "PRATOLA");
        this.put("H007", "PRATOLA PELIGNA");
        this.put("H008", "PRATOVECCHIO");
        this.put("H009", "PRATOVECCHIO-STIA");
        this.put("H009", "PRATOVECCHIO-STIA");
        this.put("H010", "PRAVISDOMINI");
        this.put("H011", "PRAZZO");
        this.put("H012", "PRE'");
        this.put("H013", "PRECACORE");
        this.put("H013", "SAMO");
        this.put("H014", "PRECENICCO");
        this.put("H015", "PRECI");
        this.put("H016", "PRECOTTO");
        this.put("H017", "PREDAPPIO");
        this.put("H017", "PREDAPPIO NUOVA");
        this.put("H018", "PREDAZZO");
        this.put("H019", "PREDOI * PRETTAU");
        this.put("H019", "SAN VALENTINO IN PREDOI * PRETTAU");
        this.put("H020", "PREDORE");
        this.put("H021", "PREDOSA");
        this.put("H022", "PREGANZIOL");
        this.put("H023", "PREGASINA");
        this.put("H024", "PREGHENA");
        this.put("H025", "PREGLIA");
        this.put("H026", "PREGNANA");
        this.put("H026", "PREGNANA MILANESE");
        this.put("H027", "PRELA'");
        this.put("H028", "PREMANA");
        this.put("H028", "PREMANA");
        this.put("H029", "PREMARIACCO");
        this.put("H030", "PREMENO");
        this.put("H030", "PREMENO");
        this.put("H031", "PREMENUGO");
        this.put("H032", "PREMEZZO");
        this.put("H033", "PREMIA");
        this.put("H033", "PREMIA");
        this.put("H034", "PREMILCUORE");
        this.put("H035", "PREMIONE");
        this.put("H036", "PREMOLO");
        this.put("H036", "PREMOLO");
        this.put("H037", "PREMOSELLO");
        this.put("H037", "PREMOSELLO-CHIOVENDA");
        this.put("H037", "PREMOSELLO-CHIOVENDA");
        this.put("H038", "PREONE");
        this.put("H039", "PREORE");
        this.put("H040", "PREPOTTO");
        this.put("H041", "PREQUARTERA");
        this.put("H042", "PRE'-SAINT-DIDIER");
        this.put("H042", "SAN DESIDERIO TERME");
        this.put("H043", "PRESEGLIE");
        this.put("H044", "PRESEGNO");
        this.put("H045", "PRESENZANO");
        this.put("H046", "PRESEZZO");
        this.put("H047", "PRESICCE");
        this.put("H048", "PRESSANA");
        this.put("H049", "PRESSON");
        this.put("H050", "PRESTINE");
        this.put("H051", "PRESTINONE");
        this.put("H052", "PRETORO");
        this.put("H053", "PRETURO");
        this.put("H054", "PREVACINA");
        this.put("H055", "PREVALLE");
        this.put("H056", "PREZZA");
        this.put("H057", "PREZZO");
        this.put("H058", "PRIACCO");
        this.put("H059", "PRIERO");
        this.put("H060", "PRIERO-MONTEZEMOLO");
        this.put("H060", "PRIERO-MONTEZEMOLO");
        this.put("H060", "PRIERO-MONTEZEMOLO");
        this.put("H061", "PRIGNANO");
        this.put("H061", "PRIGNANO SULLA SECCHIA");
        this.put("H062", "PRIGNANO");
        this.put("H062", "PRIGNANO CILENTO");
        this.put("H062", "PRIGNANO CILENTO");
        this.put("H063", "PRIMALUNA");
        this.put("H063", "PRIMALUNA");
        this.put("H064", "PRIMANO");
        this.put("H065", "PRIMEGLIO SCHIERANO");
        this.put("H066", "PRIMIERO");
        this.put("H066", "PRIMIERO");
        this.put("H066", "PRIMIERO");
        this.put("H066", "PRIMIERO");
        this.put("H066", "PRIMIERO");
        this.put("H067", "PRIO'");
        this.put("H068", "PRIOCCA");
        this.put("H069", "PRIOLA");
        this.put("H070", "PRIZZI");
        this.put("H071", "PROCENO");
        this.put("H072", "PROCIDA");
        this.put("H073", "PROPATA");
        this.put("H074", "PROSERPIO");
        this.put("H075", "PROSPIANO");
        this.put("H076", "PROSSEDI");
        this.put("H077", "PROVAGLIO");
        this.put("H077", "PROVAGLIO VAL SABBIA");
        this.put("H078", "PROVAGLIO D'ISEO");
        this.put("H079", "PROVAGLIO SOPRA");
        this.put("H080", "PROVAGLIO SOTTO");
        this.put("H081", "PROVES * PROVEIS");
        this.put("H082", "PROVEZZE");
        this.put("H083", "PROVVIDENTI");
        this.put("H084", "PRUN");
        this.put("H084", "PRUN");
        this.put("H085", "PRUNETTO");
        this.put("H086", "PUEGNAGO");
        this.put("H086", "PUEGNAGO SUL GARDA");
        this.put("H087", "PUGLIANELLO");
        this.put("H088", "PULA");
        this.put("H089", "PULFERO");
        this.put("H090", "PULSANO");
        this.put("H091", "PUMENENGO");
        this.put("H092", "PUOS D'ALPAGO");
        this.put("H093", "PURIA");
        this.put("H094", "PUSIANO");
        this.put("H095", "PUTIFIGARI");
        this.put("H096", "PUTIGNANO");
        this.put("H097", "QUADRELLE");
        this.put("H098", "QUADRI");
        this.put("H099", "QUAGLIETTA");
        this.put("H100", "QUAGLIUZZO");
        this.put("H101", "QUALIANO");
        this.put("H102", "QUARANTI");
        this.put("H103", "QUAREGNA");
        this.put("H103", "QUAREGNA");
        this.put("H104", "QUARGNENTO");
        this.put("H105", "QUARNA");
        this.put("H105", "QUARNA");
        this.put("H106", "QUARNA SOPRA");
        this.put("H106", "QUARNA SOPRA");
        this.put("H107", "QUARNA SOTTO");
        this.put("H107", "QUARNA SOTTO");
        this.put("H108", "QUARONA");
        this.put("H109", "QUARRATA");
        this.put("H109", "TIZZANA");
        this.put("H110", "QUART");
        this.put("H110", "QUARTO PRAETORIA");
        this.put("H111", "QUARTI");
        this.put("H112", "QUARTIANO");
        this.put("H113", "QUARTO");
        this.put("H113", "QUARTO ASTESE");
        this.put("H114", "QUARTO");
        this.put("H115", "QUARTO AL MARE");
        this.put("H115", "QUARTO DEI MILLE");
        this.put("H116", "QUARTO CAGNINO");
        this.put("H117", "QUARTO D'ALTINO");
        this.put("H117", "SAN MICHELE DEL QUARTO");
        this.put("H118", "QUARTU");
        this.put("H118", "QUARTU SANT'ELENA");
        this.put("H119", "QUARTUCCIU");
        this.put("H119", "QUARTUCCIU");
        this.put("H120", "QUASSOLO");
        this.put("H121", "QUATTORDIO");
        this.put("H122", "QUATTRO CASTELLA");
        this.put("H123", "QUATTROVILLE");
        this.put("H123", "VIRGILIO");
        this.put("H124", "QUERO");
        this.put("H125", "QUETTA");
        this.put("H126", "QUILIANO");
        this.put("H127", "QUINCINETTO");
        this.put("H128", "QUINDICI");
        this.put("H129", "QUINGENTOLE");
        this.put("H130", "QUINTANO");
        this.put("H130", "QUINTANO");
        this.put("H131", "QUINTO");
        this.put("H131", "QUINTO DI TREVISO");
        this.put("H132", "QUINTO");
        this.put("H132", "QUINTO VERCELLESE");
        this.put("H133", "QUINTO");
        this.put("H133", "QUINTO DI VALPANTENA");
        this.put("H134", "QUINTO");
        this.put("H134", "QUINTO VICENTINO");
        this.put("H135", "QUINTO AL MARE");
        this.put("H136", "QUINTODECIMO");
        this.put("H137", "QUINTO ROMANO");
        this.put("H138", "QUINTOSOLE");
        this.put("H139", "QUINZANELLO");
        this.put("H140", "QUINZANO");
        this.put("H140", "QUINZANO D'OGLIO");
        this.put("H141", "QUINZANO");
        this.put("H141", "QUINZANO SAN PIETRO");
        this.put("H142", "QUINZANO");
        this.put("H142", "QUINZANO VERONESE");
        this.put("H143", "QUISTELLO");
        this.put("H144", "QUISTRO");
        this.put("H145", "QUITTENGO");
        this.put("H145", "QUITTENGO");
        this.put("H146", "RABBI");
        this.put("H147", "RACALE");
        this.put("H148", "RACALMUTO");
        this.put("H149", "RACCOLANA");
        this.put("H150", "RACCONIGI");
        this.put("H151", "RACCUJA");
        this.put("H152", "RACIGNES * RATSCHINGS");
        this.put("H152", "RACINES * RATSCHINGS");
        this.put("H153", "RADDA");
        this.put("H153", "RADDA IN CHIANTI");
        this.put("H154", "RADDUSA");
        this.put("H155", "RADICENA");
        this.put("H156", "RADICOFANI");
        this.put("H157", "RADICONDOLI");
        this.put("H158", "RAFFA");
        this.put("H159", "RAFFADALI");
        this.put("H160", "RAGGIOLO");
        this.put("H161", "RAGOGNA");
        this.put("H162", "RAGOLI");
        this.put("H163", "RAGUSA");
        this.put("H164", "RAGUSA IBLA");
        this.put("H164", "RAGUSA INFERIORE");
        this.put("H165", "RAIANO");
        this.put("H165", "RUVIANO");
        this.put("H166", "RAIANO");
        this.put("H167", "RAISSA * REISCHACH");
        this.put("H167", "RISCONE * REISCHACH");
        this.put("H168", "RAMACCA");
        this.put("H169", "RAMO DI PALO");
        this.put("H170", "RAMPONIO");
        this.put("H171", "RAMPONIO VERNA");
        this.put("H172", "RANCIO");
        this.put("H172", "RANCIO DI LECCO");
        this.put("H173", "RANCIO");
        this.put("H173", "RANCIO VALCUVIA");
        this.put("H174", "RANCO");
        this.put("H175", "RANDAZZO");
        this.put("H176", "RANICA");
        this.put("H177", "RANZANICO");
        this.put("H178", "RANZIANO");
        this.put("H179", "RANZI PIETRA");
        this.put("H180", "RANZO");
        this.put("H181", "RANZO");
        this.put("H182", "RAPAGNANO");
        this.put("H182", "RAPAGNANO");
        this.put("H183", "RAPALLO");
        this.put("H184", "RAPINO");
        this.put("H185", "RAPOLANO");
        this.put("H185", "RAPOLANO TERME");
        this.put("H186", "RAPOLLA");
        this.put("H187", "RAPONE");
        this.put("H188", "RASSA");
        this.put("H189", "RASUN-ANTERSELVA * RASEN-ANTHOLZ");
        this.put("H190", "RASUN DI SOPRA * OBERRASEN");
        this.put("H191", "RASUN DI SOTTO * NIEDERRASEN");
        this.put("H192", "RASURA");
        this.put("H193", "RATECEVO IN MONTE");
        this.put("H194", "RAVANUSA");
        this.put("H195", "RAVARINO");
        this.put("H196", "RAVASCLETTO");
        this.put("H197", "RAVELLINO");
        this.put("H197", "TEGNONE");
        this.put("H198", "RAVELLO");
        this.put("H199", "RAVENNA");
        this.put("H200", "RAVEO");
        this.put("H201", "RAVINA");
        this.put("H202", "RAVISCANINA");
        this.put("H203", "RE");
        this.put("H203", "RE");
        this.put("H204", "REA");
        this.put("H204", "REA");
        this.put("H205", "REALMONTE");
        this.put("H206", "REANA");
        this.put("H206", "REANA DEL ROIALE");
        this.put("H207", "REANO");
        this.put("H208", "REBBIO");
        this.put("H209", "REBECCU");
        this.put("H210", "RECALE");
        this.put("H211", "RECANATI");
        this.put("H212", "RECCO");
        this.put("H213", "RECETTO");
        this.put("H214", "RECOARO");
        this.put("H214", "RECOARO TERME");
        this.put("H215", "RECORFANO");
        this.put("H216", "REDAVALLE");
        this.put("H217", "REDONA");
        this.put("H218", "REDONDESCO");
        this.put("H219", "REFRANCORE");
        this.put("H220", "REFRONTOLO");
        this.put("H221", "REGALBUTO");
        this.put("H222", "REGGELLO");
        this.put("H223", "REGGIO");
        this.put("H223", "REGGIO NELL'EMILIA");
        this.put("H224", "REGGIO DI CALABRIA");
        this.put("H225", "REGGIOLO");
        this.put("H226", "REGINA FITTAREZZA");
        this.put("H227", "REINO");
        this.put("H228", "REITANO");
        this.put("H229", "REMANZACCO");
        this.put("H230", "REMEDELLO");
        this.put("H231", "REMEDELLO SOPRA");
        this.put("H232", "REMEDELLO SOTTO");
        this.put("H233", "RENATE");
        this.put("H233", "RENATE");
        this.put("H234", "RENATE VEDUGGIO");
        this.put("H234", "RENATE VEDUGGIO");
        this.put("H235", "RENDE");
        this.put("H236", "RENON * RITTEN");
        this.put("H237", "REPNO");
        this.put("H237", "RUPINGRANDE");
        this.put("H238", "RESANA");
        this.put("H239", "RESCALDA");
        this.put("H240", "RESCALDINA");
        this.put("H241", "RESIA * RESCHEN");
        this.put("H241", "RESIA ALL'ADIGE * RESCHEN");
        this.put("H242", "RESIA");
        this.put("H243", "ERCOLANO");
        this.put("H243", "RESINA");
        this.put("H244", "RESIUTTA");
        this.put("H245", "RESUTTANO");
        this.put("H246", "RETORBIDO");
        this.put("H247", "REVELLO");
        this.put("H248", "REVERE");
        this.put("H249", "FOLAS-REVIAN");
        this.put("H250", "REVIGLIASCO");
        this.put("H250", "REVIGLIASCO D'ASTI");
        this.put("H251", "REVIGLIASCO");
        this.put("H251", "REVIGLIASCO TORINESE");
        this.put("H252", "REVINE");
        this.put("H253", "REVINE LAGO");
        this.put("H254", "REVO'");
        this.put("H255", "REZZAGO");
        this.put("H256", "REZZATO");
        this.put("H257", "REZZO");
        this.put("H258", "REZZOAGLIO");
        this.put("H259", "REZZO CAVARGNA");
        this.put("H259", "VAL REZZO");
        this.put("H260", "REZZONICO");
        this.put("H261", "RHEMES");
        this.put("H261", "RHEMES");
        this.put("H261", "RHEMES");
        this.put("H261", "VAL DI REMA");
        this.put("H262", "RHEMES-NOTRE-DAME");
        this.put("H263", "RHEMES-SAINT-GEORGES");
        this.put("H264", "RHO");
        this.put("H265", "RIACE");
        this.put("H266", "RIALTO");
        this.put("H267", "RIANO");
        this.put("H268", "RIARDO");
        this.put("H269", "RIBERA");
        this.put("H270", "RIBORDONE");
        this.put("H271", "RICADI");
        this.put("H271", "RICADI");
        this.put("H272", "RICALDONE");
        this.put("H273", "RICCIA");
        this.put("H274", "RICCIONE");
        this.put("H274", "RICCIONE");
        this.put("H275", "RICCO'");
        this.put("H275", "RICCO' DEL GOLFO DI SPEZIA");
        this.put("H276", "RICENGO");
        this.put("H277", "RICIGLIANO");
        this.put("H278", "RICLARETTO");
        this.put("H279", "RIDANNA * RIDNAUN");
        this.put("H280", "RIESE");
        this.put("H280", "RIESE PIO X");
        this.put("H281", "RIESI");
        this.put("H282", "RIETI");
        this.put("H283", "RIFEMBERGO");
        this.put("H284", "RIFIANO * RIFFIAN");
        this.put("H285", "RIFREDDO");
        this.put("H286", "RIGNANO");
        this.put("H286", "RIGNANO SULL'ARNO");
        this.put("H287", "RIGNANO");
        this.put("H287", "RIGNANO GARGANICO");
        this.put("H288", "RIGNANO");
        this.put("H288", "RIGNANO FLAMINIO");
        this.put("H289", "RIGOLATO");
        this.put("H290", "RIGOSA");
        this.put("H291", "RIMA SAN GIUSEPPE");
        this.put("H292", "RIMASCO");
        this.put("H293", "RIMELLA");
        this.put("H294", "RIMINI");
        this.put("H294", "RIMINI");
        this.put("H295", "RINA * WELSCHELLEN");
        this.put("H295", "RINNA * WELSCHELLEN");
        this.put("H296", "RINCO");
        this.put("H297", "RIO");
        this.put("H297", "RIO NELL'ELBA");
        this.put("H298", "RIO");
        this.put("H298", "RIO SALICETO");
        this.put("H299", "RIO DI PUSTERIA * MUEHLBACH");
        this.put("H300", "RIOFREDDO");
        this.put("H301", "RIOLA");
        this.put("H301", "RIOLA SARDO");
        this.put("H301", "RIOLA SARDO");
        this.put("H302", "RIOLO");
        this.put("H302", "RIOLO DEI BAGNI");
        this.put("H302", "RIOLO TERME");
        this.put("H303", "RIOLUNATO");
        this.put("H304", "RIOMAGGIORE");
        this.put("H305", "RIO MARINA");
        this.put("H306", "RIO MOLINO * MUEHLBACH");
        this.put("H307", "RIONERO");
        this.put("H307", "RIONERO IN VOLTURE");
        this.put("H307", "RIONERO IN VULTURE");
        this.put("H308", "RIONERO");
        this.put("H308", "RIONERO SANNITICO");
        this.put("H309", "RIOZZO");
        this.put("H310", "RIPABERARDA");
        this.put("H311", "RIPABOTTONI");
        this.put("H312", "RIPACANDIDA");
        this.put("H313", "RIPALIMOSANI");
        this.put("H314", "RIPALTA ARPINA");
        this.put("H315", "RIPALTA CREMASCA");
        this.put("H316", "RIPALTA GUERINA");
        this.put("H317", "RIPALTA NUOVA");
        this.put("H317", "RIPALTA NUOVA");
        this.put("H318", "RIPALTA VECCHIA");
        this.put("H319", "RIPARBELLA");
        this.put("H320", "RIPA TEATINA");
        this.put("H321", "RIPATRANSONE");
        this.put("H322", "RIPE");
        this.put("H323", "RIPE SAN GINESIO");
        this.put("H324", "RIPI");
        this.put("H325", "RIPOSTO");
        this.put("H326", "RITTANA");
        this.put("H327", "RIVA");
        this.put("H327", "RIVAMONTE");
        this.put("H327", "RIVAMONTE AGORDINO");
        this.put("H328", "RIVA");
        this.put("H328", "RIVA LIGURE");
        this.put("H329", "RIVA");
        this.put("H329", "RIVA VALDOBBIA");
        this.put("H330", "RIVA");
        this.put("H330", "RIVA DEL GARDA");
        this.put("H331", "RIVA DI SOLTO");
        this.put("H332", "RIVA DI TURES * REIN");
        this.put("H332", "RIVA IN VALLE * REIN");
        this.put("H333", "RIVALBA");
        this.put("H334", "RIVALTA");
        this.put("H334", "RIVALTA BORMIDA");
        this.put("H335", "RIVALTA");
        this.put("H335", "RIVALTA DI TORINO");
        this.put("H336", "RIVANAZZANO");
        this.put("H336", "RIVANAZZANO TERME");
        this.put("H337", "RIVA PRESSO CHIERI");
        this.put("H338", "RIVARA");
        this.put("H339", "RIVAROLO");
        this.put("H339", "RIVAROLO LIGURE");
        this.put("H340", "RIVAROLO");
        this.put("H340", "RIVAROLO CANAVESE");
        this.put("H341", "RIVAROLO CREMONESE");
        this.put("H341", "RIVAROLO DEL RE ED UNITI");
        this.put("H342", "RIVAROLO FUORI");
        this.put("H342", "RIVAROLO MANTOVANO");
        this.put("H343", "RIVARONE");
        this.put("H344", "RIVAROSSA");
        this.put("H345", "RIVA SANTO STEFANO");
        this.put("H345", "RIVA SANTO STEFANO");
        this.put("H346", "RIVE");
        this.put("H347", "RIVE D'ARCANO");
        this.put("H348", "RIVELLO");
        this.put("H349", "RIVERA");
        this.put("H350", "RIVERGARO");
        this.put("H351", "RIVIERA D'ADDA");
        this.put("H352", "RIVIGNANO");
        this.put("H353", "RIVISONDOLI");
        this.put("H354", "RIVODUTRI");
        this.put("H355", "RIVOLI");
        this.put("H356", "RIVOLI");
        this.put("H356", "RIVOLI VERONESE");
        this.put("H357", "RIVOLTA");
        this.put("H357", "RIVOLTA D'ADDA");
        this.put("H358", "RIVOLTELLA SUL GARDA");
        this.put("H359", "RIZZICONI");
        this.put("H360", "RO");
        this.put("H361", "ROANA");
        this.put("H362", "ROASCHIA");
        this.put("H363", "ROASCIO");
        this.put("H364", "ROASENDA");
        this.put("H364", "ROVASENDA");
        this.put("H365", "ROASIO");
        this.put("H366", "ROATTO");
        this.put("H367", "ROBASSOMERO");
        this.put("H368", "ROBBIANO");
        this.put("H369", "ROBBIO");
        this.put("H370", "ROBECCHETTO");
        this.put("H371", "ROBECCHETTO CON INDUNO");
        this.put("H372", "ROBECCO");
        this.put("H372", "ROBECCO D'OGLIO");
        this.put("H373", "ROBECCO");
        this.put("H373", "ROBECCO SUL NAVIGLIO");
        this.put("H374", "ROBECCO");
        this.put("H374", "ROBECCO LODIGIANO");
        this.put("H375", "ROBECCO");
        this.put("H375", "ROBECCO PAVESE");
        this.put("H376", "ROBELLA");
        this.put("H377", "ROBILANTE");
        this.put("H378", "ROBURENT");
        this.put("H378", "ROBURENTO");
        this.put("H379", "ROCCA");
        this.put("H379", "ROCCA D'AGORDO");
        this.put("H379", "ROCCA PIETORE");
        this.put("H380", "ROCCA");
        this.put("H380", "ROCCAVALDINA");
        this.put("H381", "ROCCA");
        this.put("H381", "ROCCA PIETRA");
        this.put("H382", "ROCCABASCERANA");
        this.put("H383", "ROCCABERNARDA");
        this.put("H383", "ROCCABERNARDA");
        this.put("H384", "ROCCABIANCA");
        this.put("H385", "ROCCABRUNA");
        this.put("H386", "ROCCA CANAVESE");
        this.put("H386", "ROCCA DI CORIO");
        this.put("H387", "ROCCA CANTERANO");
        this.put("H388", "ROCCACARAMANICO");
        this.put("H389", "ROCCACASALE");
        this.put("H390", "ROCCACASAREGNANA");
        this.put("H390", "ROCCAFLUVIONE");
        this.put("H391", "ROCCA CIGLIE'");
        this.put("H392", "ROCCA D'ARAZZO");
        this.put("H393", "ROCCADARCE");
        this.put("H394", "ROCCADASPIDE");
        this.put("H395", "ROCCA DE' BALDI");
        this.put("H396", "ROCCA DE' GIORGI");
        this.put("H397", "ROCCA DEL COLLE");
        this.put("H397", "ROCCA DEL COLLE");
        this.put("H398", "ROCCA D'EVANDRO");
        this.put("H399", "ROCCA DI BOTTE");
        this.put("H400", "ROCCA DI CAMBIO");
        this.put("H401", "ROCCA DI CAVE");
        this.put("H402", "ROCCA DI MEZZO");
        this.put("H403", "ROCCA DI NETO");
        this.put("H403", "ROCCA FERDINANDEA");
        this.put("H403", "ROCCA DI NETO");
        this.put("H404", "ROCCA DI PAPA");
        this.put("H405", "ROCCAFIORITA");
        this.put("H406", "ROCCAFORTE");
        this.put("H406", "ROCCAFORTE LIGURE");
        this.put("H407", "ROCCAFORTE");
        this.put("H407", "ROCCAFORTE MONDOVI'");
        this.put("H408", "ROCCAFORTE");
        this.put("H408", "ROCCAFORTE DEL GRECO");
        this.put("H409", "ROCCAFORZATA");
        this.put("H410", "ROCCAFRANCA");
        this.put("H411", "ROCCAGIOVINE");
        this.put("H412", "ROCCAGLORIOSA");
        this.put("H413", "ROCCAGORGA");
        this.put("H414", "ROCCA GRIMALDA");
        this.put("H415", "ROCCAGUGLIELMA");
        this.put("H416", "ROCCA IMPERIALE");
        this.put("H417", "ROCCALBEGNA");
        this.put("H418", "ROCCALUMERA");
        this.put("H419", "ROCCALVECCE");
        this.put("H419", "ROCCALVECCE");
        this.put("H420", "ROCCAMANDOLFI");
        this.put("H421", "ROCCA MASSIMA");
        this.put("H422", "ROCCAMENA");
        this.put("H423", "ROCCAMONFINA");
        this.put("H424", "ROCCAMONTEPIANO");
        this.put("H425", "ROCCAMORICE");
        this.put("H426", "ROCCANOVA");
        this.put("H427", "ROCCANTICA");
        this.put("H428", "ROCCAPALUMBA");
        this.put("H429", "ROCCA PIA");
        this.put("H429", "ROCCAVALLEOSCURA");
        this.put("H430", "ROCCAPIATTA");
        this.put("H431", "ROCCAPIEMONTE");
        this.put("H432", "ROCCA PRIORA");
        this.put("H433", "ROCCARAINOLA");
        this.put("H434", "ROCCARASO");
        this.put("H435", "ROCCAREONILE");
        this.put("H436", "ROCCAROMANA");
        this.put("H437", "ROCCA SAN CASCIANO");
        this.put("H438", "ROCCA SAN FELICE");
        this.put("H439", "ROCCA SAN GIOVANNI");
        this.put("H440", "ROCCA SANTA MARIA");
        this.put("H441", "ROCCA SANTO STEFANO");
        this.put("H442", "ROCCASCALEGNA");
        this.put("H443", "ROCCASECCA");
        this.put("H444", "ROCCASECCA DEI VOLSCI");
        this.put("H444", "ROCCASECCA");
        this.put("H445", "ROCCASICURA");
        this.put("H446", "ROCCA SINIBALDA");
        this.put("H447", "ROCCASPARVERA");
        this.put("H448", "ROCCASPINALVETI");
        this.put("H449", "ROCCASTRADA");
        this.put("H450", "ROCCA SUSELLA");
        this.put("H451", "ROCCAVERANO");
        this.put("H452", "ROCCAVIGNALE");
        this.put("H453", "ROCCAVIONE");
        this.put("H454", "ROCCAVIVARA");
        this.put("H455", "ROCCELLA");
        this.put("H455", "ROCCELLA VALDEMONE");
        this.put("H456", "ROCCELLA");
        this.put("H456", "ROCCELLA IONICA");
        this.put("H457", "ROCCHEMOLLES");
        this.put("H458", "ROCCHETTA");
        this.put("H458", "ROCCHETTA A VOLTURNO");
        this.put("H459", "ROCCHETTA");
        this.put("H459", "ROCCHETTA E CROCE");
        this.put("H460", "ROCCHETTA");
        this.put("H460", "ROCCHETTA NERVINA");
        this.put("H461", "ROCCHETTA");
        this.put("H461", "ROCCHETTA DI VARA");
        this.put("H462", "ROCCHETTA BELBO");
        this.put("H463", "ROCCHETTA CAIRO");
        this.put("H464", "ROCCHETTA CENGIO");
        this.put("H465", "ROCCHETTA LIGURE");
        this.put("H466", "ROCCHETTA PALAFEA");
        this.put("H467", "ROCCHETTA SANT'ANTONIO");
        this.put("H468", "ROCCHETTA TANARO");
        this.put("H469", "ROCCHETTE IN SABINA");
        this.put("H470", "RODANO");
        this.put("H471", "RODDA");
        this.put("H472", "RODDI");
        this.put("H473", "RODDINO");
        this.put("H474", "RODELLO");
        this.put("H475", "RODENGO * RODENECK");
        this.put("H476", "RODENGO");
        this.put("H477", "RODENGO-SAIANO");
        this.put("H478", "RODERO");
        this.put("H479", "RODI'");
        this.put("H479", "RODI' MILICI");
        this.put("H480", "RODI GARGANICO");
        this.put("H481", "RODIGO");
        this.put("H482", "RODITTI");
        this.put("H483", "RODORETTO");
        this.put("H484", "ROE' VOLCIANO");
        this.put("H484", "VOLCIANO");
        this.put("H485", "ROFRANO");
        this.put("H486", "ROGENO");
        this.put("H486", "ROGENO");
        this.put("H487", "ROGGIANO");
        this.put("H487", "ROGGIANO VALTRAVAGLIA");
        this.put("H488", "ROGGIANO GRAVINA");
        this.put("H488", "ROGIANO");
        this.put("H489", "ROGHUDI");
        this.put("H490", "ROGLIANO");
        this.put("H491", "ROGNANO");
        this.put("H492", "ROGNO");
        this.put("H493", "ROGOLO");
        this.put("H494", "ROIATE");
        this.put("H495", "ROIO");
        this.put("H495", "ROIO DEL SANGRO");
        this.put("H496", "ROIO");
        this.put("H496", "ROIO PIANO");
        this.put("H497", "ROISAN");
        this.put("H498", "ROLETTO");
        this.put("H499", "ROLLIERES");
        this.put("H499", "ROLLIERES");
        this.put("H500", "ROLO");
        this.put("H501", "ROMA");
        this.put("H502", "ROMAGNANO");
        this.put("H502", "ROMAGNANO SESIA");
        this.put("H503", "ROMAGNANO");
        this.put("H503", "ROMAGNANO AL MONTE");
        this.put("H504", "ROMAGNANO");
        this.put("H505", "ROMAGNESE");
        this.put("H506", "ROMALLO");
        this.put("H507", "ROMANA");
        this.put("H508", "ROMANENGO");
        this.put("H509", "ROMANO");
        this.put("H509", "ROMANO DI LOMBARDIA");
        this.put("H510", "ROMANO");
        this.put("H510", "ROMANO BRIANZA");
        this.put("H511", "ROMANO");
        this.put("H511", "ROMANO CANAVESE");
        this.put("H512", "ROMANO");
        this.put("H512", "ROMANO D'EZZELINO");
        this.put("H513", "ROMANS");
        this.put("H514", "ROMANS D'ISONZO");
        this.put("H515", "ROMARZOLLO");
        this.put("H516", "ROMBIOLO");
        this.put("H516", "ROMBIOLO");
        this.put("H517", "ROMENO");
        this.put("H518", "ROMENTINO");
        this.put("H519", "ROMETTA");
        this.put("H520", "ROMPREZZAGNO");
        this.put("H521", "RONAGO");
        this.put("H522", "RONCA'");
        this.put("H523", "RONCADE");
        this.put("H524", "RONCA DE' GOLFERANI");
        this.put("H525", "RONCADELLE");
        this.put("H526", "RONCADELLO");
        this.put("H526", "RONCADELLO D'ADDA");
        this.put("H527", "RONCARO");
        this.put("H528", "RONCEGNO");
        this.put("H529", "RONCELLO");
        this.put("H529", "RONCELLO");
        this.put("H530", "RONCHETTO");
        this.put("H531", "RONCHI");
        this.put("H531", "RONCHI DEI LEGIONARI");
        this.put("H531", "RONCHI DI MONFALCONE");
        this.put("H532", "RONCHI");
        this.put("H532", "RONCHI VALSUGANA");
        this.put("H533", "RONCHIS");
        this.put("H534", "RONCIGLIONE");
        this.put("H535", "RONCO");
        this.put("H535", "RONCOBELLO");
        this.put("H536", "RONCO");
        this.put("H536", "RONCO SCRIVIA");
        this.put("H537", "RONCO");
        this.put("H537", "RONCO BRIANTINO");
        this.put("H537", "RONCO BRIANTINO");
        this.put("H538", "RONCO BIELLESE");
        this.put("H538", "RONCO");
        this.put("H538", "RONCO BIELLESE");
        this.put("H539", "RONCO");
        this.put("H539", "RONCO CANAVESE");
        this.put("H540", "RONCO");
        this.put("H540", "RONCO ALL'ADIGE");
        this.put("H541", "RONCOFERRARO");
        this.put("H542", "RONCOFREDDO");
        this.put("H543", "RONCOGNO");
        this.put("H544", "RONCOLA");
        this.put("H545", "RONCONE");
        this.put("H546", "RONDANINA");
        this.put("H547", "RONDISSONE");
        this.put("H548", "RONGIO");
        this.put("H549", "RONSECCO");
        this.put("H550", "RONZINA");
        this.put("H551", "RONZO");
        this.put("H552", "RONZONE");
        this.put("H553", "ROPPOLO");
        this.put("H553", "ROPPOLO");
        this.put("H554", "RORA'");
        this.put("H555", "RORETO");
        this.put("H555", "RORETO CHISONE");
        this.put("H555", "ROURE");
        this.put("H556", "ROSA'");
        this.put("H557", "ROSALI");
        this.put("H558", "ROSARNO");
        this.put("H559", "ROSASCO");
        this.put("H560", "ROSATE");
        this.put("H561", "ROSAZZA");
        this.put("H561", "ROSAZZA");
        this.put("H562", "ROSCIANO");
        this.put("H563", "ROSCIATE");
        this.put("H564", "ROSCIGNO");
        this.put("H565", "ROSE");
        this.put("H566", "ROSELLO");
        this.put("H567", "ROSERIO");
        this.put("H568", "ROSETO");
        this.put("H568", "ROSETO VALFORTORE");
        this.put("H569", "ROSIGNANO");
        this.put("H569", "ROSIGNANO MONFERRATO");
        this.put("H570", "ROSIGNANO MARITTIMO");
        this.put("H570", "ROSIGNANO");
        this.put("H571", "ROSINGO");
        this.put("H572", "ROSITO");
        this.put("H572", "ROSITO CAPO SPULICO");
        this.put("H572", "ROSETO CAPO SPULICO");
        this.put("H573", "ROSOLINA");
        this.put("H574", "ROSOLINI");
        this.put("H575", "ROSORA");
        this.put("H576", "ROSORA MERGO");
        this.put("H576", "ROSORA MERGO");
        this.put("H577", "ROSSA");
        this.put("H578", "ROSSANA");
        this.put("H579", "ROSSANO");
        this.put("H580", "ROSSANO");
        this.put("H580", "ROSSANO VENETO");
        this.put("H581", "ROSSIGLIONE");
        this.put("H582", "ROSSINO");
        this.put("H583", "ROSTA");
        this.put("H584", "ROTA");
        this.put("H584", "ROTA D'IMAGNA");
        this.put("H585", "ROTA");
        this.put("H585", "ROTA GRECA");
        this.put("H586", "ROTA DENTRO");
        this.put("H587", "ROTA FUORI");
        this.put("H588", "ROTELLA");
        this.put("H589", "ROTELLO");
        this.put("H590", "ROTONDA");
        this.put("H591", "ROTONDELLA");
        this.put("H592", "ROTONDI");
        this.put("H593", "ROTTOFRENO");
        this.put("H594", "ROTZO");
        this.put("H595", "ROVAGNASCO");
        this.put("H596", "ROVAGNATE");
        this.put("H596", "ROVAGNATE");
        this.put("H597", "ROVATE");
        this.put("H598", "ROVATO");
        this.put("H599", "ROVEGNO");
        this.put("H600", "ROVEGRO");
        this.put("H601", "ROVELLASCA");
        this.put("H601", "ROVI PORRO");
        this.put("H602", "ROVELLO");
        this.put("H602", "ROVELLO PORRO");
        this.put("H603", "ROVENNA");
        this.put("H604", "ROVERBELLA");
        this.put("H605", "ROVER CARBONARE");
        this.put("H606", "ROVERCHIARA");
        this.put("H607", "ROVERE' DELLA LUNA");
        this.put("H608", "ROVERE' DI VELO");
        this.put("H608", "ROVERE' VERONESE");
        this.put("H609", "ROVEREDO IN PIANO");
        this.put("H609", "ROVEREDO");
        this.put("H610", "ROVEREDO");
        this.put("H610", "ROVEREDO DI GUA'");
        this.put("H611", "ROVERETO");
        this.put("H612", "ROVERETO");
        this.put("H613", "ROVERSANO");
        this.put("H614", "ROVESCALA");
        this.put("H615", "ROVETTA");
        this.put("H616", "ROVETTA CON FINO");
        this.put("H616", "ROVETTA CON FINO");
        this.put("H617", "ROVEZZANO");
        this.put("H617", "ROVEZZANO");
        this.put("H618", "ROVIANO");
        this.put("H619", "ROVIGNO D'ISTRIA");
        this.put("H620", "ROVIGO");
        this.put("H621", "ROVITO");
        this.put("H622", "ROVOLON");
        this.put("H623", "ROZZANO");
        this.put("H624", "ROZZO");
        this.put("H625", "RUBANO");
        this.put("H626", "RUBBIANO");
        this.put("H627", "RUBIANA");
        this.put("H628", "RUBIERA");
        this.put("H629", "RUDA");
        this.put("H630", "RUDIANO");
        this.put("H631", "RUEGLIO");
        this.put("H632", "RUFFANO");
        this.put("H633", "RUFFIA");
        this.put("H634", "RUFFRE'");
        this.put("H635", "RUFINA");
        this.put("H636", "RUGINELLO");
        this.put("H637", "RUINO");
        this.put("H637", "RUINO");
        this.put("H638", "RUMIANCA");
        this.put("H639", "RUMO");
        this.put("H640", "RUNO");
        this.put("H641", "RUOTI");
        this.put("H642", "RUSSI");
        this.put("H643", "RUTIGLIANO");
        this.put("H644", "RUTINO");
        this.put("H645", "RUVO");
        this.put("H645", "RUVO DI PUGLIA");
        this.put("H646", "RUVO");
        this.put("H646", "RUVO DEL MONTE");
        this.put("H647", "SABAUDIA");
        this.put("H648", "SABBIA");
        this.put("H649", "SABBIO");
        this.put("H649", "SABBIO BERGAMASCO");
        this.put("H650", "SABBIO");
        this.put("H650", "SABBIO CHIESE");
        this.put("H651", "SABBIONCELLO");
        this.put("H652", "SABBIONETA");
        this.put("H653", "SABLE GRANDE");
        this.put("H654", "SACCO");
        this.put("H655", "SACCOLONGO");
        this.put("H656", "SACCONAGO");
        this.put("H657", "SACILE");
        this.put("H658", "SACROFANO");
        this.put("H658", "SCROFANO");
        this.put("H659", "SADALI");
        this.put("H660", "SAGA");
        this.put("H661", "SAGAMA");
        this.put("H662", "SAGLIANO MICCA");
        this.put("H662", "SAGLIANO");
        this.put("H662", "SAGLIANO MICCA");
        this.put("H663", "SAGLIANO");
        this.put("H663", "SAGLIANO DI CRENNA");
        this.put("H664", "SAGORIA");
        this.put("H665", "SAGRADO");
        this.put("H666", "SAGRON MIS");
        this.put("H667", "SAGUEDO");
        this.put("H668", "SAIANO");
        this.put("H669", "SAINT-CHRISTOPHE");
        this.put("H670", "SAINT-DENIS");
        this.put("H671", "SAINT-MARCEL");
        this.put("H672", "SAINT-NICOLAS");
        this.put("H673", "SAINT-OYEN");
        this.put("H673", "SANT'EUGENDO");
        this.put("H674", "SAINT-PIERRE");
        this.put("H675", "SAINT-RHEMY-EN-BOSSES");
        this.put("H675", "SAN REMIGIO");
        this.put("H676", "SAINT-VINCENT");
        this.put("H676", "SAN VINCENZO DELLA FONTE");
        this.put("H677", "SALA");
        this.put("H677", "SALA MONFERRATO");
        this.put("H678", "SALA");
        this.put("H678", "SALA BOLOGNESE");
        this.put("H679", "SALA");
        this.put("H679", "SALA COMACINA");
        this.put("H680", "SALA");
        this.put("H680", "SALA AL BARRO");
        this.put("H681", "SALA BIELLESE");
        this.put("H681", "SALA");
        this.put("H681", "SALA BIELLESE");
        this.put("H682", "SALA");
        this.put("H682", "SALA BAGANZA");
        this.put("H683", "SALA");
        this.put("H683", "SALA CONSILINA");
        this.put("H684", "SALABERTANO");
        this.put("H684", "SALBERTRAND");
        this.put("H685", "SALABUE");
        this.put("H686", "SALA DI GIOI");
        this.put("H686", "SALENTO");
        this.put("H687", "SALANDRA");
        this.put("H688", "SALAPARUTA");
        this.put("H689", "SALARA");
        this.put("H690", "SALASCO");
        this.put("H691", "SALASSA");
        this.put("H692", "SALCANO");
        this.put("H693", "SALCITO");
        this.put("H694", "SALE");
        this.put("H695", "SALE");
        this.put("H695", "SALE DELLE LANGHE");
        this.put("H696", "SALE CANISCHIO");
        this.put("H697", "SALE CASTELNUOVO");
        this.put("H698", "SALECCHIO");
        this.put("H699", "SALE MARASINO");
        this.put("H700", "SALEMI");
        this.put("H701", "SALERANO SUL LAMBRO");
        this.put("H701", "SALERANO");
        this.put("H701", "SALERANO SUL LAMBRO");
        this.put("H702", "SALERANO");
        this.put("H702", "SALERANO CANAVESE");
        this.put("H703", "SALERNO");
        this.put("H704", "SALE SAN GIOVANNI");
        this.put("H705", "SALETTO");
        this.put("H706", "SALGAREDA");
        this.put("H707", "SALI");
        this.put("H707", "SALI VERCELLESE");
        this.put("H708", "SALICE");
        this.put("H708", "SALICE SALENTINO");
        this.put("H709", "SALICE");
        this.put("H709", "SALICE CALABRO");
        this.put("H710", "SALICETO");
        this.put("H711", "SALINA");
        this.put("H711", "SALINA");
        this.put("H711", "SALINA");
        this.put("H712", "SALINE");
        this.put("H712", "SAN MAURO DI SALINE");
        this.put("H713", "SALISANO");
        this.put("H714", "SALIZZOLE");
        this.put("H715", "SALLE");
        this.put("H716", "SALMORE");
        this.put("H716", "SALMOUR");
        this.put("H717", "SALO'");
        this.put("H718", "SALONA D'ISONZO");
        this.put("H719", "SALORNO * SALURN");
        this.put("H720", "SALSOMAGGIORE");
        this.put("H720", "SALSOMAGGIORE TERME");
        this.put("H721", "SALTARA");
        this.put("H722", "SALTO");
        this.put("H723", "SALTRIO");
        this.put("H724", "SALUDECIO");
        this.put("H724", "SALUDECIO");
        this.put("H725", "SALUGGIA");
        this.put("H726", "SALUSSOLA");
        this.put("H726", "SALUSSOLA");
        this.put("H727", "SALUZZO");
        this.put("H728", "SALVATERRA");
        this.put("H729", "SALVE");
        this.put("H730", "SALVIA");
        this.put("H730", "SAVOIA DI LUCANIA");
        this.put("H731", "SALVIROLA");
        this.put("H731", "SALVIROLA CREMASCA");
        this.put("H732", "SALVITELLE");
        this.put("H733", "SALZA");
        this.put("H733", "SALZA IRPINA");
        this.put("H734", "SALZA");
        this.put("H734", "SALZA DI PINEROLO");
        this.put("H735", "SALZANO");
        this.put("H736", "SAMARATE");
        this.put("H737", "SAMARIA");
        this.put("H738", "SAMASSI");
        this.put("H738", "SAMASSI");
        this.put("H739", "SAMATZAI");
        this.put("H740", "SAMBASSO");
        this.put("H741", "SAMBATELLO");
        this.put("H742", "SAMBIASE");
        this.put("H743", "SAMBUCA");
        this.put("H743", "SAMBUCA DI SICILIA");
        this.put("H743", "SAMBUCA LABAT");
        this.put("H743", "SAMBUCA ZABUT");
        this.put("H744", "SAMBUCA");
        this.put("H744", "SAMBUCA PISTOIESE");
        this.put("H745", "SAMBUCI");
        this.put("H746", "SAMBUCO");
        this.put("H747", "SAMBUCO PIETRAPORZIO");
        this.put("H747", "SAMBUCO PIETRAPORZIO");
        this.put("H748", "SAMBUGHETTO");
        this.put("H749", "SAMMICHELE DI BARI");
        this.put("H749", "SAN MICHELE");
        this.put("H750", "SAMOCLEVO");
        this.put("H751", "SAMO DI CALABRIA");
        this.put("H751", "SAMO DI CALABRIA");
        this.put("H751", "SAMO DI CALABRIA");
        this.put("H751", "SAMO DI CALABRIA");
        this.put("H752", "SAMOLACO");
        this.put("H753", "SAMONE");
        this.put("H754", "SAMONE");
        this.put("H755", "SAMPEIRE");
        this.put("H755", "SAMPEYRE");
        this.put("H756", "SAMUGHEO");
        this.put("H756", "SAMUGHEO");
        this.put("H757", "SANARICA");
        this.put("H758", "SAN BARBATO");
        this.put("H759", "SAN BARTOLOMEO");
        this.put("H760", "SAN BARTOLOMEO");
        this.put("H760", "SAN BARTOLOMEO VAL CAVARGNA");
        this.put("H761", "SAN BARTOLOMEO");
        this.put("H761", "SAN BARTOLOMEO AL BOSCO");
        this.put("H762", "SAN BARTOLOMEO");
        this.put("H762", "SAN BARTOLOMEO VALMARA");
        this.put("H763", "SAN BARTOLOMEO AL MARE");
        this.put("H763", "SAN BARTOLOMEO DEL CERVO");
        this.put("H764", "SAN BARTOLOMEO IN GALDO");
        this.put("H765", "SAN BASILE");
        this.put("H766", "SAN BASILIO");
        this.put("H767", "SAN BASSANO");
        this.put("H768", "SAN BELLINO");
        this.put("H769", "SAN BENEDETTO");
        this.put("H769", "SAN BENEDETTO DEL TRONTO");
        this.put("H770", "SAN BENEDETTO");
        this.put("H770", "SAN BENEDETTO BELBO");
        this.put("H771", "SAN BENEDETTO");
        this.put("H771", "SAN BENEDETTO PO");
        this.put("H772", "SAN BENEDETTO DEI MARSI");
        this.put("H773", "SAN BENEDETTO IN PERILLIS");
        this.put("H774", "SAN BENEDETTO ULLANO");
        this.put("H775", "SAN BENIGNO CANAVESE");
        this.put("H776", "SAN BERNARDINO");
        this.put("H777", "SAN BERNARDINO VERBANO");
        this.put("H777", "SAN BERNARDINO VERBANO");
        this.put("H778", "SAN BIAGIO");
        this.put("H778", "SAN BIAGIO PLATANI");
        this.put("H779", "SAN BIAGIO");
        this.put("H779", "SAN BIAGIO SARACINISCO");
        this.put("H780", "SAN BIAGIO");
        this.put("H780", "SAN BIAGIO DELLA CIMA");
        this.put("H781", "SAN BIAGIO DI CALLALTA");
        this.put("H782", "SAN BIASE");
        this.put("H783", "SAN BONIFACIO");
        this.put("H784", "SAN BUONO");
        this.put("H785", "SAN CALOGERO");
        this.put("H785", "SAN CALOGERO");
        this.put("H786", "SAN CANDIDO * INNICHEN");
        this.put("H787", "SAN CANZIAN D'ISONZO");
        this.put("H787", "SAN CANZIANO");
        this.put("H788", "SAN CARLO");
        this.put("H788", "SAN CARLO D'OSSOLA");
        this.put("H789", "SAN CARLO");
        this.put("H789", "SAN CARLO CANAVESE");
        this.put("H789", "SAN CARLO DI CIRIE'");
        this.put("H790", "SAN CASCIANO DEI BAGNI");
        this.put("H791", "SAN CASCIANO IN VAL DI PESA");
        this.put("H792", "SAN CATALDO");
        this.put("H793", "SAN CESARIO");
        this.put("H793", "SAN CESARIO DI LECCE");
        this.put("H794", "SAN CESARIO");
        this.put("H794", "SAN CESARIO SUL PANARO");
        this.put("H795", "SAN CHIRICO NUOVO");
        this.put("H796", "SAN CHIRICO RAPARO");
        this.put("H797", "SAN CIPIRELLO");
        this.put("H798", "SAN CIPRIANO");
        this.put("H798", "SAN CIPRIANO D'AVERSA");
        this.put("H799", "SAN CIPRIANO");
        this.put("H799", "SAN CIPRIANO PO");
        this.put("H800", "SAN CIPRIANO");
        this.put("H800", "SAN CIPRIANO PICENTINO");
        this.put("H801", "SAN CLEMENTE");
        this.put("H801", "SAN CLEMENTE");
        this.put("H802", "SAN COLOMBANO");
        this.put("H802", "SAN COLOMBANO CERTENOLI");
        this.put("H803", "SAN COLOMBANO");
        this.put("H803", "SAN COLOMBANO AL LAMBRO");
        this.put("H804", "SAN COLOMBANO");
        this.put("H804", "SAN COLOMBANO BELMONTE");
        this.put("H805", "SAN CONO");
        this.put("H806", "SAN COSMO");
        this.put("H806", "SAN COSMO ALBANESE");
        this.put("H807", "SAN COSTANTINO");
        this.put("H807", "SAN COSTANTINO CALABRO");
        this.put("H807", "SAN COSTANTINO CALABRO");
        this.put("H808", "SAN COSTANTINO");
        this.put("H808", "SAN COSTANTINO ALBANESE");
        this.put("H809", "SAN COSTANZO");
        this.put("H810", "SAN CRISTOFORO");
        this.put("H811", "SAN DAMIANO");
        this.put("H811", "SAN DAMIANO D'ASTI");
        this.put("H812", "SAN DAMIANO");
        this.put("H812", "SAN DAMIANO MACRA");
        this.put("H813", "SAN DAMIANO");
        this.put("H813", "SAN DAMIANO DI MONZA");
        this.put("H814", "SAN DAMIANO");
        this.put("H814", "SAN DAMIANO AL COLLE");
        this.put("H815", "SAN DANIELE");
        this.put("H815", "SAN DANIELE PO");
        this.put("H815", "SAN DANIELE RIPA PO");
        this.put("H816", "SAN DANIELE");
        this.put("H816", "SAN DANIELE DEL FRIULI");
        this.put("H817", "SAN DANIELE DEL CARSO");
        this.put("H818", "SAN DEMETRIO");
        this.put("H818", "SAN DEMETRIO CORONE");
        this.put("H819", "SAN DEMETRIO");
        this.put("H819", "SAN DEMETRIO NE' VESTINI");
        this.put("H820", "SAN DIDERO");
        this.put("H821", "SANDIGLIANO");
        this.put("H821", "SANDIGLIANO");
        this.put("H822", "SAN DONACI");
        this.put("H823", "SAN DONA' DI PIAVE");
        this.put("H824", "SAN DONATO");
        this.put("H824", "SAN DONATO VAL DI COMINO");
        this.put("H825", "SAN DONATO");
        this.put("H825", "SAN DONATO DI NINEA");
        this.put("H826", "SAN DONATO");
        this.put("H826", "SAN DONATO DI LECCE");
        this.put("H827", "SAN DONATO");
        this.put("H827", "SAN DONATO MILANESE");
        this.put("H828", "SAN DONATO");
        this.put("H828", "SAN DONATO D'ENZA");
        this.put("H829", "SANDRIGO");
        this.put("H830", "SAN FEDELE");
        this.put("H830", "SAN FEDELE INTELVI");
        this.put("H831", "SAN FELE");
        this.put("H832", "SAN FELICE");
        this.put("H832", "SAN FELICE DI SCOVOLO");
        this.put("H833", "SAN FELICE");
        this.put("H833", "SAN FELICE DEL LITTORIO");
        this.put("H833", "SAN FELICE DEL MOLISE");
        this.put("H833", "SAN FELICE SLAVO");
        this.put("H834", "SAN FELICE");
        this.put("H834", "SAN FELICE A CANCELLO");
        this.put("H835", "SAN FELICE");
        this.put("H835", "SAN FELICE SUL PANARO");
        this.put("H836", "SAN FELICE CIRCEO");
        this.put("H836", "SAN FELICE");
        this.put("H837", "SAN FELICE * SANKT FELIX");
        this.put("H838", "SAN FELICE DEL BENACO");
        this.put("H839", "SAN FERDINANDO DI PUGLIA");
        this.put("H839", "SAN FERDINANDO DI PUGLIA");
        this.put("H839", "SAN FERDINANDO");
        this.put("H840", "SAN FERMO DELLA BATTAGLIA");
        this.put("H840", "VERGOSA");
        this.put("H841", "SAN FILI");
        this.put("H842", "SAN FILIPPO DEL MELA");
        this.put("H843", "SAN FIOR");
        this.put("H844", "SAN FIORANO");
        this.put("H844", "SAN FIORANO");
        this.put("H845", "SAN FLORIANO DEL COLLIO");
        this.put("H845", "SAN FLORIANO");
        this.put("H846", "SAN FLORO");
        this.put("H847", "SAN FRANCESCO AL CAMPO");
        this.put("H847", "VAUDA SAN MORIZIO");
        this.put("H848", "AGLIENTU");
        this.put("H848", "AGLIENTU");
        this.put("H848", "SAN FRANCESCO D'AGLIENTU");
        this.put("H849", "SAN FRANCESCO D'ALBARO");
        this.put("H850", "SAN FRATELLO");
        this.put("H851", "SANFRE'");
        this.put("H852", "SANFRONT");
        this.put("H852", "SANFRONTE");
        this.put("H853", "SAN FRUTTUOSO");
        this.put("H854", "SAN GALLO");
        this.put("H854", "SAN GALLO");
        this.put("H855", "SANGANO");
        this.put("H856", "SAN GAVINO");
        this.put("H856", "SAN GAVINO MONREALE");
        this.put("H856", "SAN GAVINO MONREALE");
        this.put("H857", "SAN GEMINI");
        this.put("H858", "SAN GENESIO * JENESIEN");
        this.put("H858", "SAN GENESIO ATESINO * JENESIEN");
        this.put("H859", "SAN GENESIO");
        this.put("H859", "SAN GENESIO ED UNITI");
        this.put("H860", "SAN GENNARO");
        this.put("H860", "SAN GENNARO VESUVIANO");
        this.put("H861", "SAN GERMANO");
        this.put("H861", "SAN GERMANO VERCELLESE");
        this.put("H862", "SAN GERMANO");
        this.put("H862", "SAN GERMANO CHISONE");
        this.put("H863", "SAN GERMANO");
        this.put("H863", "SAN GERMANO DEI BERICI");
        this.put("H864", "SAN GERVASIO");
        this.put("H864", "SAN GERVASIO D'ADDA");
        this.put("H865", "SAN GERVASIO");
        this.put("H865", "SAN GERVASIO BRESCIANO");
        this.put("H866", "SAN GIACOMO * SANKT JAKOB IN AHRN");
        this.put("H866", "SAN GIACOMO IN VALLE AURINA * SANKT JAKOB IN AHRN");
        this.put("H867", "SAN GIACOMO");
        this.put("H867", "SAN GIACOMO DEGLI SCHIAVONI");
        this.put("H868", "SAN GIACOMO");
        this.put("H868", "SAN GIACOMO FILIPPO");
        this.put("H869", "SAN GIACOMO");
        this.put("H870", "SAN GIACOMO DELLE SEGNATE");
        this.put("H871", "SAN GIACOMO IN COLLE");
        this.put("H872", "SANGIANO");
        this.put("H873", "SAN GILLIO");
        this.put("H874", "SAN GILLIO TORINESE");
        this.put("H874", "SAN GILLIO TORINESE");
        this.put("H874", "SAN GILLIO TORINESE");
        this.put("H875", "SAN GIMIGNANO");
        this.put("H876", "SAN GINESIO");
        this.put("H877", "SANGINETO");
        this.put("H878", "SAN GIORGIO");
        this.put("H878", "SAN GIORGIO MONFERRATO");
        this.put("H879", "SAN GIORGIO * SANKT GEORG");
        this.put("H879", "SAN GIORGIO IN VAL TURES * SANKT GEORG");
        this.put("H880", "SAN GIORGIO");
        this.put("H880", "SAN GIORGIO A LIRI");
        this.put("H881", "SAN GIORGIO");
        this.put("H881", "SAN GIORGIO ALBANESE");
        this.put("H882", "SAN GIORGIO");
        this.put("H882", "SAN GIORGIO IONICO");
        this.put("H882", "SAN GIORGIO SOTTO TARANTO");
        this.put("H883", "SAN GIORGIO");
        this.put("H883", "SAN GIORGIO DI MANTOVA");
        this.put("H884", "SAN GIORGIO");
        this.put("H884", "SAN GIORGIO SU LEGNANO");
        this.put("H885", "SAN GIORGIO");
        this.put("H885", "SAN GIORGIO DI LOMELLINA");
        this.put("H886", "SAN GIORGIO");
        this.put("H886", "SAN GIORGIO DI PESARO");
        this.put("H887", "SAN GIORGIO");
        this.put("H887", "SAN GIORGIO PIACENTINO");
        this.put("H888", "SAN GIORGIO LUCANO");
        this.put("H888", "SAN GIORGIO");
        this.put("H889", "SAN GIORGIO");
        this.put("H889", "SAN GIORGIO MORGETO");
        this.put("H890", "SAN GIORGIO");
        this.put("H890", "SAN GIORGIO CANAVESE");
        this.put("H891", "SAN GIORGIO DELLA RICHINVELDA");
        this.put("H891", "SAN GIORGIO");
        this.put("H892", "SAN GIORGIO A CREMANO");
        this.put("H893", "SAN GIORGIO DELLE PERTICHE");
        this.put("H894", "SAN GIORGIO DEL SANNIO");
        this.put("H894", "SAN GIORGIO LA MONTAGNA");
        this.put("H895", "SAN GIORGIO DI NOGARO");
        this.put("H896", "SAN GIORGIO DI PIANO");
        this.put("H897", "SAN GIORGIO IN BOSCO");
        this.put("H898", "SAN GIORGIO LA MOLARA");
        this.put("H899", "SAN GIORGIO SCARAMPI");
        this.put("H900", "SAN GIORIO DI SUSA");
        this.put("H901", "SAN GIOVANNI");
        this.put("H901", "SAN GIOVANNI VALDARNO");
        this.put("H902", "SAN GIOVANNI * SANKT JOHANN IN AHRN");
        this.put("H902", "SAN GIOVANNI IN VALLE AURINA * SANKT JOHANN IN AHRN");
        this.put("H903", "SAN GIOVANNI");
        this.put("H903", "SAN GIOVANNI DI GERACE");
        this.put("H904", "SAN GIOVANNI");
        this.put("H904", "SAN GIOVANNI PELLICE");
        this.put("H905", "SAN GIOVANNI ALLA CASTAGNA");
        this.put("H906", "SAN GIOVANNI AL NATISONE");
        this.put("H906", "SAN GIOVANNI DI MANZANO");
        this.put("H907", "SAN GIOVANNI A PIRO");
        this.put("H908", "SAN GIOVANNI A TEDUCCIO");
        this.put("H909", "SAN GIOVANNI BATTISTA");
        this.put("H910", "SAN GIOVANNI BIANCO");
        this.put("H911", "SAN GIOVANNI D'ASSO");
        this.put("H912", "SAN GIOVANNI DEL DOSSO");
        this.put("H913", "SAN GIOVANNI DI BIEDA");
        this.put("H913", "VILLA SAN GIOVANNI IN TUSCIA");
        this.put("H914", "SAN GIOVANNI DI CAMMARATA");
        this.put("H914", "SAN GIOVANNI GEMINI");
        this.put("H915", "SAN GIOVANNI DI GALERNO");
        this.put("H916", "SAN GIOVANNI ILARIONE");
        this.put("H917", "SAN GIOVANNI INCARICO");
        this.put("H918", "SAN GIOVANNI IN CROCE");
        this.put("H919", "SAN GIOVANNI IN FIORE");
        this.put("H920", "SAN GIOVANNI IN GALDO");
        this.put("H921", "SAN GIOVANNI IN MARIGNANO");
        this.put("H921", "SAN GIOVANNI IN MARIGNANO");
        this.put("H922", "SAN GIOVANNI LA PUNTA");
        this.put("H923", "SAN GIOVANNI LIPIONI");
        this.put("H924", "SAN GIOVANNI LUPATOTO");
        this.put("H925", "SAN GIOVANNI REATINO");
        this.put("H926", "SAN GIOVANNI ROTONDO");
        this.put("H927", "SAN GIULIANO");
        this.put("H928", "SAN GIULIANO DEL SANNIO");
        this.put("H928", "SAN GIULIANO DI SEPINO");
        this.put("H929", "SAN GIULIANO DI PUGLIA");
        this.put("H930", "SAN GIULIANO MILANESE");
        this.put("H930", "VIBOLDONE");
        this.put("H931", "SAN GIUSEPPE");
        this.put("H931", "SAN GIUSEPPE VESUVIANO");
        this.put("H932", "SAN GIUSEPPE");
        this.put("H932", "SAN GIUSEPPE DI CASTO");
        this.put("H933", "SAN GIUSEPPE");
        this.put("H933", "SAN GIUSEPPE JATO");
        this.put("H934", "SAN GIUSEPPE");
        this.put("H934", "VILLA SAN GIUSEPPE");
        this.put("H935", "SAN GIUSTINO");
        this.put("H936", "SAN GIUSTO");
        this.put("H936", "SAN GIUSTO CANAVESE");
        this.put("H937", "SAN GODENZO");
        this.put("H938", "SAN GREGORIO");
        this.put("H938", "SAN GREGORIO NELLE ALPI");
        this.put("H939", "SAN GREGORIO");
        this.put("H939", "SAN GREGORIO MATESE");
        this.put("H940", "SAN GREGORIO");
        this.put("H940", "SAN GREGORIO DI CATANIA");
        this.put("H941", "SAN GREGORIO");
        this.put("H941", "SAN GREGORIO D'IPPONA");
        this.put("H941", "SAN GREGORIO D'IPPONA");
        this.put("H942", "SAN GREGORIO");
        this.put("H942", "SAN GREGORIO DA SASSOLA");
        this.put("H943", "SAN GREGORIO");
        this.put("H943", "SAN GREGORIO MAGNO");
        this.put("H944", "SANGUINETTO");
        this.put("H945", "SAN LAZZARO");
        this.put("H945", "SAN LAZZARO DI SAVENA");
        this.put("H946", "SAN LAZZARO");
        this.put("H946", "SAN LAZZARO REALE");
        this.put("H947", "SAN LAZZARO");
        this.put("H947", "SAN LAZZARO ALBERONI");
        this.put("H948", "SAN LAZZARO PARMENSE");
        this.put("H949", "SAN LEO");
        this.put("H949", "SAN LEO");
        this.put("H950", "SAN LEONARDO * SANKT LEONHARD");
        this.put("H951", "SAN LEONARDO");
        this.put("H952", "SAN LEONARDO IN PASSIRIA * SANKT LEONHARD IN PASSEIER");
        this.put("H953", "SAN LEUCIO");
        this.put("H953", "SAN LEUCIO DEL SANNIO");
        this.put("H954", "SAN LEUCIO");
        this.put("H955", "SAN LORENZELLO");
        this.put("H956", "SAN LORENZO * SANKT LORENZEN");
        this.put("H956", "SAN LORENZO DI SEBATO * SANKT LORENZEN");
        this.put("H956", "SAN LORENZO IN PUSTERIA * SANKT LORENZEN");
        this.put("H957", "SAN LORENZO");
        this.put("H957", "SAN LORENZO AL MARE");
        this.put("H958", "SAN LORENZO");
        this.put("H958", "SAN LORENZO IN CAMPO");
        this.put("H959", "SAN LORENZO");
        this.put("H960", "SAN LORENZO AROLDO");
        this.put("H961", "SAN LORENZO BELLIZZI");
        this.put("H962", "SAN LORENZO DEL VALLO");
        this.put("H963", "SAN LORENZO DE' PICENARDI");
        this.put("H964", "SAN LORENZO DI MOSSA");
        this.put("H964", "SAN LORENZO ISONTINO");
        this.put("H965", "SAN LORENZO GUAZZONE");
        this.put("H966", "SAN LORENZO IN BANALE");
        this.put("H967", "SAN LORENZO MAGGIORE");
        this.put("H968", "SAN LORENZO MONDINARI");
        this.put("H969", "SAN LORENZO NUOVO");
        this.put("H970", "SAN LUCA");
        this.put("H971", "SAN LUCIDO");
        this.put("H972", "SAN LUGANO");
        this.put("H973", "SAN LUPO");
        this.put("H974", "SANLURI");
        this.put("H974", "SANLURI");
        this.put("H975", "SAN MANGO");
        this.put("H975", "SAN MANGO SUL CALORE");
        this.put("H976", "SAN MANGO");
        this.put("H976", "SAN MANGO D'AQUINO");
        this.put("H977", "SAN MANGO");
        this.put("H977", "SAN MANGO PIEMONTE");
        this.put("H978", "SAN MARCELLINO");
        this.put("H979", "SAN MARCELLO");
        this.put("H980", "SAN MARCELLO");
        this.put("H980", "SAN MARCELLO PISTOIESE");
        this.put("H981", "SAN MARCO");
        this.put("H981", "SAN MARCO ARGENTANO");
        this.put("H982", "SAN MARCO");
        this.put("H982", "SAN MARCO D'ALFONSIO");
        this.put("H982", "SAN MARCO D'ALUNZIO");
        this.put("H983", "SAN MARCO A MONTI");
        this.put("H984", "SAN MARCO DEI CAVOTI");
        this.put("H985", "SAN MARCO IN LAMIS");
        this.put("H986", "SAN MARCO LA CATOLA");
        this.put("H987", "SAN MARTINO");
        this.put("H987", "SAN MARTINO AL TANARO");
        this.put("H987", "SAN MARTINO ALFIERI");
        this.put("H988", "SAN MARTINO * SANKT MARTIN");
        this.put("H988", "SAN MARTINO IN BADIA * SANKT MARTIN IN THURN");
        this.put("H989", "SAN MARTINO * SANKT MARTIN");
        this.put("H989", "SAN MARTINO IN PASSIRIA * SANKT MARTIN IN PASSEIER");
        this.put("H990", "SAN MARTINO");
        this.put("H990", "SAN MARTINO IN PENSILIS");
        this.put("H991", "SAN MARTINO");
        this.put("H991", "SAN MARTINO SULLA MARRUCINA");
        this.put("H992", "SAN MARTINO");
        this.put("H992", "SAN MARTINO DI FINITA");
        this.put("H993", "SAN MARTINO");
        this.put("H993", "SAN MARTINO IN VALLE");
        this.put("H994", "SAN MARTINO");
        this.put("H994", "SAN MARTINO D'AGRI");
        this.put("H995", "SAN MARTINO");
        this.put("H995", "SAN MARTINO AL CIMINO");
        this.put("H996", "SAN MARTINO");
        this.put("H996", "SAN MARTINO DI VENEZZE");
        this.put("H997", "SAN MARTINO");
        this.put("H997", "SAN MARTINO CANAVESE");
        this.put("H998", "SAN MARTINO");
        this.put("H998", "SAN MARTINO DI PERRERO");
        this.put("H999", "SAN MARTINO AL TAGLIAMENTO");
        this.put("H999", "SAN MARTINO");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
