package document;

import java.util.HashMap;

/**
 * Created by Matteo on 12/11/2015.
 */
@SuppressWarnings("serial")
public class CitiesCodes_M extends HashMap<String, String> {

    public CitiesCodes_M(){
        this.put("M001", "VILLA RAVERIO");
        this.put("M002", "VILLARBASSE");
        this.put("M003", "VILLARBOIT");
        this.put("M004", "VILLAREGGIA");
        this.put("M005", "VILLAREGGIO");
        this.put("M006", "VILLA RENDENA");
        this.put("M007", "VILLAR FOCCHIARDO");
        this.put("M008", "VILLAROCCA");
        this.put("M009", "VILLAROMAGNANO");
        this.put("M010", "VILLA ROMANO");
        this.put("M011", "VILLAROSA");
        this.put("M012", "VILLA ROSSA");
        this.put("M013", "VILLAR PELLICE");
        this.put("M014", "VILLAR PEROSA");
        this.put("M015", "VILLAR SAN COSTANZO");
        this.put("M016", "VILLASALTO");
        this.put("M017", "VILLA SAN FIORANO");
        this.put("M017", "VILLASANTA");
        this.put("M017", "VILLASANTA");
        this.put("M018", "VILLA SAN GIOVANNI");
        this.put("M019", "VILLA SAN SECONDO");
        this.put("M020", "VILLA SANTA CATERINA * AUFHOFEN");
        this.put("M021", "VILLA SANTA LUCIA DEGLI ABRUZZI");
        this.put("M022", "VILLA SANTA MARIA");
        this.put("M023", "VILLA SANT'ANGELO");
        this.put("M024", "VILLA SLAVINA");
        this.put("M025", "VILLASOR");
        this.put("M026", "VILLASPECIOSA");
        this.put("M027", "VILLASTELLONE");
        this.put("M028", "VILLATA");
        this.put("M029", "VILLA TALLA");
        this.put("M030", "VILLAURBANA");
        this.put("M030", "VILLAURBANA");
        this.put("M031", "VILLAVALLELONGA");
        this.put("M032", "VILLAVERLA");
        this.put("M033", "VILLA VIANI");
        this.put("M034", "VILLA VICENTINA");
        this.put("M035", "VILLA VOLTURNO");
        this.put("M035", "VILLA VOLTURNO");
        this.put("M036", "VILLAZZANO");
        this.put("M037", "VILLE DEL MONTE");
        this.put("M038", "VILLE MONTEVECCHIO");
        this.put("M039", "VILLE SAN PIETRO");
        this.put("M040", "VILLE SAN SEBASTIANO");
        this.put("M041", "VILLETTA BARREA");
        this.put("M042", "VILLETTE");
        this.put("M042", "VILLETTE");
        this.put("M043", "VILLESSE");
        this.put("M044", "VILLIMPENTA");
        this.put("M045", "VILLONGO");
        this.put("M046", "VILLONGO SAN FILASTRO");
        this.put("M047", "VILLONGO SANT'ALESSANDRO");
        this.put("M047", "VILLONGO SANT'ALESSANDRO");
        this.put("M048", "VILLORBA");
        this.put("M049", "VILMINORE");
        this.put("M050", "VILMINORE DI SCALVE");
        this.put("M051", "VIMANONE");
        this.put("M052", "VIMERCATE");
        this.put("M052", "VIMERCATE");
        this.put("M053", "VIMODRONE");
        this.put("M054", "VIMOGNO");
        this.put("M055", "VINADIO");
        this.put("M056", "VINAGO");
        this.put("M057", "VINCHIATURO");
        this.put("M058", "VINCHIO");
        this.put("M059", "VINCI");
        this.put("M060", "VINOVO");
        this.put("M061", "VINTEBBIO");
        this.put("M062", "VINZAGLIO");
        this.put("M063", "VIOLA");
        this.put("M064", "VION");
        this.put("M065", "VIONE");
        this.put("M066", "VIPACCO");
        this.put("M067", "VIPITENO * STERZING");
        this.put("M068", "VIRLE");
        this.put("M068", "VIRLE TRE PONTI");
        this.put("M069", "VIRLE");
        this.put("M069", "VIRLE PIEMONTE");
        this.put("M070", "VISANO");
        this.put("M071", "VISCHE");
        this.put("M072", "VISCIANO");
        this.put("M073", "VISCO");
        this.put("M074", "VISIGNANO");
        this.put("M075", "VISINADA");
        this.put("M076", "VISINO");
        this.put("M077", "VISONE");
        this.put("M077", "VISONE");
        this.put("M078", "VISSO");
        this.put("M079", "VISTARINO");
        this.put("M080", "VISTRORIO");
        this.put("M081", "VITA");
        this.put("M082", "VITERBO");
        this.put("M083", "VITICUSO");
        this.put("M084", "VITICUSO E ACQUAFONDATA");
        this.put("M084", "VITICUSO E ACQUAFONDATA");
        this.put("M085", "VITO D'ASIO");
        this.put("M086", "VITORCHIANO");
        this.put("M087", "VITTADONE");
        this.put("M088", "VITTORIA");
        this.put("M089", "VITTORIO");
        this.put("M089", "VITTORIO VENETO");
        this.put("M090", "VITTORITO");
        this.put("M091", "VITTUONE");
        this.put("M092", "VITULACCIO");
        this.put("M092", "VITULAZIO");
        this.put("M093", "VITULANO");
        this.put("M094", "VIU'");
        this.put("M095", "VIVARO");
        this.put("M095", "VIVARO ROMANO");
        this.put("M096", "VIVARO");
        this.put("M097", "VIVENTE");
        this.put("M098", "VIVERONE");
        this.put("M098", "VIVERONE");
        this.put("M099", "VIZZE * PFITSCH");
        this.put("M100", "VIZZINI");
        this.put("M101", "VIZZOLA");
        this.put("M101", "VIZZOLA TICINO");
        this.put("M102", "VIZZOLO");
        this.put("M102", "VIZZOLO PREDABISSI");
        this.put("M103", "VO");
        this.put("M104", "VOBARNO");
        this.put("M105", "VOBBIA");
        this.put("M106", "VOCCA");
        this.put("M107", "VOCOGNO E PRESTINONE");
        this.put("M108", "VODO DI CADORE");
        this.put("M109", "VOGHERA");
        this.put("M110", "VOGHIERA");
        this.put("M111", "VOGOGNA");
        this.put("M111", "VOGOGNA");
        this.put("M112", "VOISSIZZA DI COMENO");
        this.put("M113", "VOLANO");
        this.put("M114", "VOLDOMINO");
        this.put("M115", "VOLLA");
        this.put("M116", "VOLONGO");
        this.put("M117", "VOLOSCA");
        this.put("M118", "VOLPAGO");
        this.put("M118", "VOLPAGO DEL MONTELLO");
        this.put("M119", "VOLPARA");
        this.put("M120", "VOLPEDO");
        this.put("M121", "VOLPEGLINO");
        this.put("M122", "VOLPIANO");
        this.put("M123", "VOLTAGGIO");
        this.put("M124", "VOLTAGO");
        this.put("M124", "VOLTAGO AGORDINO");
        this.put("M125", "VOLTA MANTOVANA");
        this.put("M126", "VOLTERRA");
        this.put("M127", "VOLTIDO");
        this.put("M128", "VOLTORRE");
        this.put("M129", "VOLTRI");
        this.put("M130", "VOLTURARA");
        this.put("M130", "VOLTURARA IRPINA");
        this.put("M131", "VOLTURARA");
        this.put("M131", "VOLTURARA APPULA");
        this.put("M132", "VOLTURINO");
        this.put("M133", "VOLVERA");
        this.put("M134", "VOLZANA");
        this.put("M135", "VOSCHIA");
        this.put("M136", "VOTTIGNASCO");
        this.put("M137", "XITTA");
        this.put("M138", "ZACCANOPOLI");
        this.put("M138", "ZACCANOPOLI");
        this.put("M139", "ZAFFERANA ETNEA");
        this.put("M140", "ZAGARISE");
        this.put("M141", "ZAGAROLO");
        this.put("M142", "ZAMBANA");
        this.put("M143", "ZAMBRONE");
        this.put("M143", "ZAMBRONE");
        this.put("M144", "ZANDOBBIO");
        this.put("M144", "ZANDOBBIO");
        this.put("M145", "ZANE'");
        this.put("M146", "ZANENGO");
        this.put("M147", "ZANICA");
        this.put("M148", "ZAPPELLO CON BOLZONE");
        this.put("M149", "ZARA");
        this.put("M150", "ZAVATTARELLO");
        this.put("M150", "ZAVATTARELLO");
        this.put("M151", "ZAVATTARELLO VALVERDE");
        this.put("M151", "ZAVATTARELLO VALVERDE");
        this.put("M152", "ZECCONE");
        this.put("M152", "ZECCONE");
        this.put("M153", "ZEDDIANI");
        this.put("M153", "ZEDDIANI");
        this.put("M154", "ZELARINO");
        this.put("M155", "ZELATA");
        this.put("M156", "ZELBIO");
        this.put("M157", "ZELBIO VELESO");
        this.put("M157", "ZELBIO VELESO");
        this.put("M158", "ZELO BUON PERSICO");
        this.put("M158", "ZELO BUON PERSICO");
        this.put("M159", "ZELO FORAMAGNO");
        this.put("M160", "ZELO SURRIGONE");
        this.put("M161", "ZEME");
        this.put("M162", "ZENEVREDO");
        this.put("M163", "ZENSON DI PIAVE");
        this.put("M164", "ZEPPARA");
        this.put("M165", "ZERBA");
        this.put("M166", "ZERBO");
        this.put("M167", "ZERBOLO'");
        this.put("M168", "ZERFALIU");
        this.put("M168", "ZERFALIU");
        this.put("M169", "ZERI");
        this.put("M170", "ZERMEGHEDO");
        this.put("M171", "ZERO BRANCO");
        this.put("M172", "ZEVIO");
        this.put("M173", "ZIANO");
        this.put("M173", "ZIANO DI FIEMME");
        this.put("M174", "ZIBELLO");
        this.put("M175", "ZIBIDO AL LAMBRO");
        this.put("M176", "ZIBIDO SAN GIACOMO");
        this.put("M177", "ZIGNAGO");
        this.put("M178", "ZIMELLA");
        this.put("M179", "ZIMONE");
        this.put("M179", "ZIMONE");
        this.put("M180", "ZINASCO");
        this.put("M181", "ZIVIDO");
        this.put("M182", "ZOAGLI");
        this.put("M183", "ZOCCA");
        this.put("M184", "ZOGNO");
        this.put("M185", "ZOLA PREDOSA");
        this.put("M186", "ZOLLA");
        this.put("M187", "ZOLLINO");
        this.put("M188", "ZONE");
        this.put("M189", "ZOPPE'");
        this.put("M189", "ZOPPE' DI CADORE");
        this.put("M190", "ZOPPOLA");
        this.put("M191", "ZORLESCO");
        this.put("M192", "ZORNASCO");
        this.put("M193", "ZORZINO");
        this.put("M194", "ZOVENCEDO");
        this.put("M195", "ZOVERALLO");
        this.put("M196", "ZUBIENA");
        this.put("M196", "ZUBIENA");
        this.put("M197", "ZUCCARELLO");
        this.put("M198", "ZUCLO");
        this.put("M199", "ZUGLIANO");
        this.put("M200", "ZUGLIO");
        this.put("M201", "ZUMAGLIA");
        this.put("M201", "ZUMAGLIA");
        this.put("M202", "ZUMPANO");
        this.put("M203", "ZUNGOLI");
        this.put("M204", "ZUNGRI");
        this.put("M204", "ZUNGRI");
        this.put("M205", "ZUNICO");
        this.put("M206", "ZURI");
        this.put("M207", "LARIANO");
        this.put("M208", "LAMEZIA TERME");
        this.put("M209", "SANT'ANNA ARRESI");
        this.put("M209", "SANT'ANNA ARRESI");
        this.put("M210", "TERME VIGLIATORE");
        this.put("M211", "ACQUEDOLCI");
        this.put("M212", "LADISPOLI");
        this.put("M213", "ARDEA");
        this.put("M214", "BADESI");
        this.put("M214", "BADESI");
        this.put("M215", "BALBIDO");
        this.put("M216", "BALLINO");
        this.put("M217", "BARCESINO");
        this.put("M218", "BONDONE STORO");
        this.put("M219", "BONO");
        this.put("M220", "BRANCOLINO");
        this.put("M221", "BRUSINO");
        this.put("M222", "CANALE");
        this.put("M223", "CARES");
        this.put("M224", "CASANOVA DEL MORBASCO");
        this.put("M225", "CASTELPIETRA");
        this.put("M226", "CAVRASTO");
        this.put("M227", "COMIGHELLO");
        this.put("M228", "DASINDO");
        this.put("M229", "DUVREDO");
        this.put("M230", "FAVRIO");
        this.put("M231", "GODENZO");
        this.put("M232", "LAGUNA MUSTE'");
        this.put("M233", "LARIDO");
        this.put("M234", "LASES");
        this.put("M235", "LONA");
        this.put("M236", "MADICE");
        this.put("M237", "MALA");
        this.put("M238", "MENAS");
        this.put("M239", "MONTEVACCINO");
        this.put("M240", "ORTISE'");
        this.put("M241", "POIA");
        this.put("M242", "RANGO");
        this.put("M243", "RONCHI DI ALA");
        this.put("M244", "SACCO");
        this.put("M245", "SAVIGNANO");
        this.put("M246", "STRAVINO");
        this.put("M247", "TIGNERONE");
        this.put("M248", "VARANO");
        this.put("M249", "VIGO CAVEDINE");
        this.put("M250", "VIGO LOMASO");
        this.put("M251", "VILLAMONTAGNA");
        this.put("M252", "CREDERA CON ROVERETO");
        this.put("M253", "SICIGNANO");
        this.put("M253", "SICIGNANO DEGLI ALBURNI");
        this.put("M254", "VAL SANTAMARINA");
        this.put("M255", "MOLINA ATERNO");
        this.put("M256", "SCANZANO JONICO");
        this.put("M257", "PORTOPALO DI CAPO PASSERO");
        this.put("M258", "AVIGLIANO UMBRO");
        this.put("M259", "VIDDALBA");
        this.put("M260", "CASAPESENNA");
        this.put("M261", "CASTRO");
        this.put("M262", "CELLOLE");
        this.put("M263", "PORTO CESAREO");
        this.put("M264", "SAN CASSIANO");
        this.put("M265", "VAJONT");
        this.put("M266", "ORDONA");
        this.put("M267", "ZAPPONETA");
        this.put("M268", "BLUFI");
        this.put("M269", "PATERNO");
        this.put("M270", "MASAINAS");
        this.put("M270", "MASAINAS");
        this.put("M271", "MAZZARRONE");
        this.put("M272", "CIAMPINO");
        this.put("M273", "SANTA MARIA LA CARITA'");
        this.put("M274", "GOLFO ARANCI");
        this.put("M274", "GOLFO ARANCI");
        this.put("M275", "LOIRI PORTO SAN PAOLO");
        this.put("M275", "LOIRI PORTO SAN PAOLO");
        this.put("M276", "SANT'ANTONIO DI GALLURA");
        this.put("M276", "SANT'ANTONIO DI GALLURA");
        this.put("M277", "SAN FERDINANDO");
        this.put("M278", "VILLAPERUCCIO");
        this.put("M278", "VILLAPERUCCIO");
        this.put("M279", "PRIOLO GARGALLO");
        this.put("M280", "TRECASE");
        this.put("M281", "PETROSINO");
        this.put("M282", "TERGU");
        this.put("M283", "MANIACE");
        this.put("M284", "SANTA MARIA COGHINAS");
        this.put("M285", "CARDEDU");
        this.put("M285", "CARDEDU");
        this.put("M286", "TORRENOVA");
        this.put("M287", "RAGALNA");
        this.put("M288", "CASTIADAS");
        this.put("M289", "MASSA DI SOMMA");
        this.put("M290", "STINTINO");
        this.put("M291", "PISCINAS");
        this.put("M291", "PISCINAS");
        this.put("M292", "ERULA");
        this.put("M293", "VEGLIA");
        this.put("M294", "BELLIZZI");
        this.put("M295", "SAN CESAREO");
        this.put("M296", "PIEMONTE D'ISTRIA");
        this.put("M297", "FIUMICINO");
        this.put("M298", "STATTE");
        this.put("M299", "BOVILLE");
        this.put("M300", "DUE CARRARE");
        this.put("M301", "PADRU");
        this.put("M301", "PADRU");
        this.put("M302", "MONTIGLIO MONFERRATO");
        this.put("M303", "RONZO-CHIENIS");
        this.put("M304", "MOSSO");
        this.put("M305", "ALME' CON VILLA");
        this.put("M305", "ALME' CON VILLA");
        this.put("M306", "COLLE ISARCO * GOSSENSASS");
        this.put("M307", "RASUN VALDAORA * RASEN OLANG");
        this.put("M307", "RASUN VALDAORA * RASEN OLANG");
        this.put("M308", "CAVALLINO-TREPORTI");
        this.put("M309", "FONTE NUOVA");
        this.put("M310", "SEBENICO");
        this.put("M311", "CAMPOLONGO TAPOGLIANO");
        this.put("M312", "LONATO DEL GARDA");
        this.put("M313", "LEDRO");
        this.put("M314", "COMANO TERME");
        this.put("M315", "GRAVEDONA  ED UNITI");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
