package document;

import java.util.HashMap;

/**
 * Created by Matteo on 12/11/2015.
 */
@SuppressWarnings("serial")
public class CitiesCodes_G extends HashMap<String, String> {

    public CitiesCodes_G(){
        this.put("G001", "ODOLO");
        this.put("G002", "OFENA");
        this.put("G003", "OFFAGNA");
        this.put("G004", "OFFANENGO");
        this.put("G005", "OFFIDA");
        this.put("G006", "OFFLAGA");
        this.put("G007", "OGGEBBIO");
        this.put("G007", "OGGEBBIO");
        this.put("G008", "OGGIONA");
        this.put("G008", "OGGIONA CON SANTO STEFANO");
        this.put("G009", "OGGIONO");
        this.put("G009", "OGGIONO");
        this.put("G010", "OGLIANICO");
        this.put("G011", "OGLIASTRO");
        this.put("G011", "OGLIASTRO CILENTO");
        this.put("G012", "OIASSE");
        this.put("G012", "OYACE");
        this.put("G013", "OLATE");
        this.put("G014", "OLBA");
        this.put("G015", "OLBIA");
        this.put("G015", "OLBIA");
        this.put("G015", "TERRANOVA PAUSANIA");
        this.put("G015", "TERRANOVA");
        this.put("G016", "OLCENENGO");
        this.put("G017", "OLCIO");
        this.put("G018", "OLDENICO");
        this.put("G019", "OLEGGIO");
        this.put("G020", "OLEGGIO CASTELLO");
        this.put("G021", "OLEVANO");
        this.put("G021", "OLEVANO DI LOMELLINA");
        this.put("G022", "OLEVANO");
        this.put("G022", "OLEVANO ROMANO");
        this.put("G023", "OLEVANO");
        this.put("G023", "OLEVANO SUL FUSCIANO");
        this.put("G023", "OLEVANO SUL TUSCIANO");
        this.put("G024", "OLGIA");
        this.put("G025", "OLGIATE");
        this.put("G025", "OLGIATE COMASCO");
        this.put("G026", "OLGIATE");
        this.put("G026", "OLGIATE MOLGORA");
        this.put("G026", "OLGIATE MOLGORA");
        this.put("G027", "OLGIATE CALCO");
        this.put("G027", "OLGIATE CALCO");
        this.put("G028", "OLGIATE OLONA");
        this.put("G029", "OLGINASIO");
        this.put("G030", "OLGINATE");
        this.put("G030", "OLGINATE");
        this.put("G031", "OLIENA");
        this.put("G032", "OLIVA");
        this.put("G032", "OLIVA GESSI");
        this.put("G032", "OLIVA GESSI");
        this.put("G033", "OLIVA");
        this.put("G033", "TAVERNETTE");
        this.put("G034", "OLIVADI");
        this.put("G035", "OLIVASTRI");
        this.put("G036", "OLIVERI");
        this.put("G037", "OLIVETO");
        this.put("G037", "OLIVETO LUCANO");
        this.put("G038", "OLIVETO");
        this.put("G038", "OLIVETO IN SABINA");
        this.put("G039", "OLIVETO");
        this.put("G039", "OLIVETO CITRA");
        this.put("G040", "OLIVETO LARIO");
        this.put("G040", "OLIVETO LARIO");
        this.put("G041", "OLIVETTA SAN MICHELE");
        this.put("G041", "PENNA");
        this.put("G041", "PIENA");
        this.put("G042", "OLIVOLA");
        this.put("G043", "OLLASTRA SIMAXIS");
        this.put("G043", "OLLASTRA SIMAXIS");
        this.put("G043", "OLLASTRA");
        this.put("G044", "OLLOLAI");
        this.put("G045", "OLLOMONT");
        this.put("G045", "OLLOMONTE");
        this.put("G046", "OLMEDO");
        this.put("G047", "OLMENETA");
        this.put("G048", "OLMO");
        this.put("G048", "OLMO GENTILE");
        this.put("G049", "OLMO");
        this.put("G049", "OLMO AL BREMBO");
        this.put("G050", "OLTRE IL COLLE");
        this.put("G051", "OLTREPOVO");
        this.put("G052", "OLTRESARCA");
        this.put("G053", "OLTRESONZIA");
        this.put("G054", "OLTRESSENDA ALTA");
        this.put("G054", "OLTRESSENDA ALTA");
        this.put("G055", "OLTRESSENDA BASSA");
        this.put("G056", "OLTRONA");
        this.put("G056", "OLTRONA DI SAN MAMETTE");
        this.put("G057", "OLTRONA");
        this.put("G057", "OLTRONA AL LAGO");
        this.put("G058", "OLZAI");
        this.put("G059", "OMATE");
        this.put("G060", "OMBRIANO");
        this.put("G061", "OME");
        this.put("G062", "OMEGNA");
        this.put("G062", "OMEGNA");
        this.put("G063", "OMIGNANO");
        this.put("G064", "ONANI");
        this.put("G065", "ONANO");
        this.put("G066", "ONCINO");
        this.put("G067", "ONEGLIA");
        this.put("G068", "ONETA");
        this.put("G069", "ONIES * ONACH");
        this.put("G070", "ONIFAI");
        this.put("G071", "ONIFERI");
        this.put("G072", "ONNO");
        this.put("G073", "ONO");
        this.put("G073", "ONO DEGNO");
        this.put("G074", "ONO");
        this.put("G074", "ONO SAN PIETRO");
        this.put("G075", "ONORE");
        this.put("G075", "ONORE");
        this.put("G076", "ONZO");
        this.put("G077", "OPACCHIASELLA");
        this.put("G077", "OPACCHIASELLA");
        this.put("G077", "OPACCHIASELLA");
        this.put("G078", "OPERA");
        this.put("G079", "OPI");
        this.put("G080", "OPPEANO");
        this.put("G081", "OPPIDO");
        this.put("G081", "OPPIDO LUCANO");
        this.put("G081", "PALMIRA");
        this.put("G082", "OPPIDO");
        this.put("G082", "OPPIDO MAMERTINA");
        this.put("G083", "ORA * AUER");
        this.put("G084", "ORANI");
        this.put("G085", "ORASSO");
        this.put("G086", "ORATINO");
        this.put("G087", "ORBASSANO");
        this.put("G088", "ORBETELLO");
        this.put("G089", "ORCIANO");
        this.put("G089", "ORCIANO DI PESARO");
        this.put("G090", "ORCIANO");
        this.put("G090", "ORCIANO PISANO");
        this.put("G091", "ORCO");
        this.put("G092", "ORENO");
        this.put("G093", "ORERO");
        this.put("G094", "OREZZO");
        this.put("G095", "ORGIANO");
        this.put("G096", "PIEVE FISSIRAGA");
        this.put("G096", "PIEVE FISSIRAGA");
        this.put("G096", "ORGNAGA");
        this.put("G097", "ORGOSOLO");
        this.put("G098", "ORIA");
        this.put("G099", "ORIANO");
        this.put("G100", "ORIANO");
        this.put("G100", "ORIANO DI BRIANZA");
        this.put("G101", "ORIANO");
        this.put("G101", "ORIANO SOPRA TICINO");
        this.put("G102", "ORICOLA");
        this.put("G103", "ORIGGIO");
        this.put("G104", "ORIGIOSO");
        this.put("G105", "ORINO");
        this.put("G106", "ORINO AZZIO");
        this.put("G106", "ORINO AZZIO");
        this.put("G107", "ORIO LITTA");
        this.put("G107", "ORIO");
        this.put("G107", "ORIO LITTA");
        this.put("G108", "ORIO");
        this.put("G108", "ORIO AL SERIO");
        this.put("G109", "ORIO");
        this.put("G109", "ORIO CANAVESE");
        this.put("G110", "ORIOLO");
        this.put("G111", "ORIOLO");
        this.put("G111", "ORIOLO ROMANO");
        this.put("G112", "ORIS * EYRS");
        this.put("G113", "ORISTANO");
        this.put("G113", "ORISTANO");
        this.put("G114", "ORMEA");
        this.put("G115", "ORMELLE");
        this.put("G116", "ORNAGO");
        this.put("G116", "ORNAGO");
        this.put("G117", "ORNAVASSO");
        this.put("G117", "ORNAVASSO");
        this.put("G118", "ORNICA");
        this.put("G119", "OROSEI");
        this.put("G120", "OROTELLI");
        this.put("G121", "ORRIA");
        this.put("G122", "ORROLI");
        this.put("G123", "ORSAGO");
        this.put("G124", "ORSARA");
        this.put("G124", "ORSARA BORMIDA");
        this.put("G125", "ORSARA");
        this.put("G125", "ORSARA-DAUNO IRPINA");
        this.put("G125", "ORSARA DI PUGLIA");
        this.put("G126", "ORSENIGO");
        this.put("G127", "ORSERA");
        this.put("G128", "ORSOGNA");
        this.put("G129", "ORSOMARSO");
        this.put("G130", "ORTA");
        this.put("G130", "ORTA DI ATELLA");
        this.put("G131", "ORTA");
        this.put("G131", "ORTA NOVA");
        this.put("G132", "ORTA");
        this.put("G132", "ORTA NOVARESE");
        this.put("G133", "ORTACESUS");
        this.put("G134", "ORTA SAN GIULIO");
        this.put("G135", "ORTE");
        this.put("G136", "ORTELLE");
        this.put("G137", "ORTEZZANO");
        this.put("G137", "ORTEZZANO");
        this.put("G138", "ORTI");
        this.put("G139", "ORTIGNANO");
        this.put("G139", "ORTIGNANO RAGGIOLO");
        this.put("G140", "ORTISEI * SANKT ULRICH");
        this.put("G141", "ORTONA");
        this.put("G142", "ORTONA DEI MARSI");
        this.put("G143", "ORTONOVO");
        this.put("G144", "ORTOVERO");
        this.put("G145", "ORTUCCHIO");
        this.put("G146", "ORTUERI");
        this.put("G147", "ORUNE");
        this.put("G148", "ORVIETO");
        this.put("G149", "ORZINUOVI");
        this.put("G150", "ORZIVECCHI");
        this.put("G151", "OSASCO");
        this.put("G152", "OSASIO");
        this.put("G153", "OSCHIRI");
        this.put("G153", "OSCHIRI");
        this.put("G154", "OSIDDA");
        this.put("G155", "OSIGLIA");
        this.put("G156", "OSILO");
        this.put("G157", "OSIMO");
        this.put("G158", "OSINI");
        this.put("G158", "OSINI");
        this.put("G159", "OSIO SOPRA");
        this.put("G160", "OSIO SOTTO");
        this.put("G161", "OSNAGO");
        this.put("G161", "OSNAGO");
        this.put("G162", "OSOLI");
        this.put("G163", "OSOPPO");
        this.put("G164", "OSPEDALETTI");
        this.put("G165", "OSPEDALETTO");
        this.put("G165", "OSPEDALETTO D'ALPINOLO");
        this.put("G166", "OSPEDALETTO LODIGIANO");
        this.put("G166", "OSPEDALETTO");
        this.put("G166", "OSPEDALETTO LODIGIANO");
        this.put("G167", "OSPEDALETTO");
        this.put("G167", "OSPEDALETTO EUGANEO");
        this.put("G168", "OSPEDALETTO");
        this.put("G169", "OSPITALE");
        this.put("G169", "OSPITALE DI CADORE");
        this.put("G170", "OSPITALETTO");
        this.put("G171", "OSSAGO LODIGIANO");
        this.put("G171", "OSSAGO LODIGIANO");
        this.put("G172", "OSSALENGO");
        this.put("G173", "OSSANA");
        this.put("G174", "OSSANESGA");
        this.put("G175", "OSSECCA VITTUGLIA");
        this.put("G176", "OSSEGLIANO SAN MICHELE");
        this.put("G177", "OSSERO");
        this.put("G178", "OSSI");
        this.put("G179", "OSSIMO");
        this.put("G180", "OSSOLARO");
        this.put("G181", "OSSONA");
        this.put("G182", "OSSUCCIO");
        this.put("G183", "OSTANA");
        this.put("G184", "OSTELLATO");
        this.put("G185", "OSTIANO");
        this.put("G186", "OSTIGLIA");
        this.put("G187", "OSTUNI");
        this.put("G188", "OTRANTO");
        this.put("G189", "OTRICOLI");
        this.put("G190", "OTTAIANO");
        this.put("G190", "OTTAVIANO");
        this.put("G191", "OTTANA");
        this.put("G192", "OTTATI");
        this.put("G193", "OTTIGLIO");
        this.put("G194", "OTTOBIANO");
        this.put("G195", "OTTONE");
        this.put("G196", "OULX");
        this.put("G196", "ULZIO");
        this.put("G197", "OVADA");
        this.put("G198", "OVARO");
        this.put("G199", "OVIGLIO");
        this.put("G200", "OVINDOLI");
        this.put("G201", "OVODDA");
        this.put("G202", "OZEGNA");
        this.put("G203", "OZIERI");
        this.put("G204", "OZZANO");
        this.put("G204", "OZZANO DI ROBIANO");
        this.put("G204", "OZZANO MONFERRATO");
        this.put("G205", "OZZANO");
        this.put("G205", "OZZANO DELL'EMILIA");
        this.put("G206", "OZZERO");
        this.put("G207", "PABILLONIS");
        this.put("G207", "PABILLONIS");
        this.put("G208", "PACECO");
        this.put("G209", "PACE DEL MELA");
        this.put("G210", "PACENTRO");
        this.put("G211", "PACHINO");
        this.put("G212", "PACIANO");
        this.put("G213", "PADENGHE");
        this.put("G213", "PADENGHE SUL GARDA");
        this.put("G214", "PADERGNONE");
        this.put("G215", "PADERNA");
        this.put("G215", "PADERNA");
        this.put("G216", "PADERNELLO");
        this.put("G217", "PADERNO");
        this.put("G217", "PADERNO FRANCIACORTA");
        this.put("G218", "PADERNO");
        this.put("G218", "PADERNO D'ADDA");
        this.put("G218", "PADERNO D'ADDA");
        this.put("G219", "PADERNO");
        this.put("G219", "PADERNO CREMONESE");
        this.put("G219", "PADERNO FASOLARO");
        this.put("G220", "PADERNO");
        this.put("G220", "PADERNO DUGNANO");
        this.put("G220", "PADERNO MILANESE");
        this.put("G221", "PADERNO");
        this.put("G221", "PADERNO D'ASOLO");
        this.put("G221", "PADERNO DEL GRAPPA");
        this.put("G222", "PADERNO OSSOLARO");
        this.put("G222", "PADERNO PONCHIELLI");
        this.put("G223", "PADERNO ROBBIATE");
        this.put("G223", "ROBBIATE");
        this.put("G223", "ROBBIATE PADERNO");
        this.put("G223", "ROBBIATE");
        this.put("G224", "PADOVA");
        this.put("G225", "PADRIA");
        this.put("G226", "PADULA");
        this.put("G227", "PADULI");
        this.put("G228", "PAESANA");
        this.put("G229", "PAESE");
        this.put("G230", "PAGANI");
        this.put("G231", "PAGANICA");
        this.put("G232", "PAGANICO SABINO");
        this.put("G233", "PAGAZZANO");
        this.put("G234", "PAGLIARA");
        this.put("G235", "PAGLIARE");
        this.put("G236", "PAGLIERES");
        this.put("G237", "PAGLIETA");
        this.put("G238", "PAGNACCO");
        this.put("G239", "PAGNANO");
        this.put("G239", "PAGNANO VALSASSINA");
        this.put("G240", "PAGNO");
        this.put("G241", "PAGNONA");
        this.put("G241", "PAGNONA");
        this.put("G242", "PAGO");
        this.put("G242", "PAGO DEL VALLO DI LAURO");
        this.put("G243", "PAGO");
        this.put("G243", "PAGO VEIANO");
        this.put("G244", "PAINA");
        this.put("G245", "PAIRANA");
        this.put("G246", "PAISCO");
        this.put("G247", "PAISCO LOVENO");
        this.put("G248", "PAITONE");
        this.put("G249", "PALADINA");
        this.put("G250", "PALAGANO");
        this.put("G251", "PALAGIANELLO");
        this.put("G252", "PALAGIANO");
        this.put("G253", "PALAGONIA");
        this.put("G254", "PALAIA");
        this.put("G255", "PALANZANO");
        this.put("G256", "PALANZO");
        this.put("G257", "PALATA");
        this.put("G258", "PALAU");
        this.put("G258", "PALAU");
        this.put("G259", "PALAZZAGO");
        this.put("G260", "PALAZZO");
        this.put("G260", "PALAZZO PIGNANO");
        this.put("G260", "PALAZZO PUGNANO");
        this.put("G261", "PALAZZO");
        this.put("G261", "PALAZZO SAN GERVASIO");
        this.put("G262", "PALAZZO");
        this.put("G262", "PALAZZO CANAVESE");
        this.put("G263", "PALAZZO ADRIANO");
        this.put("G264", "PALAZZOLO");
        this.put("G264", "PALAZZOLO SULL'OGLIO");
        this.put("G265", "PALAZZOLO");
        this.put("G265", "PALAZZOLO MILANESE");
        this.put("G266", "PALAZZOLO");
        this.put("G266", "PALAZZOLO VERCELLESE");
        this.put("G267", "PALAZZOLO ACREIDE");
        this.put("G268", "PALAZZOLO");
        this.put("G268", "PALAZZOLO DELLO STELLA");
        this.put("G269", "PALAZZO PIVERONE");
        this.put("G269", "PALAZZO PIVERONE");
        this.put("G270", "PALAZZUOLO");
        this.put("G270", "PALAZZUOLO DI ROMAGNA");
        this.put("G270", "PALAZZUOLO SUL SENIO");
        this.put("G271", "PALENA");
        this.put("G272", "PALERMITI");
        this.put("G273", "PALERMO");
        this.put("G274", "PALESTRINA");
        this.put("G275", "PALESTRO");
        this.put("G276", "PALIANO");
        this.put("G277", "PALIZZI");
        this.put("G278", "PALLAGORIO");
        this.put("G278", "PALLAGORIO");
        this.put("G279", "PALLANZA");
        this.put("G280", "PALLANZENO");
        this.put("G280", "PALLANZENO");
        this.put("G281", "PALLARE");
        this.put("G282", "PALMA");
        this.put("G282", "PALMA DI MONTECHIARO");
        this.put("G283", "PALMA");
        this.put("G283", "PALMA CAMPANIA");
        this.put("G284", "PALMANOVA");
        this.put("G285", "PALMARIGGI");
        this.put("G286", "PALMAS");
        this.put("G286", "PALMAS ARBOREA");
        this.put("G286", "PALMAS ARBOREA");
        this.put("G287", "PALMAS");
        this.put("G287", "PALMAS SUERGIU");
        this.put("G287", "SAN GIOVANNI SUERGIU");
        this.put("G287", "SAN GIOVANNI SUERGIU");
        this.put("G288", "PALMI");
        this.put("G289", "PALMIANO");
        this.put("G290", "PALMOLI");
        this.put("G291", "PALO");
        this.put("G291", "PALO DEL COLLE");
        this.put("G292", "PALO");
        this.put("G292", "PALOMONTE");
        this.put("G293", "PALOMBARA");
        this.put("G293", "PALOMBARA SABINA");
        this.put("G294", "PALOMBARO");
        this.put("G295", "PALOSCO");
        this.put("G296", "PALU'");
        this.put("G296", "PALU' DEL FERSINA");
        this.put("G297", "PALU'");
        this.put("G298", "PALUDI");
        this.put("G299", "PALUS * PLAUS");
        this.put("G299", "PLAUS * PLAUS");
        this.put("G300", "PALUZZA");
        this.put("G301", "PALVARETO");
        this.put("G301", "PALVARETO");
        this.put("G302", "PAMPARATO");
        this.put("G303", "PANCALIERI");
        this.put("G304", "PANCARANA");
        this.put("G305", "PANCHIA'");
        this.put("G306", "PANDINO");
        this.put("G307", "PANETTIERI");
        this.put("G308", "PANICALE");
        this.put("G309", "PANICOCOLI");
        this.put("G309", "VILLARICCA");
        this.put("G310", "PANIQUA");
        this.put("G311", "PANNARANO");
        this.put("G312", "PANNI");
        this.put("G313", "PANNONE");
        this.put("G313", "PANNONE");
        this.put("G314", "PANTASINA");
        this.put("G315", "PANTELLERIA");
        this.put("G316", "PANTIGLIATE");
        this.put("G317", "PAOLA");
        this.put("G318", "PAOLISI");
        this.put("G319", "PAPARELLA SAN MARCO");
        this.put("G319", "VALDERICE");
        this.put("G320", "PAPASIDERO");
        this.put("G321", "PAPIAGO");
        this.put("G322", "PAPIGNO");
        this.put("G323", "PAPOZZE");
        this.put("G324", "PARABIAGO");
        this.put("G325", "PARABITA");
        this.put("G326", "PARACORIO");
        this.put("G327", "PARATICO");
        this.put("G328", "PARCINES * PARTSCHINS");
        this.put("G329", "PARE'");
        this.put("G330", "PARELLA");
        this.put("G331", "PARENTI");
        this.put("G332", "PARENZO");
        this.put("G333", "PARETE");
        this.put("G334", "PARETO");
        this.put("G335", "PARGHELIA");
        this.put("G335", "PARGHELIA");
        this.put("G336", "PARLASCO");
        this.put("G336", "PARLASCO");
        this.put("G337", "PARMA");
        this.put("G338", "PARODI");
        this.put("G338", "PARODI LIGURE");
        this.put("G339", "PAROLDO");
        this.put("G340", "PAROLISE");
        this.put("G341", "PARONA");
        this.put("G341", "PARONA ALL'ADIGE");
        this.put("G341", "PARONA DI VALPOLICELLA");
        this.put("G342", "PARONA");
        this.put("G343", "PARONE");
        this.put("G344", "PARRANO");
        this.put("G345", "PARRAVICINO");
        this.put("G346", "PARRE");
        this.put("G347", "PARTANNA");
        this.put("G348", "PARTINICO");
        this.put("G349", "PARUZZARO");
        this.put("G350", "PARZANICA");
        this.put("G351", "PASCELUPO");
        this.put("G352", "PASIAN DI PRATO");
        this.put("G353", "PASIANO DI PORDENONE");
        this.put("G354", "PASPARDO");
        this.put("G355", "PASSARERA");
        this.put("G356", "PASSARIANO");
        this.put("G356", "RIVOLTO");
        this.put("G357", "PASSERANO");
        this.put("G358", "PASSERANO MARMORITO");
        this.put("G359", "PASSIGNANO");
        this.put("G359", "PASSIGNANO SUL TRASIMENO");
        this.put("G360", "PASSIRANA");
        this.put("G360", "PASSIRANA MILANESE");
        this.put("G361", "PASSIRANO");
        this.put("G362", "PASTENA");
        this.put("G363", "PASTENE");
        this.put("G364", "PASTORANO");
        this.put("G365", "PASTRENGO");
        this.put("G366", "PASTURAGO");
        this.put("G367", "PASTURANA");
        this.put("G368", "PASTURO");
        this.put("G368", "PASTURO");
        this.put("G369", "PATERNO");
        this.put("G369", "PATERNO D'ANCONA");
        this.put("G370", "PATERNO");
        this.put("G370", "PATERNOPOLI");
        this.put("G371", "PATERNO'");
        this.put("G372", "PATERNO");
        this.put("G372", "PATERNO CALABRO");
        this.put("G373", "PATONE");
        this.put("G374", "PATRICA");
        this.put("G375", "PATRIGNONE");
        this.put("G376", "PATTADA");
        this.put("G377", "PATTI");
        this.put("G378", "PATU'");
        this.put("G379", "PAU");
        this.put("G379", "PAU");
        this.put("G380", "PAUGNANO");
        this.put("G381", "PAULARO");
        this.put("G382", "PAULI ARBAREI");
        this.put("G382", "PAULI ARBAREI");
        this.put("G383", "PAULI GERREI");
        this.put("G383", "SAN NICOLO' GERREI");
        this.put("G384", "PAULILATINO");
        this.put("G384", "PAULILATINO");
        this.put("G385", "PAULLO");
        this.put("G386", "PAUPISI");
        this.put("G387", "PAVAROLO");
        this.put("G388", "PAVIA");
        this.put("G389", "PAVIA");
        this.put("G389", "PAVIA DI UDINE");
        this.put("G390", "PAVONE");
        this.put("G390", "PAVONE D'ALESSANDRIA");
        this.put("G391", "PAVONE");
        this.put("G391", "PAVONE DEL MELLA");
        this.put("G392", "PAVONE");
        this.put("G392", "PAVONE CANAVESE");
        this.put("G393", "PAVULLO");
        this.put("G393", "PAVULLO NEL FRIGNANO");
        this.put("G394", "PAZZANO");
        this.put("G395", "PECCIOLI");
        this.put("G396", "PECCO");
        this.put("G397", "PECETTO");
        this.put("G397", "PECETTO DI VALENZA");
        this.put("G398", "PECETTO TORINESE");
        this.put("G399", "PECORARA");
        this.put("G400", "PEDACE");
        this.put("G401", "PEDANEA");
        this.put("G401", "PEDANEA");
        this.put("G401", "PEDANEA");
        this.put("G401", "PEDANEA");
        this.put("G401", "PEDANEA");
        this.put("G402", "PEDARA");
        this.put("G403", "PEDASO");
        this.put("G403", "PEDASO");
        this.put("G404", "PEDAVENA");
        this.put("G405", "PEDAVOLI");
        this.put("G406", "PEDEMONTE");
        this.put("G407", "PEDERGNAGA");
        this.put("G407", "PEDERGNAGA-ORIANO");
        this.put("G407", "SAN PAOLO");
        this.put("G408", "PEDEROBBA");
        this.put("G409", "PEDERSANO");
        this.put("G410", "PEDESINA");
        this.put("G411", "PEDIVIGLIANO");
        this.put("G412", "PEDRENGO");
        this.put("G413", "PEDRIANO");
        this.put("G414", "PEGLI");
        this.put("G415", "PEGLIO");
        this.put("G416", "PEGLIO");
        this.put("G417", "PEGOGNAGA");
        this.put("G418", "PEIA");
        this.put("G419", "PEIO");
        this.put("G420", "PELAGO");
        this.put("G421", "PELLA");
        this.put("G422", "PELLARO");
        this.put("G423", "PELLEGRINO");
        this.put("G423", "PELLEGRINO DA CAREGGI");
        this.put("G423", "PELLEGRINO DA CAREGGI");
        this.put("G423", "PELLEGRINO DA CAREGGI");
        this.put("G424", "PELLEGRINO");
        this.put("G424", "PELLEGRINO PARMENSE");
        this.put("G425", "PELLESTRINA");
        this.put("G426", "PELLEZZANO");
        this.put("G427", "PELLIO INTELVI");
        this.put("G428", "PELLIZZANO");
        this.put("G429", "PELUGO");
        this.put("G430", "PENANGO");
        this.put("G431", "PENDOLASCO");
        this.put("G431", "POGGIRIDENTI");
        this.put("G432", "PENNA");
        this.put("G432", "PENNA IN TEVERINA");
        this.put("G433", "PENNABILLI");
        this.put("G433", "PENNABILLI");
        this.put("G434", "PENNADOMO");
        this.put("G435", "PENNAPIEDIMONTE");
        this.put("G436", "PENNA SAN GIOVANNI");
        this.put("G437", "PENNA SANT'ANDREA");
        this.put("G438", "PENNE");
        this.put("G439", "PENTONE");
        this.put("G440", "PENZANO");
        this.put("G441", "PERANO");
        this.put("G442", "PERAROLO");
        this.put("G442", "PERAROLO DI CADORE");
        this.put("G443", "PERCA * PERCHA");
        this.put("G443", "PERGA * PERCHA");
        this.put("G444", "PERCILE");
        this.put("G445", "PERDASDEFOGU");
        this.put("G445", "PERDASDEFOGU");
        this.put("G446", "PERDAXIUS");
        this.put("G446", "PERDAXIUS");
        this.put("G447", "PERDIFUMO");
        this.put("G448", "PEREGO");
        this.put("G448", "PEREGO");
        this.put("G449", "PERETO");
        this.put("G450", "PERFUGAS");
        this.put("G451", "PERGINE");
        this.put("G451", "PERGINE VALDARNO");
        this.put("G451", "VAL D'AMBRA");
        this.put("G452", "PERGINE");
        this.put("G452", "PERGINE VALSUGANA");
        this.put("G453", "PERGOLA");
        this.put("G454", "PERINALDO");
        this.put("G455", "PERITO");
        this.put("G456", "PERLEDO");
        this.put("G456", "PERLEDO");
        this.put("G457", "PERLETTO");
        this.put("G458", "PERLO");
        this.put("G459", "PERLOZ");
        this.put("G460", "PERNO");
        this.put("G461", "PERNUMIA");
        this.put("G462", "PEROSA");
        this.put("G462", "PEROSA CANAVESE");
        this.put("G463", "PEROSA");
        this.put("G463", "PEROSA ARGENTINA");
        this.put("G464", "PERA");
        this.put("G465", "PERRERO");
        this.put("G466", "PERRILLO");
        this.put("G467", "PERSICETO");
        this.put("G467", "SAN GIOVANNI IN PERSICETO");
        this.put("G468", "PERSICO");
        this.put("G469", "PERSICO DOSIMO");
        this.put("G470", "PERSONE");
        this.put("G471", "PERTENGO");
        this.put("G472", "PERTEOLE");
        this.put("G473", "PERTI");
        this.put("G474", "PERTICA ALTA");
        this.put("G475", "PERTICA BASSA");
        this.put("G476", "PERTOSA");
        this.put("G477", "PERTUSIO");
        this.put("G478", "PERUGIA");
        this.put("G479", "PESARO");
        this.put("G480", "PESCAGLIA");
        this.put("G481", "PESCANTINA");
        this.put("G482", "PESCARA");
        this.put("G483", "PESCAROLO");
        this.put("G483", "PESCAROLO ED UNITI");
        this.put("G484", "PESCASSEROLI");
        this.put("G485", "PESCATE");
        this.put("G485", "PESCATE");
        this.put("G486", "PESCHE");
        this.put("G487", "PESCHICI");
        this.put("G488", "PESCHIERA");
        this.put("G488", "PESCHIERA BORROMEO");
        this.put("G489", "PESCHIERA");
        this.put("G489", "PESCHIERA DEL GARDA");
        this.put("G489", "PESCHIERA SUL LAGO DI GARDA");
        this.put("G490", "PESCHIERA D'ISEO");
        this.put("G490", "PESCHIERA MARAGLIO");
        this.put("G491", "PESCIA");
        this.put("G492", "PESCINA");
        this.put("G493", "PESCOCOSTANZO");
        this.put("G494", "PESCOLAMAZZA");
        this.put("G494", "PESCO SANNITA");
        this.put("G495", "PESCOLANCIANO");
        this.put("G496", "PESCOPAGANO");
        this.put("G497", "PESCOPENNATARO");
        this.put("G498", "PESCOROCCHIANO");
        this.put("G499", "PESCOSANSONESCO");
        this.put("G500", "PESCOSOLIDO");
        this.put("G501", "PESSANO");
        this.put("G502", "PESSANO CON BORNAGO");
        this.put("G503", "PESSINA");
        this.put("G503", "PESSINA VALSASSINA");
        this.put("G504", "PESSINA");
        this.put("G504", "PESSINA CREMONESE");
        this.put("G504", "PESSINA CREMONESE ED UNITI");
        this.put("G505", "PESSINETTO");
        this.put("G506", "PETACCIATO");
        this.put("G507", "PETESCIA");
        this.put("G507", "TURANIA");
        this.put("G508", "PETILIA POLICASTRO");
        this.put("G508", "POLICASTRO");
        this.put("G508", "PETILIA POLICASTRO");
        this.put("G509", "PETINA");
        this.put("G510", "PETRALIA SOPRANA");
        this.put("G511", "PETRALIA SOTTANA");
        this.put("G512", "PETRELLA");
        this.put("G512", "PETRELLA TIFERNINA");
        this.put("G513", "PETRELLA");
        this.put("G513", "PETRELLA SALTO");
        this.put("G514", "PETRIANO");
        this.put("G515", "PETRIOLO");
        this.put("G516", "PETRITOLI");
        this.put("G516", "PETRITOLI");
        this.put("G517", "PETRIZZI");
        this.put("G518", "PETRONA'");
        this.put("G519", "PETRURO");
        this.put("G519", "PETRURO IRPINO");
        this.put("G520", "PETTENASCO");
        this.put("G521", "PETTINENGO");
        this.put("G521", "PETTINENGO");
        this.put("G522", "PETTINEO");
        this.put("G523", "PETTORANELLO DI MOLISE");
        this.put("G523", "PETTORANO");
        this.put("G523", "PETTORANELLO DEL MOLISE");
        this.put("G524", "PETTORANO");
        this.put("G524", "PETTORANO SUL GIZIO");
        this.put("G525", "PETTORAZZA GRIMANI");
        this.put("G526", "PEVERAGNO");
        this.put("G527", "PEVERANZA");
        this.put("G528", "PEZZANA");
        this.put("G529", "PEZZAZE");
        this.put("G530", "PEZZOLO DE' CODAZZI");
        this.put("G531", "PEZZOLO DI TAVAZZANO");
        this.put("G532", "PEZZOLO VALLE UZZONE");
        this.put("G533", "PEZZORO");
        this.put("G534", "PIACENZA");
        this.put("G534", "PIACENZA D'ADIGE");
        this.put("G535", "PIACENZA");
        this.put("G536", "PIADENA");
        this.put("G537", "PIAGGE");
        this.put("G538", "PIAGGINE");
        this.put("G539", "PIAGGINE SOPRANE");
        this.put("G540", "PIAGGINE SOTTANE");
        this.put("G540", "VALLE DELL'ANGELO");
        this.put("G540", "VALLE DELL'ANGELO");
        this.put("G541", "PIANA");
        this.put("G541", "PIANA DI CAIAZZO");
        this.put("G541", "PIANA DI MONTE VERNA");
        this.put("G542", "PIANA");
        this.put("G542", "PIANA CRIXIA");
        this.put("G543", "PIANA DEGLI ALBANESI");
        this.put("G543", "PIANA DEI GRECI");
        this.put("G544", "PIANAVIA");
        this.put("G545", "PIANBOSETO");
        this.put("G545", "PONTBOSET");
        this.put("G545", "PONT BOZET");
        this.put("G546", "PIAN CAMUNO");
        this.put("G546", "PIANO");
        this.put("G547", "PIANCASTAGNAIO");
        this.put("G548", "PIANCERI");
        this.put("G549", "PIANCOGNO");
        this.put("G550", "PIAN D'ARTOGNE");
        this.put("G550", "PIAN D'ARTOGNE");
        this.put("G551", "PIANDIMELETO");
        this.put("G552", "PIAN DI SCO");
        this.put("G553", "PIANE");
        this.put("G553", "PIANE CRATI");
        this.put("G554", "PIANE");
        this.put("G554", "PIANE DI SERRAVALLE SESIA");
        this.put("G554", "PIANE SESIA");
        this.put("G555", "PIANELLA");
        this.put("G556", "PIANELLO");
        this.put("G556", "PIANELLO DEL LARIO");
        this.put("G557", "PIANELLO");
        this.put("G557", "PIANELLO VAL TIDONE");
        this.put("G558", "PIANENGO");
        this.put("G558", "PIANENGO");
        this.put("G559", "PIANEZZA");
        this.put("G560", "PIANEZZE");
        this.put("G561", "PIANFEI");
        this.put("G562", "PIAN GAIANO");
        this.put("G563", "PIANI");
        this.put("G564", "PIANICO");
        this.put("G565", "PIANIGA");
        this.put("G566", "PIANO");
        this.put("G566", "PIANO DEL VOGLIO");
        this.put("G566", "SAN BENEDETTO VAL DI SAMBRO");
        this.put("G567", "PIANO");
        this.put("G567", "PIANO PORLEZZA");
        this.put("G568", "PIANO");
        this.put("G568", "PIANO DI SORRENTO");
        this.put("G569", "PIANO");
        this.put("G570", "PIANORO");
        this.put("G571", "PIANSANO");
        this.put("G572", "PIANTEDO");
        this.put("G573", "PIANURA");
        this.put("G574", "PIARIO");
        this.put("G574", "PIARIO");
        this.put("G575", "PIASCO");
        this.put("G576", "PIATEDA");
        this.put("G577", "PIATTO");
        this.put("G577", "PIATTO");
        this.put("G578", "PIAVON");
        this.put("G579", "PIAZZA");
        this.put("G579", "PIAZZA BREMBANA");
        this.put("G580", "PIAZZA");
        this.put("G580", "PIAZZA ARMERINA");
        this.put("G581", "PIAZZA");
        this.put("G581", "PIAZZA SANTO STEFANO");
        this.put("G582", "PIAZZA AL SERCHIO");
        this.put("G582", "PIAZZA");
        this.put("G583", "PIAZZATORRE");
        this.put("G584", "PIAZZO");
        this.put("G585", "PIAZZO ALTO");
        this.put("G586", "PIAZZO BASSO");
        this.put("G587", "PIAZZOLA");
        this.put("G587", "PIAZZOLA SUL BRENTA");
        this.put("G588", "PIAZZOLO");
        this.put("G589", "PICCIANO");
        this.put("G590", "PICERNO");
        this.put("G591", "PICINISCO");
        this.put("G592", "PICO");
        this.put("G593", "PIEA");
        this.put("G594", "PIEDICAVALLO");
        this.put("G594", "PIEDICAVALLO");
        this.put("G595", "PIEDILUCO");
        this.put("G596", "PIEDIMONTE");
        this.put("G596", "PIEDIMONTE D'ALIFE");
        this.put("G596", "PIEDIMONTE MATESE");
        this.put("G597", "PIEDIMONTE");
        this.put("G597", "PIEDIMONTE ETNEO");
        this.put("G598", "PIEDIMONTE");
        this.put("G598", "PIEDIMONTE SAN GERMANO");
        this.put("G599", "PIEDIMONTE DEL CALVARIO");
        this.put("G599", "PODGORA");
        this.put("G600", "PIEDIMULERA");
        this.put("G600", "PIEDIMULERA");
        this.put("G601", "PIEGARO");
        this.put("G602", "PIENZA");
        this.put("G603", "PIERANICA");
        this.put("G604", "PIETRA");
        this.put("G604", "PIETRAMONTECORVINO");
        this.put("G605", "PIETRA");
        this.put("G605", "PIETRA LIGURE");
        this.put("G606", "PIETRABBONDANTE");
        this.put("G607", "PIETRABRUNA");
        this.put("G608", "PIETRACAMELA");
        this.put("G609", "PIETRACATELLA");
        this.put("G610", "PIETRACUPA");
        this.put("G611", "PIETRADEFUSI");
        this.put("G612", "PIETRA DE' GIORGI");
        this.put("G613", "PIETRAFERRAZZANA");
        this.put("G614", "PIETRAFESA");
        this.put("G614", "SATRIANO DI LUCANIA");
        this.put("G615", "PIETRAFITTA");
        this.put("G616", "PIETRAGALLA");
        this.put("G617", "PIETRA GAVINA");
        this.put("G618", "PIETRALUNGA");
        this.put("G619", "PIETRA MARAZZI");
        this.put("G620", "PIETRAMELARA");
        this.put("G621", "PIETRANICO");
        this.put("G622", "PIETRAPAOLA");
        this.put("G623", "PIETRAPERTOSA");
        this.put("G624", "PIETRAPERZIA");
        this.put("G625", "PIETRAPORZIO");
        this.put("G626", "PIETRAROJA");
        this.put("G627", "PIETRARUBBIA");
        this.put("G628", "PIETRASANTA");
        this.put("G629", "PIETRASTORNINA");
        this.put("G630", "PIETRAVAIRANO");
        this.put("G631", "PIETRELCINA");
        this.put("G632", "PIEVE");
        this.put("G632", "PIEVE DI TECO");
        this.put("G633", "PIEVE");
        this.put("G633", "PIEVE DI CORIANO");
        this.put("G634", "PIEVE");
        this.put("G634", "PIEVE EMANUELE");
        this.put("G635", "PIEVE ALBIGNOLA");
        this.put("G636", "PIEVE A NIEVOLE");
        this.put("G637", "PIEVEBOVIGLIANA");
        this.put("G638", "PIEVE D'ALPAGO");
        this.put("G639", "PIEVE DEL CAIRO");
        this.put("G640", "PIEVE DELMONA");
        this.put("G641", "PIEVE DI BONO");
        this.put("G642", "PIEVE DI CADORE");
        this.put("G643", "PIEVE DI CENTO");
        this.put("G644", "PIEVE DI LEDRO");
        this.put("G645", "PIEVE DI SOLIGO");
        this.put("G646", "PIEVE DI SORI");
        this.put("G646", "PIEVE LIGURE");
        this.put("G647", "PIEVE D'OLMI");
        this.put("G648", "PIEVE FOSCIANA");
        this.put("G649", "PIEVEPELAGO");
        this.put("G650", "PIEVE PORTO MORONE");
        this.put("G651", "PIEVE SAN GIACOMO");
        this.put("G652", "PIEVE SAN MAURIZIO");
        this.put("G653", "PIEVE SANTO STEFANO");
        this.put("G654", "PIEVE SAN VINCENZO");
        this.put("G654", "RAMISETO");
        this.put("G655", "PIEVE TERZAGNI");
        this.put("G656", "PIEVE TESINO");
        this.put("G657", "PIEVE TORINA");
        this.put("G658", "PIEVE VERGONTE");
        this.put("G658", "PIEVE VERGONTE");
        this.put("G659", "PIGLIO");
        this.put("G660", "PIGNA");
        this.put("G661", "PIGNATARO");
        this.put("G661", "PIGNATARO MAGGIORE");
        this.put("G662", "PIGNATARO");
        this.put("G662", "PIGNATARO INTERAMNA");
        this.put("G663", "PIGNOLA");
        this.put("G663", "PIGNOLA DI BASILICATA");
        this.put("G663", "VIGNOLA");
        this.put("G664", "PIGNONE");
        this.put("G665", "PIGRA");
        this.put("G666", "PILA");
        this.put("G667", "PILCANTE");
        this.put("G668", "PILZONE");
        this.put("G669", "PIMENTEL");
        this.put("G670", "PIMONTE");
        this.put("G671", "PINAROLO");
        this.put("G671", "PINAROLO PO");
        this.put("G672", "PINASCA");
        this.put("G673", "PINCARA");
        this.put("G674", "PINEROLO");
        this.put("G675", "PINGUENTE");
        this.put("G676", "PINO");
        this.put("G676", "PINO D'ASTI");
        this.put("G677", "PINO");
        this.put("G677", "PINO SULLA SPONDA DEL LAGO MAGGIORE");
        this.put("G678", "PINO DI CHIERI");
        this.put("G678", "PINO TORINESE");
        this.put("G679", "PINZANO");
        this.put("G680", "PINZANO AL TAGLIAMENTO");
        this.put("G680", "PINZANO");
        this.put("G681", "PINZOLO");
        this.put("G682", "PIOBBICO");
        this.put("G683", "PIOBESI");
        this.put("G683", "PIOBESI D'ALBA");
        this.put("G684", "PIOBESI");
        this.put("G684", "PIOBESI TORINESE");
        this.put("G685", "PIODE");
        this.put("G686", "PIOLTELLO");
        this.put("G687", "PIOMBINO");
        this.put("G688", "PIOMBINO");
        this.put("G688", "PIOMBINO DESE");
        this.put("G689", "PIONE");
        this.put("G690", "PIORACO");
        this.put("G691", "PIOSSASCO");
        this.put("G692", "PIOVA'");
        this.put("G692", "PIOVA' MASSAIA");
        this.put("G693", "PIOVE DI SACCO");
        this.put("G694", "PIOVENE");
        this.put("G694", "PIOVENE ROCCHETTE");
        this.put("G695", "PIOVERA");
        this.put("G696", "PIOZZANO");
        this.put("G696", "POMARO");
        this.put("G696", "POMARO PIACENTINO");
        this.put("G697", "PIOZZO");
        this.put("G698", "PRIVERNO");
        this.put("G698", "PIPERNO");
        this.put("G699", "PIRAINO");
        this.put("G700", "PIRANO");
        this.put("G701", "PIRRI");
        this.put("G702", "PISA");
        this.put("G703", "PISANO");
        this.put("G704", "PISCIANO");
        this.put("G704", "PISONIANO");
        this.put("G705", "PISCINA");
        this.put("G706", "PISCINOLA");
        this.put("G707", "PISCIOTTA");
        this.put("G708", "PISCOPIO");
        this.put("G709", "PISINO");
        this.put("G710", "PISOGNE");
        this.put("G711", "PISSARELLO");
        this.put("G712", "PISTICCI");
        this.put("G713", "PISTOIA");
        this.put("G714", "PISTOLESA");
        this.put("G714", "PISTOLESA");
        this.put("G715", "PITEGLIO");
        this.put("G716", "PITIGLIANO");
        this.put("G717", "PIUBEGA");
        this.put("G718", "PIURO");
        this.put("G719", "PIVERONE");
        this.put("G720", "PIZZALE");
        this.put("G721", "PIZZIGHETTONE");
        this.put("G722", "PIZZO");
        this.put("G722", "PIZZO");
        this.put("G723", "PIZZOCORNO");
        this.put("G724", "PIZZOFERRATO");
        this.put("G725", "PIZZOLANO");
        this.put("G726", "PIZZOLI");
        this.put("G727", "PIZZONE");
        this.put("G728", "PIZZONI");
        this.put("G728", "PIZZONI");
        this.put("G729", "PLACANICA");
        this.put("G730", "PLAGNOLO * PLANEIL");
        this.put("G730", "PLANOL * PLANEIL");
        this.put("G731", "PLANINA");
        this.put("G732", "PLATA * PLATT");
        this.put("G732", "PLATEA * PLATT");
        this.put("G733", "PLATACI");
        this.put("G734", "PLATANIA");
        this.put("G735", "PLATI'");
        this.put("G736", "PLATISCHIS");
        this.put("G736", "TAIPANA");
        this.put("G737", "PLESIO");
        this.put("G738", "PLEZZO");
        this.put("G739", "PLISCOVIZZA DELLA MADONNA");
        this.put("G740", "PLOAGHE");
        this.put("G741", "PLODIO");
        this.put("G742", "POCAPAGLIA");
        this.put("G743", "POCENIA");
        this.put("G744", "POCRAI DEL PERO");
        this.put("G745", "PODARGONI");
        this.put("G746", "PODENZANA");
        this.put("G747", "PODENZANO");
        this.put("G748", "PODRAGA");
        this.put("G749", "POFI");
        this.put("G750", "POGGI");
        this.put("G751", "POGGIARDO");
        this.put("G752", "POGGIBONSI");
        this.put("G753", "POGGIO");
        this.put("G753", "POGGIO RUSCO");
        this.put("G754", "POGGIO A CAIANO");
        this.put("G754", "POGGIO A CAIANO");
        this.put("G755", "POGGIO BERNI");
        this.put("G755", "POGGIO BERNI");
        this.put("G756", "POGGIO BUSTONE");
        this.put("G757", "POGGIO CATINO");
        this.put("G758", "POGGIODOMO");
        this.put("G759", "POGGIO FIDONI");
        this.put("G760", "POGGIOFIORITO");
        this.put("G760", "VILLARIELLI");
        this.put("G761", "POGGIO IMPERIALE");
        this.put("G762", "POGGIOMARINO");
        this.put("G763", "POGGIO MIRTETO");
        this.put("G764", "POGGIO MOIANO");
        this.put("G765", "POGGIO NATIVO");
        this.put("G766", "POGGIO PICENZE");
        this.put("G767", "POGGIOREALE");
        this.put("G768", "POGGIO RENATICO");
        this.put("G769", "POGGIORSINI");
        this.put("G770", "POGGIO SAN LORENZO");
        this.put("G771", "POGGIO SAN MARCELLO");
        this.put("G772", "POGLIANO");
        this.put("G772", "POGLIANO MILANESE");
        this.put("G773", "POGNANA");
        this.put("G773", "POGNANA LARIO");
        this.put("G774", "POGNANO");
        this.put("G775", "POGNO");
        this.put("G776", "POIANA MAGGIORE");
        this.put("G777", "POIRINO");
        this.put("G778", "POLA");
        this.put("G779", "POLAVENO");
        this.put("G780", "POLCENIGO");
        this.put("G781", "POLENGO");
        this.put("G782", "POLESELLA");
        this.put("G783", "POLESINE");
        this.put("G783", "POLESINE PARMENSE");
        this.put("G784", "POLI");
        this.put("G785", "POLIA");
        this.put("G785", "POLIA");
        this.put("G786", "POLICORO");
        this.put("G787", "POLIGNANO");
        this.put("G787", "POLIGNANO A MARE");
        this.put("G788", "POLIGNANO");
        this.put("G788", "POLIGNANO PIACENTINO");
        this.put("G788", "SAN PIETRO IN CERRO");
        this.put("G789", "POLINAGO");
        this.put("G790", "POLINO");
        this.put("G791", "POLISTENA");
        this.put("G792", "POLIZZI");
        this.put("G792", "POLIZZI GENEROSA");
        this.put("G793", "POLLA");
        this.put("G794", "POLLEIN");
        this.put("G795", "POLLENA TROCCHIA");
        this.put("G796", "POLLICA");
        this.put("G797", "POLLINA");
        this.put("G798", "POLLONE");
        this.put("G798", "POLLONE");
        this.put("G799", "POLLUTRI");
        this.put("G800", "POLONGHERA");
        this.put("G801", "POLPENAZZE DEL GARDA");
        this.put("G802", "POLVERARA");
        this.put("G803", "POLVERIGI");
        this.put("G804", "POMARANCE");
        this.put("G805", "POMARETTO");
        this.put("G806", "POMARICO");
        this.put("G807", "POMARO");
        this.put("G807", "POMARO MONFERRATO");
        this.put("G808", "POMAROLO");
        this.put("G809", "POMBIA");
        this.put("G810", "POMETO");
        this.put("G810", "POMETO");
        this.put("G811", "POMEZIA");
        this.put("G812", "POMIGLIANO D'ARCO");
        this.put("G813", "POMPEI");
        this.put("G814", "POMPEIANA");
        this.put("G815", "POMPIANO");
        this.put("G816", "POMPONESCO");
        this.put("G817", "POMPU");
        this.put("G817", "POMPU");
        this.put("G817", "POMPU");
        this.put("G818", "PONCARALE");
        this.put("G819", "PONCARALE FLERO");
        this.put("G819", "PONCARALE FLERO");
        this.put("G820", "PONDERANO");
        this.put("G820", "PONDERANO");
        this.put("G821", "PONNA");
        this.put("G822", "PONSACCO");
        this.put("G823", "PONSO");
        this.put("G824", "PONTAGNA");
        this.put("G825", "PONTASSIEVE");
        this.put("G826", "PONT CANAVESE");
        this.put("G827", "PONTE");
        this.put("G828", "PONTE");
        this.put("G829", "PONTE");
        this.put("G829", "PONTE IN VALTELLINA");
        this.put("G830", "PONTE ALL'ISARCO * WAIDBRUCK");
        this.put("G830", "PONTE GARDENA * WAIDBRUCK");
        this.put("G831", "PONTEBBA");
        this.put("G832", "PONTEBBA NOVA");
        this.put("G832", "PONTEFELLA");
        this.put("G833", "PONTE BUGGIANESE");
        this.put("G834", "PONTECAGNANO FAIANO");
        this.put("G835", "PONTE CARATE");
        this.put("G836", "PONTECCHIO");
        this.put("G836", "PONTECCHIO POLESINE");
        this.put("G837", "PONTECHIANALE");
        this.put("G838", "PONTECORVO");
        this.put("G839", "PONTECURONE");
        this.put("G840", "PONTEDASSIO");
        this.put("G841", "PONTEDECIMO");
        this.put("G842", "PONTE DELL'OLIO");
        this.put("G843", "PONTEDERA");
        this.put("G844", "PONTE DI LEGNO");
        this.put("G845", "PONTE DI NOSSA");
        this.put("G846", "PONTE DI PIAVE");
        this.put("G847", "PONTE LAMBRO");
        this.put("G847", "PONTELEZZA");
        this.put("G848", "PONTELANDOLFO");
        this.put("G849", "PONTELATONE");
        this.put("G850", "PONTELONGO");
        this.put("G851", "PONTE NIZZA");
        this.put("G852", "PONTENURE");
        this.put("G853", "PONTERANICA");
        this.put("G854", "PONTE SAN MARTINO");
        this.put("G854", "PONT-SAINT-MARTIN");
        this.put("G855", "PONTE SAN NICOLO'");
        this.put("G856", "PONTE SAN PIETRO");
        this.put("G857", "PONTESESTO");
        this.put("G858", "PONTESTURA");
        this.put("G859", "PONTEVICO");
        this.put("G860", "PONTEY");
        this.put("G861", "PONTI");
        this.put("G862", "PONTI SUL MINCIO");
        this.put("G862", "PONTI");
        this.put("G863", "PONTICELLI");
        this.put("G864", "PONTIDA");
        this.put("G864", "PONTITA");
        this.put("G865", "PONTINIA");
        this.put("G866", "PONTINVREA");
        this.put("G867", "PONTIROLO");
        this.put("G867", "PONTIROLO NUOVO");
        this.put("G868", "PONTIROLO");
        this.put("G868", "PONTIROLO CAPREDONI");
        this.put("G869", "PONTOGLIO");
        this.put("G870", "PONTREMOLI");
        this.put("G871", "PONZA");
        this.put("G872", "PONZANO");
        this.put("G872", "PONZANO MONFERRATO");
        this.put("G873", "PONZANO");
        this.put("G873", "PONZANO DI FERMO");
        this.put("G873", "PONZANO DI FERMO");
        this.put("G874", "PONZANO");
        this.put("G874", "PONZANO ROMANO");
        this.put("G875", "PONZANO");
        this.put("G875", "PONZANO VENETO");
        this.put("G876", "PONZATE");
        this.put("G877", "PONZONE");
        this.put("G878", "POPOLI");
        this.put("G879", "POPPI");
        this.put("G880", "POR");
        this.put("G881", "PORANO");
        this.put("G882", "PORCARI");
        this.put("G883", "PORCHIA");
        this.put("G884", "PORCHIANO");
        this.put("G884", "PORCHIANO DEL MONTE");
        this.put("G885", "PORCHIANO ASCOLI");
        this.put("G885", "PORCHIANO DELL'ASCENSIONE");
        this.put("G886", "PORCIA");
        this.put("G887", "PORCILI");
        this.put("G887", "STELLA CILENTO");
        this.put("G888", "PORDENONE");
        this.put("G889", "PORLEZZA");
        this.put("G890", "PORNASSIO");
        this.put("G891", "PORPETTO");
        this.put("G892", "PORTA AL BORGO");
        this.put("G893", "PORTA CARRATICA");
        this.put("G894", "PORTACOMARO");
        this.put("G895", "PORTALBERA");
        this.put("G896", "PORTA LUCCHESE");
        this.put("G897", "PORTA OMBRIANO");
        this.put("G898", "PORTARIA");
        this.put("G899", "PORTA SAN MARCO");
        this.put("G900", "PORTE");
        this.put("G901", "PORTESE");
        this.put("G902", "PORTICI");
        this.put("G903", "PORTICO");
        this.put("G903", "PORTICO DI CASERTA");
        this.put("G904", "PORTICO E SAN BENEDETTO");
        this.put("G904", "PORTICO");
        this.put("G904", "PORTICO DI ROMAGNA");
        this.put("G905", "PORTIGLIOLA");
        this.put("G906", "PORTO");
        this.put("G906", "PORTO CERESIO");
        this.put("G907", "PORTO");
        this.put("G907", "PORTO VALTRAVAGLIA");
        this.put("G908", "PORTO");
        this.put("G908", "PORTO D'ADDA");
        this.put("G909", "PORTOBUFFOLE'");
        this.put("G910", "PORTOCANNONE");
        this.put("G911", "PORTO CIVITANOVA");
        this.put("G912", "PORTOFERRAIO");
        this.put("G913", "PORTOFINO");
        this.put("G914", "PORTOGRUARO");
        this.put("G915", "PORTOLE");
        this.put("G916", "PORTOMAGGIORE");
        this.put("G917", "PORTO MANTOVANO");
        this.put("G918", "PORTO MAURIZIO");
        this.put("G919", "PORTO RECANATI");
        this.put("G920", "PORTO SAN GIORGIO");
        this.put("G920", "PORTO SAN GIORGIO");
        this.put("G921", "PORTO SANT'ELPIDIO");
        this.put("G921", "PORTO SANT'ELPIDIO");
        this.put("G922", "PORTOSCUSO");
        this.put("G922", "PORTOSCUSO");
        this.put("G923", "PORTO TOLLE");
        this.put("G923", "SAN NICCOLO");
        this.put("G924", "PORTO TORRES");
        this.put("G925", "PORTOVENERE");
        this.put("G926", "PORTO VIRO");
        this.put("G926", "PORTO VIRO");
        this.put("G926", "TAGLIO DI PORTO VIRO");
        this.put("G926", "PORTO VIRO");
        this.put("G927", "PORTULA");
        this.put("G927", "PORTULA");
        this.put("G928", "PORZANO");
        this.put("G929", "POSADA");
        this.put("G930", "POSCANTE");
        this.put("G930", "POSCANTE");
        this.put("G931", "POSINA");
        this.put("G932", "POSITANO");
        this.put("G933", "POSSAGNO");
        this.put("G934", "POSTA");
        this.put("G935", "POSTA FIBRENO");
        this.put("G936", "POSTAL * BURGSTALL");
        this.put("G937", "POSTALESIO");
        this.put("G938", "POSTICCIOLA");
        this.put("G939", "POSTIGLIONE");
        this.put("G940", "POSTUA");
        this.put("G941", "POSTUMIA GROTTE");
        this.put("G942", "POTENZA");
        this.put("G943", "POVE");
        this.put("G943", "POVE DEL GRAPPA");
        this.put("G944", "POVEGLIANO");
        this.put("G945", "POVEGLIANO VERONESE");
        this.put("G946", "POVERIO");
        this.put("G947", "POVIGLIO");
        this.put("G948", "POVO");
        this.put("G949", "POVOLETTO");
        this.put("G950", "POZZA");
        this.put("G950", "POZZA DI FASSA");
        this.put("G951", "POZZAGLIA");
        this.put("G951", "POZZAGLIA SABINA");
        this.put("G952", "POZZAGLIO");
        this.put("G953", "POZZALLO");
        this.put("G954", "POZZILLI");
        this.put("G955", "POZZO");
        this.put("G955", "POZZO D'ADDA");
        this.put("G956", "POZZO");
        this.put("G956", "POZZO ALTO");
        this.put("G957", "POZZO");
        this.put("G957", "POZZOLEONE");
        this.put("G958", "POZZO BARONZIO");
        this.put("G959", "POZZOLENGO");
        this.put("G960", "POZZOL GROPPO");
        this.put("G961", "POZZOLO FORMIGARO");
        this.put("G962", "POZZOMAGGIORE");
        this.put("G963", "POZZONOVO");
        this.put("G964", "POZZUOLI");
        this.put("G965", "POZZUOLO");
        this.put("G965", "POZZUOLO MARTESANA");
        this.put("G966", "POZZUOLO");
        this.put("G966", "POZZUOLO DEL FRIULI");
        this.put("G967", "PRA");
        this.put("G968", "PRADALUNGA");
        this.put("G969", "PRADAMANO");
        this.put("G970", "PRADLEVE");
        this.put("G970", "PRADLEVES");
        this.put("G971", "PRADO");
        this.put("G972", "PRADURO E SASSO");
        this.put("G972", "SASSO BOLOGNESE");
        this.put("G972", "SASSO MARCONI");
        this.put("G973", "PRAGELATO");
        this.put("G974", "PRAY");
        this.put("G974", "PRAY");
        this.put("G975", "PRAIA A MARE");
        this.put("G976", "PRAIANO");
        this.put("G977", "PRALBOINO");
        this.put("G978", "PRALI");
        this.put("G978", "PRALY");
        this.put("G979", "PRALORMO");
        this.put("G980", "PRALUNGO");
        this.put("G980", "PRALUNGO");
        this.put("G981", "PRAMAGGIORE");
        this.put("G982", "PRAMOLLO");
        this.put("G983", "PRANDAGLIO");
        this.put("G984", "PRANZO");
        this.put("G985", "PRAROLO");
        this.put("G986", "PRAROSTINO");
        this.put("G987", "PRASCO");
        this.put("G988", "PRASCORSANO");
        this.put("G989", "PRASO");
        this.put("G990", "PRATA");
        this.put("G990", "PRATA DI PRINCIPATO ULTRA");
        this.put("G991", "PRATA");
        this.put("G991", "PRATA SANNITA");
        this.put("G992", "PRATA");
        this.put("G992", "PRATA D'ANSIDONIA");
        this.put("G993", "PRATA");
        this.put("G993", "PRATA CAMPORTACCIO");
        this.put("G994", "PRATA DI PORDENONE");
        this.put("G994", "PRATA");
        this.put("G995", "PRATELLA");
        this.put("G996", "PRATI * WIESEN");
        this.put("G997", "PRATIGLIONE");
        this.put("G998", "PRATO");
        this.put("G998", "PRATO MUZIO");
        this.put("G999", "PRATO");
        this.put("G999", "PRATO IN TOSCANA");
        this.put("G999", "PRATO");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
