package document;

import java.util.HashMap;

/**
 * Created by Matteo on 12/11/2015.
 */
@SuppressWarnings("serial")
public class CitiesCodes_F extends HashMap<String, String> {

    public CitiesCodes_F(){
        this.put("F001", "MARZI");
        this.put("F002", "MARZIO");
        this.put("F003", "MASATE");
        this.put("F004", "MASCALI");
        this.put("F005", "MASCALUCIA");
        this.put("F006", "MASCHITO");
        this.put("F007", "MASCIAGO");
        this.put("F007", "MASCIAGO PRIMO");
        this.put("F008", "MASCIAGO");
        this.put("F008", "MASCIAGO MILANESE");
        this.put("F009", "MASER");
        this.put("F010", "MASERA");
        this.put("F010", "MASERA");
        this.put("F011", "MASERA'");
        this.put("F011", "MASERA' DI PADOVA");
        this.put("F012", "MASERADA");
        this.put("F012", "MASERADA SUL PIAVE");
        this.put("F013", "MASI");
        this.put("F014", "MASI DI VIGO");
        this.put("F015", "MASIO");
        this.put("F016", "MASI TORELLO");
        this.put("F017", "MASLIANICO");
        this.put("F018", "MASNAGO");
        this.put("F019", "MASON");
        this.put("F019", "MASON VICENTINO");
        this.put("F020", "MASONE");
        this.put("F021", "MASSA");
        this.put("F021", "MASSA FERMANA");
        this.put("F021", "MASSA FERMANA");
        this.put("F022", "MASSA");
        this.put("F022", "MASSA D'ALBE");
        this.put("F023", "MASSA");
        this.put("F023", "MASSA-CARRARA");
        this.put("F024", "MASSA");
        this.put("F024", "MASSA MARTANA");
        this.put("F025", "MASSA E COZZILE");
        this.put("F026", "MASSA FISCAGLIA");
        this.put("F027", "MASSAFRA");
        this.put("F028", "MASSALENGO");
        this.put("F028", "MASSALENGO");
        this.put("F029", "MASSA LOMBARDA");
        this.put("F030", "MASSA LUBRENSE");
        this.put("F031", "MASSAMA");
        this.put("F032", "MASSA MARITTIMA");
        this.put("F033", "MASSANZAGO");
        this.put("F034", "MASSARI-MELZI");
        this.put("F035", "MASSAROSA");
        this.put("F036", "MASSA SUPERIORE");
        this.put("F037", "MASSAZZA");
        this.put("F037", "MASSAZZA");
        this.put("F038", "MASSE DEL TERZO DI CITTA'");
        this.put("F038", "MASSE DI CITTA'");
        this.put("F039", "MASSE DI SAN MARTINO");
        this.put("F040", "MASSE DI SIENA");
        this.put("F041", "MASSELLO");
        this.put("F042", "MASSERANO");
        this.put("F042", "MASSERANO");
        this.put("F043", "SAN MARCO EVANGELISTA");
        this.put("F043", "MASSERIE");
        this.put("F043", "SAN MARCO EVANGELISTA");
        this.put("F044", "MASSIGNANO");
        this.put("F045", "MASSIMENO");
        this.put("F046", "MASSIMINO");
        this.put("F047", "MASSINO");
        this.put("F047", "MASSINO VISCONTI");
        this.put("F048", "MASSIOLA");
        this.put("F048", "MASSIOLA");
        this.put("F049", "MASTELLINA");
        this.put("F050", "MASULLAS");
        this.put("F050", "MASULLAS");
        this.put("F051", "MATELICA");
        this.put("F052", "MATERA");
        this.put("F053", "MATHI");
        this.put("F053", "MATI");
        this.put("F054", "MATINO");
        this.put("F055", "MATRICE");
        this.put("F056", "MATTARELLO");
        this.put("F057", "MATTERIA");
        this.put("F058", "MATTIE");
        this.put("F059", "MATTINATA");
        this.put("F060", "MATTUGLIE");
        this.put("F061", "MAZARA");
        this.put("F061", "MAZARA DEL VALLO");
        this.put("F062", "MAZIA * MATSCH");
        this.put("F063", "MAZZANO");
        this.put("F064", "MAZZANO");
        this.put("F064", "MAZZANO ROMANO");
        this.put("F065", "MAZZARINO");
        this.put("F066", "MAZZARA'");
        this.put("F066", "MAZZARRA' SANT'ANDREA");
        this.put("F067", "MAZZE'");
        this.put("F068", "MAZZIN");
        this.put("F069", "MAZZO");
        this.put("F069", "MAZZO MILANESE");
        this.put("F070", "MAZZO");
        this.put("F070", "MAZZO DI VALTELLINA");
        this.put("F071", "MAZZOLENI E FALGHERA");
        this.put("F072", "MAZZUNNO");
        this.put("F073", "MEANA");
        this.put("F073", "MEANA SARDO");
        this.put("F074", "MEANA");
        this.put("F074", "MEANA DI SUSA");
        this.put("F075", "MEANO");
        this.put("F076", "MEANO");
        this.put("F077", "MECHEL");
        this.put("F078", "MEDA");
        this.put("F078", "MEDA");
        this.put("F079", "MEDANA");
        this.put("F080", "MEDE");
        this.put("F081", "MEDEA");
        this.put("F082", "MEDESANO");
        this.put("F083", "MEDICINA");
        this.put("F084", "MEDIGLIA");
        this.put("F085", "MEDOLAGO");
        this.put("F085", "MEDOLAGO");
        this.put("F086", "MEDOLE");
        this.put("F087", "MEDOLLA");
        this.put("F088", "MEDUNA");
        this.put("F088", "MEDUNA DI LIVENZA");
        this.put("F089", "MEDUNO");
        this.put("F090", "MEGGIANO");
        this.put("F090", "PIEDIPATERNO SUL NERA");
        this.put("F091", "MEGLIADINO SAN FIDENZIO");
        this.put("F092", "MEGLIADINO SAN VITALE");
        this.put("F093", "MEINA");
        this.put("F094", "MEL");
        this.put("F095", "MELARA");
        this.put("F096", "MELAZZO");
        this.put("F097", "MELDOLA");
        this.put("F098", "MELE");
        this.put("F099", "MELEGNANELLO");
        this.put("F100", "MELEGNANO");
        this.put("F101", "MELENDUGNO");
        this.put("F102", "MELETI");
        this.put("F102", "MELETI");
        this.put("F103", "MELEZET");
        this.put("F104", "MELFI");
        this.put("F105", "MELICUCCA'");
        this.put("F106", "MELICUCCO");
        this.put("F107", "MELILLI");
        this.put("F108", "MELISSA");
        this.put("F108", "MELISSA");
        this.put("F109", "MELISSANO");
        this.put("F110", "MELITO");
        this.put("F110", "MELITO IRPINO");
        this.put("F110", "MELITO VALLE BONITO");
        this.put("F111", "MELITO");
        this.put("F111", "MELITO DI NAPOLI");
        this.put("F112", "MELITO");
        this.put("F112", "MELITO DI PORTO SALVO");
        this.put("F113", "MELIZZANO");
        this.put("F114", "MELLE");
        this.put("F115", "MELLO");
        this.put("F116", "MELMA");
        this.put("F116", "SILEA");
        this.put("F117", "MELPIGNANO");
        this.put("F118", "MELTINA * MOELTEN");
        this.put("F119", "MELZO");
        this.put("F120", "MENAGGIO");
        this.put("F121", "MENAROLA");
        this.put("F122", "MENCONICO");
        this.put("F123", "MENDATICA");
        this.put("F124", "MENDATICA-MONTEGROSSO");
        this.put("F124", "MENDATICA-MONTEGROSSO");
        this.put("F125", "MENDICINO");
        this.put("F126", "MENFI");
        this.put("F127", "MENTANA");
        this.put("F128", "MENTOULLES");
        this.put("F129", "MENZAGO");
        this.put("F130", "MEOLO");
        this.put("F131", "MERANA");
        this.put("F131", "MERANA");
        this.put("F132", "MERANO * MERAN");
        this.put("F133", "MERATE");
        this.put("F133", "MERATE");
        this.put("F134", "MERCALLO");
        this.put("F135", "MERCATELLO");
        this.put("F135", "MERCATELLO SUL METAURO");
        this.put("F136", "MERCATINO CONCA");
        this.put("F136", "PIAN DI CASTELLO");
        this.put("F137", "MERCATINO MARECCHIA");
        this.put("F137", "NOVAFELTRIA");
        this.put("F137", "NOVAFELTRIA");
        this.put("F138", "MERCATO");
        this.put("F138", "MERCATO SAN SEVERINO");
        this.put("F138", "SAN SEVERINO ROTA");
        this.put("F139", "MERCATO SARACENO");
        this.put("F140", "MERCENASCO");
        this.put("F141", "MERCOGLIANO");
        this.put("F142", "MERCUGNANO");
        this.put("F143", "MERCURAGO");
        this.put("F144", "MERETO DI TOMBA");
        this.put("F144", "MERETTO DI TOMBA");
        this.put("F145", "MERGO");
        this.put("F146", "MERGOZZO");
        this.put("F146", "MERGOZZO");
        this.put("F147", "MERI'");
        this.put("F148", "MERLARA");
        this.put("F149", "MERLINO");
        this.put("F149", "MERLINO");
        this.put("F150", "MERNA");
        this.put("F150", "MERNA");
        this.put("F151", "MERONE");
        this.put("F152", "MESAGNE");
        this.put("F153", "MESE");
        this.put("F154", "MESENZANA");
        this.put("F155", "MESERO");
        this.put("F156", "MESOLA");
        this.put("F157", "MESORACA");
        this.put("F157", "MESORACA");
        this.put("F158", "MESSINA");
        this.put("F159", "MESTRE");
        this.put("F160", "MESTRIAGO");
        this.put("F161", "MESTRINO");
        this.put("F162", "META");
        this.put("F163", "METTONE");
        this.put("F164", "MEUGLIANO");
        this.put("F165", "MEZZAGO");
        this.put("F165", "MEZZAGO");
        this.put("F166", "MEZZANA");
        this.put("F166", "MEZZANA CASATI");
        this.put("F167", "MEZZANA MORTIGLIENGO");
        this.put("F167", "MEZZANA");
        this.put("F167", "MEZZANA MORTIGLIENGO");
        this.put("F168", "MEZZANA");
        this.put("F169", "MEZZANA");
        this.put("F169", "MEZZANA SUPERIORE");
        this.put("F170", "MEZZANA BIGLI");
        this.put("F171", "MEZZANA RABATTONE");
        this.put("F172", "MEZZANE DI SOTTO");
        this.put("F173", "MEZZANEGO");
        this.put("F174", "MEZZANI");
        this.put("F175", "MEZZANINO");
        this.put("F176", "MEZZANO");
        this.put("F177", "MEZZANO IMER");
        this.put("F177", "MEZZANO IMER");
        this.put("F178", "MEZZANO PARPANESE");
        this.put("F179", "MEZZANO PASSONE");
        this.put("F180", "MEZZANO");
        this.put("F180", "MEZZANO SICCOMARIO");
        this.put("F181", "MEZZEGRA");
        this.put("F182", "MEZZENILE");
        this.put("F183", "MEZZOCORONA");
        this.put("F184", "MEZZOJUSO");
        this.put("F185", "MEZZOLAGO");
        this.put("F186", "MEZZOLDO");
        this.put("F187", "MEZZOLOMBARDO");
        this.put("F188", "MEZZOMERICO");
        this.put("F189", "MIAGLIANO");
        this.put("F189", "MIAGLIANO");
        this.put("F190", "MIANE");
        this.put("F191", "MIASINO");
        this.put("F192", "MIAZZINA");
        this.put("F192", "MIAZZINA");
        this.put("F193", "MICIGLIANO");
        this.put("F194", "MIGGIANO");
        this.put("F195", "MIGIANDONE");
        this.put("F196", "MIGLIANICO");
        this.put("F197", "MIGLIANO");
        this.put("F198", "MIGLIARINO");
        this.put("F199", "MIGLIARO");
        this.put("F200", "MIGLIERINA");
        this.put("F201", "MIGLIONICO");
        this.put("F202", "MIGNANEGO");
        this.put("F203", "MIGNANO");
        this.put("F203", "MIGNANO MONTE LUNGO");
        this.put("F204", "MIGNETE");
        this.put("F204", "MIGNETTES");
        this.put("F205", "MILANO");
        this.put("F206", "MILAZZO");
        this.put("F207", "MILETO");
        this.put("F207", "MILETO");
        this.put("F208", "MILIS");
        this.put("F208", "MILIS");
        this.put("F209", "MILITELLO");
        this.put("F209", "MILITELLO IN VAL DI CATANIA");
        this.put("F210", "MILITELLO");
        this.put("F210", "MILITELLO ROSMARINO");
        this.put("F211", "MILLAN-SARNES * MILLAND-SARNS");
        this.put("F212", "MILLAURES");
        this.put("F213", "MILLESIMO");
        this.put("F214", "MILO");
        this.put("F215", "MILZANELLO");
        this.put("F216", "MILZANO");
        this.put("F217", "MINEO");
        this.put("F218", "MINERBE");
        this.put("F219", "MINERBIO");
        this.put("F220", "MINERVINO MURGE");
        this.put("F220", "MINERVINO MURGE");
        this.put("F220", "MINERVINO");
        this.put("F221", "MINERVINO");
        this.put("F221", "MINERVINO DI LECCE");
        this.put("F222", "MINOPRIO");
        this.put("F223", "MINORI");
        this.put("F224", "TRAETTO");
        this.put("F224", "MINTURNO");
        this.put("F225", "MINUCCIANO");
        this.put("F226", "MIOGLIA");
        this.put("F227", "MIOLA");
        this.put("F228", "MIONE");
        this.put("F229", "MIRA");
        this.put("F229", "MIRA ED ORIAGO");
        this.put("F230", "MIRABELLA");
        this.put("F230", "MIRABELLA ECLANO");
        this.put("F231", "MIRABELLA");
        this.put("F231", "MIRABELLA IMBACCARI");
        this.put("F232", "MIRABELLO");
        this.put("F232", "MIRABELLO MONFERRATO");
        this.put("F233", "MIRABELLO");
        this.put("F233", "MIRABELLO SANNITICO");
        this.put("F234", "MIRABELLO");
        this.put("F234", "MIRABELLO CIRIA");
        this.put("F235", "MIRABELLO");
        this.put("F236", "MIRABELLO");
        this.put("F236", "MIRABELLO SAN BERNARDINO");
        this.put("F237", "MIRABELLO");
        this.put("F237", "MIRABELLO ED UNITI DI PAVIA");
        this.put("F237", "MIRABELLO ED UNITI DI PAVIA");
        this.put("F238", "MIRADOLO");
        this.put("F238", "MIRADOLO TERME");
        this.put("F239", "MIRANDA");
        this.put("F240", "MIRANDOLA");
        this.put("F241", "MIRANO");
        this.put("F242", "MIRTO");
        this.put("F243", "MISANO");
        this.put("F243", "MISANO DI GERA D'ADDA");
        this.put("F244", "MISANO");
        this.put("F244", "MISANO ADRIATICO");
        this.put("F244", "MISANO IN VILLA VITTORIA");
        this.put("F244", "MISANO ADRIATICO");
        this.put("F245", "MISANO");
        this.put("F245", "MISANO OLONA");
        this.put("F246", "MISILMERI");
        this.put("F247", "MISINTO");
        this.put("F247", "MISINTO");
        this.put("F248", "MISSAGLIA");
        this.put("F248", "MISSAGLIA");
        this.put("F249", "MISSANELLO");
        this.put("F250", "MISTERBIANCO");
        this.put("F251", "MISTRETTA");
        this.put("F252", "MIZZOLE");
        this.put("F253", "MOANO");
        this.put("F254", "MOASCA");
        this.put("F255", "MOCCHIE");
        this.put("F256", "MOCONESI");
        this.put("F257", "MODENA");
        this.put("F258", "MODICA");
        this.put("F259", "MODIGLIANA");
        this.put("F260", "TAVAZZANO CON VILLAVESCO");
        this.put("F260", "MODIGNANO");
        this.put("F260", "TAVAZZANO CON VILLAVESCO");
        this.put("F260", "VILLAVESCO");
        this.put("F261", "MODOLO");
        this.put("F262", "MODUGNO");
        this.put("F263", "MOENA");
        this.put("F264", "MOERNA");
        this.put("F265", "MOGGIO");
        this.put("F265", "MOGGIO");
        this.put("F266", "MOGGIO UDINESE");
        this.put("F267", "MOGLIA");
        this.put("F268", "MOGLIANO");
        this.put("F269", "MOGLIANO");
        this.put("F269", "MOGLIANO VENETO");
        this.put("F270", "MOGORELLA");
        this.put("F270", "MOGORELLA");
        this.put("F271", "MOGORELLA RUINAS");
        this.put("F271", "RUINAS");
        this.put("F271", "RUINAS");
        this.put("F272", "MOGORO");
        this.put("F272", "MOGORO");
        this.put("F273", "MOIANA");
        this.put("F274", "MOIANO");
        this.put("F275", "MOIMACCO");
        this.put("F276", "MOIO");
        this.put("F276", "MOIO DE' CALVI");
        this.put("F277", "MOIO");
        this.put("F277", "MOIO ALCANTARA");
        this.put("F278", "MOIO");
        this.put("F278", "MOIO DELLA CIVITELLA");
        this.put("F278", "MOIO DELLA CIVITELLA");
        this.put("F279", "MOIOLA");
        this.put("F280", "MOLA DI BARI");
        this.put("F281", "MOLARE");
        this.put("F282", "MOLASSANA");
        this.put("F283", "MOLAZZANA");
        this.put("F284", "MOLFETTA");
        this.put("F285", "MOLINA");
        this.put("F286", "MOLINA DI LEDRO");
        this.put("F287", "MOLINARA");
        this.put("F288", "MOLINELLA");
        this.put("F289", "MOLINI DI COLOGNOLA");
        this.put("F290", "MOLINI DI TRIORA");
        this.put("F291", "MOLINI DI TURES * MUEHLEN");
        this.put("F292", "MOLINO ALZANO");
        this.put("F292", "MOLINO ALZANO");
        this.put("F293", "MOLINO DEI TORTI");
        this.put("F293", "MOLINO DEI TORTI");
        this.put("F294", "MOLISE");
        this.put("F295", "MOLITERNO");
        this.put("F296", "MOLLARO");
        this.put("F297", "MOLLIA");
        this.put("F298", "MOLLIERES");
        this.put("F299", "MOLO");
        this.put("F299", "PORTO EMPEDOCLE");
        this.put("F300", "MOLO");
        this.put("F300", "MOLO DI BORBERA");
        this.put("F301", "MOLOCHIO");
        this.put("F302", "MOLTEDO INFERIORE");
        this.put("F302", "MONTEGRAZIE");
        this.put("F303", "MOLTEDO SUPERIORE");
        this.put("F304", "MOLTENO");
        this.put("F304", "MOLTENO");
        this.put("F305", "MOLTRASIO");
        this.put("F306", "MOLVENA");
        this.put("F307", "MOLVENO");
        this.put("F308", "MOMBALDONE");
        this.put("F309", "MOMBARCARO");
        this.put("F310", "MOMBAROCCIO");
        this.put("F311", "MOMBARUZZO");
        this.put("F312", "MOMBASIGLIO");
        this.put("F313", "MOMBELLO");
        this.put("F313", "MOMBELLO MONFERRATO");
        this.put("F314", "MOMBELLO");
        this.put("F314", "MOMBELLO LAGO MAGGIORE");
        this.put("F315", "MOMBELLO");
        this.put("F315", "MOMBELLO DI TORINO");
        this.put("F316", "MOMBERCELLI");
        this.put("F317", "MOMO");
        this.put("F318", "MOMPANTERO");
        this.put("F319", "MOMPEO");
        this.put("F320", "MOMPERONE");
        this.put("F321", "MOMPIANO");
        this.put("F322", "MONACILIONI");
        this.put("F323", "MONALE");
        this.put("F324", "MONASTERACE");
        this.put("F325", "MONASTERO");
        this.put("F325", "MONASTERO BORMIDA");
        this.put("F326", "MONASTERO");
        this.put("F326", "MONASTERO DI VASCO");
        this.put("F327", "MONASTERO");
        this.put("F327", "MONASTERO DI LANZO");
        this.put("F328", "MONASTEROLO");
        this.put("F328", "MONASTEROLO DEL CASTELLO");
        this.put("F329", "MONASTEROLO");
        this.put("F329", "MONASTEROLO CASOTTO");
        this.put("F329", "MONASTEROLO CASSOTO");
        this.put("F330", "MONASTEROLO");
        this.put("F330", "MONASTEROLO DI SAVIGLIANO");
        this.put("F331", "MONASTEROLO");
        this.put("F331", "MONASTEROLO TORINESE");
        this.put("F332", "MONASTIER");
        this.put("F332", "MONASTIER DI TREVISO");
        this.put("F333", "MONASTIR");
        this.put("F334", "MONATE");
        this.put("F335", "MONCALIERI");
        this.put("F336", "MONCALVO");
        this.put("F337", "MONCESTINO");
        this.put("F338", "MONCHIERO");
        this.put("F339", "MONCHIERO NOVELLO");
        this.put("F339", "NOVELLO MONCHIERO");
        this.put("F339", "NOVELLO MONCHIERO");
        this.put("F340", "MONCHIO");
        this.put("F340", "MONCHIO DELLE CORTI");
        this.put("F341", "MONCLASSICO");
        this.put("F342", "MONCRIVELLO");
        this.put("F343", "MONCUCCO");
        this.put("F343", "MONCUCCO TORINESE");
        this.put("F344", "MONCUCCO");
        this.put("F344", "MONCUCCO VECCHIO");
        this.put("F345", "MONCUCCO");
        this.put("F345", "MONCUCCO DI MONZA");
        this.put("F345", "MONCUCCO DI MONZA");
        this.put("F346", "MONDAINO");
        this.put("F346", "MONDAINO");
        this.put("F347", "MONDAVIO");
        this.put("F348", "MONDOLFO");
        this.put("F349", "MONDONICO");
        this.put("F350", "MONDONIO");
        this.put("F351", "MONDOVI'");
        this.put("F352", "MONDRAGONE");
        this.put("F353", "MONDRONE");
        this.put("F354", "MONEGLIA");
        this.put("F355", "MONESIGLIO");
        this.put("F356", "MONFALCONE");
        this.put("F357", "MONFESTINO IN SERRA MAZZONI");
        this.put("F357", "MONFESTINO IN SERRAMAZZONI");
        this.put("F357", "SERRAMAZZONI");
        this.put("F358", "MONFORTE");
        this.put("F358", "MONFORTE D'ALBA");
        this.put("F359", "MONFORTE");
        this.put("F359", "MONFORTE SAN GIORGIO");
        this.put("F360", "MONFUMO");
        this.put("F361", "MONGARDINO");
        this.put("F362", "MONGHEZZO DI FUORI * GETZENBERG");
        this.put("F362", "MONGHEZZO ESTERNO * GETZENBERG");
        this.put("F363", "MONGHIDORO");
        this.put("F364", "MONGIANA");
        this.put("F364", "MONGIANA");
        this.put("F365", "MONGIARDINO");
        this.put("F365", "MONGIARDINO LIGURE");
        this.put("F366", "MONGIARDINO");
        this.put("F366", "MONGIARDINO SILLARO");
        this.put("F367", "MONGIOVE");
        this.put("F367", "MONTJOVET");
        this.put("F368", "MONGIUFFI MELIA");
        this.put("F369", "MONGRANDO");
        this.put("F369", "MONGRANDO");
        this.put("F370", "MONGRASSANO");
        this.put("F371", "MONGUELFO * WELSBERG");
        this.put("F371", "MONGUELFO-TESIDO * WELSBERG-TAISTEN");
        this.put("F372", "MONGUZZO");
        this.put("F373", "MONIGA");
        this.put("F373", "MONIGA DEL GARDA");
        this.put("F374", "MONLEALE");
        this.put("F375", "MONNO");
        this.put("F376", "MONOPOLI");
        this.put("F377", "MONREALE");
        this.put("F378", "MONRUPINO");
        this.put("F379", "MONSAMPIETRO MORICO");
        this.put("F379", "MONSAMPIETRO MORICO");
        this.put("F380", "MONSAMPOLO");
        this.put("F380", "MONSAMPOLO DEL TRONTO");
        this.put("F381", "MONSANO");
        this.put("F381", "MOSCIANO");
        this.put("F382", "MONSELICE");
        this.put("F383", "MONSERRATO");
        this.put("F383", "PAULI MONSERRATO");
        this.put("F383", "PAULI PIRRI");
        this.put("F383", "MONSERRATO");
        this.put("F384", "MONSUMMANO");
        this.put("F384", "MONSUMMANO TERME");
        this.put("F385", "MONTA'");
        this.put("F386", "MONTABONE");
        this.put("F387", "MONTACUTO");
        this.put("F388", "MONTACUTO");
        this.put("F389", "MONTADAMO");
        this.put("F390", "MONTAFIA");
        this.put("F391", "MONTAGANO");
        this.put("F392", "MONTAGNA * MONTAN");
        this.put("F393", "MONTAGNA");
        this.put("F393", "MONTAGNA IN VALTELLINA");
        this.put("F394", "MONTAGNANA");
        this.put("F395", "MONTAGNAREALE");
        this.put("F396", "MONTAGNE");
        this.put("F397", "MONTAGUTO");
        this.put("F398", "MONTAIONE");
        this.put("F399", "MONTALBANO");
        this.put("F399", "MONTALBANO JONICO");
        this.put("F400", "MONTALBANO");
        this.put("F400", "MONTALBANO DI ELICONA");
        this.put("F400", "MONTALBANO ELICONA");
        this.put("F401", "MONTALBODDO");
        this.put("F401", "OSTRA");
        this.put("F402", "MONTALCINO");
        this.put("F403", "MONTALDEO");
        this.put("F404", "MONTALDO");
        this.put("F404", "MONTALDO BORMIDA");
        this.put("F405", "MONTALDO");
        this.put("F405", "MONTALDO DI MONDOVI'");
        this.put("F406", "MONTALDO");
        this.put("F406", "MONTALDO LIGURE");
        this.put("F406", "MONTALTO LIGURE");
        this.put("F407", "MONTALDO");
        this.put("F407", "MONTALDO TORINESE");
        this.put("F408", "MONTALDO ROERO");
        this.put("F409", "MONTALDO SCARAMPI");
        this.put("F410", "MONTALE");
        this.put("F411", "MONTALENGHE");
        this.put("F412", "MONTALERO");
        this.put("F413", "MONTALFOGLIO");
        this.put("F414", "MONTALLEGRO");
        this.put("F415", "MONTALTO");
        this.put("F415", "MONTALTO DELLE MARCHE");
        this.put("F416", "MONTALTO");
        this.put("F416", "MONTALTO AFFUGO");
        this.put("F416", "MONTALTO UFFUGO");
        this.put("F417", "MONTALTO");
        this.put("F417", "MONTALTO PAVESE");
        this.put("F418", "MONTALTO");
        this.put("F418", "MONTALTO TARUGO");
        this.put("F419", "MONTALTO");
        this.put("F419", "MONTALTO DI CASTRO");
        this.put("F420", "MONTALTO");
        this.put("F420", "MONTALTO DORA");
        this.put("F421", "MONTANARA");
        this.put("F422", "MONTANARO");
        this.put("F423", "MONTANASO LOMBARDO");
        this.put("F423", "MONTANASO");
        this.put("F423", "MONTANASO LOMBARDO");
        this.put("F424", "MONTANERA");
        this.put("F425", "MONTANO");
        this.put("F425", "MONTANO COMASCO");
        this.put("F426", "MONTANO");
        this.put("F426", "MONTANO ANTILIA");
        this.put("F427", "MONTANO LUCINO");
        this.put("F428", "MONTAPPONE");
        this.put("F428", "MONTAPPONE");
        this.put("F429", "MONTAQUILA");
        this.put("F430", "MONTASOLA");
        this.put("F431", "MONTASSILO * TESSELBERG");
        this.put("F431", "MONTASSILONE * TESSELBERG");
        this.put("F432", "MONTAURO");
        this.put("F433", "MONTAZZOLI");
        this.put("F434", "MONTE");
        this.put("F434", "MONTE CREMASCO");
        this.put("F435", "MONTE");
        this.put("F435", "MONTESIRO");
        this.put("F436", "MONTE A MEZZODI' * SONNENBERG");
        this.put("F436", "MONTE DI MEZZODI' * SONNENBERG");
        this.put("F437", "MONTE ARGENTARIO");
        this.put("F438", "MONTE A TRAMONTANA * NOERDERSBERG");
        this.put("F438", "MONTE DI TRAMONTANA * NOERDERSBERG");
        this.put("F439", "MONTEBELLO");
        this.put("F439", "MONTEBELLO METAURENSE");
        this.put("F440", "MONTEBELLO");
        this.put("F440", "MONTEBELLO DELLA BATTAGLIA");
        this.put("F441", "MONTEBELLO");
        this.put("F441", "MONTEBELLO DI BERTONA");
        this.put("F442", "MONTEBELLO");
        this.put("F442", "MONTEBELLO VICENTINO");
        this.put("F443", "MONTEBELLUNA");
        this.put("F444", "MONTE BOLOGNOLA");
        this.put("F445", "MONTEBRUNO");
        this.put("F446", "MONTEBUONO");
        this.put("F447", "MONTECALVO");
        this.put("F447", "MONTECALVO DEL CASTELLANO");
        this.put("F448", "MONTECALVO");
        this.put("F448", "MONTECALVO IRPINO");
        this.put("F449", "MONTECALVO");
        this.put("F449", "MONTECALVO VERSIGGIA");
        this.put("F450", "MONTECALVO");
        this.put("F450", "MONTECALVO IN FOGLIA");
        this.put("F451", "MONTECALVOLI");
        this.put("F452", "MONTECARLO");
        this.put("F453", "MONTECAROTTO");
        this.put("F454", "MONTECASSIANO");
        this.put("F455", "MONTECASTELLO");
        this.put("F456", "MONTE CASTELLO");
        this.put("F456", "MONTE CASTELLO DI VIBIO");
        this.put("F457", "MONTECASTRILLI");
        this.put("F458", "MONTECATINI VAL DI CECINA");
        this.put("F459", "MONTECATINI VAL DI NIEVOLE");
        this.put("F460", "MONTE CAVALLO");
        this.put("F460", "MONTE SAN POLO");
        this.put("F461", "MONTECCHIA DI CROSARA");
        this.put("F462", "MONTECCHIO");
        this.put("F463", "MONTECCHIO EMILIA");
        this.put("F464", "MONTECCHIO MAGGIORE");
        this.put("F465", "MONTECCHIO PRECALCINO");
        this.put("F466", "MONTECELIO");
        this.put("F466", "MONTICELLI");
        this.put("F467", "MONTE CERIGNONE");
        this.put("F468", "MONTECHIARO");
        this.put("F468", "MONTECHIARO D'ASTI");
        this.put("F469", "MONTECHIARO");
        this.put("F469", "MONTECHIARO D'ACQUI");
        this.put("F470", "MONTECHIARO * LICHTENBERG");
        this.put("F471", "MONTECHIARO");
        this.put("F471", "MONTECHIARO SUL CHIESE");
        this.put("F471", "MONTICHIARI");
        this.put("F472", "MONTECHIARO DENICE");
        this.put("F472", "MONTECHIARO DENICE");
        this.put("F473", "MONTECHIARUGOLO");
        this.put("F474", "MONTECICCARDO");
        this.put("F475", "MONTECILFONE");
        this.put("F476", "MONTE COLOMBO");
        this.put("F476", "MONTE COLOMBO");
        this.put("F477", "MONTECOMPATRI");
        this.put("F478", "MONTECOPIOLO");
        this.put("F479", "MONTECORICE");
        this.put("F479", "ORTODONICO");
        this.put("F480", "MONTECORVINO PUGLIANO");
        this.put("F481", "MONTECORVINO ROVELLA");
        this.put("F482", "MONTECOSARO");
        this.put("F483", "MONTECRESTESE");
        this.put("F483", "MONTECRESTESE");
        this.put("F484", "MONTECRETO");
        this.put("F485", "MONTE DI CAPODISTRIA");
        this.put("F486", "MONTE DI MALO");
        this.put("F487", "MONTEDINOVE");
        this.put("F488", "MONTE DI PROCIDA");
        this.put("F489", "MONTEDORO");
        this.put("F490", "MONTEFABBRI");
        this.put("F490", "MONTEFABBRI");
        this.put("F491", "MONTEFALCIONE");
        this.put("F492", "MONTEFALCO");
        this.put("F493", "MONTEFALCONE");
        this.put("F493", "MONTEFALCONE APPENNINO");
        this.put("F493", "MONTEFALCONE APPENNINO");
        this.put("F494", "MONTEFALCONE");
        this.put("F494", "MONTEFALCONE DI VAL FORTORE");
        this.put("F495", "MONTEFALCONE");
        this.put("F495", "MONTEFALCONE NEL SANNIO");
        this.put("F496", "MONTEFANO");
        this.put("F497", "MONTEFELCINO");
        this.put("F498", "MONTEFERRANTE");
        this.put("F499", "MONTEFIASCONE");
        this.put("F500", "MONTEFINO");
        this.put("F500", "MONTESECCO");
        this.put("F501", "MONTEFIORE");
        this.put("F501", "MONTEFIORE DELL'ASO");
        this.put("F502", "MONTEFIORE");
        this.put("F502", "MONTEFIORE CONCA");
        this.put("F502", "MONTEFIORITO");
        this.put("F502", "MONTEFIORE CONCA");
        this.put("F503", "MONTEFIORINO");
        this.put("F504", "MONTEFLAVIO");
        this.put("F505", "MONTEFONTANA * TOMBERG");
        this.put("F506", "MONTEFORTE");
        this.put("F506", "MONTEFORTE IRPINO");
        this.put("F507", "MONTEFORTE");
        this.put("F507", "MONTEFORTE CILENTO");
        this.put("F508", "MONTEFORTE");
        this.put("F508", "MONTEFORTE D'ALPONE");
        this.put("F509", "MONTEFORTINO");
        this.put("F509", "MONTEFORTINO");
        this.put("F510", "MONTEFRANCO");
        this.put("F511", "MONTEFREDANE");
        this.put("F512", "MONTEFUSCO");
        this.put("F513", "MONTEGABBIONE");
        this.put("F514", "MONTEGALDA");
        this.put("F515", "MONTEGALDELLA");
        this.put("F516", "MONTEGALLO");
        this.put("F517", "MONTE GIBERTO");
        this.put("F517", "MONTE GIBERTO");
        this.put("F518", "MONTEGIOCO");
        this.put("F519", "MONTEGIORDANO");
        this.put("F520", "MONTEGIORGIO");
        this.put("F520", "MONTEGIORGIO");
        this.put("F521", "MONTEGIOVE");
        this.put("F522", "MONTEGRANARO");
        this.put("F522", "MONTEGRANARO");
        this.put("F523", "MONTEGRIDOLFO");
        this.put("F523", "MONTEGRIDOLFO");
        this.put("F524", "MONTE GRIMANO");
        this.put("F524", "MONTE GRIMANO TERME");
        this.put("F525", "MONTEGRINO");
        this.put("F526", "MONTEGRINO VALTRAVAGLIA");
        this.put("F527", "MONTEGROSSO");
        this.put("F527", "MONTEGROSSO D'ASTI");
        this.put("F528", "MONTEGROSSO");
        this.put("F528", "MONTEGROSSO PIAN LATTE");
        this.put("F529", "MONTEGROTTO TERME");
        this.put("F529", "SAN PIETRO MONTAGNON");
        this.put("F530", "MONTEGUIDUCCIO");
        this.put("F531", "MONTEIASI");
        this.put("F532", "MONTE ISOLA");
        this.put("F533", "MONTELABBATE");
        this.put("F534", "MONTELANICO");
        this.put("F535", "MONTELAPIANO");
        this.put("F536", "MONTELEONE");
        this.put("F536", "MONTELEONE DI FERMO");
        this.put("F536", "MONTELEONE DI FERMO");
        this.put("F537", "MONTELEONE");
        this.put("F537", "MONTELEONE DI CALABRIA");
        this.put("F537", "VIBO VALENTIA");
        this.put("F537", "VIBO VALENTIA");
        this.put("F538", "MONTELEONE");
        this.put("F538", "MONTELEONE DI PUGLIA");
        this.put("F539", "MONTELEONE");
        this.put("F539", "MONTELEONE SUI COLLI PAVESI");
        this.put("F540", "MONTELEONE");
        this.put("F540", "MONTELEONE DI SPOLETO");
        this.put("F541", "MONTELEONE");
        this.put("F541", "MONTELEONE SABINO");
        this.put("F542", "MONTELEONE");
        this.put("F542", "MONTELEONE ROCCA DORIA");
        this.put("F543", "MONTELEONE");
        this.put("F543", "MONTELEONE D'ORVIETO");
        this.put("F544", "MONTELEPRE");
        this.put("F545", "MONTELIBRETTI");
        this.put("F546", "MONTELLA");
        this.put("F547", "MONTELLO");
        this.put("F547", "MONTICELLI");
        this.put("F547", "MONTICELLI DI BORGOGNA");
        this.put("F548", "MONTELONGO");
        this.put("F549", "MONTELPARO");
        this.put("F549", "MONTELPARO");
        this.put("F550", "MONTELUPO");
        this.put("F550", "MONTELUPO ALBESE");
        this.put("F551", "MONTELUPO");
        this.put("F551", "MONTELUPO FIORENTINO");
        this.put("F552", "MONTELUPONE");
        this.put("F553", "MONTEMAGGIORE");
        this.put("F553", "MONTEMAGGIORE BELSITO");
        this.put("F554", "MONTEMAGGIORE");
        this.put("F555", "MONTEMAGGIORE");
        this.put("F555", "MONTEMAGGIORE AL METAURO");
        this.put("F556", "MONTEMAGNO");
        this.put("F557", "MONTEMALE");
        this.put("F557", "SANT'ARCANGELO");
        this.put("F557", "SANT'ARCANGELO TRIMONTE");
        this.put("F557", "SANT'ARCANGELO TRIMONTE");
        this.put("F558", "MONTEMALE");
        this.put("F558", "MONTEMALE DI CUNEO");
        this.put("F559", "MONTEMARANO");
        this.put("F560", "MONTEMARCIANO");
        this.put("F561", "MONTE MARENZO");
        this.put("F561", "MONTE MARENZO");
        this.put("F562", "MONTEMARZINO");
        this.put("F563", "MONTEMESOLA");
        this.put("F564", "MONTEMEZZO");
        this.put("F565", "MONTEMIGNAIO");
        this.put("F566", "MONTEMILETTO");
        this.put("F567", "MONTEMILONE");
        this.put("F567", "POLLENZA");
        this.put("F568", "MONTEMILONE");
        this.put("F569", "MONTEMITRO");
        this.put("F570", "MONTEMONACO");
        this.put("F571", "MONTE MONTANARO");
        this.put("F572", "MONTEMURLO");
        this.put("F572", "MONTEMURLO");
        this.put("F573", "MONTEMURRO");
        this.put("F574", "MONTENARS");
        this.put("F575", "MONTENATE");
        this.put("F576", "MONTENERO DI BISACCIA");
        this.put("F577", "MONTENERO D'IDRIA");
        this.put("F578", "MONTENERODOMO");
        this.put("F579", "MONTENERO SABINO");
        this.put("F580", "MONTENERO VAL COCCHIARA");
        this.put("F581", "MONTENOVO");
        this.put("F581", "OSTRA VETERE");
        this.put("F582", "MONTEODORISIO");
        this.put("F583", "MONTE OLIMPINO");
        this.put("F584", "MONTE OSSOLANO");
        this.put("F585", "MONTEPAGANO");
        this.put("F585", "ROSETO DEGLI ABRUZZI");
        this.put("F586", "MONTEPAONE");
        this.put("F587", "MONTEPARANO");
        this.put("F588", "MONTEPONENTE * PFEFFERSBERG");
        this.put("F589", "MONTE PORZIO");
        this.put("F590", "MONTE PORZIO");
        this.put("F590", "MONTE PORZIO CATONE");
        this.put("F591", "MONTEPRANDONE");
        this.put("F592", "MONTEPULCIANO");
        this.put("F593", "MONTERADO");
        this.put("F594", "MONTERCHI");
        this.put("F595", "MONTEREALE");
        this.put("F596", "MONTEREALE VALCELLINA");
        this.put("F596", "MONTEREALE");
        this.put("F596", "MONTEREALE CELLINA");
        this.put("F597", "MONTERENZIO");
        this.put("F598", "MONTERIGGIONI");
        this.put("F599", "MONTE RINALDO");
        this.put("F599", "MONTE RINALDO");
        this.put("F600", "MONTE ROBERTO");
        this.put("F601", "MONTERODUNI");
        this.put("F602", "MONTEROLO");
        this.put("F603", "MONTE ROMANO");
        this.put("F604", "MONTERONI");
        this.put("F604", "MONTERONI DI LECCE");
        this.put("F605", "MONTERONI");
        this.put("F605", "MONTERONI D'ARBIA");
        this.put("F606", "MONTEROSI");
        this.put("F607", "MONTEROSSO");
        this.put("F607", "MONTEROSSO CALABRO");
        this.put("F607", "MONTEROSSO CALABRO");
        this.put("F608", "MONTEROSSO");
        this.put("F608", "MONTEROSSO GRANA");
        this.put("F609", "MONTEROSSO");
        this.put("F609", "MONTEROSSO AL MARE");
        this.put("F610", "MONTEROSSO");
        this.put("F610", "MONTEROSSO ALMO");
        this.put("F611", "MONTEROTONDO");
        this.put("F612", "MONTEROTONDO MARITTIMO");
        this.put("F613", "MONTERUBBIAGLIO");
        this.put("F614", "MONTERUBBIANO");
        this.put("F614", "MONTERUBBIANO");
        this.put("F615", "MONTES");
        this.put("F616", "MONTE SAN BIAGIO");
        this.put("F616", "MONTE SAN VITO");
        this.put("F616", "MONTICELLO");
        this.put("F617", "MONTE SAN CANDIDO * INNICHBERG");
        this.put("F618", "MONTE SAN GIACOMO");
        this.put("F618", "SAN GIACOMO");
        this.put("F619", "MONTE SAN GIOVANNI");
        this.put("F619", "MONTE SAN GIOVANNI IN SABINA");
        this.put("F620", "MONTE SAN GIOVANNI CAMPANO");
        this.put("F620", "MONTE SAN GIOVANNI");
        this.put("F621", "MONTE SAN GIUSTO");
        this.put("F621", "SAN GIUSTO");
        this.put("F622", "MONTE SAN MARTINO");
        this.put("F623", "MONTESANO");
        this.put("F623", "MONTESANO SALENTINO");
        this.put("F624", "MONTESANO");
        this.put("F624", "MONTESANO AL PIANO");
        this.put("F625", "MONTESANO");
        this.put("F625", "MONTESANO SULLA MARCELLANA");
        this.put("F626", "MONTE SAN PIETRANGELI");
        this.put("F626", "MONTE SAN PIETRANGELI");
        this.put("F627", "MONTE SAN PIETRO");
        this.put("F628", "MONTE SAN SAVINO");
        this.put("F629", "MONTE SANTA MARIA");
        this.put("F629", "MONTE SANTA MARIA TIBERINA");
        this.put("F630", "MONTE SANTA MARIA");
        this.put("F630", "MONTE SANTA MARIA IN SABINA");
        this.put("F631", "MONTE SANT'ANGELO");
        this.put("F632", "MONTESANTO");
        this.put("F632", "POTENZA PICENA");
        this.put("F633", "MONTESANTO");
        this.put("F633", "MONTESANTO VIEZI");
        this.put("F633", "MONTESANTO VIGI");
        this.put("F634", "MONTE SAN VITO");
        this.put("F635", "MONTE SAN VITO");
        this.put("F636", "MONTESARCHIO");
        this.put("F637", "MONTESCAGLIOSO");
        this.put("F638", "MONTESCANO");
        this.put("F638", "MONTESCANO");
        this.put("F639", "MONTESCHENO");
        this.put("F639", "MONTESCHENO");
        this.put("F640", "MONTESCUDAIO");
        this.put("F641", "MONTESCUDO");
        this.put("F641", "MONTESCUDOLO");
        this.put("F641", "MONTESCUDO");
        this.put("F642", "MONTESE");
        this.put("F643", "MONTESECCO");
        this.put("F643", "MONTESECCO ANTICO");
        this.put("F644", "MONTESEGALE");
        this.put("F645", "MONTESICURO");
        this.put("F646", "MONTESILVANO");
        this.put("F647", "MONTESILVANO MARINA");
        this.put("F648", "MONTESPERTOLI");
        this.put("F649", "MONTESPINO");
        this.put("F650", "MONTESTRUTTO");
        this.put("F651", "MONTEU DA PO");
        this.put("F652", "MONTE URABICE");
        this.put("F653", "MONTE URANO");
        this.put("F653", "MONTE URANO");
        this.put("F654", "MONTEU ROERO");
        this.put("F655", "MONTEVAGO");
        this.put("F656", "MONTEVARCHI");
        this.put("F657", "MONTEVECCHIA");
        this.put("F657", "MONTEVECCHIA");
        this.put("F657", "MONTEVECCHIA");
        this.put("F658", "MONTEVECCHIO");
        this.put("F659", "MONTEVEGLIO");
        this.put("F660", "MONTEVERDE");
        this.put("F661", "MONTEVERDI");
        this.put("F661", "MONTEVERDI MARITTIMO");
        this.put("F662", "MONTEVIALE");
        this.put("F663", "MONTEVIASCO");
        this.put("F664", "MONTE VIDON COMBATTE");
        this.put("F664", "MONTE VIDON COMBATTE");
        this.put("F665", "MONTE VIDON CORRADO");
        this.put("F665", "MONTE VIDON CORRADO");
        this.put("F666", "MONTEZEMOLO");
        this.put("F667", "MONTI");
        this.put("F667", "MONTI");
        this.put("F668", "MONTIANO");
        this.put("F669", "MONTICELLI");
        this.put("F669", "MONTICELLI ALBA");
        this.put("F669", "MONTICELLO D'ALBA");
        this.put("F670", "MONTICELLI");
        this.put("F670", "MONTICELLI PAVESE");
        this.put("F671", "MONTICELLI");
        this.put("F671", "MONTICELLI D'ONGINA");
        this.put("F672", "MONTICELLI BRUSATI");
        this.put("F673", "MONTICELLI RIPA D'OGLIO");
        this.put("F674", "MONTICELLO BRIANZA");
        this.put("F674", "MONTICELLO BRIANZA");
        this.put("F675", "MONTICELLO CONTE OTTO");
        this.put("F676", "MONTICIANO");
        this.put("F677", "MONTIERI");
        this.put("F678", "MONTIGLIO");
        this.put("F679", "MONTIGNOSO");
        this.put("F680", "MONTIRONE");
        this.put("F681", "MONTODINE");
        this.put("F682", "MONTOGGIO");
        this.put("F683", "MONTONA");
        this.put("F684", "MONTONATE");
        this.put("F685", "MONTONE");
        this.put("F686", "MONTOPOLI");
        this.put("F686", "MONTOPOLI IN VAL D'ARNO");
        this.put("F687", "MONTOPOLI");
        this.put("F687", "MONTOPOLI DI SABINA");
        this.put("F688", "MONTORFANO");
        this.put("F689", "MONTORIO");
        this.put("F689", "MONTORIO NEI FRENTANI");
        this.put("F690", "MONTORIO");
        this.put("F690", "MONTORIO AL VOMANO");
        this.put("F691", "MONTORIO");
        this.put("F691", "MONTORIO VERONESE");
        this.put("F692", "MONTORIO ROMANO");
        this.put("F693", "MONTORO INFERIORE");
        this.put("F694", "MONTORO SUPERIORE");
        this.put("F695", "MONTORSO");
        this.put("F696", "MONTORSO VICENTINO");
        this.put("F697", "MONTOTTONE");
        this.put("F697", "MONTOTTONE");
        this.put("F698", "MONTRESTA");
        this.put("F699", "MONTRIGIASCO");
        this.put("F700", "MONTRONE");
        this.put("F701", "MONTU' BECCARIA");
        this.put("F702", "MONTU' BERCHIELLI");
        this.put("F702", "MONTU' BERCHIELLI");
        this.put("F702", "MONTU' BERCHIELLI");
        this.put("F703", "MONVALLE");
        this.put("F704", "MONZA");
        this.put("F704", "MONZA");
        this.put("F705", "MONZAMBANO");
        this.put("F706", "MONZUNO");
        this.put("F707", "MORANO");
        this.put("F707", "MORANO SUL PO");
        this.put("F708", "MORANO");
        this.put("F708", "MORANO CALABRO");
        this.put("F709", "MORANSENGO");
        this.put("F710", "MORARO");
        this.put("F711", "MORAZZONE");
        this.put("F712", "MORBEGNO");
        this.put("F713", "MORBELLO");
        this.put("F714", "MORCA");
        this.put("F715", "MORCIANO");
        this.put("F715", "MORCIANO DI ROMAGNA");
        this.put("F715", "MORCIANO DI ROMAGNA");
        this.put("F716", "MORCIANO");
        this.put("F716", "MORCIANO DI LEUCA");
        this.put("F717", "MORCONE");
        this.put("F718", "MORDANO");
        this.put("F719", "MOREGNANO");
        this.put("F720", "MORENGO");
        this.put("F721", "MORES");
        this.put("F722", "MORESCO");
        this.put("F722", "MORESCO");
        this.put("F723", "MORETTA");
        this.put("F724", "MORFASSO");
        this.put("F725", "MORGANO");
        this.put("F726", "MORGEX");
        this.put("F727", "MORGONGIORI");
        this.put("F727", "MORGONGIORI");
        this.put("F728", "MORI");
        this.put("F729", "MORIAGO");
        this.put("F729", "MORIAGO DELLA BATTAGLIA");
        this.put("F730", "MORICONE");
        this.put("F731", "MORIGERATI");
        this.put("F732", "MORINO");
        this.put("F733", "MORIONDO TORINESE");
        this.put("F734", "MORLUPO");
        this.put("F735", "MORMANNO");
        this.put("F736", "MORNAGO");
        this.put("F737", "MORNESE");
        this.put("F738", "MORNICO");
        this.put("F738", "MORNICO AL SERIO");
        this.put("F739", "MORNICO");
        this.put("F739", "MORNICO LOSANA");
        this.put("F740", "MOROLO");
        this.put("F741", "MORONDO");
        this.put("F742", "MOROSOLO");
        this.put("F742", "MOROSOLO");
        this.put("F743", "MOROZZO");
        this.put("F744", "MORRA");
        this.put("F744", "MORRA DE SANCTIS");
        this.put("F744", "MORRA IRPINO");
        this.put("F745", "MORRO");
        this.put("F745", "MORRO D'ALBA");
        this.put("F746", "MORRO");
        this.put("F746", "MORRO REATINO");
        this.put("F747", "MORRO");
        this.put("F747", "MORRO D'ORO");
        this.put("F748", "MORRONE");
        this.put("F748", "MORRONE DEL SANNIO");
        this.put("F749", "MORROVALLE");
        this.put("F750", "MORSANO AL TAGLIAMENTO");
        this.put("F751", "MORSASCO");
        this.put("F752", "MORSENCHIO");
        this.put("F753", "MORTANO");
        this.put("F754", "MORTARA");
        this.put("F755", "MORTASO");
        this.put("F756", "MORTEGLIANO");
        this.put("F757", "MORTER * MORTER");
        this.put("F758", "MORTERONE");
        this.put("F758", "MORTERONE");
        this.put("F759", "MORTIZZA");
        this.put("F760", "MORUZZO");
        this.put("F761", "MOSCAZZANO");
        this.put("F762", "MOSCHIANO");
        this.put("F763", "MOSCHIENA");
        this.put("F764", "MOSCIANO");
        this.put("F764", "MOSCIANO SANT'ANGELO");
        this.put("F765", "MOSCUFO");
        this.put("F766", "MOSO * MOOS");
        this.put("F766", "MOSO IN PASSIRIA * MOOS IN PASSEIER");
        this.put("F766", "PIANO IN PASSIRIA * MOOS IN PASSEIER");
        this.put("F767", "MOSSA");
        this.put("F768", "MOSSANO");
        this.put("F769", "MOSSO SANTA MARIA");
        this.put("F769", "MOSSO SANTA MARIA");
        this.put("F770", "MOTTA");
        this.put("F770", "MOTTA DI LIVENZA");
        this.put("F771", "MOTTA BALUFFI");
        this.put("F772", "MOTTA CAMASTRA");
        this.put("F773", "MOTTA D'AFFERMO");
        this.put("F774", "MOTTA DE' CONTI");
        this.put("F775", "MOTTAFOLLONE");
        this.put("F776", "MOTTALCIATA");
        this.put("F776", "MOTTALCIATA");
        this.put("F777", "MOTTA MONTECORVINO");
        this.put("F778", "MOTTA SAN DAMIANO");
        this.put("F779", "MOTTA SAN GIOVANNI");
        this.put("F780", "MOTTA SANTA LUCIA");
        this.put("F781", "MOTTA SANT'ANASTASIA");
        this.put("F782", "MOTTA VIGANA");
        this.put("F783", "MOTTA VISCONTI");
        this.put("F784", "MOTTOLA");
        this.put("F785", "MOZZAGROGNA");
        this.put("F786", "MOZZANICA");
        this.put("F787", "MOZZANO");
        this.put("F788", "MOZZATE");
        this.put("F789", "MOZZECANE");
        this.put("F790", "MOZZIO");
        this.put("F791", "MOZZO");
        this.put("F792", "MU");
        this.put("F793", "MUCCIA");
        this.put("F794", "MUCENO");
        this.put("F795", "MUGGIA");
        this.put("F796", "MUGGIANO");
        this.put("F797", "MUGGIO'");
        this.put("F797", "MUGGIO'");
        this.put("F798", "MUGNANO");
        this.put("F798", "MUGNANO DEL CARDINALE");
        this.put("F799", "MUGNANO");
        this.put("F799", "MUGNANO DI NAPOLI");
        this.put("F800", "MULARGIA");
        this.put("F801", "MULAZZANO");
        this.put("F801", "MULAZZANO");
        this.put("F802", "MULAZZO");
        this.put("F803", "MULES * MAULS");
        this.put("F804", "MULO");
        this.put("F804", "VILLA POMA");
        this.put("F805", "MULTEDO");
        this.put("F806", "MURA");
        this.put("F807", "MURANO");
        this.put("F808", "MURAVERA");
        this.put("F809", "MURAZZANO");
        this.put("F810", "MURE");
        this.put("F810", "SALCEDO");
        this.put("F811", "MURELLO");
        this.put("F812", "MURIAGLIO");
        this.put("F813", "MURIALDO");
        this.put("F814", "MURISENGO");
        this.put("F815", "MURLO");
        this.put("F816", "MURO");
        this.put("F816", "MURO LECCESE");
        this.put("F817", "MURO");
        this.put("F817", "MURO LUCANO");
        this.put("F818", "MUROS");
        this.put("F819", "MUSADINO");
        this.put("F820", "MUSCOLINE");
        this.put("F821", "MUSCOLO-STRASSOLDO");
        this.put("F822", "MUSEI");
        this.put("F822", "MUSEI");
        this.put("F823", "MUSELLARO");
        this.put("F824", "MUSIANO");
        this.put("F825", "MUSIGNANO");
        this.put("F826", "MUSILE");
        this.put("F826", "MUSILE DI PIAVE");
        this.put("F827", "MUSOCCO");
        this.put("F828", "MUSSO");
        this.put("F829", "MUSSOLENTE");
        this.put("F830", "MUSSOMELI");
        this.put("F831", "MUTIGNANO");
        this.put("F831", "PINETO");
        this.put("F832", "MUZZANA");
        this.put("F832", "MUZZANA DEL TURGNANO");
        this.put("F833", "MUZZANO");
        this.put("F833", "MUZZANO");
        this.put("F834", "NACLA SAN MAURIZIO");
        this.put("F835", "NAGO-TORBOLE");
        this.put("F836", "NALLES * NALS");
        this.put("F837", "NANNO");
        this.put("F838", "NANTO");
        this.put("F839", "NAPOLI");
        this.put("F840", "NARBOLIA");
        this.put("F840", "NARBOLIA");
        this.put("F841", "NARCAO");
        this.put("F841", "NARCAO");
        this.put("F842", "NARDO'");
        this.put("F843", "NARDODIPACE");
        this.put("F843", "NARDODIPACE");
        this.put("F844", "NARNI");
        this.put("F845", "NARO");
        this.put("F846", "NARZOLE");
        this.put("F847", "NASINO");
        this.put("F848", "NASO");
        this.put("F849", "NATURNO * NATURNS");
        this.put("F850", "NAVA");
        this.put("F851", "NAVE");
        this.put("F852", "NAVELLI");
        this.put("F853", "NAVE SAN ROCCO");
        this.put("F854", "NAVONO");
        this.put("F855", "NAZ * NATZ");
        this.put("F855", "NOCI * NATZ");
        this.put("F856", "NAZ-SCIAVES * NATZ-SCHABS");
        this.put("F857", "NAZZANO");
        this.put("F858", "NE");
        this.put("F859", "NEBBIUNO");
        this.put("F860", "NEGARINE");
        this.put("F860", "NEGARINE");
        this.put("F861", "NEGRAR");
        this.put("F862", "NEIRONE");
        this.put("F863", "NEIVE");
        this.put("F864", "NEMBRO");
        this.put("F865", "NEMI");
        this.put("F866", "NEMOLI");
        this.put("F867", "NEONELI");
        this.put("F867", "NEONELI");
        this.put("F868", "NEPI");
        this.put("F869", "NERESINE");
        this.put("F870", "NERETO");
        this.put("F871", "NEROLA");
        this.put("F872", "NERVESA");
        this.put("F872", "NERVESA DELLA BATTAGLIA");
        this.put("F873", "NERVI");
        this.put("F874", "NERVIANO");
        this.put("F875", "NESE");
        this.put("F876", "NESPOLO");
        this.put("F877", "NESSO");
        this.put("F878", "NETRO");
        this.put("F878", "NETRO");
        this.put("F879", "NETTUNIA");
        this.put("F879", "NETTUNIA");
        this.put("F880", "NETTUNO");
        this.put("F881", "NEVIANO");
        this.put("F882", "NEVIANO DEGLI ARDUINI");
        this.put("F883", "NEVIGLIE");
        this.put("F884", "NIARDO");
        this.put("F885", "NIBBIANO");
        this.put("F886", "NIBBIOLA");
        this.put("F887", "NIBIONNO");
        this.put("F887", "NIBIONNO");
        this.put("F888", "NICASTRO");
        this.put("F889", "NICHELINO");
        this.put("F890", "NICOLOSI");
        this.put("F891", "NICORVO");
        this.put("F892", "NICOSIA");
        this.put("F893", "NICOTERA");
        this.put("F893", "NICOTERA");
        this.put("F894", "NIELLA BELBO");
        this.put("F895", "NIELLA TANARO");
        this.put("F896", "NIGOLINE");
        this.put("F896", "NIGOLINE-BONOMELLI");
        this.put("F897", "NIGUARDA");
        this.put("F898", "NIMIS");
        this.put("F899", "NISCEMI");
        this.put("F900", "NISSORIA");
        this.put("F901", "NIZZA DI SICILIA");
        this.put("F901", "SAN FERDINANDO");
        this.put("F902", "NIZZA MONFERRATO");
        this.put("F903", "NIZZOLINA");
        this.put("F904", "NOALE");
        this.put("F905", "NOARNA");
        this.put("F906", "NOASCA");
        this.put("F907", "NOCARA");
        this.put("F908", "NOCCIANO");
        this.put("F909", "NOCCO");
        this.put("F910", "NOCERA");
        this.put("F910", "NOCERA TERINESE");
        this.put("F911", "NOCERA");
        this.put("F911", "NOCERA UMBRA");
        this.put("F912", "NOCERA INFERIORE");
        this.put("F913", "NOCERA SUPERIORE");
        this.put("F914", "NOCETO");
        this.put("F915", "NOCI");
        this.put("F916", "NOCIGLIA");
        this.put("F917", "NOEPOLI");
        this.put("F917", "NOIA");
        this.put("F918", "NOGARA");
        this.put("F919", "NOGARE'");
        this.put("F920", "NOGAREDO");
        this.put("F921", "NOGAROLE");
        this.put("F921", "NOGAROLE ROCCA");
        this.put("F922", "NOGAROLE");
        this.put("F922", "NOGAROLE VICENTINO");
        this.put("F923", "NOICATTARO");
        this.put("F923", "NOJA");
        this.put("F924", "NOLA");
        this.put("F925", "NOLE");
        this.put("F926", "NOLI");
        this.put("F927", "NOMAGLIO");
        this.put("F928", "NOMESINO");
        this.put("F929", "NOMI");
        this.put("F930", "NONANTOLA");
        this.put("F931", "NONE");
        this.put("F932", "NONIO");
        this.put("F932", "NONIO");
        this.put("F933", "NORAGUGUME");
        this.put("F934", "NORBELLO");
        this.put("F934", "NORGHIDDO");
        this.put("F934", "NORBELLO");
        this.put("F935", "NORCIA");
        this.put("F936", "NORIGLIO");
        this.put("F937", "NORMA");
        this.put("F938", "NOSADELLO");
        this.put("F939", "NOSATE");
        this.put("F940", "NOSEDO");
        this.put("F941", "NOSSA");
        this.put("F941", "PONTE NOSSA");
        this.put("F942", "NOTARESCO");
        this.put("F943", "NOTO");
        this.put("F944", "NOVA");
        this.put("F944", "NOVA MILANESE");
        this.put("F944", "NOVA MILANESE");
        this.put("F945", "NOVACELLA * NEUSTIFT");
        this.put("F946", "NOVALE");
        this.put("F947", "NOVALEDO");
        this.put("F948", "NOVALESA");
        this.put("F949", "NOVA LEVANTE * WELSCHNOFEN");
        this.put("F950", "NOVA PONENTE * DEUTSCHNOFEN");
        this.put("F951", "NOVARA");
        this.put("F951", "NOVARA DI SICILIA");
        this.put("F952", "NOVARA");
        this.put("F953", "NOVAREGLIA");
        this.put("F954", "NOVATE");
        this.put("F954", "NOVATE BRIANZA");
        this.put("F955", "NOVATE");
        this.put("F955", "NOVATE MILANESE");
        this.put("F956", "NOVATE");
        this.put("F956", "NOVATE MEZZOLA");
        this.put("F957", "NOVE");
        this.put("F958", "NOVEDRATE");
        this.put("F959", "NOVEGRO");
        this.put("F960", "NOVELLARA");
        this.put("F961", "NOVELLO");
        this.put("F962", "NOVENTA");
        this.put("F962", "NOVENTA PADOVANA");
        this.put("F963", "NOVENTA");
        this.put("F963", "NOVENTA DI PIAVE");
        this.put("F964", "NOVENTA VICENTINA");
        this.put("F965", "NOVI");
        this.put("F965", "NOVI LIGURE");
        this.put("F965", "NOVI PIEMONTE");
        this.put("F966", "NOVI");
        this.put("F966", "NOVI DI MODENA");
        this.put("F967", "NOVI");
        this.put("F967", "NOVI VELIA");
        this.put("F967", "NOVI VELIA");
        this.put("F968", "NOVIGLIO");
        this.put("F969", "NOVILARA");
        this.put("F970", "NOVOLI");
        this.put("F971", "NOZZA");
        this.put("F972", "NUCETTO");
        this.put("F973", "NUCHIS");
        this.put("F973", "NUCHIS");
        this.put("F974", "NUGHEDU");
        this.put("F974", "NUGHEDU SANTA VITTORIA");
        this.put("F974", "NUGHEDU SANTA VITTORIA");
        this.put("F975", "NUGHEDU");
        this.put("F975", "NUGHEDU SAN NICOLO'");
        this.put("F976", "NULE");
        this.put("F977", "NULVI");
        this.put("F978", "NUMANA");
        this.put("F978", "UMANA");
        this.put("F979", "NUORO");
        this.put("F980", "NURACHI");
        this.put("F980", "NURACHI");
        this.put("F981", "NURAGUS");
        this.put("F982", "NURALLAO");
        this.put("F983", "NURAMINIS");
        this.put("F984", "NURAXINIEDDU");
        this.put("F985", "NURECI");
        this.put("F985", "NURECI");
        this.put("F986", "NURRI");
        this.put("F987", "NUS");
        this.put("F988", "NUSCO");
        this.put("F989", "NUVOLENTO");
        this.put("F990", "NUVOLERA");
        this.put("F991", "NUXIS");
        this.put("F991", "NUXIS");
        this.put("F992", "OCCHIEPPO INFERIORE");
        this.put("F992", "OCCHIEPPO INFERIORE");
        this.put("F993", "OCCHIEPPO SUPERIORE");
        this.put("F993", "OCCHIEPPO SUPERIORE");
        this.put("F994", "OCCHIOBELLO");
        this.put("F995", "OCCIMIANO");
        this.put("F996", "OCRE");
        this.put("F997", "ODALENGO GRANDE");
        this.put("F998", "ODALENGO PICCOLO");
        this.put("F999", "ODERZO");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
