package document;

import java.util.HashMap;

/**
 * Created by Matteo on 12/11/2015.
 */
@SuppressWarnings("serial")
public class CitiesCodes_D extends HashMap<String, String> {

    public CitiesCodes_D(){
        this.put("D001", "CORGENO");
        this.put("D002", "CORGNALE");
        this.put("D003", "CORI");
        this.put("D004", "CORIANO");
        this.put("D004", "CORIANO");
        this.put("D005", "CORIGLIANO");
        this.put("D005", "CORIGLIANO CALABRO");
        this.put("D006", "CORIGLIANO");
        this.put("D006", "CORIGLIANO D'OTRANTO");
        this.put("D007", "CORINALDO");
        this.put("D008", "CORIO");
        this.put("D009", "CORLEONE");
        this.put("D010", "CORLETO");
        this.put("D010", "CORLETO PERTICARA");
        this.put("D011", "CORLETO");
        this.put("D011", "CORLETO MONFORTE");
        this.put("D012", "CORMAIORE");
        this.put("D012", "COURMAYEUR");
        this.put("D013", "CORMANO");
        this.put("D014", "CORMONS");
        this.put("D015", "CORNA IMAGNA");
        this.put("D016", "CORNALBA");
        this.put("D016", "CORNALBA");
        this.put("D017", "CORNALE");
        this.put("D018", "CORNAREDO");
        this.put("D019", "CORNATE");
        this.put("D019", "CORNATE D'ADDA");
        this.put("D019", "CORNATE D'ADDA");
        this.put("D020", "CORNEDO");
        this.put("D020", "CORNEDO VICENTINO");
        this.put("D021", "CORNEGLIANO LAUDENSE");
        this.put("D021", "CORNEGLIANO");
        this.put("D021", "CORNEGLIANO LAUDENSE");
        this.put("D022", "CORNELIANO");
        this.put("D022", "CORNELIANO D'ALBA");
        this.put("D023", "CORNELIANO");
        this.put("D023", "CORNELIANO BERTARIO");
        this.put("D024", "CORNETO");
        this.put("D024", "CORNETO TARQUINIA");
        this.put("D024", "TARQUINIA");
        this.put("D025", "CORNIGLIANO");
        this.put("D025", "CORNIGLIANO LIGURE");
        this.put("D026", "CORNIGLIO");
        this.put("D027", "CORNO DI ROSAZZO");
        this.put("D028", "CORNO GIOVINE");
        this.put("D028", "CORNO GIOVINE");
        this.put("D029", "CORNOVECCHIO");
        this.put("D029", "CORNOVECCHIO");
        this.put("D030", "CORNUDA");
        this.put("D031", "CORONA");
        this.put("D032", "CORONA ALLA MUTA * GRAUN");
        this.put("D032", "CURON * GRAUN");
        this.put("D033", "CORONATE");
        this.put("D033", "MORIMONDO");
        this.put("D034", "CORPI SANTI DI CREMONA");
        this.put("D035", "CORPI SANTI DI MILANO");
        this.put("D036", "CORPI SANTI DI PAVIA");
        this.put("D036", "CORPI SANTI DI PAVIA");
        this.put("D037", "CORREGGIO");
        this.put("D038", "CORREZZANA");
        this.put("D038", "CORREZZANA");
        this.put("D039", "CORREZZO");
        this.put("D040", "CORREZZOLA");
        this.put("D041", "CORRIDO");
        this.put("D042", "CORRIDONIA");
        this.put("D042", "PAUSULA");
        this.put("D043", "CORROPOLI");
        this.put("D044", "CORSANO");
        this.put("D045", "CORSICO");
        this.put("D046", "CORSIONE");
        this.put("D047", "CORTABBIO");
        this.put("D048", "CORTACCIA * KURTATSCH");
        this.put("D048", "CORTACCIA SULLA STRADA DEL VINO * KURTATSCH AN DER WEINSTRASSE");
        this.put("D049", "CORTALE");
        this.put("D050", "CORTANDONE");
        this.put("D051", "CORTANZE");
        this.put("D052", "CORTAZZONE");
        this.put("D053", "CORTE");
        this.put("D054", "CORTE BRUGNATELLA");
        this.put("D055", "CORTE DE' CORTESI");
        this.put("D056", "CORTE DE' CORTESI CON CIGNONE");
        this.put("D057", "CORTE DE' FRATI");
        this.put("D058", "CORTE FRANCA");
        this.put("D059", "CORTE IN PUSTERIA * HOFERN");
        this.put("D059", "CORTI IN PUSTERIA * HOFERN");
        this.put("D060", "CORTE MADAMA");
        this.put("D061", "CORTEMAGGIORE");
        this.put("D062", "CORTEMILIA");
        this.put("D063", "CORTENEDOLO");
        this.put("D064", "CORTENO");
        this.put("D064", "CORTENO GOLGI");
        this.put("D065", "CORTENOVA");
        this.put("D065", "CORTENOVA");
        this.put("D066", "CORTENUOVA");
        this.put("D067", "CORTEOLONA");
        this.put("D068", "CORTE PALASIO");
        this.put("D068", "CORTE PALASIO");
        this.put("D069", "CORTERANZO");
        this.put("D070", "CORTE SANT'ANDREA");
        this.put("D071", "CORTETANO");
        this.put("D072", "CORTICELLE");
        this.put("D072", "CORTIGLIONE");
        this.put("D073", "CORTICELLE");
        this.put("D073", "CORTICELLE PIEVE");
        this.put("D074", "CORTILE SAN MARTINO");
        this.put("D075", "CORTINA ALL'ADIGE * KURTINIG");
        this.put("D075", "CORTINA SULLA STRADA DEL VINO * KURTINIG AN DER WEINSTRASSE");
        this.put("D076", "CORTINO");
        this.put("D077", "CORTONA");
        this.put("D078", "CORVARA");
        this.put("D079", "CORVARA IN BADIA * CORVARA");
        this.put("D079", "LADINIA");
        this.put("D080", "CORVARA IN PASSIRIA * RABENSTEIN");
        this.put("D081", "CORVINO");
        this.put("D081", "CORVINO SAN QUIRICO");
        this.put("D082", "CORZANO");
        this.put("D083", "CORCES * KORTSCH");
        this.put("D084", "COSBANA");
        this.put("D084", "COSBANA NEL COLLIO");
        this.put("D085", "COSEANO");
        this.put("D086", "COSENZA");
        this.put("D087", "COSIO");
        this.put("D087", "COSIO D'ARROSCIA");
        this.put("D088", "COSIO");
        this.put("D088", "COSIO VALTELLINO");
        this.put("D089", "COSOLETO");
        this.put("D090", "COSSANA");
        this.put("D091", "COSSANO");
        this.put("D091", "DUE COSSANI");
        this.put("D092", "COSSANO");
        this.put("D092", "COSSANO CANAVESE");
        this.put("D093", "COSSANO BELBO");
        this.put("D094", "COSSATO");
        this.put("D094", "COSSATO");
        this.put("D095", "COSSERIA");
        this.put("D096", "COSSIGNANO");
        this.put("D097", "COSSILA");
        this.put("D098", "COSSIRANO");
        this.put("D099", "COSSOGNO");
        this.put("D099", "COSSOGNO");
        this.put("D100", "COSSOINE");
        this.put("D101", "COSSOMBRATO");
        this.put("D102", "COSTA");
        this.put("D102", "COSTA VESCOVATO");
        this.put("D103", "COSTA");
        this.put("D103", "COSTA VALLE IMAGNA");
        this.put("D104", "COSTA");
        this.put("D104", "COSTA DI ONEGLIA");
        this.put("D105", "COSTA");
        this.put("D105", "COSTA DI ROVIGO");
        this.put("D106", "COSTA AL LAMBRO");
        this.put("D106", "COSTA LOMBARDA");
        this.put("D107", "COSTABISSARA");
        this.put("D108", "COSTACCIARO");
        this.put("D109", "COSTA DE' NOBILI");
        this.put("D109", "COSTA SAN ZENONE");
        this.put("D110", "COSTA DI MEZZATE");
        this.put("D110", "COSTA DI MONTICELLI");
        this.put("D110", "COSTA DI MEZZATE");
        this.put("D111", "COSTA SERINA");
        this.put("D112", "COSTA MASNAGA");
        this.put("D112", "COSTA MASNAGA");
        this.put("D113", "COSTANZANA");
        this.put("D114", "COSTARAINERA");
        this.put("D114", "COSTA RAINERA");
        this.put("D115", "COSTA SANT'ABRAMO");
        this.put("D116", "COSTASAVINA");
        this.put("D117", "COSTA VOLPINO");
        this.put("D117", "VOLPINO");
        this.put("D118", "COSTERMANO");
        this.put("D119", "COSTIGLIOLE D'ASTI");
        this.put("D120", "COSTIGLIOLE SALUZZO");
        this.put("D121", "COTIGNOLA");
        this.put("D122", "COTRONE");
        this.put("D122", "CROTONE");
        this.put("D122", "CROTONE");
        this.put("D123", "COTRONEI");
        this.put("D123", "COTRONEI");
        this.put("D124", "COTTANELLO");
        this.put("D125", "COVELO");
        this.put("D126", "COVO");
        this.put("D127", "COZZO");
        this.put("D128", "CRACO");
        this.put("D129", "CRANA");
        this.put("D130", "CRANA CATTUGNO");
        this.put("D131", "CRANDOLA");
        this.put("D131", "CRANDOLA VALSASSINA");
        this.put("D131", "CRANDOLA VALSASSINA");
        this.put("D132", "CRAVAGLIANA");
        this.put("D133", "CRAVANZANA");
        this.put("D134", "CRAVEGGIA");
        this.put("D134", "CRAVEGGIA");
        this.put("D135", "CRAVEGNA");
        this.put("D136", "CREAZZO");
        this.put("D137", "CRECCHIO");
        this.put("D138", "CREDA");
        this.put("D139", "CREDARO");
        this.put("D140", "CREDERA");
        this.put("D141", "CREDERA RUBBIANO");
        this.put("D142", "CREMA");
        this.put("D143", "CREMELLA");
        this.put("D143", "CREMELLA");
        this.put("D144", "CREMENAGA");
        this.put("D145", "CREMENO");
        this.put("D145", "CREMENO");
        this.put("D146", "CREMEZZANO");
        this.put("D147", "CREMIA");
        this.put("D148", "CREMNAGO");
        this.put("D149", "CREMOLINO");
        this.put("D150", "CREMONA");
        this.put("D150", "CREMONA ED UNITI");
        this.put("D151", "CREMOSANO");
        this.put("D152", "CRENNA");
        this.put("D153", "CRENOVIZZA");
        this.put("D154", "CRESCENTINO");
        this.put("D155", "CRESCENZAGO");
        this.put("D156", "CRESPADORO");
        this.put("D157", "CRESPANO");
        this.put("D157", "CRESPANO DEL GRAPPA");
        this.put("D157", "CRESPANO VENETO");
        this.put("D158", "CRESPELLANO");
        this.put("D159", "CRESPIATICA");
        this.put("D159", "CRESPIATICA");
        this.put("D160", "CRESPINA");
        this.put("D161", "CRESPINO");
        this.put("D162", "CRESSA");
        this.put("D163", "CRESSOGNO");
        this.put("D164", "CRETO");
        this.put("D165", "CREVACUORE");
        this.put("D165", "CREVACUORE");
        this.put("D166", "CREVALCORE");
        this.put("D167", "CREVENNA");
        this.put("D168", "CREVOLA");
        this.put("D168", "CREVOLA D'OSSOLA");
        this.put("D168", "CREVOLADOSSOLA");
        this.put("D168", "CREVOLADOSSOLA");
        this.put("D169", "CREVOLA");
        this.put("D169", "CREVOLA SESIA");
        this.put("D170", "CRISPANO");
        this.put("D171", "CRISPIANO");
        this.put("D172", "CRISSOLO");
        this.put("D173", "CROCE");
        this.put("D174", "CROCE DI MOSSO");
        this.put("D175", "CROCEFIESCHI");
        this.put("D176", "CROCETTA");
        this.put("D176", "CROCETTA");
        this.put("D177", "CRODO");
        this.put("D177", "CRODO");
        this.put("D178", "CRODO MOZZIO");
        this.put("D179", "CROGNALETO");
        this.put("D180", "CROPALATI");
        this.put("D181", "CROPANI");
        this.put("D182", "CROSA");
        this.put("D182", "CROSA");
        this.put("D183", "CROSARA");
        this.put("D184", "CROSIA");
        this.put("D185", "CROSIO DELLA VALLE");
        this.put("D186", "CROTTA D'ADDA");
        this.put("D187", "CROVA");
        this.put("D188", "CROVIANA");
        this.put("D189", "CRUCOLI");
        this.put("D189", "CRUCOLI");
        this.put("D190", "CRUGNOLA");
        this.put("D191", "CRUSINALLO");
        this.put("D192", "CUASSO AL MONTE");
        this.put("D193", "CUCCA");
        this.put("D193", "VERONELLA");
        this.put("D194", "CUCCARO");
        this.put("D194", "CUCCARO MONFERRATO");
        this.put("D195", "CUCCARO");
        this.put("D195", "CUCCARO VETERE");
        this.put("D196", "CUCCIAGO");
        this.put("D197", "CUCEGLIO");
        this.put("D198", "CUGGIONO");
        this.put("D199", "CUGLIATE");
        this.put("D199", "CUGLIATE-FABIASCO");
        this.put("D200", "CUGLIERI");
        this.put("D200", "CUGLIERI");
        this.put("D201", "CUGNOLI");
        this.put("D202", "CUMIANA");
        this.put("D203", "CUMIGNANO");
        this.put("D203", "CUMIGNANO SUL NAVIGLIO");
        this.put("D204", "CUNARDO");
        this.put("D205", "CUNEO");
        this.put("D206", "CUNEVO");
        this.put("D207", "CUNICO");
        this.put("D208", "CUORGNE'");
        this.put("D209", "CUPELLO");
        this.put("D210", "CUPRA MARITTIMA");
        this.put("D210", "MARANO");
        this.put("D211", "CUPRAMONTANA");
        this.put("D211", "MASSACCIO");
        this.put("D212", "CUQUELLO");
        this.put("D213", "CURACES * GRATSCH");
        this.put("D213", "QUARAZZE * GRATSCH");
        this.put("D214", "CURCURIS");
        this.put("D214", "CURCURIS");
        this.put("D215", "CURDOMO");
        this.put("D215", "CURDOMO");
        this.put("D216", "CUREGGIO");
        this.put("D217", "CURIGLIA");
        this.put("D217", "CURIGLIA CON MONTEVIASCO");
        this.put("D218", "CURINGA");
        this.put("D219", "CURINO");
        this.put("D219", "CURINO");
        this.put("D220", "CURNASCO");
        this.put("D221", "CURNO");
        this.put("D222", "CURON VENOSTA * GRAUN IM VINSCHGAU");
        this.put("D223", "CURSI");
        this.put("D224", "CURSOLO");
        this.put("D225", "CURSOLO-ORASSO");
        this.put("D225", "CURSOLO-ORASSO");
        this.put("D226", "CURTAROLO");
        this.put("D227", "CURTATONE");
        this.put("D228", "CURTI");
        this.put("D229", "CUSAGO");
        this.put("D230", "CUSANO");
        this.put("D230", "CUSANO MUTRI");
        this.put("D231", "CUSANO");
        this.put("D231", "CUSANO MILANINO");
        this.put("D231", "CUSANO SUL SEVESO");
        this.put("D232", "CUSINO");
        this.put("D233", "CUSIO");
        this.put("D234", "CUSTONACI");
        this.put("D235", "CUTIGLIANO");
        this.put("D236", "CUTRO");
        this.put("D236", "CUTRO");
        this.put("D237", "CUTROFIANO");
        this.put("D238", "CUVEGLIO");
        this.put("D238", "CUVEGLIO IN VALLE");
        this.put("D239", "CUVIO");
        this.put("D240", "CUVIRONE");
        this.put("D241", "CUZZAGO");
        this.put("D242", "DAGNENTE");
        this.put("D243", "DAIANO");
        this.put("D244", "DAIRAGO");
        this.put("D245", "DALMINE");
        this.put("D246", "DAMBEL");
        this.put("D247", "DANTA");
        this.put("D247", "DANTA DI CADORE");
        this.put("D248", "DAONE");
        this.put("D249", "DARDINE");
        this.put("D250", "DARE'");
        this.put("D251", "DARFO");
        this.put("D251", "DARFO BOARIO TERME");
        this.put("D252", "DARZO");
        this.put("D253", "DASA'");
        this.put("D253", "DASA'");
        this.put("D254", "DASIO");
        this.put("D255", "DAVAGNA");
        this.put("D255", "ROSSO");
        this.put("D256", "DAVERIO");
        this.put("D257", "DAVOLI");
        this.put("D258", "DAZIO");
        this.put("D259", "DECIMOMANNU");
        this.put("D260", "DECIMOPUTZU");
        this.put("D261", "DECOLLATURA");
        this.put("D262", "DEGAGNA");
        this.put("D263", "DEGGIANO");
        this.put("D264", "DEGO");
        this.put("D265", "DEIVA");
        this.put("D265", "DEIVA MARINA");
        this.put("D266", "DELEBIO");
        this.put("D267", "DELIA");
        this.put("D268", "DELIANUOVA");
        this.put("D269", "DELICETO");
        this.put("D270", "DELLO");
        this.put("D271", "DEMONTE");
        this.put("D272", "DENICE");
        this.put("D272", "DENICE");
        this.put("D273", "DENNO");
        this.put("D274", "DERCOLO");
        this.put("D275", "DERGANO");
        this.put("D276", "DERMULO");
        this.put("D277", "DERNICE");
        this.put("D278", "DEROVERE");
        this.put("D279", "DERUTA");
        this.put("D280", "DERVIO");
        this.put("D280", "DERVIO");
        this.put("D281", "DESANA");
        this.put("D282", "DESCLA");
        this.put("D283", "DESENZANO");
        this.put("D283", "DESENZANO AL SERIO");
        this.put("D284", "DESENZANO");
        this.put("D284", "DESENZANO DEL GARDA");
        this.put("D284", "DESENZANO SUL LAGO");
        this.put("D285", "DESERTES");
        this.put("D286", "DESIO");
        this.put("D286", "DESIO");
        this.put("D287", "DESULO");
        this.put("D288", "DEZZO DI SCALVE");
        this.put("D288", "DEZZO DI SCALVE");
        this.put("D289", "DIAMANTE");
        this.put("D290", "DIANO");
        this.put("D290", "FEGGIANO");
        this.put("D290", "SCIGLIANO");
        this.put("D291", "DIANO");
        this.put("D291", "DIANO D'ALBA");
        this.put("D292", "DIANO");
        this.put("D292", "TEGGIANO");
        this.put("D293", "DIANO ARENTINO");
        this.put("D294", "DIANO BORELLO");
        this.put("D295", "DIANO CALDERINA");
        this.put("D296", "DIANO CASTELLO");
        this.put("D297", "DIANO MARINA");
        this.put("D298", "DIANO SAN PIETRO");
        this.put("D299", "DICOMANO");
        this.put("D300", "DIGNANO");
        this.put("D301", "DIGNANO D'ISTRIA");
        this.put("D302", "DIMARO");
        this.put("D303", "DINAMI");
        this.put("D303", "DINAMI");
        this.put("D304", "DIPIGNANO");
        this.put("D305", "DISO");
        this.put("D306", "DISSIMO");
        this.put("D307", "DIVACCIA GROTTE DEL TIMAVO");
        this.put("D308", "DIVACCIA SAN CANZIANO");
        this.put("D309", "DIVIGNANO");
        this.put("D310", "DIZZASCO");
        this.put("D311", "DOBBIACO * TOBLACH");
        this.put("D312", "DOBERDO'");
        this.put("D312", "DOBERDO' DEL LAGO");
        this.put("D313", "DOCCIO");
        this.put("D314", "DOGLIANI");
        this.put("D315", "DOGLIOLA");
        this.put("D316", "DOGNA");
        this.put("D317", "DOLCE'");
        this.put("D318", "DOLCEACQUA");
        this.put("D319", "DOLCEDO");
        this.put("D320", "DOLE");
        this.put("D321", "DOLEGNA");
        this.put("D321", "DOLEGNA DEL COLLIO");
        this.put("D322", "DOL GRANDE");
        this.put("D323", "DOLIANOVA");
        this.put("D324", "DOLINA");
        this.put("D324", "SAN DORLIGO DELLA VALLE");
        this.put("D325", "DOLO");
        this.put("D326", "DOL OTTELZA");
        this.put("D327", "DOLZAGO");
        this.put("D327", "DOLZAGO");
        this.put("D328", "DOMANICO");
        this.put("D329", "DOMASO");
        this.put("D330", "DOMEGGE");
        this.put("D330", "DOMEGGE DI CADORE");
        this.put("D331", "DOMICELLA");
        this.put("D332", "DOMODOSSOLA");
        this.put("D332", "DOMODOSSOLA");
        this.put("D333", "DOMUS DE MARIA");
        this.put("D334", "DOMUSNOVAS");
        this.put("D334", "DOMUSNOVAS");
        this.put("D335", "DOMUSNOVAS CANALES");
        this.put("D336", "DON");
        this.put("D337", "DONADA");
        this.put("D338", "DONAS");
        this.put("D338", "DONNAS");
        this.put("D338", "DONNAZ");
        this.put("D339", "DONATO");
        this.put("D339", "DONATO");
        this.put("D340", "DONELASCO");
        this.put("D341", "DONGO");
        this.put("D342", "DONIGALA");
        this.put("D342", "DONIGALA FENUGHEDU");
        this.put("D343", "DONIGALA");
        this.put("D343", "DONIGALA SIURGUS");
        this.put("D344", "DONORI");
        this.put("D345", "DORGALI");
        this.put("D346", "DORIO");
        this.put("D346", "DORIO");
        this.put("D347", "DORMELLETTO");
        this.put("D348", "DORNO");
        this.put("D349", "DORSINO");
        this.put("D350", "DORZANO");
        this.put("D350", "DORZANO");
        this.put("D351", "DOSOLO");
        this.put("D352", "DOSSENA");
        this.put("D353", "DOSSO BAROARDO");
        this.put("D354", "DOSSO DE' FRATI");
        this.put("D355", "DOSSO DEL LIRO");
        this.put("D356", "DOUES");
        this.put("D356", "DOVIA D'AOSTA");
        this.put("D357", "DOVADOLA");
        this.put("D358", "DOVERA");
        this.put("D359", "DOZIO");
        this.put("D360", "DOZZA");
        this.put("D361", "DRAGONI");
        this.put("D362", "DRAGUCCIO");
        this.put("D363", "DRANO");
        this.put("D364", "DRAPIA");
        this.put("D364", "DRAPIA");
        this.put("D365", "DRENA");
        this.put("D366", "DRENCHIA");
        this.put("D367", "DRESANO");
        this.put("D368", "DRESENZA");
        this.put("D369", "DREZZO");
        this.put("D370", "DRIZZONA");
        this.put("D371", "DRO");
        this.put("D372", "DRONERO");
        this.put("D373", "DRUENT");
        this.put("D373", "DRUENTO");
        this.put("D374", "DRUOGNO");
        this.put("D374", "DRUOGNO");
        this.put("D375", "DRUSACCO");
        this.put("D376", "DUALCHI");
        this.put("D377", "DUBINO");
        this.put("D378", "DUEMIGLIA");
        this.put("D379", "DUEVILLE");
        this.put("D380", "DUGENTA");
        this.put("D381", "DUGNANO");
        this.put("D382", "DUINO");
        this.put("D383", "DUINO-AURISINA");
        this.put("D384", "DUMENZA");
        this.put("D385", "DUNO");
        this.put("D386", "DURAZZANO");
        this.put("D387", "DUSINO");
        this.put("D388", "DUSINO SAN MICHELE");
        this.put("D389", "DUTTOGLIANO");
        this.put("D390", "EBOLI");
        this.put("D391", "EDOLO");
        this.put("D392", "EGNA * NEUMARKT");
        this.put("D393", "ELENA");
        this.put("D394", "ELICE");
        this.put("D395", "ELINI");
        this.put("D395", "ELINI");
        this.put("D396", "ELLE * ELLEN");
        this.put("D397", "ELLERA");
        this.put("D398", "ELLO");
        this.put("D398", "ELLO");
        this.put("D399", "ELMAS");
        this.put("D399", "ELMAS");
        this.put("D400", "ELSANE");
        this.put("D401", "ELVA");
        this.put("D402", "EMARESE");
        this.put("D403", "EMPOLI");
        this.put("D404", "ENDENNA");
        this.put("D405", "ENDINE");
        this.put("D406", "ENDINE GAIANO");
        this.put("D407", "ENEGO");
        this.put("D408", "ENEMONZO");
        this.put("D409", "ENGUISO");
        this.put("D410", "ENTRACQUE");
        this.put("D410", "ENTRAQUE");
        this.put("D411", "ENTRATICO");
        this.put("D412", "ENVIE");
        this.put("D413", "EORES * AFERS");
        this.put("D414", "EPISCOPIA");
        this.put("D415", "ERACLEA");
        this.put("D415", "GRISOLERA");
        this.put("D416", "ERBA");
        this.put("D417", "ERBA INCINO");
        this.put("D418", "ERBANNO");
        this.put("D419", "ERBE'");
        this.put("D420", "ERBEZZO");
        this.put("D421", "ERBUSCO");
        this.put("D422", "ERCHIE");
        this.put("D423", "ERICE");
        this.put("D423", "MONTE SAN GIULIANO");
        this.put("D424", "ERLI");
        this.put("D425", "ERPELLE-COSINA");
        this.put("D426", "ERTO E CASSO");
        this.put("D427", "ERSEL IN MONTE");
        this.put("D428", "ERVE");
        this.put("D428", "ERVE");
        this.put("D429", "ESANATOGLIA");
        this.put("D429", "SANT'ANATOLIA");
        this.put("D430", "ESCALAPLANO");
        this.put("D431", "ESCOLCA");
        this.put("D432", "ESCOVEDU");
        this.put("D433", "ESILLE");
        this.put("D433", "EXILLES");
        this.put("D434", "ESINE");
        this.put("D435", "ESINO INFERIORE");
        this.put("D436", "ESINO LARIO");
        this.put("D436", "ESINO LARIO");
        this.put("D437", "ESINO SUPERIORE");
        this.put("D438", "ESIO");
        this.put("D439", "ESMATE");
        this.put("D440", "ESPERIA");
        this.put("D441", "ESPORLATU");
        this.put("D442", "ESTE");
        this.put("D443", "ESTERZILI");
        this.put("D444", "ETROBLE");
        this.put("D444", "ETROUBLES");
        this.put("D445", "EUPILIO");
        this.put("D446", "FABIASCO");
        this.put("D447", "FABBRICA");
        this.put("D447", "FABBRICA CURONE");
        this.put("D448", "FABBRICA");
        this.put("D448", "FABBRICA DURINI");
        this.put("D449", "FABBRICHE DI VALLICO");
        this.put("D449", "TRASSILICO");
        this.put("D450", "FABBRICO");
        this.put("D451", "FABRIANO");
        this.put("D452", "FABRICA");
        this.put("D452", "FABRICA DI ROMA");
        this.put("D453", "FABRIZIA");
        this.put("D453", "FABRIZIA");
        this.put("D454", "FABRO");
        this.put("D455", "FAEDIS");
        this.put("D456", "FAEDO");
        this.put("D456", "FAEDO VALTELLINO");
        this.put("D457", "FAEDO");
        this.put("D458", "FAENZA");
        this.put("D459", "FAETO");
        this.put("D460", "FAETTO");
        this.put("D461", "FAGAGNA");
        this.put("D462", "FAGGETO LARIO");
        this.put("D463", "FAGGIANO");
        this.put("D464", "FAGNANO");
        this.put("D464", "FAGNANO CASTELLO");
        this.put("D465", "FAGNANO");
        this.put("D465", "FAGNANO ALTO");
        this.put("D466", "FAGNANO");
        this.put("D466", "FAGNANO SUL NAVIGLIO");
        this.put("D467", "FAGNANO");
        this.put("D467", "FAGNANO OLONA");
        this.put("D468", "FAI");
        this.put("D468", "FAI DELLA PAGANELLA");
        this.put("D469", "FAICCHIO");
        this.put("D470", "FALCADE");
        this.put("D471", "FALCIANO DEL MASSICO");
        this.put("D472", "FALCONARA");
        this.put("D472", "FALCONARA MARITTIMA");
        this.put("D473", "FALCONARA");
        this.put("D473", "FALCONARA ALBANESE");
        this.put("D474", "FALCONE");
        this.put("D475", "STABIA");
        this.put("D475", "FALERIA");
        this.put("D476", "FALERNA");
        this.put("D477", "FALERONE");
        this.put("D477", "FALERONE");
        this.put("D478", "FALESINA");
        this.put("D479", "FALLASCOSO");
        this.put("D480", "FALLO");
        this.put("D481", "FALMENTA");
        this.put("D481", "FALMENTA");
        this.put("D482", "FALOPPIO");
        this.put("D483", "FALVATERRA");
        this.put("D484", "FALZES * PFALZEN");
        this.put("D485", "FAMIE");
        this.put("D486", "FANANO");
        this.put("D487", "FANNA");
        this.put("D488", "FANO");
        this.put("D489", "FANO ADRIANO");
        this.put("D490", "FARA");
        this.put("D490", "FARA D'ADDA");
        this.put("D490", "FARA GERA D'ADDA");
        this.put("D491", "FARA");
        this.put("D491", "FARA OLIVANA CON SOLA");
        this.put("D492", "FARA");
        this.put("D492", "FARA NOVARESE");
        this.put("D493", "FARA");
        this.put("D493", "FARA IN SABINA");
        this.put("D494", "FARA FILIORUM PETRI");
        this.put("D495", "FARA SAN MARTINO");
        this.put("D496", "FARA VICENTINO");
        this.put("D497", "FARDELLA");
        this.put("D498", "FARFENGO");
        this.put("D499", "FARIGLIANO");
        this.put("D500", "FARINATE");
        this.put("D501", "FARINDOLA");
        this.put("D502", "FARINI");
        this.put("D502", "FARINI D'OLMO");
        this.put("D503", "FARNESE");
        this.put("D504", "FARRA");
        this.put("D504", "FARRA D'ISONZO");
        this.put("D505", "FARRA");
        this.put("D505", "FARRA DI SOLIGO");
        this.put("D506", "FARRA D'ALPAGO");
        this.put("D507", "FASANA");
        this.put("D508", "FASANO");
        this.put("D509", "FASCIA");
        this.put("D510", "FAUGLIA");
        this.put("D511", "FAULE");
        this.put("D512", "FAVALE");
        this.put("D512", "FAVALE DI MALVARO");
        this.put("D513", "VALSINNI");
        this.put("D513", "FAVALE");
        this.put("D513", "FAVALE SAN CATULDO");
        this.put("D514", "FAVARA");
        this.put("D515", "FAVARO");
        this.put("D515", "FAVARO VENETO");
        this.put("D516", "FAVER");
        this.put("D517", "FAVERZANO");
        this.put("D518", "FAVIGNANA");
        this.put("D519", "FAOGNA DI SOTTO * UNTERFENNBERG");
        this.put("D519", "FAVOGNA DI SOTTO");
        this.put("D520", "FAVRIA");
        this.put("D521", "FAVRIA-OGLIANICO");
        this.put("D521", "FAVRIA-OGLIANICO");
        this.put("D522", "FEGLINO");
        this.put("D522", "ORCO FEGLINO");
        this.put("D523", "FEISOGLIO");
        this.put("D524", "FELETTO");
        this.put("D525", "FELETTO");
        this.put("D525", "FELETTO UMBERTO");
        this.put("D526", "FELINO");
        this.put("D527", "FELITTO");
        this.put("D528", "FELIZZANO");
        this.put("D529", "FELONICA");
        this.put("D530", "FELTRE");
        this.put("D531", "FENEGRO'");
        this.put("D532", "FENESTRELLE");
        this.put("D533", "FENGO");
        this.put("D534", "FENIGLI");
        this.put("D535", "FENILE");
        this.put("D536", "FENILS");
        this.put("D537", "FENIS");
        this.put("D538", "FERENTILLO");
        this.put("D539", "FERENTINO");
        this.put("D540", "FERLA");
        this.put("D541", "FERMIGNANO");
        this.put("D542", "FERMO");
        this.put("D542", "FERMO");
        this.put("D543", "FERNO");
        this.put("D544", "FEROLETO ANTICO");
        this.put("D545", "FEROLETO DELLA CHIESA");
        this.put("D546", "FEROLETO PIANO");
        this.put("D546", "PIANOPOLI");
        this.put("D547", "FERRANDINA");
        this.put("D548", "FERRARA");
        this.put("D549", "FERRARA DI MONTE BALDO");
        this.put("D550", "FERRAZZANO");
        this.put("D551", "FERRERA");
        this.put("D551", "FERRERA DI VARESE");
        this.put("D552", "FERRERA");
        this.put("D552", "FERRERA ERBOGNONE");
        this.put("D553", "FERRERA");
        this.put("D553", "FERRERA CENISIO");
        this.put("D553", "MONCENISIO");
        this.put("D554", "FERRERE");
        this.put("D555", "FERRIERE");
        this.put("D556", "FERRUTA");
        this.put("D557", "FERRUZZANO");
        this.put("D558", "FERTILIA");
        this.put("D558", "FERTILIA");
        this.put("D559", "FIACCONE");
        this.put("D559", "FRACONALTO");
        this.put("D560", "FIAMIGNANO");
        this.put("D561", "FIANO");
        this.put("D561", "FIANO ROMANO");
        this.put("D562", "FIANO");
        this.put("D563", "FIANONA");
        this.put("D564", "FIASTRA");
        this.put("D565", "FIAVE'");
        this.put("D566", "FICANO");
        this.put("D566", "POGGIO SAN VICINO");
        this.put("D567", "FICARAZZI");
        this.put("D568", "FICAROLO");
        this.put("D569", "FICARRA");
        this.put("D570", "FICULLE");
        this.put("D571", "FIE' * VOELS");
        this.put("D571", "FIE' ALLO SCILIAR * VOELS AM SCHLERN");
        this.put("D572", "FIERA DI PRIMIERO");
        this.put("D573", "FIEROZZO");
        this.put("D574", "FIESCO");
        this.put("D575", "FIESOLE");
        this.put("D576", "FIESSE");
        this.put("D577", "FIESSO");
        this.put("D577", "FIESSO UMBERTIANO");
        this.put("D578", "FIESSO");
        this.put("D578", "FIESSO D'ARTICO");
        this.put("D579", "FIGINO");
        this.put("D579", "FIGINO SERENZA");
        this.put("D580", "FIGINO");
        this.put("D580", "FIGINO DI MILANO");
        this.put("D581", "FIGLIARO");
        this.put("D581", "MIRABELLO COMASCO");
        this.put("D581", "MIRABELLO COMASCO");
        this.put("D582", "FIGLINE");
        this.put("D582", "FIGLINE VEGLIATURO");
        this.put("D583", "FIGLINE");
        this.put("D583", "FIGLINE VALDARNO");
        this.put("D584", "FIGU");
        this.put("D585", "FIGU-GONNOSNO'");
        this.put("D585", "GONNOSNO'");
        this.put("D585", "GONNOSNO'");
        this.put("D586", "FILACCIANO");
        this.put("D587", "FILADELFIA");
        this.put("D587", "FILADELFIA");
        this.put("D588", "FILAGO");
        this.put("D588", "MARNE");
        this.put("D589", "FILANDARI");
        this.put("D589", "FILANDARI");
        this.put("D590", "FILATTIERA");
        this.put("D591", "FILETTINO");
        this.put("D591", "FILETTINO GRAZIANI");
        this.put("D592", "FILETTO");
        this.put("D593", "FILIANO");
        this.put("D594", "FILIGHERA");
        this.put("D595", "FILIGNANO");
        this.put("D596", "FILOGASO");
        this.put("D596", "FILOGASO");
        this.put("D597", "FILOTTRANO");
        this.put("D598", "FINALBORGO");
        this.put("D599", "FINALE");
        this.put("D599", "FINALE EMILIA");
        this.put("D599", "FINALE NELL'EMILIA");
        this.put("D600", "FINALE LIGURE");
        this.put("D601", "FINALMARINA");
        this.put("D602", "FINALPIA");
        this.put("D603", "FINERO");
        this.put("D604", "FINO");
        this.put("D604", "FINO DEL MONTE");
        this.put("D605", "FINO");
        this.put("D605", "FINO MORNASCO");
        this.put("D606", "FIORANO");
        this.put("D606", "FIORANO AL SERIO");
        this.put("D606", "FIORANO AL SERIO");
        this.put("D607", "FIORANO");
        this.put("D607", "FIORANO MODENESE");
        this.put("D608", "FIORANO");
        this.put("D608", "FIORANO CANAVESE");
        this.put("D609", "FIORDIMONTE");
        this.put("D610", "FIORENZUOLA");
        this.put("D610", "FIORENZUOLA DI FOCARA");
        this.put("D611", "FIORENZUOLA");
        this.put("D611", "FIORENZUOLA D'ARDA");
        this.put("D612", "FIRENZE");
        this.put("D613", "FIRENZUOLA");
        this.put("D614", "FIRMO");
        this.put("D615", "FISCIANO");
        this.put("D616", "FISTO");
        this.put("D617", "FIUMALBO");
        this.put("D618", "FIUMANA");
        this.put("D618", "FIUMANA");
        this.put("D619", "FIUMARA");
        this.put("D620", "FIUME");
        this.put("D621", "FIUME VENETO");
        this.put("D621", "FIUME");
        this.put("D622", "FIUMEDINISI");
        this.put("D623", "FIUMEFREDDO");
        this.put("D623", "FIUMEFREDDO DI SICILIA");
        this.put("D624", "FIUMEFREDDO");
        this.put("D624", "FIUMEFREDDO BRUZIO");
        this.put("D625", "FIUMENERO");
        this.put("D626", "FIUMICELLO");
        this.put("D626", "FIUMICELLO URAGO");
        this.put("D627", "FIUMICELLO");
        this.put("D628", "FIUMINATA");
        this.put("D629", "FIVIZZANO");
        this.put("D630", "FLAIBANO");
        this.put("D630", "SANT'ODORICO");
        this.put("D631", "FLAVON");
        this.put("D632", "FLECCHIA");
        this.put("D633", "FLERES * PFLERSCH");
        this.put("D634", "FLERO");
        this.put("D635", "FLORESTA");
        this.put("D636", "FLORIDIA");
        this.put("D637", "FLORINAS");
        this.put("D638", "FLUMERI");
        this.put("D639", "FLUMINIMAGGIORE");
        this.put("D639", "FLUMINIMAGGIORE");
        this.put("D640", "FLUSSIO");
        this.put("D641", "FOBELLO");
        this.put("D642", "FOCE");
        this.put("D643", "FOGGIA");
        this.put("D644", "FOGLIANISE");
        this.put("D645", "FOGLIANO REDIPUGLIA");
        this.put("D645", "FOGLIANO DI MONFALCONE");
        this.put("D646", "FOGLIZZO");
        this.put("D647", "FOGNA");
        this.put("D648", "FOIANA * VOELLAN");
        this.put("D649", "FOIANO");
        this.put("D649", "FOIANO DELLA CHIANA");
        this.put("D650", "FOIANO");
        this.put("D650", "FOIANO DI VAL FORTORE");
        this.put("D651", "FOLGARIA");
        this.put("D652", "FOLIGNANO");
        this.put("D653", "FOLIGNO");
        this.put("D654", "FOLLINA");
        this.put("D655", "FOLLO");
        this.put("D656", "FOLLONICA");
        this.put("D657", "FOLSOGNO");
        this.put("D658", "FOLZANO");
        this.put("D659", "FOMARCO");
        this.put("D660", "FOMBIO");
        this.put("D660", "FOMBIO");
        this.put("D661", "FONDACHELLI-FANTINA");
        this.put("D662", "FONDI");
        this.put("D663", "FONDO");
        this.put("D664", "FONDRA");
        this.put("D665", "FONNI");
        this.put("D666", "FONTAINEMORE");
        this.put("D667", "FONTANA");
        this.put("D667", "FONTANA LIRI");
        this.put("D668", "FONTANA ELICE");
        this.put("D668", "FONTANELICE");
        this.put("D668", "FONTANA");
        this.put("D669", "FONTANA DEL CONTE");
        this.put("D670", "FONTANAFREDDA");
        this.put("D671", "FONTANAROSA");
        this.put("D672", "FONTANELLA");
        this.put("D673", "FONTANELLATO");
        this.put("D674", "FONTANELLE");
        this.put("D675", "FONTANETO D'AGOGNA");
        this.put("D675", "FONTANETTO");
        this.put("D676", "FONTANETTO");
        this.put("D676", "FONTANETTO DA PO");
        this.put("D676", "FONTANETTO PO");
        this.put("D677", "FONTANIGORDA");
        this.put("D678", "FONTANILE");
        this.put("D679", "FONTANIVA");
        this.put("D680", "FONTE");
        this.put("D681", "FONTECCHIO");
        this.put("D682", "FONTECHIARI");
        this.put("D682", "SCHIAVI");
        this.put("D683", "FONTEGRECA");
        this.put("D683", "FOSSACECA");
        this.put("D684", "FONTENO");
        this.put("D684", "FONTENO");
        this.put("D685", "FONTEVIVO");
        this.put("D686", "FONZASO");
        this.put("D687", "FOPPA");
        this.put("D688", "FOPPOLO");
        this.put("D689", "FORANO");
        this.put("D690", "FORCABOBOLINA");
        this.put("D690", "SAN GIOVANNI TEATINO");
        this.put("D691", "FORCE");
        this.put("D692", "FORCELLO");
        this.put("D693", "FORCHIA");
        this.put("D694", "FORCOLA");
        this.put("D695", "FORDONGIANUS");
        this.put("D695", "FORDONGIANUS");
        this.put("D696", "FORENZA");
        this.put("D697", "FORESTO");
        this.put("D697", "FORESTO SPARSO");
        this.put("D698", "FORESTO");
        this.put("D698", "FORESTO SESIA");
        this.put("D699", "FORESTO");
        this.put("D699", "FORESTO DI SUSA");
        this.put("D700", "FORGARIA");
        this.put("D700", "FORGARIA NEL FRIULI");
        this.put("D701", "FORINO");
        this.put("D702", "FORIO");
        this.put("D703", "FORLI");
        this.put("D703", "FORLI' DEL SANNIO");
        this.put("D704", "FORLI'");
        this.put("D705", "FORLIMPOPOLI");
        this.put("D706", "FORMAZZA");
        this.put("D706", "FORMAZZA");
        this.put("D707", "FORMELLO");
        this.put("D708", "FORMIA");
        this.put("D708", "MOLA E CASTELLONE");
        this.put("D709", "FORMICOLA");
        this.put("D710", "FORMIGARA");
        this.put("D711", "FORMIGINE");
        this.put("D712", "FORMIGLIANA");
        this.put("D713", "FORMIGNANA");
        this.put("D714", "FORNACE");
        this.put("D715", "FORNELLI");
        this.put("D716", "FORNERO");
        this.put("D717", "FORNI");
        this.put("D717", "TONEZZA");
        this.put("D717", "TONEZZA DEL CIMONE");
        this.put("D718", "FORNI AVOLTRI");
        this.put("D719", "FORNI DI SOPRA");
        this.put("D720", "FORNI DI SOTTO");
        this.put("D721", "FORNI IN VAL D'ASTICO");
        this.put("D722", "FORNO");
        this.put("D723", "FORNO");
        this.put("D724", "FORNO ALPI GRAIE");
        this.put("D724", "FORNO GROSCAVALLO");
        this.put("D725", "FORNO CANAVESE");
        this.put("D725", "FORNO DI RIVARA");
        this.put("D726", "FORNO DI ZOLDO");
        this.put("D727", "FORNOVO");
        this.put("D727", "FORNOVO DI SAN GIOVANNI");
        this.put("D727", "FORNOVO SAN GIOVANNI");
        this.put("D728", "FORNOVO");
        this.put("D728", "FORNOVO DI TARO");
        this.put("D729", "FOROTONDO");
        this.put("D730", "FORTE DEI MARMI");
        this.put("D731", "FORTEZZA * FRANZENSFESTE");
        this.put("D731", "MEZZASELVA * MITTEWALD");
        this.put("D731", "MEZZASELVA ALL'ISARCO * MITTEWALD AM EISAK");
        this.put("D732", "FORTUNAGO");
        this.put("D733", "FORZA D'AGRO'");
        this.put("D734", "FOSCIANDORA");
        this.put("D735", "FOSDINOVO");
        this.put("D736", "FOSSA");
        this.put("D737", "FOSSACECA");
        this.put("D737", "FOSSALTO");
        this.put("D738", "FOSSACECA");
        this.put("D738", "FOSSACESIA");
        this.put("D739", "FOSSA GUAZZONA");
        this.put("D740", "FOSSALTA");
        this.put("D740", "FOSSALTA DI PIAVE");
        this.put("D741", "FOSSALTA");
        this.put("D741", "FOSSALTA DI PORTOGRUARO");
        this.put("D742", "FOSSANO");
        this.put("D743", "FOSSARMATO");
        this.put("D743", "FOSSARMATO");
        this.put("D744", "FOSSATO");
        this.put("D744", "FOSSATO SERRALTA");
        this.put("D745", "FOSSATO");
        this.put("D745", "FOSSATO DI VICO");
        this.put("D746", "FOSSATO CALABRO");
        this.put("D746", "MONTEBELLO");
        this.put("D746", "MONTEBELLO IONICO");
        this.put("D747", "FOSSENO");
        this.put("D748", "FOSSO'");
        this.put("D749", "FOSSOMBRONE");
        this.put("D750", "FOZA");
        this.put("D751", "FRABOSA SOPRANA");
        this.put("D752", "FRABOSA SOTTANA");
        this.put("D753", "FRACCHIA");
        this.put("D754", "FRAGAGNANO");
        this.put("D755", "FRAGNETO L'ABATE");
        this.put("D756", "FRAGNETO MONFORTE");
        this.put("D757", "FRAINE");
        this.put("D758", "FRAMURA");
        this.put("D759", "FRANCAVILLA");
        this.put("D759", "FRANCAVILLA BISIO");
        this.put("D760", "FRANCAVILLA");
        this.put("D760", "FRANCAVILLA D'ETE");
        this.put("D760", "FRANCAVILLA D'ETE");
        this.put("D761", "FRANCAVILLA");
        this.put("D761", "FRANCAVILLA FONTANA");
        this.put("D762", "FRANCAVILLA");
        this.put("D762", "FRANCAVILLA ANGITOLA");
        this.put("D762", "FRANCAVILLA ANGITOLA");
        this.put("D763", "FRANCAVILLA");
        this.put("D763", "FRANCAVILLA AL MARE");
        this.put("D764", "FRANCAVILLA");
        this.put("D764", "FRANCAVILLA MARITTIMA");
        this.put("D765", "FRANCAVILLA");
        this.put("D765", "FRANCAVILLA DI SICILIA");
        this.put("D766", "FRANCAVILLA");
        this.put("D766", "FRANCAVILLA IN SINNI");
        this.put("D767", "FRANCICA");
        this.put("D767", "FRANCICA");
        this.put("D768", "FRANCOFONTE");
        this.put("D769", "FRANCOLISE");
        this.put("D770", "FRASCARO");
        this.put("D771", "FRASCAROLO");
        this.put("D772", "FRASCATA");
        this.put("D773", "FRASCATI");
        this.put("D774", "FRASCINETO");
        this.put("D775", "FRASSILONGO");
        this.put("D776", "FRASSINELLE");
        this.put("D776", "FRASSINELLE POLESINE");
        this.put("D777", "FRASSINELLO");
        this.put("D777", "FRASSINELLO MONFERRATO");
        this.put("D778", "FRASSINELLO-OLIVOLA");
        this.put("D778", "FRASSINELLO-OLIVOLA");
        this.put("D779", "FRASSINERE");
        this.put("D780", "FRASSINETO PO");
        this.put("D781", "FRASSINETTO");
        this.put("D782", "FRASSINO");
        this.put("D783", "FRASSINORO");
        this.put("D784", "FRASSO");
        this.put("D784", "FRASSO TELESINO");
        this.put("D785", "FRASSO");
        this.put("D785", "FRASSO SABINO");
        this.put("D786", "FRATTA");
        this.put("D786", "UMBERTIDE");
        this.put("D787", "FRATTA");
        this.put("D787", "FRATTA TODINA");
        this.put("D788", "FRATTA");
        this.put("D788", "FRATTA POLESINE");
        this.put("D789", "FRATTAMAGGIORE");
        this.put("D790", "FRATTAMINORE");
        this.put("D790", "POMIGLIANO D'ATELLA");
        this.put("D791", "FRATTE");
        this.put("D791", "FRATTE ROSA");
        this.put("D792", "FRAVEGGIO");
        this.put("D793", "FRAZZANO'");
        this.put("D794", "FREGONA");
        this.put("D795", "FREROLA");
        this.put("D796", "FRESAGRANDINARIA");
        this.put("D797", "FRESONARA");
        this.put("D798", "FRIGENTO");
        this.put("D799", "FRIGNANO");
        this.put("D800", "FRIGNANO MAGGIORE");
        this.put("D801", "FRIGNANO PICCOLO");
        this.put("D801", "VILLA DI BRIANO");
        this.put("D802", "FRINCO");
        this.put("D803", "FRISA");
        this.put("D804", "FRISANCO");
        this.put("D805", "FRONT");
        this.put("D806", "FRONTIGNANO");
        this.put("D807", "FRONTINO");
        this.put("D808", "FRONTONE");
        this.put("D809", "FRONTONE-SERRA");
        this.put("D809", "FRONTONE-SERRA");
        this.put("D810", "FROSINONE");
        this.put("D811", "FROSOLONE");
        this.put("D812", "FROSSASCO");
        this.put("D813", "FRUGAROLO");
        this.put("D814", "FUBINE");
        this.put("D815", "FUCECCHIO");
        this.put("D816", "FUIPIANO");
        this.put("D816", "FUIPIANO AL BREMBO");
        this.put("D816", "FUIPIANO AL BREMBO");
        this.put("D817", "FUIPIANO VALLE IMAGNA");
        this.put("D818", "FUMANE");
        this.put("D819", "FUMONE");
        this.put("D820", "FUNDOLES * PFUNDERS");
        this.put("D820", "FUNDRES * PFUNDERS");
        this.put("D821", "FUNES * VILLNOESS");
        this.put("D822", "FURATO");
        this.put("D823", "FURCI");
        this.put("D824", "FURCI SICULO");
        this.put("D825", "FURNARI");
        this.put("D826", "FURORE");
        this.put("D826", "FURORE");
        this.put("D827", "FURTEI");
        this.put("D827", "FURTEI");
        this.put("D828", "FUSCALDO");
        this.put("D829", "FUSIGNANO");
        this.put("D830", "FUSINE");
        this.put("D831", "FUSINE IN VALROMANA");
        this.put("D831", "ROCCALBA");
        this.put("D832", "FUTANI");
        this.put("D833", "GABBIONETA");
        this.put("D834", "GABBIONETA BINANUOVA");
        this.put("D835", "GABIANO");
        this.put("D836", "GABICCE");
        this.put("D836", "GABICCE MARE");
        this.put("D837", "GABRIA");
        this.put("D838", "GABROVIZZA");
        this.put("D839", "GABY");
        this.put("D840", "GADESCO");
        this.put("D841", "GADESCO PIEVE DELMONA");
        this.put("D842", "GADONI");
        this.put("D843", "GAETA");
        this.put("D844", "GAGGI");
        this.put("D844", "KAGGI");
        this.put("D845", "GAGGIANO");
        this.put("D846", "GAGGINO");
        this.put("D847", "GAGGIO MONTANO");
        this.put("D848", "GAGLIANICO");
        this.put("D848", "GAGLIANICO");
        this.put("D849", "GAGLIANO");
        this.put("D849", "GAGLIANO CASTELFERRATO");
        this.put("D850", "GAGLIANO");
        this.put("D850", "GAGLIANO ATERNO");
        this.put("D851", "GAGLIANO");
        this.put("D851", "GAGLIANO DEL CAPO");
        this.put("D852", "GAGLIATO");
        this.put("D853", "GAGLIOLE");
        this.put("D854", "GAIARINE");
        this.put("D855", "GAIBA");
        this.put("D856", "GAIOLA");
        this.put("D857", "GAIOLA-MOIOLA");
        this.put("D857", "GAIOLA-MOIOLA");
        this.put("D858", "GAIOLE");
        this.put("D858", "GAIOLE IN CHIANTI");
        this.put("D859", "GAIRO");
        this.put("D859", "GAIRO");
        this.put("D860", "GAIS * GAIS");
        this.put("D861", "GALATI");
        this.put("D861", "GALATI MAMERTINO");
        this.put("D862", "GALATINA");
        this.put("D863", "GALATONE");
        this.put("D864", "GALATRO");
        this.put("D865", "GALBIATE");
        this.put("D865", "GALBIATE");
        this.put("D866", "GALDO");
        this.put("D867", "GALEATA");
        this.put("D868", "GALGAGNANO");
        this.put("D868", "GALGAGNANO");
        this.put("D869", "GALLARATE");
        this.put("D870", "GALLESE");
        this.put("D871", "GALLIATE");
        this.put("D871", "GALLIATE LOMBARDO");
        this.put("D872", "GALLIATE");
        this.put("D873", "GALLIAVOLA");
        this.put("D874", "GALLICANO");
        this.put("D875", "GALLICANO");
        this.put("D875", "GALLICANO NEL LAZIO");
        this.put("D876", "GALLICCHIO");
        this.put("D877", "GALLICO");
        this.put("D878", "GALLIERA");
        this.put("D879", "GALLIERA");
        this.put("D879", "GALLIERA VENETA");
        this.put("D880", "GALLINA");
        this.put("D881", "GALLINARO");
        this.put("D882", "GALLIO");
        this.put("D883", "GALLIPOLI");
        this.put("D884", "GALLO");
        this.put("D884", "GALLO MATESE");
        this.put("D885", "GALLODORO");
        this.put("D886", "GALLUCCIO");
        this.put("D887", "GALLUZZO");
        this.put("D887", "GALLUZZO");
        this.put("D887", "GALLUZZO");
        this.put("D887", "GALLUZZO");
        this.put("D888", "GALTELLI");
        this.put("D889", "GALZIGNANO");
        this.put("D889", "GALZIGNANO TERME");
        this.put("D890", "GAMALERO");
        this.put("D891", "GAMBARA");
        this.put("D892", "GAMBARANA");
        this.put("D893", "GAMBARARE");
        this.put("D894", "GAMBASCA");
        this.put("D895", "GAMBASSI");
        this.put("D895", "GAMBASSI TERME");
        this.put("D896", "GAMBATESA");
        this.put("D897", "GAMBELLARA");
        this.put("D898", "GAMBERALE");
        this.put("D899", "GAMBETTOLA");
        this.put("D900", "GAMBINA BARCHETTI");
        this.put("D901", "GAMBOLO'");
        this.put("D902", "GAMBUGLIANO");
        this.put("D903", "GANDELLINO");
        this.put("D904", "GANDINI");
        this.put("D905", "GANDINO");
        this.put("D906", "GANDOSSO");
        this.put("D907", "GANGI");
        this.put("D908", "GARABIOLO");
        this.put("D909", "GARAGUSO");
        this.put("D910", "GARBAGNA");
        this.put("D911", "GARBAGNA");
        this.put("D911", "GARBAGNA NOVARESE");
        this.put("D912", "GARBAGNATE");
        this.put("D912", "GARBAGNATE MILANESE");
        this.put("D913", "GARBAGNATE MONASTERO");
        this.put("D913", "GARBAGNATE MONASTERO");
        this.put("D914", "GARBATOLA");
        this.put("D915", "GARDA");
        this.put("D916", "GARDOLO");
        this.put("D917", "GARDONE RIVIERA");
        this.put("D918", "GARDONE VAL TROMPIA");
        this.put("D919", "GAREGNANO");
        this.put("D920", "GARESSIO");
        this.put("D921", "GARGALLO");
        this.put("D922", "GARGARO");
        this.put("D923", "GARGAZZONE * GARGAZON");
        this.put("D924", "GARGNANO");
        this.put("D925", "GARLASCO");
        this.put("D926", "GARLATE");
        this.put("D926", "GARLATE");
        this.put("D927", "GARLENDA");
        this.put("D928", "GARNIGA");
        this.put("D928", "GARNIGA TERME");
        this.put("D929", "GAROFAI");
        this.put("D930", "GARZENO");
        this.put("D931", "GARZIGLIANA");
        this.put("D932", "GASPERINA");
        this.put("D933", "GASSINO");
        this.put("D933", "GASSINO TORINESE");
        this.put("D934", "GATTATICO");
        this.put("D935", "GATTEO");
        this.put("D936", "GATTERA MAIOCCA");
        this.put("D937", "GATTICO");
        this.put("D938", "GATTINARA");
        this.put("D939", "GAUNA");
        this.put("D940", "GAVARDO");
        this.put("D941", "GAVAZZANA");
        this.put("D941", "GAVAZZANA");
        this.put("D942", "GAVELLO");
        this.put("D943", "GAVERINA");
        this.put("D943", "GAVERINA TERME");
        this.put("D944", "GAVI");
        this.put("D945", "GAVIGNANO");
        this.put("D946", "GAVIRATE");
        this.put("D947", "GAVOI");
        this.put("D948", "GAVORRANO");
        this.put("D949", "GAZOLDO DEGLI IPPOLITI");
        this.put("D949", "GAZZOLDO");
        this.put("D950", "GAZZADA");
        this.put("D951", "GAZZADA SCHIANNO");
        this.put("D952", "GAZZANIGA");
        this.put("D953", "GAZZANO");
        this.put("D954", "GAZZELLI");
        this.put("D955", "GAZZO");
        this.put("D956", "GAZZO");
        this.put("D956", "GAZZO PADOVANO");
        this.put("D957", "GAZZO");
        this.put("D957", "GAZZO VERONESE");
        this.put("D958", "GAZZOLA");
        this.put("D958", "RIVALTA");
        this.put("D958", "RIVALTA TREBBIA");
        this.put("D959", "GAZZUOLO");
        this.put("D960", "GELA");
        this.put("D960", "TERRANOVA");
        this.put("D960", "TERRANOVA DI SICILIA");
        this.put("D961", "GEMMANO");
        this.put("D961", "GEMMANO");
        this.put("D962", "GEMONA");
        this.put("D962", "GEMONA DEL FRIULI");
        this.put("D963", "GEMONIO");
        this.put("D964", "GENAZZANO");
        this.put("D965", "GENGA");
        this.put("D966", "GENIVOLTA");
        this.put("D967", "GENOLA");
        this.put("D968", "GENONI");
        this.put("D969", "GENOVA");
        this.put("D970", "GENURI");
        this.put("D970", "GENURI");
        this.put("D971", "GENZANO");
        this.put("D971", "GENZANO DI LUCANIA");
        this.put("D972", "GENZANO");
        this.put("D972", "GENZANO DI ROMA");
        this.put("D973", "GENZONE");
        this.put("D974", "GERA");
        this.put("D974", "GERA LARIO");
        this.put("D975", "GERACE");
        this.put("D975", "GERACE SUPERIORE");
        this.put("D976", "GERACE MARINA");
        this.put("D976", "LOCRI");
        this.put("D977", "GERACI");
        this.put("D977", "GERACI SICULO");
        this.put("D978", "GERANO");
        this.put("D979", "GERE DEL PESCE");
        this.put("D980", "GERENZAGO");
        this.put("D981", "GERENZANO");
        this.put("D982", "GERGEI");
        this.put("D983", "GERMAGNANO");
        this.put("D984", "GERMAGNO");
        this.put("D984", "GERMAGNO");
        this.put("D985", "GERMANEDO");
        this.put("D986", "GERMASINO");
        this.put("D987", "GERMIGNAGA");
        this.put("D988", "GEROCARNE");
        this.put("D988", "GEROCARNE");
        this.put("D989", "GEROLA");
        this.put("D989", "GEROLANUOVA");
        this.put("D990", "GEROLA");
        this.put("D990", "GEROLA ALTA");
        this.put("D991", "GEROSA");
        this.put("D992", "GERRE CHIOZZO");
        this.put("D993", "GERRE DE' CAPRIOLI");
        this.put("D994", "GESICO");
        this.put("D995", "GESSATE");
        this.put("D996", "GESSOPALENA");
        this.put("D997", "GESTURI");
        this.put("D997", "GESTURI");
        this.put("D998", "GESUALDO");
        this.put("D999", "GHEDI");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
