package document;

import java.util.HashMap;

/**
 * Created by Matteo on 12/11/2015.
 */
@SuppressWarnings("serial")
public class CitiesCodes_L extends HashMap<String, String> {

    public CitiesCodes_L(){
        this.put("L001", "SULBIATE SUPERIORE");
        this.put("L002", "SULZANO");
        this.put("L003", "SUMIRAGO");
        this.put("L004", "SUMMONTE");
        this.put("L005", "SUNA");
        this.put("L006", "SUNI");
        this.put("L007", "SUNO");
        this.put("L008", "SUPERSANO");
        this.put("L009", "SUPINO");
        this.put("L010", "SURANO");
        this.put("L011", "SURBO");
        this.put("L012", "SUSA'");
        this.put("L013", "SUSA");
        this.put("L014", "SUSEGANA");
        this.put("L015", "SUSTINENTE");
        this.put("L016", "SUTERA");
        this.put("L017", "SUTRI");
        this.put("L018", "SUTRIO");
        this.put("L019", "SUVERETO");
        this.put("L020", "SUZZARA");
        this.put("L021", "TABLA' * TABLAND");
        this.put("L022", "TACENO");
        this.put("L022", "TACENO");
        this.put("L023", "TADASUNI");
        this.put("L023", "TADASUNI");
        this.put("L024", "TAGGIA");
        this.put("L025", "TAGLIACOZZO");
        this.put("L026", "TAGLIO DI PO");
        this.put("L027", "TAGLIOLO");
        this.put("L027", "TAGLIOLO MONFERRATO");
        this.put("L028", "TAGLIOLO-BELFORTE");
        this.put("L028", "TAGLIOLO-BELFORTE");
        this.put("L029", "TAGLIUNO");
        this.put("L030", "TAIBON");
        this.put("L030", "TAIBON AGORDINO");
        this.put("L031", "TAINATE");
        this.put("L032", "TAINO");
        this.put("L033", "TAIO");
        this.put("L034", "TALAMELLO");
        this.put("L034", "TALAMELLO");
        this.put("L035", "TALAMONA");
        this.put("L036", "TALANA");
        this.put("L036", "TALANA");
        this.put("L037", "TALEGGIO");
        this.put("L038", "TALLA");
        this.put("L039", "TALMASSONS");
        this.put("L040", "TAMBRE");
        this.put("L041", "TANAS * TANAS");
        this.put("L042", "TAORMINA");
        this.put("L043", "TAPIGLIANO");
        this.put("L044", "TAPOGLIANO");
        this.put("L045", "TAPPIA");
        this.put("L046", "TARANO");
        this.put("L047", "TARANTA");
        this.put("L047", "TARANTA PELIGNA");
        this.put("L048", "TARANTASCA");
        this.put("L049", "TARANTO");
        this.put("L050", "TARCENTO");
        this.put("L051", "TARCES * TARTSCH");
        this.put("L051", "TARRES DI SOPRA * TARTSCH");
        this.put("L052", "TARCETTA");
        this.put("L053", "TARNOVA DELLA SELVA");
        this.put("L054", "TARRES * TARSCH");
        this.put("L054", "TARRES DI SOTTO * TARSCH");
        this.put("L055", "TARSIA");
        this.put("L056", "TARTANO");
        this.put("L057", "TARVISIO");
        this.put("L058", "TARZO");
        this.put("L059", "TASSAROLO");
        this.put("L060", "TASSULLO");
        this.put("L061", "TAURANO");
        this.put("L062", "TAURASI");
        this.put("L063", "TAURIANOVA");
        this.put("L064", "TAURISANO");
        this.put("L065", "TAVAGNACCO");
        this.put("L066", "TAVAGNASCO");
        this.put("L067", "TAVARNELLE");
        this.put("L067", "TAVARNELLE VAL DI PESA");
        this.put("L068", "TAVAZZANO");
        this.put("L069", "TAVENNA");
        this.put("L070", "TAVERNA");
        this.put("L071", "TAVERNERIO");
        this.put("L072", "TAVERNOLA");
        this.put("L072", "TAVERNOLA SAN FELICE");
        this.put("L073", "TAVERNOLA");
        this.put("L073", "TAVERNOLA BERGAMASCA");
        this.put("L074", "TAVIANO");
        this.put("L075", "TAVIGLIANO");
        this.put("L075", "TAVIGLIANO");
        this.put("L076", "TAVODO");
        this.put("L077", "TAVOLE");
        this.put("L078", "TAVOLETO");
        this.put("L079", "TAVON");
        this.put("L080", "TAVORDO");
        this.put("L081", "TAVULLIA");
        this.put("L081", "TOMBA DI PESARO");
        this.put("L082", "TEANA");
        this.put("L083", "TEANO");
        this.put("L084", "TEGLIO");
        this.put("L085", "TEGLIO");
        this.put("L085", "TEGLIO VENETO");
        this.put("L086", "TELESE");
        this.put("L086", "TELESE TERME");
        this.put("L087", "TELGATE");
        this.put("L088", "TELTI");
        this.put("L088", "TELTI");
        this.put("L089", "TELVE");
        this.put("L090", "TELVE DI SOPRA");
        this.put("L091", "TELVES * TELFES");
        this.put("L092", "TEMENIZZA");
        this.put("L093", "TEMPIO PAUSANIA");
        this.put("L093", "TEMPIO PAUSANIA");
        this.put("L094", "TEMU'");
        this.put("L095", "TENDA");
        this.put("L095", "TENDA");
        this.put("L095", "TENDA");
        this.put("L096", "TENNA");
        this.put("L097", "TENNO");
        this.put("L098", "TEODONA * DIETENHEIM");
        this.put("L098", "TEODONE * DIETENHEIM");
        this.put("L099", "TEODORANO");
        this.put("L099", "TEODORANO");
        this.put("L099", "TEODORANO");
        this.put("L099", "TEODORANO");
        this.put("L100", "TEOLO");
        this.put("L101", "TEOR");
        this.put("L102", "TEORA");
        this.put("L103", "TERAMO");
        this.put("L104", "TERDOBBIATE");
        this.put("L105", "TERELLE");
        this.put("L106", "TERENTO * TERENTEN");
        this.put("L107", "TERLAGO");
        this.put("L108", "TERLANO * TERLAN");
        this.put("L109", "TERLIZZI");
        this.put("L110", "TERMENAGO");
        this.put("L111", "TERMENO * TRAMIN");
        this.put("L111", "TERMENO SULLA STRADA DEL VINO * TRAMIN AN DER WEINSTRASSE");
        this.put("L112", "TERMINI");
        this.put("L112", "TERMINI IMERESE");
        this.put("L113", "TERMOLI");
        this.put("L114", "TERMON");
        this.put("L115", "TERNATE");
        this.put("L116", "TERNENGO");
        this.put("L116", "TERNENGO");
        this.put("L117", "TERNI");
        this.put("L118", "TERNO");
        this.put("L118", "TERNO D'ISOLA");
        this.put("L119", "TERNOVA D'ISONZO");
        this.put("L120", "TERRACINA");
        this.put("L121", "TERRAGNOLO");
        this.put("L122", "TERRALBA");
        this.put("L122", "TERRALBA");
        this.put("L123", "TERRANOVA");
        this.put("L123", "TERRANUOVA BRACCIOLINI");
        this.put("L124", "TERRANOVA");
        this.put("L124", "TERRANOVA DA SIBARI");
        this.put("L125", "TERRANOVA DEI PASSERINI");
        this.put("L125", "TERRANOVA");
        this.put("L125", "TERRANOVA DEI PASSERINI");
        this.put("L126", "TERRANOVA");
        this.put("L126", "TERRANOVA DI POLLINO");
        this.put("L127", "TERRANOVA");
        this.put("L127", "TERRANOVA SAPPO MINULIO");
        this.put("L128", "TERRANOVA DI BISTERZA");
        this.put("L129", "TERRAROSSA");
        this.put("L129", "TERRAROSSA");
        this.put("L130", "TERRASA");
        this.put("L131", "TERRASINI");
        this.put("L131", "TERRASINI FAVAROTTA");
        this.put("L132", "TERRASSA");
        this.put("L132", "TERRASSA PADOVANA");
        this.put("L133", "TERRATI");
        this.put("L134", "TERRAVECCHIA");
        this.put("L135", "TERRAZZANO");
        this.put("L136", "TERRAZZO");
        this.put("L137", "TERRES");
        this.put("L138", "TERRICCIOLA");
        this.put("L139", "TERRUGGIA");
        this.put("L140", "TERTENIA");
        this.put("L140", "TERTENIA");
        this.put("L141", "TERZANO");
        this.put("L142", "TERZIGNO");
        this.put("L143", "TERZO");
        this.put("L143", "TERZO");
        this.put("L144", "TERZO");
        this.put("L144", "TERZO DI AQUILEIA");
        this.put("L145", "TERZOLAS");
        this.put("L146", "TERZORIO");
        this.put("L147", "TESERO");
        this.put("L148", "TESIDO * TAISTEN");
        this.put("L149", "TESIMO * TISENS");
        this.put("L150", "TESSENNANO");
        this.put("L151", "TESTACCIO");
        this.put("L151", "TESTACCIO D'ISCHIA");
        this.put("L152", "TESTICO");
        this.put("L153", "TETI");
        this.put("L154", "TEULADA");
        this.put("L155", "TEVEROLA");
        this.put("L156", "TEZZE");
        this.put("L156", "TEZZE SUL BRENTA");
        this.put("L157", "THIENE");
        this.put("L158", "THIESI");
        this.put("L159", "THURES");
        this.put("L160", "TIANA");
        this.put("L161", "TIARNO");
        this.put("L161", "TIARNO");
        this.put("L162", "TIARNO DI SOPRA");
        this.put("L163", "TIARNO DI SOTTO");
        this.put("L164", "TICENGO");
        this.put("L165", "TICINETO");
        this.put("L166", "TIGGIANO");
        this.put("L167", "TIGLIETO");
        this.put("L168", "TIGLIOLE");
        this.put("L169", "TIGNALE");
        this.put("L170", "TIMOLINE");
        this.put("L171", "TINA");
        this.put("L172", "TINNURA");
        this.put("L173", "TIONE");
        this.put("L173", "TIONE DEGLI ABRUZZI");
        this.put("L174", "TIONE");
        this.put("L174", "TIONE DI TRENTO");
        this.put("L175", "TIRANO");
        this.put("L176", "TIRES * TIERS");
        this.put("L177", "TIRIOLO");
        this.put("L178", "TIROLO * TIROL");
        this.put("L179", "TISA * TEIS");
        this.put("L179", "TISO * TEIS");
        this.put("L180", "TISSI");
        this.put("L181", "TITO");
        this.put("L182", "TIVOLI");
        this.put("L183", "TIZZANO");
        this.put("L183", "TIZZANO VAL PARMA");
        this.put("L184", "TOANO");
        this.put("L185", "TOCCO");
        this.put("L185", "TOCCO CAUDIO");
        this.put("L186", "TOCCO");
        this.put("L186", "TOCCO DA CASAURIA");
        this.put("L187", "TOCENO");
        this.put("L187", "TOCENO");
        this.put("L188", "TODI");
        this.put("L189", "TOFFIA");
        this.put("L190", "TOIRANO");
        this.put("L191", "TOLENTINO");
        this.put("L192", "TOLFA");
        this.put("L193", "TOLLEGNO");
        this.put("L193", "TOLLEGNO");
        this.put("L194", "TOLLO");
        this.put("L195", "TOLMEZZO");
        this.put("L196", "TOLMINO");
        this.put("L197", "TOLVE");
        this.put("L198", "TOMADIO");
        this.put("L199", "TOMBOLO");
        this.put("L200", "TON");
        this.put("L201", "TONADICO");
        this.put("L202", "TONARA");
        this.put("L203", "TONCO");
        this.put("L204", "TONENGO");
        this.put("L205", "TORA E PICCILLI");
        this.put("L206", "TORANO");
        this.put("L206", "TORANO CASTELLO");
        this.put("L207", "TORANO");
        this.put("L207", "TORANO NUOVO");
        this.put("L208", "TORBA");
        this.put("L209", "TORBIATO");
        this.put("L210", "TORBOLE");
        this.put("L210", "TORBOLE CASAGLIA");
        this.put("L211", "TORCEGNO");
        this.put("L212", "TORCHIARA");
        this.put("L213", "TORCHIAROLO");
        this.put("L214", "TORELLA");
        this.put("L214", "TORELLA DEI LOMBARDI");
        this.put("L215", "TORELLA");
        this.put("L215", "TORELLA DEL SANNIO");
        this.put("L216", "TORGIANO");
        this.put("L217", "TORGNON");
        this.put("L217", "TORGNONE");
        this.put("L218", "TORINO");
        this.put("L218", "TORINO DI SANGRO");
        this.put("L219", "TORINO");
        this.put("L220", "TORITTO");
        this.put("L221", "TORLINO");
        this.put("L221", "TORLINO VIMERCATI");
        this.put("L222", "TORMO");
        this.put("L223", "TORNACO");
        this.put("L224", "TORNARECCIO");
        this.put("L225", "TORNATA");
        this.put("L226", "TORNAVENTO");
        this.put("L227", "TORNIMPARTE");
        this.put("L228", "TORNO");
        this.put("L229", "TORNOLO");
        this.put("L230", "TORO");
        this.put("L231", "TORPE'");
        this.put("L232", "TORRA");
        this.put("L233", "TORRACA");
        this.put("L234", "TORRADELLO");
        this.put("L235", "TORRALBA");
        this.put("L236", "TORRAZZA");
        this.put("L237", "TORRAZZA COSTE");
        this.put("L238", "TORRAZZA PIEMONTE");
        this.put("L239", "TORRAZZO");
        this.put("L239", "TORRAZZO");
        this.put("L240", "TORRE");
        this.put("L240", "TORRE DI RUGGIERO");
        this.put("L241", "TORRE");
        this.put("L241", "TORRE MONDOVI'");
        this.put("L242", "TORRE");
        this.put("L242", "TORRE SAN MARCO");
        this.put("L243", "TORRE CAJETANI");
        this.put("L243", "TORRE");
        this.put("L244", "TORRE");
        this.put("L244", "TORRE DI SANTA MARIA");
        this.put("L245", "TORRE ANNUNZIATA");
        this.put("L246", "TORREANO");
        this.put("L247", "TORRE BAIRO");
        this.put("L247", "TORRE CANAVESE");
        this.put("L248", "TORREBELVICINO");
        this.put("L249", "TORRE BERETTI");
        this.put("L250", "TORRE BERETTI E CASTELLARO");
        this.put("L251", "TORRE BOLDONE");
        this.put("L252", "TORRE BORMIDA");
        this.put("L253", "TORREBRUNA");
        this.put("L254", "TORRECUSO");
        this.put("L255", "TORRE D'ANGIOLINI");
        this.put("L256", "TORRE D'ARESE");
        this.put("L256", "TORRE D'ARESE");
        this.put("L257", "TORRE DE' BUSI");
        this.put("L257", "TORRE DE' BUSI");
        this.put("L258", "TORRE DEI MALAMBERTI");
        this.put("L258", "TORRE DE' PICENARDI");
        this.put("L259", "TORRE DEL GRECO");
        this.put("L260", "TORRE DEL MANGANO");
        this.put("L261", "TORRE DEL MONTE");
        this.put("L262", "TORRE DE' NEGRI");
        this.put("L262", "TORRE DE' NEGRI");
        this.put("L263", "TORRE DE' PASSERI");
        this.put("L264", "TORRE DE' RATTI");
        this.put("L265", "TORRE DE' ROVERI");
        this.put("L266", "TORRE DE' TORTI");
        this.put("L267", "TORRE DI MOSTO");
        this.put("L268", "TORRE DI PALME");
        this.put("L269", "TORRE D'ISOLA");
        this.put("L270", "TORREGLIA");
        this.put("L271", "TORREGROTTA");
        this.put("L272", "TORRE LE NOCELLE");
        this.put("L273", "TORREMAGGIORE");
        this.put("L274", "TORRE ORSAIA");
        this.put("L275", "TORRE ORSINA");
        this.put("L276", "TORRE PALLAVICINA");
        this.put("L277", "TORRE PELLICE");
        this.put("L278", "TORRE SAN GIORGIO");
        this.put("L279", "TORRE SAN PATRIZIO");
        this.put("L279", "TORRE SAN PATRIZIO");
        this.put("L280", "TORRE SANTA SUSANNA");
        this.put("L281", "TORRESINA");
        this.put("L281", "TORRICELLA");
        this.put("L282", "TORRETTA");
        this.put("L283", "TORRE UZZONE");
        this.put("L284", "TORREVECCHIA");
        this.put("L284", "TORREVECCHIA TEATINA");
        this.put("L285", "TORRE VECCHIA");
        this.put("L285", "TORREVECCHIA PIA");
        this.put("L286", "TORRI");
        this.put("L286", "TORRI IN SABINA");
        this.put("L287", "TORRI");
        this.put("L287", "TORRI DEL BENACO");
        this.put("L288", "TORRIA");
        this.put("L289", "TORRIANO");
        this.put("L290", "TORRICE");
        this.put("L291", "TORRICELLA");
        this.put("L291", "TORRICELLA PELIGNA");
        this.put("L292", "TORRICELLA");
        this.put("L292", "TORRICELLA VERZATE");
        this.put("L292", "TORRICELLA VERZATE");
        this.put("L293", "TORRICELLA");
        this.put("L293", "TORRICELLA IN SABINA");
        this.put("L294", "TORRICELLA");
        this.put("L295", "TORRICELLA");
        this.put("L295", "TORRICELLA SICURA");
        this.put("L296", "TORRICELLA DEL PIZZO");
        this.put("L297", "TORRI DI QUARTESOLO");
        this.put("L298", "TORRIGLIA");
        this.put("L299", "TORRILE");
        this.put("L300", "TORRINO");
        this.put("L301", "TORRIONI");
        this.put("L302", "TORRITA");
        this.put("L302", "TORRITA TIBERINA");
        this.put("L303", "TORRITA");
        this.put("L303", "TORRITA DI SIENA");
        this.put("L304", "TORTONA");
        this.put("L305", "TORTORA");
        this.put("L306", "TORTORELLA");
        this.put("L307", "TORTORETO");
        this.put("L308", "TORTORICI");
        this.put("L309", "TORVISCOSA");
        this.put("L310", "TOSCANELLA");
        this.put("L310", "TUSCANIA");
        this.put("L311", "TOSCOLANO");
        this.put("L312", "TOSCOLANO-MADERNO");
        this.put("L313", "TOSS");
        this.put("L314", "TOSSICIA");
        this.put("L315", "TOVO");
        this.put("L315", "TOVO SAN GIACOMO");
        this.put("L316", "TOVO");
        this.put("L316", "TOVO DI SANT'AGATA");
        this.put("L317", "TRABIA");
        this.put("L318", "TRABUCHELLO");
        this.put("L319", "TRADATE");
        this.put("L320", "TRAFFIUME");
        this.put("L321", "TRAMATZA");
        this.put("L321", "TRAMATZA");
        this.put("L322", "TRAMBILENO");
        this.put("L322", "TRAMBILLENO O TRAMBILENO");
        this.put("L323", "TRAMONTI");
        this.put("L324", "TRAMONTI DI SOPRA");
        this.put("L325", "TRAMONTI DI SOTTO");
        this.put("L326", "TRAMUTOLA");
        this.put("L327", "TRANA");
        this.put("L328", "TRANI");
        this.put("L328", "TRANI");
        this.put("L329", "TRANSACQUA");
        this.put("L330", "TRAONA");
        this.put("L331", "TRAPANI");
        this.put("L332", "TRAPPETO");
        this.put("L333", "TRAREGO");
        this.put("L333", "TRAREGO VIGGIONA");
        this.put("L333", "TRAREGO VIGGIONA");
        this.put("L334", "TRASACCO");
        this.put("L335", "TRASAGHIS");
        this.put("L336", "TRASQUERA");
        this.put("L336", "TRASQUERA");
        this.put("L337", "TRATALIAS");
        this.put("L337", "TRATALIAS");
        this.put("L338", "TRAUSELLA");
        this.put("L339", "TRAVAGLIATO");
        this.put("L340", "TRAVE");
        this.put("L340", "TRAVES");
        this.put("L341", "TRAVEDONA");
        this.put("L342", "TRAVEDONA-MONATE");
        this.put("L343", "TRAVERSA");
        this.put("L344", "TRAVERSE");
        this.put("L345", "TRAVERSELLA");
        this.put("L346", "TRAVERSETOLO");
        this.put("L347", "TRAVESIO");
        this.put("L348", "TRAVO");
        this.put("L349", "TREBASELEGHE");
        this.put("L350", "TREBBIANO");
        this.put("L350", "TREBBIANO NIZZA");
        this.put("L351", "TREBECCO");
        this.put("L352", "TREBIANO");
        this.put("L352", "TREBIANO MAGRA");
        this.put("L353", "TREBISACCE");
        this.put("L354", "TRECASALI");
        this.put("L355", "TRECASTAGNI");
        this.put("L356", "TRECATE");
        this.put("L357", "TRECCHINA");
        this.put("L358", "TRECELLA");
        this.put("L359", "TRECENTA");
        this.put("L360", "TREDOSSI");
        this.put("L361", "TREDOZIO");
        this.put("L362", "TREGASIO");
        this.put("L363", "TREGLIO");
        this.put("L364", "TREGNAGO");
        this.put("L365", "TREGOLO");
        this.put("L366", "TREIA");
        this.put("L367", "TREISO");
        this.put("L368", "TREMENICO");
        this.put("L368", "TREMENICO");
        this.put("L369", "TREMESTIERI");
        this.put("L369", "TREMESTIERI ETNEO");
        this.put("L370", "TREMEZZINA");
        this.put("L370", "TREMEZZINA");
        this.put("L370", "TREMEZZINA");
        this.put("L371", "TREMEZZO");
        this.put("L372", "TREMOSINE");
        this.put("L373", "TRENNO");
        this.put("L374", "TRENS * TRENS");
        this.put("L375", "TRENTA");
        this.put("L376", "TRENTA D'ISONZO");
        this.put("L377", "TRENTINARA");
        this.put("L378", "TRENTO");
        this.put("L379", "TRENTOLA");
        this.put("L379", "TRENTOLA DUCENTA");
        this.put("L380", "TRENZANO");
        this.put("L381", "TREPPO");
        this.put("L381", "TREPPO CARNICO");
        this.put("L382", "TREPPO GRANDE");
        this.put("L383", "TREPUZZI");
        this.put("L384", "TREQUANDA");
        this.put("L385", "TRES");
        this.put("L386", "TRESANA");
        this.put("L387", "TRESCHE-CONCA");
        this.put("L388", "TRESCORE");
        this.put("L388", "TRESCORE BALNEARIO");
        this.put("L389", "TRESCORE");
        this.put("L389", "TRESCORE CREMASCO");
        this.put("L390", "TRESIGALLO");
        this.put("L391", "TRESILICO");
        this.put("L392", "TRESIVIO");
        this.put("L393", "TRESNURAGHES");
        this.put("L393", "TRESNURAGHES");
        this.put("L394", "TRETTO");
        this.put("L395", "TREVANO");
        this.put("L396", "TREVENZUOLO");
        this.put("L397", "TREVI");
        this.put("L398", "TREVI NEL LAZIO");
        this.put("L398", "TREVI");
        this.put("L399", "TREVICO");
        this.put("L400", "TREVIGLIO");
        this.put("L401", "TREVIGNANO");
        this.put("L401", "TREVIGNANO ROMANO");
        this.put("L402", "TREVIGNANO");
        this.put("L403", "TREVILLE");
        this.put("L404", "TREVIOLO");
        this.put("L405", "TREVISAGO");
        this.put("L406", "TREVISO");
        this.put("L406", "TREVISO BRESCIANO");
        this.put("L407", "TREVISO");
        this.put("L408", "TREZZANO");
        this.put("L408", "TREZZANO ROSA");
        this.put("L409", "TREZZANO");
        this.put("L409", "TREZZANO SUL NAVIGLIO");
        this.put("L410", "TREZZO");
        this.put("L410", "TREZZO TINELLA");
        this.put("L411", "TREZZO");
        this.put("L411", "TREZZO SULL'ADDA");
        this.put("L412", "TREZZOLASCO");
        this.put("L413", "TREZZONE");
        this.put("L414", "TRIBANO");
        this.put("L415", "TRIBIANO");
        this.put("L416", "TRIBOGNA");
        this.put("L417", "TRIBUSSA");
        this.put("L418", "TRICARICO");
        this.put("L419", "TRICASE");
        this.put("L420", "TRICERRO");
        this.put("L421", "TRICESIMO");
        this.put("L422", "TRICHIANA");
        this.put("L423", "TRIEI");
        this.put("L423", "TRIEI");
        this.put("L424", "TRIESTE");
        this.put("L425", "TRIGGIANO");
        this.put("L426", "TRIGOLO");
        this.put("L427", "TRINITA'");
        this.put("L428", "TRINITA' D'AGULTU E VIGNOLA");
        this.put("L428", "TRINITA' D'AGULTU E VIGNOLA");
        this.put("L429", "TRINO VERCELLESE");
        this.put("L430", "TRIORA");
        this.put("L431", "TRIPI");
        this.put("L432", "TRISOBBIO");
        this.put("L433", "TRISSINO");
        this.put("L434", "TRIUGGIO");
        this.put("L434", "TRIUGGIO");
        this.put("L435", "TRIVENTO");
        this.put("L436", "TRIVERO");
        this.put("L436", "TRIVERO");
        this.put("L437", "TRIVIGLIANO");
        this.put("L438", "TRIVIGNANO UDINESE");
        this.put("L439", "TRIVIGNO");
        this.put("L440", "TRIVOLZIO");
        this.put("L441", "TRIVULZA");
        this.put("L442", "TRIVULZINA");
        this.put("L443", "TROBASO");
        this.put("L444", "TRODENA * TRUDEN");
        this.put("L444", "TRODENA NEL PARCO NATURALE  * TRUDEN IM NATURPARK");
        this.put("L445", "TROFARELLO");
        this.put("L446", "TROGNANO");
        this.put("L447", "TROIA");
        this.put("L448", "TROINA");
        this.put("L449", "TROMELLO");
        this.put("L450", "TRONTANO");
        this.put("L450", "TRONTANO");
        this.put("L451", "TRONZANO");
        this.put("L451", "TRONZANO VERCELLESE");
        this.put("L452", "TROPEA");
        this.put("L452", "TROPEA");
        this.put("L453", "TROVO");
        this.put("L454", "TRUCCAZZANO");
        this.put("L455", "TUBRE * TAUFERS");
        this.put("L456", "TUENETTO");
        this.put("L457", "TUENNO");
        this.put("L458", "TUFARA");
        this.put("L459", "TUFILLO");
        this.put("L460", "TUFINO");
        this.put("L461", "TUFO");
        this.put("L462", "TUGLIE");
        this.put("L463", "TUILI");
        this.put("L463", "TUILI");
        this.put("L464", "TULA");
        this.put("L465", "TUNES * THUINS");
        this.put("L466", "TUORO");
        this.put("L466", "TUORO SUL TRASIMENO");
        this.put("L467", "TURAGO BORDONE");
        this.put("L468", "TURANO");
        this.put("L468", "VALVESTINO");
        this.put("L469", "TURANO LODIGIANO");
        this.put("L469", "TURANO");
        this.put("L469", "TURANO LODIGIANO");
        this.put("L470", "TURATE");
        this.put("L471", "TURBIGO");
        this.put("L472", "TURI");
        this.put("L473", "TURRI");
        this.put("L473", "TURRI");
        this.put("L474", "TURRIACO");
        this.put("L475", "TURRIVALIGNANI");
        this.put("L476", "TURRO");
        this.put("L476", "TURRO MILANESE");
        this.put("L477", "TURSI");
        this.put("L478", "TUSA");
        this.put("L479", "UBAGA");
        this.put("L480", "UBOLDO");
        this.put("L481", "UCOVIZZA");
        this.put("L481", "UGOVIZZA VALBRUNA");
        this.put("L482", "UCRIA");
        this.put("L483", "UDINE");
        this.put("L484", "UGENTO");
        this.put("L485", "UGGIANO LA CHIESA");
        this.put("L486", "UGGIATE");
        this.put("L487", "UGGIATE-TREVANO");
        this.put("L488", "ULA'");
        this.put("L488", "ULA' TIRSO");
        this.put("L488", "ULA' TIRSO");
        this.put("L489", "ULASSAI");
        this.put("L489", "ULASSAI");
        this.put("L490", "ULTIMO * ULTEN");
        this.put("L491", "UMAGO");
        this.put("L492", "UMBRIATICO");
        this.put("L492", "UMBRIATICO");
        this.put("L493", "UNCHIO");
        this.put("L494", "URAGO D'OGLIO");
        this.put("L495", "URAGO MELLA");
        this.put("L496", "URAS");
        this.put("L496", "URAS");
        this.put("L497", "URBANA");
        this.put("L498", "URBANIA");
        this.put("L499", "URBE");
        this.put("L500", "URBINO");
        this.put("L501", "URBISAGLIA");
        this.put("L501", "URBISAGLIA BONSERVIZI");
        this.put("L502", "URGNANO");
        this.put("L503", "URI");
        this.put("L504", "URIO");
        this.put("L505", "URURI");
        this.put("L506", "URZULEI");
        this.put("L506", "URZULEI");
        this.put("L507", "USCIO");
        this.put("L508", "USELLUS");
        this.put("L508", "USELLUS");
        this.put("L509", "USINI");
        this.put("L510", "USMATE");
        this.put("L511", "VELATE");
        this.put("L511", "VELATE MILANESE");
        this.put("L511", "USMATE VELATE");
        this.put("L511", "USMATE VELATE");
        this.put("L512", "USSANA");
        this.put("L513", "USSARAMANNA");
        this.put("L513", "USSARAMANNA");
        this.put("L514", "USSASSAI");
        this.put("L514", "USSASSAI");
        this.put("L515", "USSEAUX");
        this.put("L516", "USSEGLIO");
        this.put("L517", "USSITA");
        this.put("L518", "USSOLO");
        this.put("L519", "USTICA");
        this.put("L520", "USTIE");
        this.put("L521", "UTA");
        this.put("L522", "UZZANO");
        this.put("L523", "VACCARIZZA");
        this.put("L524", "VACCARIZZO");
        this.put("L524", "VACCARIZZO ALBANESE");
        this.put("L525", "VACONE");
        this.put("L526", "VACRI");
        this.put("L527", "VADENA * PFATTEN");
        this.put("L528", "VADO");
        this.put("L528", "VADO LIGURE");
        this.put("L529", "VAGLIA");
        this.put("L530", "VAGLIERANO");
        this.put("L531", "VAGLIO");
        this.put("L531", "VAGLIO SERRA");
        this.put("L532", "VAGLIO");
        this.put("L532", "VAGLIO BASILICATA");
        this.put("L532", "VAGLIO DI BASILICATA");
        this.put("L532", "VAGLIO LUCANO");
        this.put("L533", "VAGLI SOTTO");
        this.put("L534", "VAGNA");
        this.put("L535", "VAIANO");
        this.put("L535", "VAIANO CREMASCO");
        this.put("L536", "VAIANO");
        this.put("L536", "VAIANO VALLE");
        this.put("L537", "VAIANO");
        this.put("L537", "VAIANO");
        this.put("L538", "VAIE");
        this.put("L538", "VAYES");
        this.put("L539", "VAILATE");
        this.put("L540", "VAIRANO");
        this.put("L540", "VAIRANO PATENORA");
        this.put("L541", "VAIRANO");
        this.put("L541", "VAIRANO CREMASCO");
        this.put("L541", "VAIRANO CREMASCO");
        this.put("L542", "VAIRANO");
        this.put("L542", "VAIRANO PAVESE");
        this.put("L543", "VALAS * FLAAS");
        this.put("L543", "VELASIO * FLAAS");
        this.put("L544", "VALBONDIONE");
        this.put("L545", "VALBREMBO");
        this.put("L546", "VALBREVENNA");
        this.put("L547", "VALBRONA");
        this.put("L548", "VALCHIUSA");
        this.put("L548", "VICO");
        this.put("L548", "VICO CANAVESE");
        this.put("L549", "VALCHIUSELLA");
        this.put("L550", "VALDA");
        this.put("L551", "VALDAGNO");
        this.put("L552", "VALDAORA * OLANG");
        this.put("L552", "VALDAORA * OLANG");
        this.put("L553", "VALDARSA");
        this.put("L554", "VALDASTICO");
        this.put("L555", "VAL DELLA TORRE");
        this.put("L556", "VALDENGO");
        this.put("L556", "VALDENGO");
        this.put("L557", "VALDIDENTRO");
        this.put("L558", "VALDIERI");
        this.put("L559", "VALDIGIOVO * JAUFENTAL");
        this.put("L559", "VALGIOVO * JAUFENTAL");
        this.put("L560", "VALDIGNA D'AOSTA");
        this.put("L560", "VALDIGNA D'AOSTA");
        this.put("L561", "VALDINA");
        this.put("L562", "VAL DI NIZZA");
        this.put("L563", "VALDISOTTO");
        this.put("L564", "VAL DI VIZZE * PFITSCH");
        this.put("L565", "VALDOBBIADENE");
        this.put("L566", "VALDUGGIA");
        this.put("L567", "VALEGGIO");
        this.put("L567", "VALEGGIO SUL MINCIO");
        this.put("L568", "VALEGGIO");
        this.put("L569", "VALENTANO");
        this.put("L570", "VALENZA");
        this.put("L571", "VALENZANO");
        this.put("L572", "VALERA FRATTA");
        this.put("L572", "VALERA FRATTA");
        this.put("L573", "VALFABBRICA");
        this.put("L574", "VALFENERA");
        this.put("L575", "VALFLORIANA");
        this.put("L576", "VALFURVA");
        this.put("L577", "VALGANNA");
        this.put("L578", "VALGIOIE");
        this.put("L579", "VALGOGLIO");
        this.put("L580", "VALGRANA");
        this.put("L581", "VALGREGHENTINO");
        this.put("L581", "VALGREGHENTINO");
        this.put("L582", "VALGRISANCHE");
        this.put("L582", "VALGRISENCHE");
        this.put("L582", "VALGRISENZA");
        this.put("L583", "VALGUARNERA CAROPEPE");
        this.put("L584", "VALLADA");
        this.put("L584", "VALLADA AGORDINA");
        this.put("L585", "VALL'ALTA");
        this.put("L586", "VALLANZENGO");
        this.put("L586", "VALLANZENGO");
        this.put("L587", "VALLARGA * WEITENTAL");
        this.put("L588", "VALLARSA");
        this.put("L589", "VALLATA");
        this.put("L590", "VALLE");
        this.put("L590", "VALLE DI CADORE");
        this.put("L591", "VALLE");
        this.put("L591", "VALLE DI MADDALONI");
        this.put("L592", "VALLE");
        this.put("L592", "VALLE GUIDINO");
        this.put("L593", "VALLE");
        this.put("L593", "VALLE LOMELLINA");
        this.put("L594", "VALLE AGRICOLA");
        this.put("L594", "VALLE DI PRATA");
        this.put("L595", "VALLE AURINA * AHRNTAL");
        this.put("L596", "VALLEBONA");
        this.put("L597", "VALLE CASTELLANA");
        this.put("L598", "VALLECORSA");
        this.put("L599", "VALLECROSIA");
        this.put("L600", "VALLECROSIA CON SAN BIAGIO DELLA CIMA");
        this.put("L600", "VALLECROSIA CON SAN BIAGIO DELLA CIMA");
        this.put("L601", "VALLE DI CASIES * GSIES");
        this.put("L602", "VALLE D'ISTRIA");
        this.put("L603", "VALLEDOLMO");
        this.put("L604", "VALLEDORIA");
        this.put("L605", "VALLEFREDDA");
        this.put("L605", "VALLEMAIO");
        this.put("L606", "VALLE MOSSO");
        this.put("L606", "VALLE INFERIORE MOSSO");
        this.put("L606", "VALLE MOSSO");
        this.put("L607", "VALLELONGA");
        this.put("L607", "VALLELONGA");
        this.put("L608", "VALLELUNGA * LANGTAUFERS");
        this.put("L608", "VALLELUNGA CARLINO * LANGTAUFERS");
        this.put("L609", "VALLELUNGA");
        this.put("L609", "VALLELUNGA PRATAMENO");
        this.put("L610", "VALLENONCELLO");
        this.put("L611", "VALLEPIETRA");
        this.put("L612", "VALLERANO");
        this.put("L613", "VALLERMOSA");
        this.put("L614", "VALLEROTONDA");
        this.put("L615", "VALLES * VALS");
        this.put("L616", "VALLESACCARDA");
        this.put("L617", "VALLE SALIMBENE");
        this.put("L618", "VALLE SAN FELICE");
        this.put("L619", "VALLE SAN GIOVANNI");
        this.put("L619", "VALLE SAN GIOVANNI");
        this.put("L619", "VALLE SAN GIOVANNI");
        this.put("L619", "VALLE SAN GIOVANNI");
        this.put("L620", "VALLE SAN NICOLAO");
        this.put("L620", "VALLE SAN NICOLAO");
        this.put("L621", "VALLE SAN SILVESTRO * VAHLEN");
        this.put("L622", "VALLE SUPERIORE MOSSO");
        this.put("L623", "VALLEVE");
        this.put("L624", "VALLI DEI SIGNORI");
        this.put("L624", "VALLI DEL PASUBIO");
        this.put("L625", "VALLINFREDA");
        this.put("L626", "VALLIO");
        this.put("L626", "VALLIO TERME");
        this.put("L627", "VALLO");
        this.put("L627", "VALLO DI NERA");
        this.put("L628", "VALLO");
        this.put("L628", "VALLO DELLA LUCANIA");
        this.put("L629", "VALLO");
        this.put("L629", "VALLO TORINESE");
        this.put("L630", "VALLONARA");
        this.put("L631", "VALLORIA");
        this.put("L631", "VALLORIATE");
        this.put("L632", "VALLORIA");
        this.put("L632", "VALLORIA MARITTIMA");
        this.put("L633", "VALMACCA");
        this.put("L634", "VALMADRERA");
        this.put("L634", "VALMADRERA");
        this.put("L635", "VALMAGGIA");
        this.put("L636", "VALMALA");
        this.put("L637", "VAL MARCHIROLO");
        this.put("L637", "VAL MARCHIROLO");
        this.put("L638", "VAL MASINO");
        this.put("L639", "VALMONTONE");
        this.put("L640", "VALMOREA");
        this.put("L641", "VALMOZZOLA");
        this.put("L642", "VALNEGRA");
        this.put("L643", "VALPELLINA");
        this.put("L643", "VALPELLINE");
        this.put("L644", "VALPERGA");
        this.put("L645", "VALPRATO");
        this.put("L646", "VALROVINA");
        this.put("L647", "VALSAVARA");
        this.put("L647", "VALSAVARANCHE");
        this.put("L647", "VALSAVARENCHE");
        this.put("L648", "VALSAVIORE");
        this.put("L648", "VALSAVIORE");
        this.put("L649", "VALSECCA");
        this.put("L650", "VALSTAGNA");
        this.put("L651", "VALSTRONA");
        this.put("L651", "VALSTRONA");
        this.put("L652", "VALTESSE");
        this.put("L653", "VALTOPINA");
        this.put("L654", "VALTORNENZA");
        this.put("L654", "VALTOURNANCHE");
        this.put("L654", "VALTOURNENCHE");
        this.put("L655", "VALTORTA");
        this.put("L656", "VALVA");
        this.put("L657", "VALVASONE");
        this.put("L658", "VALVERDE");
        this.put("L659", "VALVERDE");
        this.put("L659", "VALVERDE");
        this.put("L660", "VANDOIES * VINTL");
        this.put("L661", "VANDOIES DI SOPRA * OBERVINTL");
        this.put("L662", "VANDOIES DI SOTTO * NIEDERVINTL");
        this.put("L663", "VANGA * WANGEN");
        this.put("L664", "VANZAGHELLO");
        this.put("L664", "VANZAGHELLO");
        this.put("L665", "VANZAGO");
        this.put("L666", "VANZONE");
        this.put("L666", "VANZONE CON SAN CARLO");
        this.put("L666", "VANZONE CON SAN CARLO");
        this.put("L667", "VAPRIO");
        this.put("L667", "VAPRIO D'ADDA");
        this.put("L668", "VAPRIO");
        this.put("L668", "VAPRIO D'AGOGNA");
        this.put("L669", "VARALLO");
        this.put("L670", "VARALLO POMBIA");
        this.put("L671", "VARANO");
        this.put("L671", "VARANO BORGHI");
        this.put("L672", "VARANO DE' MELEGARI");
        this.put("L673", "VARAPODIO");
        this.put("L674", "VARARO");
        this.put("L675", "VARAZZE");
        this.put("L676", "VARCO");
        this.put("L676", "VARCO SABINO");
        this.put("L677", "VAREDO");
        this.put("L677", "VAREDO");
        this.put("L678", "VARENA");
        this.put("L679", "VARENGO");
        this.put("L680", "VARENNA");
        this.put("L680", "VARENNA");
        this.put("L681", "VARESE");
        this.put("L681", "VARESE LIGURE");
        this.put("L682", "VARESE");
        this.put("L683", "VARGO");
        this.put("L684", "VARIGOTTI");
        this.put("L685", "VARISELLA");
        this.put("L686", "VARMO");
        this.put("L687", "VARNA * VAHRN");
        this.put("L688", "VARONI");
        this.put("L689", "VARSI");
        this.put("L690", "VARZI");
        this.put("L691", "VARZO");
        this.put("L691", "VARZO");
        this.put("L692", "VAS");
        this.put("L693", "VASIA");
        this.put("L694", "VASIO");
        this.put("L695", "VASSENA");
        this.put("L696", "VASTOGIRARDI");
        this.put("L697", "VATTARO");
        this.put("L698", "VAUDA CANAVESE");
        this.put("L698", "VAUDA DI FRONT");
        this.put("L699", "VAZZANO");
        this.put("L699", "VAZZANO");
        this.put("L700", "VAZZOLA");
        this.put("L701", "VECCANA");
        this.put("L702", "VECCHIANO");
        this.put("L703", "VEDANO");
        this.put("L703", "VEDANO OLONA");
        this.put("L704", "VEDANO");
        this.put("L704", "VEDANO AL LAMBRO");
        this.put("L704", "VEDANO AL LAMBRO");
        this.put("L705", "VEDDASCA");
        this.put("L706", "VEDELAGO");
        this.put("L707", "VEDESETA");
        this.put("L708", "VEDUGGIO");
        this.put("L709", "VEDUGGIO CON COLZANO");
        this.put("L709", "VEDUGGIO CON COLZANO");
        this.put("L710", "VEGGIANO");
        this.put("L711", "VEGLIE");
        this.put("L712", "VEGLIO");
        this.put("L712", "VEGLIO");
        this.put("L713", "VIANO");
        this.put("L713", "VEJANO");
        this.put("L714", "VELATE");
        this.put("L715", "VELESO");
        this.put("L716", "VELEZZO");
        this.put("L716", "VELEZZO LOMELLINA");
        this.put("L717", "VELLANO");
        this.put("L718", "VELLEGO");
        this.put("L718", "VELLEGO");
        this.put("L719", "VELLETRI");
        this.put("L720", "VELLEZZO");
        this.put("L720", "VELLEZZO BELLINI");
        this.put("L721", "VELLO");
        this.put("L722", "VELO");
        this.put("L722", "VELO VERONESE");
        this.put("L723", "VELO");
        this.put("L723", "VELO D'ASTICO");
        this.put("L724", "VELTURNO * FELDTHURNS");
        this.put("L725", "VENAFRO");
        this.put("L726", "VENALZIO");
        this.put("L726", "VENAUS");
        this.put("L727", "VENARIA REALE");
        this.put("L728", "VENAROTTA");
        this.put("L729", "VENASCA");
        this.put("L730", "VENDONE");
        this.put("L731", "VENDROGNO");
        this.put("L731", "VENDROGNO");
        this.put("L732", "VENEGONO");
        this.put("L732", "VENEGONO");
        this.put("L733", "VENEGONO INFERIORE");
        this.put("L734", "VENEGONO SUPERIORE");
        this.put("L735", "VENETICO");
        this.put("L736", "VENEZIA");
        this.put("L737", "VENIANO");
        this.put("L738", "VENOSA");
        this.put("L739", "VENTICANO");
        this.put("L740", "VENTIMIGLIA");
        this.put("L740", "VENTIMIGLIA DI SICILIA");
        this.put("L741", "VENTIMIGLIA");
        this.put("L742", "VENTOTENE");
        this.put("L743", "VENZONE");
        this.put("L744", "VERANO");
        this.put("L744", "VERANO BRIANZA");
        this.put("L744", "VERANO BRIANZA");
        this.put("L745", "VERANO * VOERAN");
        this.put("L746", "VERBANIA");
        this.put("L746", "VERBANIA");
        this.put("L747", "VERBICARO");
        this.put("L748", "VERCANA");
        this.put("L749", "VERCEIA");
        this.put("L750", "VERCELLI");
        this.put("L751", "VERCURAGO");
        this.put("L751", "VERCURAGO");
        this.put("L752", "VERDELLINO");
        this.put("L753", "VERDELLO");
        this.put("L754", "VERDERIO");
        this.put("L754", "VERDERIO");
        this.put("L755", "VERDERIO INFERIORE");
        this.put("L755", "VERDERIO INFERIORE");
        this.put("L756", "VERDERIO SUPERIORE");
        this.put("L756", "VERDERIO SUPERIORE");
        this.put("L757", "VERDESINA");
        this.put("L758", "VERDUNO");
        this.put("L759", "VEREZZI");
        this.put("L760", "VERGANO");
        this.put("L760", "VILLA VERGANO");
        this.put("L761", "VERGANO");
        this.put("L761", "VERGANO NOVARESE");
        this.put("L762", "VERGATO");
        this.put("L763", "VERGEMOLI");
        this.put("L764", "VERGHERETO");
        this.put("L765", "VERGIATE");
        this.put("L766", "VERGO");
        this.put("L767", "VERGOBBIO");
        this.put("L768", "VERMEZZO");
        this.put("L769", "VERMIGLIO");
        this.put("L770", "VERNA");
        this.put("L771", "VERNANTE");
        this.put("L772", "VERNASCA");
        this.put("L773", "VERNATE");
        this.put("L774", "VERNAZZA");
        this.put("L775", "VERNIO");
        this.put("L775", "VERNIO");
        this.put("L776", "VERNOLE");
        this.put("L777", "VEROLANUOVA");
        this.put("L778", "VEROLAVECCHIA");
        this.put("L779", "VEROLENGO");
        this.put("L780", "VEROLI");
        this.put("L781", "VERONA");
        this.put("L782", "VERPOGLIANO");
        this.put("L783", "VERRAYES");
        this.put("L784", "VERRETTO");
        this.put("L785", "VERRONE");
        this.put("L785", "VERRONE");
        this.put("L786", "VERRUA");
        this.put("L786", "VERRUA SICCOMARIO");
        this.put("L787", "VERRUA");
        this.put("L787", "VERRUA SAVOIA");
        this.put("L788", "VERRUA PO");
        this.put("L789", "VERSA");
        this.put("L790", "VERSCIAGO * VIERSCHACH");
        this.put("L791", "VERTEMATE");
        this.put("L792", "VERTEMATE CON MINOPRIO");
        this.put("L793", "VERTENEGLIO");
        this.put("L794", "VERTOIBA");
        this.put("L794", "VERTOIBA IN CAMPI");
        this.put("L795", "VERTOVA");
        this.put("L796", "VERTOVINO");
        this.put("L797", "VERUCCHIO");
        this.put("L797", "VERUCCHIO");
        this.put("L798", "VERUNO");
        this.put("L799", "VERVIO");
        this.put("L800", "VERVO'");
        this.put("L801", "VERZEGNIS");
        this.put("L802", "VERZINO");
        this.put("L802", "VERZINO");
        this.put("L803", "VERZI PIETRA");
        this.put("L804", "VERZUOLO");
        this.put("L805", "VESCOVANA");
        this.put("L806", "VESCOVATO");
        this.put("L807", "VESIME");
        this.put("L808", "VESPOLATE");
        this.put("L809", "VESSALICO");
        this.put("L810", "VESTENANOVA");
        this.put("L811", "VESTIGNE'");
        this.put("L812", "VESTONE");
        this.put("L813", "VESTRENO");
        this.put("L813", "VESTRENO");
        this.put("L814", "VETRALLA");
        this.put("L815", "VETTO");
        this.put("L816", "VEZZA");
        this.put("L816", "VEZZA D'OGLIO");
        this.put("L817", "VEZZA");
        this.put("L817", "VEZZA D'ALBA");
        this.put("L818", "VEZZANO * VEZZAN");
        this.put("L818", "VEZZANO IN VENOSTA * VEZZAN");
        this.put("L819", "VEZZANO");
        this.put("L819", "VEZZANO LIGURE");
        this.put("L820", "VEZZANO");
        this.put("L820", "VEZZANO SUL CROSTOLO");
        this.put("L821", "VEZZANO");
        this.put("L822", "VEZZI");
        this.put("L823", "VEZZI PORTIO");
        this.put("L824", "VEZZO");
        this.put("L825", "VHO");
        this.put("L826", "VIADANA");
        this.put("L827", "VIADANICA");
        this.put("L828", "VIAGRANDE");
        this.put("L829", "VIALE D'ASTI");
        this.put("L830", "VIALFRE'");
        this.put("L831", "VIANO");
        this.put("L832", "VIARAGO");
        this.put("L833", "VIAREGGIO");
        this.put("L834", "VIARIGI");
        this.put("L835", "VIBONATI");
        this.put("L836", "VICALVI");
        this.put("L837", "VICARI");
        this.put("L838", "VICCHIO");
        this.put("L839", "VICENO");
        this.put("L840", "VICENZA");
        this.put("L841", "VICO");
        this.put("L841", "VICOFORTE");
        this.put("L842", "VICO");
        this.put("L842", "VICO DEL GARGANO");
        this.put("L843", "VICO NEL LAZIO");
        this.put("L843", "VICO");
        this.put("L844", "VICO DI PANTANO");
        this.put("L844", "VILLA LITERNO");
        this.put("L845", "VICO EQUENSE");
        this.put("L846", "VICOLI");
        this.put("L847", "VICOLUNGO");
        this.put("L848", "VICOMARINO");
        this.put("L848", "ZIANO");
        this.put("L848", "ZIANO PIACENTINO");
        this.put("L849", "VICONAGO");
        this.put("L850", "VICOPISANO");
        this.put("L851", "VICOVARO");
        this.put("L852", "VIDARDO");
        this.put("L853", "VIDICETO CON GURATA");
        this.put("L854", "VIDIGULFO");
        this.put("L855", "VIDOLASCO");
        this.put("L856", "VIDOR");
        this.put("L857", "VIDRACCO");
        this.put("L858", "VIESTE");
        this.put("L859", "VIETRI");
        this.put("L859", "VIETRI DI POTENZA");
        this.put("L860", "VIETRI");
        this.put("L860", "VIETRI SUL MARE");
        this.put("L861", "VIGADORE");
        this.put("L862", "VIGALFO");
        this.put("L863", "VIGALZANO");
        this.put("L864", "VIGANELLA");
        this.put("L864", "VIGANELLA");
        this.put("L865", "VIGANO");
        this.put("L865", "VIGANO SAN MARTINO");
        this.put("L866", "VIGANO'");
        this.put("L866", "VIGANO'");
        this.put("L867", "VIGANO");
        this.put("L867", "VIGANO CERTOSINO");
        this.put("L868", "VIGARANO MAINARDA");
        this.put("L869", "VIGASIO");
        this.put("L870", "VIGATTO");
        this.put("L871", "VIGENTINO");
        this.put("L872", "VIGEVANO");
        this.put("L873", "VIGGIANELLO");
        this.put("L874", "VIGGIANO");
        this.put("L875", "VIGGIONA");
        this.put("L876", "VIGGIU'");
        this.put("L876", "VIGGIU' ED UNITI");
        this.put("L877", "VIGHIZZOLO");
        this.put("L878", "VIGHIZZOLO");
        this.put("L878", "VIGHIZZOLO D'ESTE");
        this.put("L879", "VIGLIANO");
        this.put("L879", "VIGLIANO D'ASTI");
        this.put("L880", "VIGLIANO BIELLESE");
        this.put("L880", "VIGLIANO");
        this.put("L880", "VIGLIANO BIELLESE");
        this.put("L881", "VIGNALE MONFERRATO");
        this.put("L882", "VIGNANELLO");
        this.put("L883", "VIGNATE");
        this.put("L884", "VIGNOLA");
        this.put("L885", "VIGNOLA");
        this.put("L886", "VIGNOLA FALESINA");
        this.put("L887", "VIGNOLE BORBERA");
        this.put("L888", "VIGNOLO");
        this.put("L889", "VIGNONE");
        this.put("L889", "VIGNONE");
        this.put("L890", "VIGO");
        this.put("L890", "VIGO DI CADORE");
        this.put("L891", "VIGO D'ANAUNIA");
        this.put("L892", "VIGODARZERE");
        this.put("L893", "VIGO DI FASSA");
        this.put("L894", "VIGOLO");
        this.put("L895", "VIGOLO BASELGA");
        this.put("L896", "VIGOLO VATTARO");
        this.put("L897", "VIGOLZONE");
        this.put("L898", "VIGONE");
        this.put("L899", "VIGONOVO");
        this.put("L900", "VIGONZA");
        this.put("L901", "VIGONZINO");
        this.put("L902", "VIGONZONE");
        this.put("L903", "VIGO RENDENA");
        this.put("L904", "VIGUZZOLO");
        this.put("L905", "VILLA");
        this.put("L905", "VILLA SANTA LUCIA");
        this.put("L906", "VILLA");
        this.put("L906", "VILLADOSSOLA");
        this.put("L906", "VILLADOSSOLA");
        this.put("L907", "VILLA");
        this.put("L907", "VILLA DI CHIAVENNA");
        this.put("L908", "VILLA");
        this.put("L908", "VILLA DI TIRANO");
        this.put("L909", "VILLA");
        this.put("L909", "VILLA SANTINA");
        this.put("L910", "VILLA AGNEDO");
        this.put("L911", "VILLA BANALE");
        this.put("L912", "VILLA BARTOLOMEA");
        this.put("L913", "VILLA BASILICA");
        this.put("L914", "VILLABASSA");
        this.put("L915", "VILLABASSA * NIEDERDORF");
        this.put("L916", "VILLABATE");
        this.put("L917", "VILLA BISCOSSI");
        this.put("L918", "VILLABONA");
        this.put("L918", "VILLA D'ADIGE");
        this.put("L919", "VILLA CARCINA");
        this.put("L920", "VILLA CASTELLI");
        this.put("L921", "VILLA CASTELNUOVO");
        this.put("L922", "VILLA CELIERA");
        this.put("L923", "VILLACHIARA");
        this.put("L924", "VILLACIDRO");
        this.put("L924", "VILLACIDRO");
        this.put("L925", "VILLA COGOZZO");
        this.put("L926", "VILLA COLLEMANDINA");
        this.put("L927", "VILLA CORSIONE");
        this.put("L927", "VILLA CORSIONE");
        this.put("L928", "VILLA CORTESE");
        this.put("L928", "VILLA CORTESE");
        this.put("L929", "VILLA D'ADDA");
        this.put("L930", "VILLA D'ALLEGNO");
        this.put("L931", "VILLADEATI");
        this.put("L932", "VILLA DECANI");
        this.put("L933", "VILLA DEL BOSCO");
        this.put("L933", "VILLA DEL BOSCO");
        this.put("L934", "VILLA DEL CONTE");
        this.put("L935", "VILLA DEL NEVOSO");
        this.put("L936", "VILLA DI SERIO");
        this.put("L937", "VILLA DI VILLA");
        this.put("L937", "VILLA ESTENSE");
        this.put("L938", "VILLA D'OGNA");
        this.put("L939", "VILLADOSE");
        this.put("L940", "VILLA DOSIA");
        this.put("L941", "VILLA D'UTA * UTTENHEIM");
        this.put("L941", "VILLA OTTONE * UTTENHEIM");
        this.put("L942", "VILLAFALLETTO");
        this.put("L943", "VILLA FARALDI");
        this.put("L944", "VILLAFRANCA");
        this.put("L944", "VILLAFRANCA SICULA");
        this.put("L945", "VILLAFRANCA");
        this.put("L945", "VILLAFRANCA D'ASTI");
        this.put("L946", "VILLAFRANCA");
        this.put("L946", "VILLAFRANCA IN LUNIGIANA");
        this.put("L947", "VILLAFRANCA");
        this.put("L947", "VILLAFRANCA PADOVANA");
        this.put("L948", "VILLAFRANCA");
        this.put("L948", "VILLAFRANCA PIEMONTE");
        this.put("L948", "VILLAFRANCA SABAUDA");
        this.put("L949", "VILLAFRANCA");
        this.put("L949", "VILLAFRANCA DI VERONA");
        this.put("L950", "VILLAFRANCA TIRRENA");
        this.put("L951", "VILLAFRATI");
        this.put("L952", "VILLAGA");
        this.put("L953", "VILLAGRANDE STRISAILI");
        this.put("L953", "VILLAGRANDE STRISAILI");
        this.put("L954", "VILLAGRECA");
        this.put("L955", "VILLA GUARDIA");
        this.put("L956", "VILLA GUARDIA");
        this.put("L957", "VILLA LAGARINA");
        this.put("L958", "VILLALAGO");
        this.put("L959", "VILLALBA");
        this.put("L960", "VILL'ALBESE");
        this.put("L961", "VILLALFONSINA");
        this.put("L962", "VILLALUNGA");
        this.put("L963", "VILLALVERNIA");
        this.put("L964", "VILLAMAGNA");
        this.put("L965", "VILLAMAINA");
        this.put("L966", "VILLAMAR");
        this.put("L966", "VILLAMAR");
        this.put("L967", "VILLAMARZANA");
        this.put("L968", "VILLAMASSARGIA");
        this.put("L968", "VILLAMASSARGIA");
        this.put("L969", "VILLA MINOZZO");
        this.put("L970", "VILLAMIROGLIO");
        this.put("L971", "VILLANDRO * VILLANDERS");
        this.put("L972", "VILLANOVA");
        this.put("L972", "VILLANOVA DI CASALE MONFERRATO");
        this.put("L972", "VILLANOVA MONFERRATO");
        this.put("L973", "VILLANOVA");
        this.put("L973", "VILLANOVA DEL BATTISTA");
        this.put("L974", "VILLANOVA");
        this.put("L974", "VILLANOVA MONDOVI'");
        this.put("L975", "VILLANOVA");
        this.put("L975", "VILLANOVA D'ALBENGA");
        this.put("L976", "VILLANOVA");
        this.put("L976", "VILLANOVA VIMERCATE");
        this.put("L977", "VILLANOVA DEL SILLARO");
        this.put("L977", "VILLANOVA DEL SILLARO");
        this.put("L977", "VILLANUOVA");
        this.put("L978", "VILLANOVA BIELLESE");
        this.put("L978", "VILLANOVA");
        this.put("L978", "VILLANOVA BIELLESE");
        this.put("L979", "VILLANOVA");
        this.put("L979", "VILLANOVA DI CAMPOSAMPIERO");
        this.put("L980", "VILLANOVA");
        this.put("L980", "VILLANOVA SULL'ARDA");
        this.put("L981", "VILLANOVA BALTEA");
        this.put("L981", "VILLENEUVE");
        this.put("L982", "VILLANOVA CANAVESE");
        this.put("L982", "VILLANOVA MATHI");
        this.put("L983", "VILLANOVA D'ARDENGHI");
        this.put("L984", "VILLANUOVA");
        this.put("L984", "VILLANOVA D'ASTI");
        this.put("L984", "VILLANUOVA D'ASTI");
        this.put("L985", "VILLANOVA DEL GHEBBO");
        this.put("L986", "VILLANOVAFORRU");
        this.put("L986", "VILLANOVAFORRU");
        this.put("L987", "VILLANOVAFRANCA");
        this.put("L987", "VILLANOVAFRANCA");
        this.put("L988", "VILLANOVA MARCHESANA");
        this.put("L989", "VILLANOVA MONTELEONE");
        this.put("L990", "VILLANOVA SOLARO");
        this.put("L991", "VILLANOVA TRUSCHEDU");
        this.put("L991", "VILLANOVA TRUSCHEDU");
        this.put("L992", "VILLANOVATULO");
        this.put("L993", "VILLANOVAVETTA");
        this.put("L994", "VILLANTERIO");
        this.put("L995", "VILLANUOVA");
        this.put("L995", "VILLANUOVA SUL CLISI");
        this.put("L996", "VILLA PIZZONE");
        this.put("L997", "VILLA POMPEIANA");
        this.put("L998", "VILLAPUTZU");
        this.put("L999", "VILLAR ALMESE");
        this.put("L999", "VILLAR DORA");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
