package document;

import java.util.HashMap;

/**
 * Created by Matteo on 12/11/2015.
 */
@SuppressWarnings("serial")
public class CitiesCodes_B extends HashMap<String, String> {

    public CitiesCodes_B(){
        this.put("B001", "BORGHI");
        this.put("B002", "BORGIA");
        this.put("B003", "BORGIALLO");
        this.put("B004", "BORGIO");
        this.put("B005", "BORGIO VEREZZI");
        this.put("B006", "BORGO");
        this.put("B006", "BORGO VALSUGANA");
        this.put("B007", "BORGO A MOZZANO");
        this.put("B007", "BORGO A MOZZANO E CERRETO DI SOTTO");
        this.put("B008", "BORGOCOLLEFEGATO");
        this.put("B008", "BORGOROSE");
        this.put("B009", "BORGO D'ALE");
        this.put("B010", "BORGO DI TERZO");
        this.put("B011", "BORGOFORTE");
        this.put("B012", "BORGOFORTE A DESTRA");
        this.put("B012", "MOTTEGGIANA");
        this.put("B013", "BORGOFRANCO");
        this.put("B013", "BORGOFRANCO SUL PO");
        this.put("B014", "BORGOFRANCO");
        this.put("B014", "SUARDI");
        this.put("B015", "BORGOFRANCO");
        this.put("B015", "BORGOFRANCO D'IVREA");
        this.put("B016", "BORGOLAVEZZARO");
        this.put("B017", "BORGO SAN GIOVANNI");
        this.put("B017", "BORGO LITTORIO");
        this.put("B017", "BORGO SAN GIOVANNI");
        this.put("B017", "CAZZIMANI");
        this.put("B018", "BORGOMALE");
        this.put("B019", "BORGOMANERO");
        this.put("B020", "BORGOMARO");
        this.put("B021", "BORGOMASINO");
        this.put("B022", "BORGONATO");
        this.put("B023", "BORGONE");
        this.put("B023", "BORGONE D'OSSOLA");
        this.put("B024", "BORGONE");
        this.put("B024", "BORGONE SUSA");
        this.put("B025", "BORGONOVO VAL TIDONE");
        this.put("B026", "BORGO PACE");
        this.put("B027", "BORGO PANIGALE");
        this.put("B028", "BORGO PRIOLO");
        this.put("B029", "BORGORATTO");
        this.put("B029", "BORGORATTO ALESSANDRINO");
        this.put("B030", "BORGORATTO");
        this.put("B030", "BORGORATTO MORMOROLO");
        this.put("B031", "BORGORICCO");
        this.put("B031", "SANT'EUFEMIA");
        this.put("B032", "BORGO SAN BERNARDINO");
        this.put("B033", "BORGO SAN DALMAZZO");
        this.put("B034", "BORGO SAN DONNINO");
        this.put("B034", "FIDENZA");
        this.put("B035", "BORGO SAN GIACOMO");
        this.put("B035", "GABBIANO");
        this.put("B036", "BORGO SAN LORENZO");
        this.put("B037", "BORGO SAN MARTINO");
        this.put("B038", "BORGO SAN SIRO");
        this.put("B039", "BORGO SANT'AGATA");
        this.put("B040", "BORGOSATOLLO");
        this.put("B041", "BORGOSESIA");
        this.put("B042", "BORGOTARO");
        this.put("B042", "BORGO VAL DI TARO");
        this.put("B043", "BORGO TICINO");
        this.put("B044", "BORGO TOSSIGNANO");
        this.put("B044", "TOSSIGNANO");
        this.put("B045", "BORGOUNITO");
        this.put("B045", "BORGOUNITO");
        this.put("B045", "BORGOUNITO");
        this.put("B045", "BORGOUNITO");
        this.put("B046", "BORGO VERCELLI");
        this.put("B047", "BORIANO");
        this.put("B048", "BORMIDA");
        this.put("B049", "BORMIO");
        this.put("B050", "BORNAGO");
        this.put("B051", "BORNASCO");
        this.put("B052", "BORNATE");
        this.put("B053", "BORNATO");
        this.put("B054", "BORNO");
        this.put("B055", "BORONEDDU");
        this.put("B055", "BORONEDDU");
        this.put("B056", "BORORE");
        this.put("B057", "BORRELLO");
        this.put("B058", "BORRIANA");
        this.put("B058", "BORRIANA");
        this.put("B059", "BORSANO");
        this.put("B060", "BORSEA");
        this.put("B061", "BORSO");
        this.put("B061", "BORSO DEL GRAPPA");
        this.put("B062", "BORTIGALI");
        this.put("B063", "BORTIGIADAS");
        this.put("B063", "BORTIGIADAS");
        this.put("B064", "BORUTTA");
        this.put("B065", "BORZAGO");
        this.put("B066", "BORZOLI");
        this.put("B067", "BORZONASCA");
        this.put("B068", "BOSA");
        this.put("B069", "BOSARO");
        this.put("B070", "BOSCHI SANT'ANNA");
        this.put("B071", "BOSCO");
        this.put("B071", "BOSCO MARENGO");
        this.put("B072", "BOSCO");
        this.put("B072", "BOSCO VALTRAVAGLIA");
        this.put("B073", "BOSCO CHIESANUOVA");
        this.put("B074", "BOSCOMARE");
        this.put("B075", "BOSCONERO");
        this.put("B076", "BOSCOREALE");
        this.put("B077", "BOSCOTRECASE");
        this.put("B078", "BOSENTINO");
        this.put("B079", "BOSIA");
        this.put("B080", "BOSIO");
        this.put("B081", "BOSISIO");
        this.put("B081", "BOSISIO PARINI");
        this.put("B081", "BOSISIO PARINI");
        this.put("B082", "BOSNASCO");
        this.put("B083", "BOSSICO");
        this.put("B084", "BOSSOLASCO");
        this.put("B085", "BOTRICELLO");
        this.put("B086", "BOTRUGNO");
        this.put("B087", "BOTTAIANO");
        this.put("B088", "BOTTANUCO");
        this.put("B089", "BOTTARONE");
        this.put("B089", "MEZZANA CORTI BOTTARONE");
        this.put("B090", "BOTTEDO");
        this.put("B091", "BOTTICINO");
        this.put("B092", "BOTTICINO MATTINA");
        this.put("B093", "BOTTICINO SERA");
        this.put("B094", "BOTTIDDA");
        this.put("B095", "BOTTRIGHE");
        this.put("B096", "BOUSSON");
        this.put("B097", "BOVA");
        this.put("B098", "BOVALINO");
        this.put("B099", "BOVA MARINA");
        this.put("B100", "BOVEGNO");
        this.put("B101", "BOVES");
        this.put("B102", "BOVEZZO");
        this.put("B103", "BOVILE");
        this.put("B104", "BOVINO");
        this.put("B105", "BOVISIO");
        this.put("B105", "BOVISIO-MASCIAGO");
        this.put("B105", "BOVISIO-MASCIAGO");
        this.put("B106", "BOVOLENTA");
        this.put("B107", "BOVOLONE");
        this.put("B108", "BOZZANA");
        this.put("B109", "BOZZOLE");
        this.put("B110", "BOZZOLO");
        this.put("B111", "BRA");
        this.put("B112", "BRACCA");
        this.put("B113", "BRACCA DI COSTA SERINA");
        this.put("B113", "BRACCA DI COSTA SERINA");
        this.put("B113", "BRACCA DI COSTA SERINA");
        this.put("B114", "BRACCIANO");
        this.put("B115", "BRACIGLIANO");
        this.put("B116", "BRAIES * PRAGS");
        this.put("B117", "BRALLO DI PREGOLA");
        this.put("B117", "PREGOLA");
        this.put("B118", "BRANCALEONE");
        this.put("B119", "BRANCERE");
        this.put("B120", "BRANDICO");
        this.put("B121", "BRANDIZZO");
        this.put("B122", "BRANDUZZO");
        this.put("B123", "BRANZI");
        this.put("B124", "BRAONE");
        this.put("B125", "BRAZZANO");
        this.put("B126", "BREBBIA");
        this.put("B127", "BRECCIA");
        this.put("B128", "BREDA");
        this.put("B128", "BREDA DI PIAVE");
        this.put("B129", "BREDA DE' BUGNI");
        this.put("B129", "CASTELVERDE");
        this.put("B130", "BREDA GUAZZONE");
        this.put("B131", "BREGANO");
        this.put("B132", "BREGANZE");
        this.put("B133", "BREGLIA");
        this.put("B134", "BREGNANO");
        this.put("B135", "BREGUZZO");
        this.put("B136", "BREIA");
        this.put("B137", "BREMBATE");
        this.put("B138", "BREMBATE DI SOPRA");
        this.put("B138", "BREMBATE DI SOPRA");
        this.put("B139", "BREMBATE DI SOTTO");
        this.put("B140", "BREMBILLA");
        this.put("B141", "BREMBIO");
        this.put("B141", "BREMBIO");
        this.put("B142", "BREME");
        this.put("B143", "BRENDOLA");
        this.put("B144", "BRENNA");
        this.put("B145", "BRENNERO * BRENNER");
        this.put("B145", "BRENNERO * BRENNER");
        this.put("B146", "BRENNO");
        this.put("B146", "BRENNO USERIA");
        this.put("B147", "BRENNO");
        this.put("B147", "BRENNO DELLA TORRE");
        this.put("B148", "BRENO");
        this.put("B148", "SOMBRENO");
        this.put("B149", "BRENO");
        this.put("B150", "BRENTA");
        this.put("B151", "BRENTINO");
        this.put("B152", "BRENTINO BELLUNO");
        this.put("B153", "BRENTONICO");
        this.put("B154", "BRENZONE");
        this.put("B154", "CASTELLETTO");
        this.put("B154", "CASTELLETTO DI BRENZONE");
        this.put("B155", "BREONIO");
        this.put("B155", "BREONIO");
        this.put("B156", "BRESCELLO");
        this.put("B157", "BRESCIA");
        this.put("B158", "BRESIMO");
        this.put("B159", "BRESSANA BOTTARONE");
        this.put("B160", "BRESSANONE * BRIXEN");
        this.put("B161", "BRESSANVIDO");
        this.put("B162", "BRESSO");
        this.put("B163", "BRESTOVIZZA IN VALLE");
        this.put("B164", "BRETTO");
        this.put("B165", "BREZ");
        this.put("B166", "BREZZO DI BEDERO");
        this.put("B167", "BRIAGLIA");
        this.put("B168", "BRIANZOLA");
        this.put("B169", "BRIATICO");
        this.put("B169", "BRIATICO");
        this.put("B170", "BRIAVACCA");
        this.put("B171", "BRICHERASIO");
        this.put("B172", "BRIENNO");
        this.put("B173", "BRIENZA");
        this.put("B174", "BRIGA");
        this.put("B174", "BRIGA MARITTIMA");
        this.put("B174", "BRIGA MARITTIMA");
        this.put("B174", "BRIGA MARITTIMA");
        this.put("B175", "BRIGA ALTA");
        this.put("B176", "BRIGA NOVARESE");
        this.put("B177", "BRIGNANO");
        this.put("B177", "BRIGNANO DEL CURONE");
        this.put("B178", "BRIGNANO");
        this.put("B178", "BRIGNANO GERA D'ADDA");
        this.put("B179", "BRIGNANO-FRASCATA");
        this.put("B180", "BRINDISI");
        this.put("B181", "BRINDISI");
        this.put("B181", "BRINDISI MONTAGNA");
        this.put("B182", "BRINZIO");
        this.put("B183", "BRIONA");
        this.put("B184", "BRIONE");
        this.put("B185", "BRIONE");
        this.put("B186", "BRIONI MAGGIORE");
        this.put("B187", "BRIOSCO");
        this.put("B187", "BRIOSCO");
        this.put("B188", "BRISIGHELLA");
        this.put("B189", "BRISINO");
        this.put("B190", "BRISSAGO");
        this.put("B191", "BRISSAGO-VALTRAVAGLIA");
        this.put("B192", "BRISSOGNE");
        this.put("B193", "BRITTOLI");
        this.put("B194", "BRIVIO");
        this.put("B194", "BRIVIO");
        this.put("B195", "BROCCO");
        this.put("B195", "BROCCOSTELLA");
        this.put("B196", "BROGLIANO");
        this.put("B197", "BROGNATURO");
        this.put("B197", "BROGNATURO");
        this.put("B198", "BROLO");
        this.put("B199", "BROLPASINO");
        this.put("B200", "BRONDELLO");
        this.put("B201", "BRONI");
        this.put("B202", "BRONTE");
        this.put("B203", "BRONZOLO * BRANZOLL");
        this.put("B204", "BROSSASCO");
        this.put("B205", "BROSSO");
        this.put("B206", "BROVELLO");
        this.put("B207", "BROVELLO-CARPUGNINO");
        this.put("B207", "BROVELLO-CARPUGNINO");
        this.put("B208", "BROVIDA");
        this.put("B208", "BROVIDA");
        this.put("B209", "BROZOLO");
        this.put("B210", "BROZZI");
        this.put("B210", "BROZZI");
        this.put("B210", "BROZZI");
        this.put("B210", "BROZZI");
        this.put("B211", "BROZZO");
        this.put("B212", "BRUGHERIO");
        this.put("B212", "BRUGHERIO");
        this.put("B213", "BRUGINE");
        this.put("B214", "BRUGNATO");
        this.put("B215", "BRUGNERA");
        this.put("B216", "BRUINO");
        this.put("B217", "BRUMANO");
        this.put("B218", "BRUNATE");
        this.put("B219", "BRUNELLO");
        this.put("B220", "BRUNICO * BRUNECK");
        this.put("B221", "BRUNO");
        this.put("B222", "BRUNTINO");
        this.put("B223", "BRUSAPORTO");
        this.put("B224", "BRUSASCHETTO");
        this.put("B225", "BRUSASCO");
        this.put("B226", "BRUSASCO CAVAGNOLO");
        this.put("B226", "BRUSASCO CAVAGNOLO");
        this.put("B227", "BRUSCIANO");
        this.put("B228", "BRUSIMPIANO");
        this.put("B229", "BRUSNENGO");
        this.put("B229", "BRUSNENGO");
        this.put("B230", "BRUSSON");
        this.put("B230", "BRUSSONE");
        this.put("B231", "BRUSUGLIO");
        this.put("B232", "BRUZOLO");
        this.put("B233", "BRUZZANO");
        this.put("B233", "BRUZZANO DEI DUE BORGHI");
        this.put("B234", "BRUZZANO");
        this.put("B234", "BRUZZANO ZEFFIRIO");
        this.put("B235", "BUBBIANO");
        this.put("B236", "BUBBIO");
        this.put("B237", "BUCCHERI");
        this.put("B238", "BUCCHIANICO");
        this.put("B239", "BUCCIANO");
        this.put("B240", "BUCCINASCO");
        this.put("B241", "BUCCINIGO");
        this.put("B242", "BUCCINO");
        this.put("B243", "BUCINE");
        this.put("B244", "BUCUIE");
        this.put("B245", "BUDAGNE");
        this.put("B246", "BUDDUSO'");
        this.put("B246", "BUDDUSO'");
        this.put("B247", "BUDOIA");
        this.put("B248", "BUDONI");
        this.put("B248", "BUDONI");
        this.put("B249", "BUDRIO");
        this.put("B250", "BUGGERRU");
        this.put("B250", "BUGGERRU");
        this.put("B251", "BUGGIANO");
        this.put("B252", "BUGGIOLO");
        this.put("B253", "BUGIALLO");
        this.put("B254", "BUGLIO");
        this.put("B254", "MONTEBUGLIO");
        this.put("B255", "BUGLIO");
        this.put("B255", "BUGLIO IN MONTE");
        this.put("B256", "BUGNARA");
        this.put("B257", "BUGNATE");
        this.put("B258", "BUGUGGIATE");
        this.put("B259", "BUJA");
        this.put("B260", "BUIE D'ISTRIA");
        this.put("B261", "BULCIAGO");
        this.put("B261", "BULCIAGO");
        this.put("B262", "BULGAROGRASSO");
        this.put("B263", "BULGORELLO");
        this.put("B264", "BULTEI");
        this.put("B265", "BULZI");
        this.put("B266", "BUONABITACOLO");
        this.put("B267", "BUONALBERGO");
        this.put("B268", "BUONANOTTE");
        this.put("B268", "MONTEBELLO SUL SANGRO");
        this.put("B269", "BUONCONVENTO");
        this.put("B270", "BUONVICINO");
        this.put("B271", "BURAGO");
        this.put("B271", "BURAGO RIVIERA");
        this.put("B272", "BURAGO");
        this.put("B272", "BURAGO DI MOLGORA");
        this.put("B272", "BURAGO DI MOLGORA");
        this.put("B273", "BURANO");
        this.put("B274", "BURCEI");
        this.put("B275", "BURGIO");
        this.put("B276", "BURGOS");
        this.put("B277", "BURGUSIO * BURGEIS");
        this.put("B278", "BURIASCO");
        this.put("B279", "BUROLO");
        this.put("B280", "BURONZO");
        this.put("B281", "BUSACHI");
        this.put("B281", "BUSACHI");
        this.put("B282", "BUSALLA");
        this.put("B283", "BUSANA");
        this.put("B284", "BUSANO");
        this.put("B285", "BUSCA");
        this.put("B286", "BUSCATE");
        this.put("B287", "BUSCEMI");
        this.put("B288", "BUSETO PALIZZOLO");
        this.put("B289", "BUSNAGO");
        this.put("B289", "BUSNAGO");
        this.put("B290", "BUSO");
        this.put("B290", "BUSO SARZANO");
        this.put("B291", "BUSSANA");
        this.put("B292", "BUSSERO");
        this.put("B293", "BUSSETO");
        this.put("B294", "BUSSI");
        this.put("B294", "BUSSI SUL TIRINO");
        this.put("B295", "BUSSO");
        this.put("B296", "BUSSOLENGO");
        this.put("B297", "BUSSOLENO");
        this.put("B298", "BUSSOLINO");
        this.put("B298", "BUSSOLINO GASSINESE");
        this.put("B299", "BUSTIGHERA");
        this.put("B300", "BUSTO ARSIZIO");
        this.put("B301", "BUSTO GAROLFO");
        this.put("B302", "BUTERA");
        this.put("B303", "BUTI");
        this.put("B304", "BUTTAPIETRA");
        this.put("B305", "BUTTIGLIERA");
        this.put("B305", "BUTTIGLIERA ALTA");
        this.put("B306", "BUTTIGLIERA D'ASTI");
        this.put("B307", "BUTTIRAGO");
        this.put("B308", "BUTTOGNO");
        this.put("B309", "BUTTRIO");
        this.put("B310", "BUZZONE SAN PAOLO");
        this.put("B310", "SAN PAOLO D'ARGON");
        this.put("B311", "CABELLA LIGURE");
        this.put("B312", "CABIAGLIO");
        this.put("B312", "CASTELLO CABIAGLIO");
        this.put("B313", "CABIATE");
        this.put("B314", "CABRAS");
        this.put("B314", "CABRAS");
        this.put("B315", "CACCAMO");
        this.put("B316", "CACCAVERO");
        this.put("B316", "CAMPOVERDE");
        this.put("B317", "CACCAVONE");
        this.put("B317", "POGGIO SANNITA");
        this.put("B318", "CACCIA");
        this.put("B318", "VILLA CACCIA");
        this.put("B319", "CACCURI");
        this.put("B319", "CACCURI");
        this.put("B320", "CA' D'ANDREA");
        this.put("B321", "CADDO");
        this.put("B322", "CA' DE' BONAVOGLI");
        this.put("B323", "CA' DE' CAGGI");
        this.put("B324", "CA' DE' CORTI");
        this.put("B325", "CADEGLIANO");
        this.put("B326", "CADEGLIANO-VICONAGO");
        this.put("B327", "CA' DEI BOLLI");
        this.put("B328", "CADELBOSCO DI SOPRA");
        this.put("B329", "CA' DELL'ACQUA");
        this.put("B330", "CA' DELLA TERRA");
        this.put("B331", "CA' DE' MAZZI");
        this.put("B332", "CADEO");
        this.put("B333", "CA' DE' QUINZANI");
        this.put("B334", "GRAGLIO CON CADERO");
        this.put("B334", "CADERO CON GRAGLIO");
        this.put("B335", "CADERZONE");
        this.put("B336", "CA' DE' SFONDRATI");
        this.put("B337", "CA' DE' SORESINI");
        this.put("B338", "CA' DE' STAOLI");
        this.put("B339", "CA' DE' STEFANI");
        this.put("B340", "CA' DE' TEDIOLI");
        this.put("B341", "CA' DE' ZECCHI");
        this.put("B342", "CA' DI DAVID");
        this.put("B343", "CADIGNANO");
        this.put("B344", "CADINE");
        this.put("B345", "CADONEGHE");
        this.put("B346", "CADORAGO");
        this.put("B347", "CADREZZATE");
        this.put("B348", "CA' EMO");
        this.put("B348", "CA' EMO");
        this.put("B348", "FASANA POLESINE");
        this.put("B349", "CAERANO");
        this.put("B349", "CAERANO DI SAN MARCO");
        this.put("B350", "CAFASSE");
        this.put("B351", "CAGGIANO");
        this.put("B352", "CAGLI");
        this.put("B353", "CAGLIANO");
        this.put("B354", "CAGLIARI");
        this.put("B355", "CAGLIO");
        this.put("B356", "CAGNA");
        this.put("B357", "CAGNANO");
        this.put("B357", "CAGNANO VARANO");
        this.put("B358", "CAGNANO");
        this.put("B358", "CAGNANO AMITERNO");
        this.put("B359", "CAGNO");
        this.put("B360", "CAGNO'");
        this.put("B361", "CAIANELLO");
        this.put("B362", "CAIAZZO");
        this.put("B363", "CAIDATE");
        this.put("B364", "CAINES * KUENS");
        this.put("B365", "CAINO");
        this.put("B366", "CAIOLO");
        this.put("B367", "CAIRANO");
        this.put("B368", "CAIRATE");
        this.put("B369", "CAIRO");
        this.put("B369", "CAIRO MONTENOTTE");
        this.put("B370", "CAIRO");
        this.put("B370", "CAIRO LOMELLINO");
        this.put("B371", "CAIVANO");
        this.put("B372", "CAJELLO");
        this.put("B373", "CAJONVICO");
        this.put("B374", "CALABRITTO");
        this.put("B375", "CALALZO");
        this.put("B375", "CALALZO DI CADORE");
        this.put("B376", "CALAMANDRANA");
        this.put("B377", "CALAMONACI");
        this.put("B378", "CALANGIANUS");
        this.put("B378", "CALANGIANUS");
        this.put("B379", "CALANNA");
        this.put("B380", "CALASCA");
        this.put("B380", "CALASCA-CASTIGLIONE");
        this.put("B380", "CALASCA-CASTIGLIONE");
        this.put("B381", "CALASCIBETTA");
        this.put("B382", "CALASCIO");
        this.put("B383", "CALASETTA");
        this.put("B383", "CALASETTA");
        this.put("B384", "CALATABIANO");
        this.put("B385", "CALATAFIMI");
        this.put("B385", "CALATAFIMI SEGESTA");
        this.put("B386", "CALAVINO");
        this.put("B387", "CALCABABBIO");
        this.put("B387", "LUNGAVILLA");
        this.put("B388", "CALCATA");
        this.put("B389", "CALCERANICA");
        this.put("B389", "CALCERANICA AL LAGO");
        this.put("B390", "CALCI");
        this.put("B391", "CALCIANO");
        this.put("B392", "CALCINAIA");
        this.put("B393", "CALCINATE");
        this.put("B394", "CALCINATO");
        this.put("B395", "CALCIO");
        this.put("B396", "CALCO");
        this.put("B396", "CALCO");
        this.put("B397", "CALDARO * KALTERN");
        this.put("B397", "CALDARO SULLA STRADA DEL VINO * KALTERN AN DER WEINSTRASSE");
        this.put("B398", "CALDAROLA");
        this.put("B399", "CALDERARA");
        this.put("B399", "CALDERARA DI RENO");
        this.put("B400", "CALDES");
        this.put("B401", "CAL DI CANALE");
        this.put("B402", "CALDIERO");
        this.put("B403", "CALDOGNO");
        this.put("B404", "CALDONAZZO");
        this.put("B405", "CALENDASCO");
        this.put("B406", "CALENZANO");
        this.put("B407", "CALEPIO");
        this.put("B408", "CALESTANO");
        this.put("B409", "CALICE");
        this.put("B409", "CALICE LIGURE");
        this.put("B410", "CALICE");
        this.put("B410", "CALICE AL CORNOVIGLIO");
        this.put("B411", "CALICE OSSOLANO");
        this.put("B412", "CALIGNANO");
        this.put("B413", "CALIMERA");
        this.put("B414", "CALINO");
        this.put("B415", "CALITRI");
        this.put("B416", "CALIZZANO");
        this.put("B417", "CALLABIANA");
        this.put("B417", "CALLABIANA");
        this.put("B418", "CALLIANO");
        this.put("B419", "CALLIANO");
        this.put("B420", "CALO'");
        this.put("B421", "CALOGNA");
        this.put("B422", "CALOLZIO");
        this.put("B423", "CALOLZIOCORTE");
        this.put("B423", "CALOLZIOCORTE");
        this.put("B424", "CALOPEZZATI");
        this.put("B425", "CALOSSO");
        this.put("B426", "CALOVETO");
        this.put("B427", "CALTABELLOTTA");
        this.put("B428", "CALTAGIRONE");
        this.put("B429", "CALTANISSETTA");
        this.put("B430", "CALTAVUTURO");
        this.put("B431", "CALTIGNAGA");
        this.put("B432", "CALTO");
        this.put("B433", "CALTRANO");
        this.put("B434", "CALUSCO");
        this.put("B434", "CALUSCO D'ADDA");
        this.put("B435", "CALUSO");
        this.put("B436", "CALVAGESE");
        this.put("B436", "CALVAGESE DELLA RIVIERA");
        this.put("B437", "CALVANICO");
        this.put("B438", "CALVARUSO");
        this.put("B439", "CALVATONE");
        this.put("B440", "CALVELLO");
        this.put("B441", "CALVENE");
        this.put("B442", "CALVENZANO");
        this.put("B443", "CALVERA");
        this.put("B444", "CALVI");
        this.put("B445", "CALVI");
        this.put("B445", "CALVI RISORTA");
        this.put("B446", "CALVI");
        this.put("B446", "CALVI DELL'UMBRIA");
        this.put("B447", "CALVIGNANO");
        this.put("B448", "CALVIGNASCO");
        this.put("B449", "CALVI SAN NAZZARO");
        this.put("B449", "CALVI SAN NAZZARO");
        this.put("B449", "SAN NAZZARO CALVI");
        this.put("B450", "CALVISANO");
        this.put("B451", "CALVISIO");
        this.put("B452", "CALVIZZANO");
        this.put("B453", "CAMAGNA MONFERRATO");
        this.put("B454", "CAMAGNA");
        this.put("B454", "CAMAGNA DI TORINO");
        this.put("B455", "CAMAIORE");
        this.put("B456", "CAMAIRAGO");
        this.put("B456", "CAMAIRAGO");
        this.put("B457", "CAMANDONA");
        this.put("B457", "CAMANDONA");
        this.put("B458", "CAMARDA");
        this.put("B459", "CAMASCO");
        this.put("B460", "CAMASTRA");
        this.put("B461", "CAMBIAGO");
        this.put("B462", "CAMBIANO");
        this.put("B463", "CAMBIASCA");
        this.put("B463", "CAMBIASCA");
        this.put("B464", "CAMBIO'");
        this.put("B465", "CAMBURZANO");
        this.put("B465", "CAMBURZANO");
        this.put("B466", "CAMELI");
        this.put("B466", "SANT'ELENA SANNITA");
        this.put("B467", "CAMERANA");
        this.put("B468", "CAMERANO");
        this.put("B469", "CAMERANO CASASCO");
        this.put("B470", "CAMERATA");
        this.put("B470", "CAMERATA PICENA");
        this.put("B471", "CAMERATA");
        this.put("B471", "CAMERATA CORNELLO");
        this.put("B472", "CAMERATA");
        this.put("B472", "CAMERATA NUOVA");
        this.put("B473", "CAMERI");
        this.put("B474", "CAMERINO");
        this.put("B475", "CAMERLATA");
        this.put("B476", "CAMEROTA");
        this.put("B477", "CAMIGLIANO");
        this.put("B478", "CAMIGNONE");
        this.put("B479", "CAMINATA");
        this.put("B480", "CAMINATA DI TURES * KEMATEN");
        this.put("B481", "CAMINI");
        this.put("B482", "CAMINO");
        this.put("B483", "CAMINO AL TAGLIAMENTO");
        this.put("B483", "CAMINO DI CODROIPO");
        this.put("B484", "CAMISANO");
        this.put("B485", "CAMISANO");
        this.put("B485", "CAMISANO VICENTINO");
        this.put("B486", "CAMMARATA");
        this.put("B487", "CAMNAGO");
        this.put("B487", "CAMNAGO SAN MARTINO");
        this.put("B487", "CAMNAGO VOLTA");
        this.put("B488", "CAMNAGO D'UGGIATE");
        this.put("B488", "CAMNAGO FALOPPIA");
        this.put("B489", "CAMO");
        this.put("B490", "CAMOGLI");
        this.put("B491", "CAMOSIO");
        this.put("B491", "CHAMOIS");
        this.put("B492", "CAMPAGNA");
        this.put("B493", "CAMPAGNA");
        this.put("B493", "CAMPAGNA LUPIA");
        this.put("B494", "CAMPAGNANO");
        this.put("B494", "CASTEL CAMPAGNANO");
        this.put("B494", "CASTELLO DI CAMPAGNANO");
        this.put("B495", "CAMPAGNANO");
        this.put("B495", "CAMPAGNANO VEDASCA");
        this.put("B496", "CAMPAGNANO");
        this.put("B496", "CAMPAGNANO DI ROMA");
        this.put("B497", "CAMPAGNATICO");
        this.put("B498", "CAMPAGNOLA");
        this.put("B498", "CAMPAGNOLA CREMASCA");
        this.put("B498", "CAMPAGNOLA CREMASCA");
        this.put("B499", "CAMPAGNOLA");
        this.put("B499", "CAMPAGNOLA EMILIA");
        this.put("B500", "CAMPANA");
        this.put("B501", "CAMPARADA");
        this.put("B501", "CAMPARADA");
        this.put("B502", "CAMPEGINE");
        this.put("B503", "CAMPELLO");
        this.put("B503", "CAMPELLO MONTI");
        this.put("B504", "CAMPELLO");
        this.put("B504", "CAMPELLO SUL CLITUNNO");
        this.put("B505", "CAMPERTOGNO");
        this.put("B506", "CAMPI");
        this.put("B506", "CAMPI SALENTINA");
        this.put("B507", "CAMPI BISENZIO");
        this.put("B508", "CAMPIGLIA CERVO");
        this.put("B508", "CAMPIGLIA");
        this.put("B508", "CAMPIGLIA CERVO");
        this.put("B509", "CAMPIGLIA MARITTIMA");
        this.put("B509", "CAMPIGLIA");
        this.put("B510", "CAMPIGLIA SOANA");
        this.put("B510", "CAMPIGLIA");
        this.put("B510", "VALPRATO SOANA");
        this.put("B511", "CAMPIGLIA");
        this.put("B511", "CAMPIGLIA DEI BERICI");
        this.put("B512", "CAMPIGLIONE");
        this.put("B512", "CAMPIGLIONE FENILE");
        this.put("B513", "CAMPIONE");
        this.put("B513", "CAMPIONE D'ITALIA");
        this.put("B514", "CAMPITELLO");
        this.put("B514", "CAMPITELLO DI FASSA");
        this.put("B515", "CAMPLI");
        this.put("B516", "CAMPO");
        this.put("B516", "CAMPO CALABRO");
        this.put("B516", "CAMPO DI CALABRIA");
        this.put("B517", "CAMPO");
        this.put("B517", "CAMPO CANAVESE");
        this.put("B518", "CAMPO");
        this.put("B519", "CAMPOBASSO");
        this.put("B520", "CAMPOBELLO DI LICATA");
        this.put("B521", "CAMPOBELLO DI MAZARA");
        this.put("B522", "CAMPOCHIARO");
        this.put("B523", "CAMPOCHIESA");
        this.put("B524", "CAMPODARSEGO");
        this.put("B525", "CAMPODENNO");
        this.put("B526", "CAMPO DI GIOVE");
        this.put("B527", "CAMPODIMELE");
        this.put("B528", "CAMPODIPIETRA");
        this.put("B529", "CAMPO DI TRENS * FREIENFELD");
        this.put("B530", "CAMPODOLCINO");
        this.put("B531", "CAMPODORO");
        this.put("B532", "CAMPOFELICE");
        this.put("B532", "CAMPOFELICE DI ROCCELLA");
        this.put("B533", "CAMPOFELICE DI FITALIA");
        this.put("B534", "CAMPOFILONE");
        this.put("B534", "CAMPOFILONE");
        this.put("B535", "CAMPOFIORITO");
        this.put("B536", "CAMPOFORMIDO");
        this.put("B537", "CAMPOFRANCO");
        this.put("B538", "CAMPOFREDDO");
        this.put("B538", "CAMPO LIGURE");
        this.put("B539", "CAMPOGALLIANO");
        this.put("B540", "CAMPO LARIS");
        this.put("B540", "CHAMPORCHER");
        this.put("B541", "CAMPOLATTARO");
        this.put("B542", "CAMPOLI");
        this.put("B542", "CAMPOLI DEL MONTE TABURNO");
        this.put("B543", "CAMPOLI");
        this.put("B543", "CAMPOLI APPENNINO");
        this.put("B544", "CAMPOLIETO");
        this.put("B545", "CAMPOLONGO");
        this.put("B545", "CAMPOLONGO AL TORRE");
        this.put("B546", "CAMPOLONGO");
        this.put("B546", "CAMPOLONGO MAGGIORE");
        this.put("B547", "CAMPOLONGO");
        this.put("B547", "CAMPOLONGO SUL BRENTA");
        this.put("B548", "CAMPOLUNGO");
        this.put("B548", "CAMPOLUNGO");
        this.put("B549", "CAMPOMAGGIORE");
        this.put("B550", "CAMPOMARINO");
        this.put("B551", "CAMPOMORONE");
        this.put("B551", "LARVEGO");
        this.put("B552", "CAMPOMORTO");
        this.put("B553", "CAMPO NELL'ELBA");
        this.put("B554", "CAMPONOGARA");
        this.put("B555", "CAMPORA");
        this.put("B556", "CAMPOREALE");
        this.put("B557", "CAMPORGIANO");
        this.put("B558", "CAMPO RINALDO");
        this.put("B559", "CAMPOROSSO");
        this.put("B560", "CAMPOROSSO");
        this.put("B560", "CAMPOROSSO IN VALCANALE");
        this.put("B561", "CAMPOROTONDO");
        this.put("B561", "CAMPOROTONDO ETNEO");
        this.put("B562", "CAMPOROTONDO");
        this.put("B562", "CAMPOROTONDO DI FIASTRONE");
        this.put("B563", "CAMPOSAMPIERO");
        this.put("B564", "CAMPO SAN MARTINO");
        this.put("B565", "CAMPOSANO");
        this.put("B566", "CAMPOSANTO");
        this.put("B567", "CAMPOSPINOSO");
        this.put("B568", "CAMPOSPINOSO ALBAREDO");
        this.put("B568", "CAMPOSPINOSO ALBAREDO");
        this.put("B569", "CAMPOTOSTO");
        this.put("B570", "CAMPO TURES * SAND IN TAUFERS");
        this.put("B571", "CAMPOVICO");
        this.put("B572", "CAMUGNANO");
        this.put("B573", "CANALE");
        this.put("B574", "CANALE D'AGORDO");
        this.put("B574", "FORNO DI CANALE");
        this.put("B575", "CANALE D'ISONZO");
        this.put("B576", "CANALE E MONTEVIRGINIO");
        this.put("B576", "CANALE MONTERANO");
        this.put("B577", "CANAL SAN BOVO");
        this.put("B578", "CANARO");
        this.put("B579", "CANAZEI");
        this.put("B580", "CANCELLARA");
        this.put("B581", "CANCELLO ED ARNONE");
        this.put("B582", "CANDA");
        this.put("B583", "CANDEASCO");
        this.put("B584", "CANDELA");
        this.put("B585", "CANDELARA");
        this.put("B586", "CANDELO");
        this.put("B586", "CANDELO");
        this.put("B587", "CANDIA");
        this.put("B587", "CANDIA LOMELLINA");
        this.put("B588", "CANDIA");
        this.put("B588", "CANDIA CANAVESE");
        this.put("B589", "CANDIANA");
        this.put("B589", "PONTE CASALE");
        this.put("B590", "CANDIDA");
        this.put("B591", "CANDIDONI");
        this.put("B592", "CANDIOLO");
        this.put("B593", "CANEGRATE");
        this.put("B594", "CANELLI");
        this.put("B595", "CANEMORTO");
        this.put("B595", "ORVINIO");
        this.put("B596", "CANEPA");
        this.put("B597", "CANEPINA");
        this.put("B598", "CANEVA");
        this.put("B599", "CANEVINO");
        this.put("B600", "CANEZZA");
        this.put("B601", "CANFANARO");
        this.put("B602", "CANICATTI'");
        this.put("B603", "CANICATTINI BAGNI");
        this.put("B604", "CANINO");
        this.put("B605", "CANISCHIO");
        this.put("B606", "CANISTRO");
        this.put("B607", "CANNA");
        this.put("B608", "CANNALONGA");
        this.put("B608", "CANNALONGA");
        this.put("B609", "CANNARA");
        this.put("B610", "CANNERO");
        this.put("B610", "CANNERO RIVIERA");
        this.put("B610", "CANNERO RIVIERA");
        this.put("B611", "CANNETO");
        this.put("B611", "CANNETO DI BARI");
        this.put("B612", "CANNETO");
        this.put("B612", "CANNETO SULL'OGLIO");
        this.put("B613", "CANNETO PAVESE");
        this.put("B613", "MONTU' DEI GABBI");
        this.put("B614", "CANNITELLO");
        this.put("B615", "CANNOBIO");
        this.put("B615", "CANNOBIO");
        this.put("B616", "CANNOLE");
        this.put("B617", "CANOLO");
        this.put("B618", "CANONICA D'ADDA");
        this.put("B619", "CANOSA");
        this.put("B619", "CANOSA DI PUGLIA");
        this.put("B619", "CANOSA DI PUGLIA");
        this.put("B620", "CANOSA");
        this.put("B620", "CANOSA SANNITA");
        this.put("B621", "CANOSIO");
        this.put("B622", "CANOVA DEL MORBASCO");
        this.put("B623", "CANOVA OLZANO");
        this.put("B624", "CANSANO");
        this.put("B625", "CANSERO");
        this.put("B626", "CANTAGALLO");
        this.put("B626", "CANTAGALLO");
        this.put("B627", "CANTALICE");
        this.put("B628", "CANTALUPA");
        this.put("B629", "CANTALUPO");
        this.put("B629", "CANTALUPO LIGURE");
        this.put("B630", "CANTALUPO");
        this.put("B630", "CANTALUPO NEL SANNIO");
        this.put("B631", "CANTALUPO");
        this.put("B631", "CANTALUPO IN SABINA");
        this.put("B632", "CANTALUPO BARDELLA");
        this.put("B632", "MANDELA");
        this.put("B633", "CANTARANA");
        this.put("B634", "CANTELLO");
        this.put("B634", "CAZZONE");
        this.put("B635", "CANTERANO");
        this.put("B636", "CANTIANO");
        this.put("B637", "CANTOIRA");
        this.put("B638", "CANTONALE");
        this.put("B639", "CANTU'");
        this.put("B640", "CANZANO");
        this.put("B641", "CANZO");
        this.put("B642", "CAORLE");
        this.put("B643", "CAORSO");
        this.put("B644", "CAPACCIO");
        this.put("B645", "CAPACI");
        this.put("B646", "CAPALBIO");
        this.put("B647", "CAPANNOLI");
        this.put("B648", "CAPANNORI");
        this.put("B649", "CAPENA");
        this.put("B649", "LEPRIGNANO");
        this.put("B650", "CAPERGNANICA");
        this.put("B651", "CAPESTRANO");
        this.put("B652", "CAPIAGO");
        this.put("B653", "CAPIAGO INTIMIANO");
        this.put("B653", "SALVADERA");
        this.put("B654", "CAPIATE");
        this.put("B655", "CAPISTRANO");
        this.put("B655", "CAPISTRANO");
        this.put("B656", "CAPISTRELLO");
        this.put("B657", "CAPITELLO");
        this.put("B657", "CAPITELLO");
        this.put("B657", "POLICASTRO DEL GOLFO");
        this.put("B658", "CAPITIGNANO");
        this.put("B659", "CAPITONE");
        this.put("B660", "CAPIZZI");
        this.put("B661", "CAPIZZONE");
        this.put("B662", "CAPODIPONTE");
        this.put("B662", "PONTE NELLE ALPI");
        this.put("B663", "CAPODIMONTE");
        this.put("B664", "CAPO DI PONTE");
        this.put("B665", "CAPODISTRIA");
        this.put("B666", "CAPO D'ORLANDO");
        this.put("B667", "CAPODRISE");
        this.put("B668", "CAPOLAGO");
        this.put("B669", "CAPOLIVERI");
        this.put("B670", "CAPOLONA");
        this.put("B671", "CAPONAGO");
        this.put("B671", "CAPONAGO");
        this.put("B672", "CAPORCIANO");
        this.put("B673", "CAPORETTO");
        this.put("B674", "CAPOSELE");
        this.put("B675", "CAPOTERRA");
        this.put("B676", "CAPOVALLE");
        this.put("B676", "HANO");
        this.put("B677", "CAPPADOCIA");
        this.put("B678", "CAPPELLA");
        this.put("B678", "CAPPELLA MAGGIORE");
        this.put("B679", "CAPPELLA CANTONE");
        this.put("B679", "CAPPELLA CANTONE CON OSCASALE");
        this.put("B680", "CAPPELLA DE' PICENARDI");
        this.put("B681", "CAPPELLE");
        this.put("B681", "CAPPELLE SUL TAVO");
        this.put("B682", "CAPRACOTTA");
        this.put("B683", "CAPRADOSSO");
        this.put("B684", "CAPRAIA");
        this.put("B684", "CAPRAIA E LIMITE");
        this.put("B685", "CAPRAIA ISOLA");
        this.put("B686", "CAPRALBA");
        this.put("B686", "CAPRALBA CON FARINATE");
        this.put("B687", "CAPRANICA");
        this.put("B687", "CAPRANICA PRENESTINA");
        this.put("B688", "CAPRANICA");
        this.put("B689", "CAPRARA SOPRA PANICO");
        this.put("B689", "MARZABOTTO");
        this.put("B690", "CAPRARICA DI LECCE");
        this.put("B691", "CAPRAROLA");
        this.put("B692", "CAPRAUNA");
        this.put("B693", "CAPRESE");
        this.put("B693", "CAPRESE MICHELANGELO");
        this.put("B694", "CAPREZZO");
        this.put("B694", "CAPREZZO");
        this.put("B695", "CAPRI");
        this.put("B695", "CAPRI LEONE");
        this.put("B696", "CAPRI");
        this.put("B697", "CAPRIANA");
        this.put("B698", "CAPRIANO");
        this.put("B698", "CAPRIANO DEL COLLE");
        this.put("B699", "CAPRIANO");
        this.put("B699", "CAPRIANO DI BRIANZA");
        this.put("B700", "CAPRIANO-AZZANO");
        this.put("B700", "CAPRIANO-AZZANO");
        this.put("B701", "CAPRIATA");
        this.put("B701", "CAPRIATA D'ORBA");
        this.put("B702", "CAPRIATE");
        this.put("B702", "CAPRIATE D'ADDA");
        this.put("B703", "CAPRIATE SAN GERVASIO");
        this.put("B704", "CAPRIATI");
        this.put("B704", "CAPRIATI A VOLTURNO");
        this.put("B705", "CAPRIE");
        this.put("B705", "CHIAVRIE");
        this.put("B706", "CAPRIGLIA IRPINA");
        this.put("B707", "CAPRIGLIO");
        this.put("B708", "CAPRILE");
        this.put("B708", "CAPRILE");
        this.put("B709", "CAPRINO");
        this.put("B709", "CAPRINO VERONESE");
        this.put("B710", "CAPRINO BERGAMASCO");
        this.put("B711", "CAPRIOLO");
        this.put("B712", "CAPRIVA");
        this.put("B712", "CAPRIVA DEL FRIULI");
        this.put("B712", "CAPRIVA DI CORMONS");
        this.put("B713", "CAPRIVA DEL CARSO");
        this.put("B714", "CAPRONNO");
        this.put("B715", "CAPUA");
        this.put("B716", "CAPURSO");
        this.put("B717", "CARAFFA");
        this.put("B717", "CARAFFA DI CATANZARO");
        this.put("B718", "CARAFFA");
        this.put("B718", "CARAFFA DEL BIANCO");
        this.put("B719", "CARAGLIO");
        this.put("B720", "CARAMAGNA");
        this.put("B720", "CARAMAGNA PIEMONTE");
        this.put("B721", "CARAMAGNA");
        this.put("B721", "CARAMAGNA LIGURE");
        this.put("B722", "CARAMANICO");
        this.put("B722", "CARAMANICO TERME");
        this.put("B723", "CARANO");
        this.put("B724", "CARAPELLE");
        this.put("B725", "CARAPELLE");
        this.put("B725", "CARAPELLE CALVISIO");
        this.put("B726", "CARASCO");
        this.put("B727", "CARASSAI");
        this.put("B728", "CARATE");
        this.put("B728", "CARATE LARIO");
        this.put("B729", "CARATE");
        this.put("B729", "CARATE BRIANZA");
        this.put("B729", "CARATE BRIANZA");
        this.put("B730", "CARATE URIO");
        this.put("B731", "CARAVAGGIO");
        this.put("B732", "CARAVATE");
        this.put("B733", "CARAVINO");
        this.put("B733", "MASINO");
        this.put("B734", "CARAVONICA");
        this.put("B735", "CARBOGNANO");
        this.put("B736", "CARBONARA");
        this.put("B736", "CARBONARA SCRIVIA");
        this.put("B737", "CARBONARA");
        this.put("B737", "CARBONARA DI BARI");
        this.put("B738", "CARBONARA");
        this.put("B738", "VILLASIMIUS");
        this.put("B739", "CARBONARA");
        this.put("B739", "CARBONARA DI PO");
        this.put("B740", "CARBONARA");
        this.put("B740", "CARBONARA DI NOLA");
        this.put("B741", "CARBONARA");
        this.put("B741", "CARBONARA AL TICINO");
        this.put("B742", "CARBONATE");
        this.put("B743", "CARBONE");
        this.put("B744", "CARBONERA");
        this.put("B745", "CARBONIA");
        this.put("B745", "CARBONIA");
        this.put("B746", "CARCACI");
        this.put("B747", "CARCANO");
        this.put("B748", "CARCARE");
        this.put("B749", "CARCERI");
        this.put("B750", "CARCIATO");
        this.put("B751", "CARCINA");
        this.put("B752", "CARCOFORO");
        this.put("B753", "CARDANA");
        this.put("B754", "CARDANO");
        this.put("B754", "CARDANO AL CAMPO");
        this.put("B755", "CARDE'");
        this.put("B756", "CARDETO");
        this.put("B757", "CARDEZZA");
        this.put("B758", "CARDINALE");
        this.put("B759", "CARDITO");
        this.put("B760", "CAREGGINE");
        this.put("B761", "CARELLA CON MARIAGA");
        this.put("B762", "CAREMA");
        this.put("B763", "CARENNO");
        this.put("B763", "CARENNO");
        this.put("B764", "CARENO");
        this.put("B765", "CARENTINO");
        this.put("B765", "CARENTINO");
        this.put("B766", "CARERI");
        this.put("B767", "CARESANA");
        this.put("B768", "CARESANABLOT");
        this.put("B769", "CAREZZANO");
        this.put("B769", "CAREZZANO INFERIORE");
        this.put("B769", "CAREZZANO MAGGIORE");
        this.put("B770", "CAREZZANO SUPERIORE");
        this.put("B771", "CARFIZZI");
        this.put("B771", "CARFIZZI");
        this.put("B772", "CARGEGHE");
        this.put("B773", "CARGIAGO");
        this.put("B774", "CARIATI");
        this.put("B775", "CARIDA'");
        this.put("B776", "CARIFE");
        this.put("B777", "CARIGNANO");
        this.put("B778", "CARIMATE");
        this.put("B779", "CARINARO");
        this.put("B780", "CARINI");
        this.put("B781", "CARINOLA");
        this.put("B782", "CARISIO");
        this.put("B783", "CARISOLO");
        this.put("B784", "CARLANTINO");
        this.put("B785", "CARLAZZO");
        this.put("B786", "CARLAZZO VALSOLDA");
        this.put("B787", "CARLENTINI");
        this.put("B788", "CARLINO");
        this.put("B789", "CARLOFORTE");
        this.put("B789", "CARLOFORTE");
        this.put("B790", "CARLOPOLI");
        this.put("B791", "CARMAGNOLA");
        this.put("B792", "CARMIANO");
        this.put("B793", "CAMIGNA");
        this.put("B794", "CARMIGNANO");
        this.put("B794", "CARMIGNANO");
        this.put("B795", "CARMIGNANO");
        this.put("B795", "CARMIGNANO DI BRENTA");
        this.put("B796", "CARNAGO");
        this.put("B797", "CARNAIOLA");
        this.put("B798", "CARNATE");
        this.put("B798", "CARNATE");
        this.put("B799", "CARNEDO * KARNEID");
        this.put("B799", "CORNEDO * KARNEID");
        this.put("B799", "CORNEDO ALL'ISARCO * KARNEID");
        this.put("B800", "CAROBBIO");
        this.put("B801", "CAROBBIO DEGLI ANGELI");
        this.put("B802", "CAROLEI");
        this.put("B803", "CARONA");
        this.put("B804", "CARONIA");
        this.put("B805", "CARONNO");
        this.put("B805", "CARONNO MILANESE");
        this.put("B805", "CARONNO PERTUSELLA");
        this.put("B806", "CARONNO CORBELLARO");
        this.put("B807", "CARONNO GHIRINGHELLO");
        this.put("B807", "CARONNO VARESINO");
        this.put("B808", "CAROSINO");
        this.put("B809", "CAROVIGNO");
        this.put("B810", "CAROVILLI");
        this.put("B811", "CARPANETA CON DOSIMO");
        this.put("B812", "CARPANETO");
        this.put("B812", "CARPANETO PIACENTINO");
        this.put("B813", "CARPANZANO");
        this.put("B814", "CARPASIO");
        this.put("B815", "CARPE");
        this.put("B816", "CARPEGNA");
        this.put("B817", "CARPENEDOLO");
        this.put("B818", "CARPENETO");
        this.put("B819", "CARPI");
        this.put("B820", "CARPIANO");
        this.put("B821", "CARPIGNAGO");
        this.put("B822", "CARPIGNANO");
        this.put("B822", "CARPIGNANO SALENTINO");
        this.put("B823", "CARPIGNANO");
        this.put("B823", "CARPIGNANO SESIA");
        this.put("B824", "CARPIGNANO");
        this.put("B824", "CAVA CARPIGNANO");
        this.put("B824", "CURA CARPIGNANO");
        this.put("B825", "CARPINETI");
        this.put("B826", "CARPINETO");
        this.put("B826", "CARPINETO SINELLO");
        this.put("B827", "CARPINETO");
        this.put("B827", "CARPINETO DELLA NORA");
        this.put("B828", "CARPINETO");
        this.put("B828", "CARPINETO ROMANO");
        this.put("B829", "CARPINO");
        this.put("B830", "CARPINONE");
        this.put("B831", "CARPUGNINO");
        this.put("B832", "CARRARA");
        this.put("B833", "CARRARA SAN GIORGIO");
        this.put("B834", "CARRARA SANTO STEFANO");
        this.put("B835", "CARRE'");
        this.put("B836", "CARREGA LIGURE");
        this.put("B837", "CARRETTO");
        this.put("B838", "CARRO");
        this.put("B839", "CARRODANO");
        this.put("B840", "CARROSIO");
        this.put("B841", "CARRU'");
        this.put("B842", "CARSOLI");
        this.put("B843", "CARTARI E CALDERARA");
        this.put("B843", "CARTARI E CALDERARA");
        this.put("B843", "CARTARI E CALDERARA");
        this.put("B844", "CARTIGLIANO");
        this.put("B845", "CARTIGNANO");
        this.put("B846", "CARTOCETO");
        this.put("B847", "CARTOSIO");
        this.put("B848", "CARTURA");
        this.put("B849", "CARUBERTO");
        this.put("B850", "CARUGATE");
        this.put("B851", "CARUGO");
        this.put("B852", "CARUGO AROSIO");
        this.put("B852", "CARUGO AROSIO");
        this.put("B852", "CARUGO CON AROSIO");
        this.put("B853", "CARUNCHIO");
        this.put("B854", "CARVICO");
        this.put("B855", "CARZAGO");
        this.put("B855", "CARZAGO DELLA RIVIERA");
        this.put("B856", "CARZANO");
        this.put("B857", "CASABONA");
        this.put("B857", "CASABONA");
        this.put("B858", "CASACALENDA");
        this.put("B859", "CASACANDITELLA");
        this.put("B860", "CASAGIOVE");
        this.put("B860", "CASANOVA");
        this.put("B860", "CASANOVA E COCCAGNA");
        this.put("B861", "CASALANGUIDA");
        this.put("B862", "CASALATTICO");
        this.put("B863", "CASALBA");
        this.put("B863", "CASALBA");
        this.put("B864", "CASALBELTRAME");
        this.put("B865", "CASALBORDINO");
        this.put("B866", "CASALBORE");
        this.put("B867", "CASALBORGONE");
        this.put("B868", "CASALBUONO");
        this.put("B868", "CASALNUOVO");
        this.put("B869", "CASALBUTTANO");
        this.put("B869", "CASALBUTTANO ED UNITI");
        this.put("B870", "CASAL CERMELLI");
        this.put("B871", "CASALCIPRANO");
        this.put("B872", "CASAL DI PRINCIPE");
        this.put("B873", "CASALDUNI");
        this.put("B874", "CASALE");
        this.put("B874", "CASALE CREMASCO");
        this.put("B875", "CASALE");
        this.put("B875", "CASALE LITTA");
        this.put("B876", "CASALE");
        this.put("B876", "CASALE CORTE CERRO");
        this.put("B876", "CASALE CORTE CERRO");
        this.put("B877", "CASALE");
        this.put("B877", "CASALE DI SCODOSIA");
        this.put("B878", "CASALE");
        this.put("B878", "CASALE DI VAL DI CECINA");
        this.put("B878", "CASALE MARITTIMO");
        this.put("B879", "CASALE");
        this.put("B879", "CASALE SUL SILE");
        this.put("B880", "CASALECCHIO DI RENO");
        this.put("B881", "CASALE CREMASCO-VIDOLASCO");
        this.put("B882", "CASALEGGIO");
        this.put("B882", "CASALEGGIO BOIRO");
        this.put("B883", "CASALEGGIO");
        this.put("B883", "CASALEGGIO NOVARA");
        this.put("B884", "CASALEGGIO CASTELLAZZO");
        this.put("B884", "CASALEGGIO CASTELLAZZO");
        this.put("B885", "CASALE MONFERRATO");
        this.put("B886", "CASALEONE");
        this.put("B887", "CASALETTO LODIGIANO");
        this.put("B887", "CASALETTO");
        this.put("B887", "CASALETTO LODIGIANO");
        this.put("B888", "CASALETTO");
        this.put("B888", "CASALETTO SPARTANO");
        this.put("B889", "CASALETTO CEREDANO");
        this.put("B890", "CASALETTO DI SOPRA");
        this.put("B891", "CASALETTO VAPRIO");
        this.put("B892", "CASALFIUMANESE");
        this.put("B893", "CASALGRANDE");
        this.put("B894", "CASALGRASSO");
        this.put("B895", "CASALICCHIO");
        this.put("B895", "CASAL VELINO");
        this.put("B896", "CASALINCONTRADA");
        this.put("B897", "CASALINO");
        this.put("B898", "CASALMAGGIORE");
        this.put("B899", "CASALMAIOCCO");
        this.put("B899", "CASALMAIOCCO");
        this.put("B899", "COLOGNO");
        this.put("B900", "CASALMORANO");
        this.put("B901", "CASALMORO");
        this.put("B902", "CASALNOCETO");
        this.put("B903", "CASALNUOVO");
        this.put("B903", "VILLAPIANA");
        this.put("B904", "CASALNUOVO");
        this.put("B904", "CASALNUOVO MONTEROTARO");
        this.put("B905", "CASALNUOVO");
        this.put("B905", "CASALNUOVO DI NAPOLI");
        this.put("B906", "CASALNUOVO");
        this.put("B906", "CASALNUOVO LUCANO");
        this.put("B906", "SAN PAOLO ALBANESE");
        this.put("B907", "CASALOLDO");
        this.put("B908", "CASALORZO GEROLDI");
        this.put("B909", "CASALPOGLIO");
        this.put("B910", "CASALPUSTERLENGO");
        this.put("B910", "CASALPUSTERLENGO");
        this.put("B911", "CASALROMANO");
        this.put("B912", "CASAL SER UGO");
        this.put("B912", "CASALSERUGO");
        this.put("B913", "CASALSIGONE");
        this.put("B914", "CASALSIGONE ED UNITI");
        this.put("B914", "POZZAGLIO ED UNITI");
        this.put("B915", "CASALTRINITA");
        this.put("B915", "TRINITAPOLI");
        this.put("B915", "TRINITAPOLI");
        this.put("B916", "CASALUCE");
        this.put("B917", "CASALVECCHIO");
        this.put("B917", "CASALVECCHIO DI PUGLIA");
        this.put("B918", "CASALVECCHIO");
        this.put("B918", "CASALVECCHIO SICULO");
        this.put("B919", "CASALVIERI");
        this.put("B920", "CASALVOLONE");
        this.put("B921", "CASALZUIGNO");
        this.put("B922", "CASAMARCIANO");
        this.put("B923", "CASAMASSIMA");
        this.put("B924", "CASAMICCIOLA");
        this.put("B924", "CASAMICCIOLA TERME");
        this.put("B925", "CASANDRINO");
        this.put("B926", "CASANOVA");
        this.put("B926", "CASANOVA DI UGGIATE");
        this.put("B926", "CASANOVA LANZA");
        this.put("B927", "CASANOVA");
        this.put("B927", "CASANOVA LERRONE");
        this.put("B928", "CASANOVA");
        this.put("B928", "CASANOVA ELVO");
        this.put("B929", "CASANOVA LONATI");
        this.put("B930", "CA' SANTO SPIRITO DELLA BAINSIZZA");
        this.put("B931", "CASANUOVA OFFREDI");
        this.put("B932", "CASAPE");
        this.put("B933", "CASAPINTA");
        this.put("B933", "CASAPINTA");
        this.put("B934", "CASAPROTA");
        this.put("B935", "CASAPULLA");
        this.put("B936", "CASARANO");
        this.put("B937", "CASARGO");
        this.put("B937", "CASARGO");
        this.put("B938", "CASARILE");
        this.put("B938", "ZANAVASCO");
        this.put("B939", "CASARZA");
        this.put("B939", "CASARZA LIGURE");
        this.put("B940", "CASARSA DELLA DELIZIA");
        this.put("B940", "CASARSA");
        this.put("B941", "CASASCO");
        this.put("B942", "CASASCO");
        this.put("B942", "CASASCO D'INTELVI");
        this.put("B943", "CASATENOVO");
        this.put("B943", "CASATENOVO");
        this.put("B944", "CASATICO");
        this.put("B945", "CASATISMA");
        this.put("B946", "CASAVATORE");
        this.put("B947", "CASAZZA");
        this.put("B947", "MOLOGNO");
        this.put("B948", "CASCIA");
        this.put("B949", "CASCIAGO");
        this.put("B950", "CASCINA");
        this.put("B951", "CASCINE DI STRA");
        this.put("B952", "CASCINE SAN GIACOMO");
        this.put("B952", "SAN GIACOMO VERCELLESE");
        this.put("B953", "CASCINETTE D'IVREA");
        this.put("B954", "CASEI GEROLA");
        this.put("B955", "CASELETTE");
        this.put("B956", "CASELLA");
        this.put("B957", "CASELLE");
        this.put("B957", "CASELLE D'OZERO");
        this.put("B958", "CASELLE LURANI");
        this.put("B958", "CASELLE");
        this.put("B958", "CASELLE LURANI");
        this.put("B959", "CASELLE");
        this.put("B959", "CASELLE IN PITTARI");
        this.put("B960", "CASELLE");
        this.put("B960", "CASELLE TORINESE");
        this.put("B961", "CASELLE LANDI");
        this.put("B961", "CASELLE LANDI");
        this.put("B962", "CASELLINA E TORRI");
        this.put("B962", "SCANDICCI");
        this.put("B963", "CASERTA");
        this.put("B964", "CASEZ");
        this.put("B965", "CASIER");
        this.put("B966", "CASIGNANA");
        this.put("B967", "CASINA");
        this.put("B968", "CASINO");
        this.put("B968", "CASTELSILANO");
        this.put("B968", "CASTELSILANO");
        this.put("B969", "CASIO E CASOLA");
        this.put("B969", "CASTEL DI CASIO");
        this.put("B970", "CASIRAGO");
        this.put("B971", "CASIRATE");
        this.put("B971", "CASIRATE D'ADDA");
        this.put("B972", "CASIRATE");
        this.put("B972", "CASIRATE OLONA");
        this.put("B973", "CASLETTO");
        this.put("B974", "CASLINO");
        this.put("B974", "CASLINO D'ERBA");
        this.put("B974", "CASLINO PIANO D'ERBA");
        this.put("B975", "CASLINO");
        this.put("B975", "CASLINO AL PIANO");
        this.put("B976", "CASNATE");
        this.put("B977", "CASNATE CON BERNATE");
        this.put("B978", "CASNIGO");
        this.put("B979", "CASOLA");
        this.put("B979", "CASOLA IN LUNIGIANA");
        this.put("B980", "CASOLA");
        this.put("B980", "CASOLA DI NAPOLI");
        this.put("B981", "CASOLATE");
        this.put("B982", "CASOLA VALSENIO");
        this.put("B983", "CASOLE");
        this.put("B983", "CASOLE BRUZIO");
        this.put("B984", "CASOLE");
        this.put("B984", "CASOLE D'ELSA");
        this.put("B985", "CASOLI");
        this.put("B986", "CASONE");
        this.put("B986", "MENEDRAGO");
        this.put("B987", "CASORATE");
        this.put("B987", "CASORATE SEMPIONE");
        this.put("B988", "CASORATE");
        this.put("B988", "CASORATE PRIMO");
        this.put("B989", "CASOREZZO");
        this.put("B990", "CASORIA");
        this.put("B991", "CASORZO");
        this.put("B992", "CASOTTO");
        this.put("B993", "CASPOGGIO");
        this.put("B994", "CASSACCO");
        this.put("B995", "CASSAGO");
        this.put("B996", "CASSAGO BRIANZA");
        this.put("B996", "CASSAGO BRIANZA");
        this.put("B997", "CASSANO");
        this.put("B997", "CASSANO IRPINO");
        this.put("B998", "CASSANO");
        this.put("B998", "CASSANO DELLE MURGE");
        this.put("B999", "CASSANO");
        this.put("B999", "CASSANO VALCUVIA");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
