package document;

import java.util.HashMap;

/**
 * Created by Matteo on 12/11/2015.
 */
@SuppressWarnings("serial")
public class CitiesCodes_A extends HashMap<String, String> {

    public CitiesCodes_A(){
        this.put("A001", "ABANO BAGNI");
        this.put("A001", "ABANO TERME");
        this.put("A002", "ABBADIA");
        this.put("A002", "ABBADIA SOPRA ADDA");
        this.put("A003", "ABBADIA");
        this.put("A003", "ABBADIA ALPINA");
        this.put("A004", "ABBADIA CERRETO");
        this.put("A004", "ABBADIA CERRETO");
        this.put("A005", "ABBADIA LARIANA");
        this.put("A005", "ABBADIA LARIANA");
        this.put("A006", "ABBADIA SAN SALVATORE");
        this.put("A007", "ABBASANTA");
        this.put("A007", "ABBASANTA");
        this.put("A008", "ABBATEGGIO");
        this.put("A009", "ABBAZIA");
        this.put("A010", "ABBIATEGRASSO");
        this.put("A011", "ABBIATEGUAZZONE");
        this.put("A012", "ABETONE");
        this.put("A013", "ABRIOLA");
        this.put("A014", "ACATE");
        this.put("A014", "BISCARI");
        this.put("A015", "ACCADIA");
        this.put("A016", "ACCEGLIO");
        this.put("A017", "ACCETTURA");
        this.put("A018", "ACCIANO");
        this.put("A019", "ACCUMOLI");
        this.put("A020", "ACERENZA");
        this.put("A021", "ACERETO * AHORNACH");
        this.put("A022", "ACERNES * TSCHERMS");
        this.put("A022", "CERMES * TSCHERMS");
        this.put("A023", "ACERNO");
        this.put("A024", "ACERRA");
        this.put("A025", "ACI BONACCORSI");
        this.put("A026", "ACI CASTELLO");
        this.put("A027", "ACI CATENA");
        this.put("A028", "ACIREALE");
        this.put("A029", "ACI SANT'ANTONIO");
        this.put("A030", "ACQUA");
        this.put("A031", "ACQUACANINA");
        this.put("A032", "ACQUAFONDATA");
        this.put("A033", "ACQUAFORMOSA");
        this.put("A034", "ACQUAFREDDA");
        this.put("A035", "ACQUALAGNA");
        this.put("A036", "ACQUALUNGA");
        this.put("A037", "ACQUALUNGA BADONA");
        this.put("A038", "ACQUANEGRA");
        this.put("A038", "ACQUANEGRA SUL CHIESE");
        this.put("A039", "ACQUANEGRA");
        this.put("A039", "ACQUANEGRA CREMONESE");
        this.put("A040", "ACQUAPENDENTE");
        this.put("A041", "ACQUAPPESA");
        this.put("A042", "ACQUARICA DEL CAPO");
        this.put("A043", "ACQUARO");
        this.put("A043", "ACQUARO");
        this.put("A044", "ACQUASANTA");
        this.put("A044", "ACQUASANTA TERME");
        this.put("A045", "ACQUASPARTA");
        this.put("A046", "ACQUATE");
        this.put("A047", "ACQUAVIVA");
        this.put("A047", "ACQUAVIVA PICENA");
        this.put("A048", "ACQUAVIVA");
        this.put("A048", "ACQUAVIVA DELLE FONTI");
        this.put("A049", "ACQUAVIVA");
        this.put("A049", "ACQUAVIVA PLATANI");
        this.put("A050", "ACQUAVIVA COLLECROCE");
        this.put("A051", "ACQUAVIVA D'ISERNIA");
        this.put("A052", "ACQUI");
        this.put("A052", "ACQUI TERME");
        this.put("A053", "ACRI");
        this.put("A054", "ACUTO");
        this.put("A055", "ADELFIA");
        this.put("A056", "ADERNO");
        this.put("A056", "ADRANO");
        this.put("A057", "ADRARA SAN MARTINO");
        this.put("A058", "ADRARA SAN ROCCO");
        this.put("A059", "ADRIA");
        this.put("A060", "ADRO");
        this.put("A061", "AFFI");
        this.put("A062", "AFFILE");
        this.put("A063", "AFFORI");
        this.put("A064", "AFRAGOLA");
        this.put("A065", "AFRICO");
        this.put("A066", "AGARO");
        this.put("A067", "AGAZZANO");
        this.put("A068", "AGEROLA");
        this.put("A069", "AGGIUS");
        this.put("A069", "AGGIUS");
        this.put("A070", "AGIRA");
        this.put("A071", "AGLIANA");
        this.put("A072", "AGLIANO");
        this.put("A072", "AGLIANO TERME");
        this.put("A073", "AGLIATE");
        this.put("A074", "AGLIE'");
        this.put("A075", "AGNA");
        this.put("A076", "AGNADELLO");
        this.put("A077", "AGNANA CALABRA");
        this.put("A078", "AGNELLENGO");
        this.put("A079", "AGNONA");
        this.put("A080", "AGNONE");
        this.put("A081", "AGNONE");
        this.put("A081", "VILLA LATINA");
        this.put("A082", "AGNOSINE");
        this.put("A083", "AGORDO");
        this.put("A084", "AGOSTA");
        this.put("A085", "AGRA");
        this.put("A086", "AGRANO");
        this.put("A087", "AGRATE");
        this.put("A087", "AGRATE BRIANZA");
        this.put("A087", "AGRATE BRIANZA");
        this.put("A088", "AGRATE");
        this.put("A088", "AGRATE CONTURBIA");
        this.put("A089", "AGRIGENTO");
        this.put("A089", "GIRGENTI");
        this.put("A090", "AGRONE");
        this.put("A091", "AGROPOLI");
        this.put("A092", "AGUGLIANO");
        this.put("A093", "AGUGLIARO");
        this.put("A094", "AIAS");
        this.put("A094", "AYAS");
        this.put("A095", "AIBA");
        this.put("A096", "AICURZIO");
        this.put("A096", "AICURZIO");
        this.put("A097", "AIDOMAGGIORE");
        this.put("A097", "AIDOMAGGIORE");
        this.put("A098", "AIDONE");
        this.put("A099", "AIDUSSINA");
        this.put("A100", "AIELLI");
        this.put("A101", "AIELLO");
        this.put("A101", "AIELLO DEL SABATO");
        this.put("A102", "AIELLO CALABRO");
        this.put("A103", "AIELLO DEL FRIULI");
        this.put("A104", "AIELLO IN CALABRIA");
        this.put("A105", "AIETA");
        this.put("A106", "AILANO");
        this.put("A107", "AILOCHE");
        this.put("A107", "AILOCHE");
        this.put("A108", "AIMAVILLA");
        this.put("A108", "AYMAVILLES");
        this.put("A109", "AIRASCA");
        this.put("A110", "AIROLA");
        this.put("A111", "AIROLE");
        this.put("A112", "AIRUNO");
        this.put("A112", "AIRUNO");
        this.put("A113", "AISONE");
        this.put("A114", "AIZURRO");
        this.put("A115", "ALA' DEI SARDI");
        this.put("A115", "ALA' DEI SARDI");
        this.put("A115", "ALA");
        this.put("A116", "ALA");
        this.put("A117", "ALA DI STURA");
        this.put("A118", "ALAGNA");
        this.put("A119", "ALAGNA");
        this.put("A119", "ALAGNA VALSESIA");
        this.put("A120", "ALANNO");
        this.put("A121", "ALANO");
        this.put("A121", "ALANO DI PIAVE");
        this.put("A122", "ALASSIO");
        this.put("A123", "ALATRI");
        this.put("A124", "ALBA");
        this.put("A125", "ALBA ADRIATICA");
        this.put("A126", "ALBAGIARA");
        this.put("A126", "OLLASTA");
        this.put("A126", "OLLASTRA USELLUS");
        this.put("A126", "ALBAGIARA");
        this.put("A127", "ALBAIRATE");
        this.put("A128", "ALBANELLA");
        this.put("A129", "ALBANO");
        this.put("A129", "ALBANO SANT'ALESSANDRO");
        this.put("A130", "ALBANO");
        this.put("A130", "ALBANO VERCELLESE");
        this.put("A131", "ALBANO");
        this.put("A131", "ALBANO DI LUCANIA");
        this.put("A132", "ALBANO");
        this.put("A132", "ALBANO LAZIALE");
        this.put("A133", "ALBANOVA");
        this.put("A133", "ALBANOVA");
        this.put("A134", "ALBAREDO");
        this.put("A134", "ALBAREDO ARNABOLDI");
        this.put("A135", "ALBAREDO");
        this.put("A135", "ALBAREDO PER SAN MARCO");
        this.put("A136", "ALBAREDO");
        this.put("A136", "SANT'ANDREA DI CAVASAGRA");
        this.put("A137", "ALBAREDO");
        this.put("A137", "ALBAREDO D'ADIGE");
        this.put("A138", "ALBARETO");
        this.put("A138", "ALBARETO DI BORGOTARO");
        this.put("A139", "ALBARETTO");
        this.put("A139", "ALBARETTO DELLA TORRE");
        this.put("A140", "ALBARETTO");
        this.put("A140", "ALBARETTO VALLE DI MACRA");
        this.put("A141", "ALBARO VESCOVA");
        this.put("A142", "ALBATE");
        this.put("A143", "ALBAVILLA");
        this.put("A144", "ALBEGNO");
        this.put("A145", "ALBENGA");
        this.put("A146", "ALBERA");
        this.put("A146", "ALBERA LIGURE");
        this.put("A147", "ALBERA");
        this.put("A147", "TRIBURGO");
        this.put("A148", "ALBER DI SESANA");
        this.put("A149", "ALBEROBELLO");
        this.put("A150", "ALBERONA");
        this.put("A151", "ALBES * ALBEINS");
        this.put("A152", "ALBESE");
        this.put("A153", "ALBESE CON CASSANO");
        this.put("A154", "ALBETTONE");
        this.put("A155", "ALBI");
        this.put("A156", "ALBIANO");
        this.put("A156", "ALBIANO MAGRA");
        this.put("A156", "ALBIANO MAGRA");
        this.put("A157", "ALBIANO");
        this.put("A157", "ALBIANO D'IVREA");
        this.put("A158", "ALBIANO");
        this.put("A159", "ALBIATE");
        this.put("A159", "ALBIATE");
        this.put("A160", "ALBIDONA");
        this.put("A161", "ALBIGNASEGO");
        this.put("A162", "ALBINEA");
        this.put("A163", "ALBINO");
        this.put("A164", "ALBIOLO");
        this.put("A165", "ALBISSOLA MARINA");
        this.put("A166", "ALBISOLA SUPERIORE");
        this.put("A167", "ALBIZZATE");
        this.put("A168", "ALBOGASIO");
        this.put("A169", "ALBOGNO");
        this.put("A170", "ALBONA");
        this.put("A171", "ALBONESE");
        this.put("A172", "ALBOSAGGIA");
        this.put("A173", "ALBUGNANO");
        this.put("A174", "ALBUSCIAGO");
        this.put("A175", "ALBUZZANO");
        this.put("A176", "ALCAMO");
        this.put("A177", "ALCARA LI FUSI");
        this.put("A178", "ALDENO");
        this.put("A179", "ALDINO * ALDEIN");
        this.put("A179", "VALDAGNO * ALDEIN");
        this.put("A179", "VALDAGNO DI TRENTO * ALDEIN");
        this.put("A180", "ALES");
        this.put("A180", "ALES");
        this.put("A181", "ALESSANDRIA");
        this.put("A181", "ALESSANDRIA DELLA ROCCA");
        this.put("A182", "ALESSANDRIA");
        this.put("A183", "ALESSANDRIA");
        this.put("A183", "ALESSANDRIA DEL CARRETTO");
        this.put("A184", "ALESSANO");
        this.put("A185", "ALEZIO");
        this.put("A185", "VILLAPICCIOTTI");
        this.put("A186", "ALFANO");
        this.put("A187", "ALFEDENA");
        this.put("A188", "ALFIANELLO");
        this.put("A189", "ALFIANO");
        this.put("A189", "ALFIANO NATTA");
        this.put("A190", "ALFIANO");
        this.put("A190", "ALFIANO ED UNITI");
        this.put("A191", "ALFONSINE");
        this.put("A192", "ALGHERO");
        this.put("A193", "ALGUA");
        this.put("A193", "ALGUA DI COSTA SERINA");
        this.put("A194", "ALI'");
        this.put("A194", "ALI' SUPERIORE");
        this.put("A195", "ALIA");
        this.put("A196", "ALIANO");
        this.put("A197", "ALICE");
        this.put("A197", "ALICE BEL COLLE");
        this.put("A198", "ALICE");
        this.put("A198", "ALICE CASTELLO");
        this.put("A199", "ALICE SUPERIORE");
        this.put("A200", "ALIFE");
        this.put("A201", "ALI' MARINA");
        this.put("A201", "ALI' TERME");
        this.put("A202", "ALIMENA");
        this.put("A203", "ALIMINUSA");
        this.put("A204", "ALLAI");
        this.put("A204", "ALLAI");
        this.put("A205", "ALLAIN");
        this.put("A205", "ALLEIN");
        this.put("A205", "ALLENO");
        this.put("A206", "ALLEGHE");
        this.put("A207", "ALLERONA");
        this.put("A208", "ALLISTE");
        this.put("A209", "ALLIZ * ALLITZ");
        this.put("A210", "ALLUMIERE");
        this.put("A211", "ALLUVIONI CAMBIO'");
        this.put("A212", "ALMA");
        this.put("A213", "ALMAZZAGO");
        this.put("A214", "ALME'");
        this.put("A214", "ALME'");
        this.put("A215", "VILLA D'ALME'");
        this.put("A215", "VILLA D'ALME'");
        this.put("A216", "ALMENNO SAN BARTOLOMEO");
        this.put("A217", "ALMENNO SAN SALVATORE");
        this.put("A218", "ALMESE");
        this.put("A219", "ALONE");
        this.put("A220", "ALONTE");
        this.put("A221", "ALPETTE");
        this.put("A222", "ALPIGNANO");
        this.put("A223", "ALSENO");
        this.put("A224", "ALSERIO");
        this.put("A225", "ALTAMURA");
        this.put("A226", "ALTARE");
        this.put("A227", "ALTAVILLA");
        this.put("A227", "ALTAVILLA MONFERRATO");
        this.put("A228", "ALTAVILLA");
        this.put("A228", "ALTAVILLA IRPINA");
        this.put("A229", "ALTAVILLA");
        this.put("A229", "ALTAVILLA MILICIA");
        this.put("A230", "ALTAVILLA");
        this.put("A230", "ALTAVILLA SILENTINA");
        this.put("A231", "ALTAVILLA");
        this.put("A231", "ALTAVILLA VICENTINA");
        this.put("A232", "ALTETA");
        this.put("A233", "ALTIDONA");
        this.put("A233", "ALTIDONA");
        this.put("A234", "ALTILIA");
        this.put("A235", "ALTINO");
        this.put("A236", "ALTISSIMO");
        this.put("A237", "ALTIVOLE");
        this.put("A238", "ALTO");
        this.put("A239", "ALTOFONTE");
        this.put("A239", "PARCO");
        this.put("A240", "ALTOMONTE");
        this.put("A241", "ALTOPASCIO");
        this.put("A242", "ALVIANO");
        this.put("A243", "ALVIGNANO");
        this.put("A244", "ALVITO");
        this.put("A245", "ALZANO");
        this.put("A245", "ALZANO SCRIVIA");
        this.put("A245", "ALZANO SCRIVIA");
        this.put("A246", "ALZANO LOMBARDO");
        this.put("A247", "ALZANO MAGGIORE");
        this.put("A248", "ALZANO SOPRA");
        this.put("A249", "ALZATE");
        this.put("A249", "ALZATE BRIANZA");
        this.put("A249", "ALZATE CON VERZAGO");
        this.put("A250", "ALZATE");
        this.put("A250", "ALZATE CON LINDUNO");
        this.put("A251", "AMALFI");
        this.put("A252", "AMANDOLA");
        this.put("A252", "AMANDOLA");
        this.put("A253", "AMANTEA");
        this.put("A254", "AMARO");
        this.put("A255", "AMARONI");
        this.put("A256", "AMASENO");
        this.put("A256", "SAN LORENZO");
        this.put("A257", "AMATO");
        this.put("A258", "AMATRICE");
        this.put("A259", "AMBIVERE");
        this.put("A260", "AMBLAR");
        this.put("A261", "AMEGLIA");
        this.put("A262", "AMELIA");
        this.put("A263", "AMENDOLARA");
        this.put("A264", "AMENO");
        this.put("A265", "AMOROSI");
        this.put("A266", "AMPEZZO");
        this.put("A266", "CORTINA D'AMPEZZO");
        this.put("A267", "AMPEZZO");
        this.put("A268", "ANACAPRI");
        this.put("A269", "ANAGNI");
        this.put("A270", "ANCARANO");
        this.put("A271", "ANCONA");
        this.put("A272", "ANDALI");
        this.put("A273", "ANDALO");
        this.put("A273", "ANDALO VALTELLINO");
        this.put("A274", "ANDALO");
        this.put("A275", "ANDEZENO");
        this.put("A276", "ANDOGNO");
        this.put("A277", "ANDONNO");
        this.put("A278", "ANDORA");
        this.put("A279", "ANDORNO CACCIORNA");
        this.put("A280", "ANDORNO MICCA");
        this.put("A280", "ANDORNO MICCA");
        this.put("A281", "ANDRANO");
        this.put("A282", "ANDRATE");
        this.put("A283", "ANDREIS");
        this.put("A284", "ANDRETTA");
        this.put("A285", "ANDRIA");
        this.put("A285", "ANDRIA");
        this.put("A286", "ANDRIANO * ANDRIAN");
        this.put("A287", "ANELA");
        this.put("A288", "ANFO");
        this.put("A289", "ANFURRO");
        this.put("A290", "ANGERA");
        this.put("A291", "ANGHIARI");
        this.put("A292", "ANGIARI");
        this.put("A293", "ANGOLO");
        this.put("A293", "ANGOLO TERME");
        this.put("A294", "ANGRI");
        this.put("A295", "ANGROGNA");
        this.put("A296", "ANGUILLARA");
        this.put("A296", "ANGUILLARA VENETA");
        this.put("A297", "ANGUILLARA");
        this.put("A297", "ANGUILLARA SABAZIA");
        this.put("A298", "ANICOVA CORADA");
        this.put("A299", "ANNICCO");
        this.put("A300", "ANNONE");
        this.put("A300", "CASTELLO DI ANNONE");
        this.put("A301", "ANNONE");
        this.put("A301", "ANNONE DI BRIANZA");
        this.put("A301", "ANNONE DI BRIANZA");
        this.put("A302", "ANNONE");
        this.put("A302", "ANNONE VENETO");
        this.put("A303", "ANOIA");
        this.put("A304", "ANTEGNATE");
        this.put("A305", "ANTEI SANT'ANDREA");
        this.put("A305", "ANTEY-SAINT-ANDRE'");
        this.put("A306", "ANTERIVO * ALTREI");
        this.put("A307", "ANTERSELVA * ANTHOLZ");
        this.put("A308", "LA MADDALENA D'AOSTA");
        this.put("A308", "LA MAGDELEINE");
        this.put("A308", "ANTEY LA MAGDELEINE");
        this.put("A309", "ANTICOLI");
        this.put("A309", "ANTICOLI CORRADO");
        this.put("A310", "ANTICOLI DI CAMPAGNA");
        this.put("A310", "FIUGGI");
        this.put("A311", "ANTIGNANA");
        this.put("A312", "ANTIGNANO");
        this.put("A313", "ANTILLO");
        this.put("A314", "ANTONIMINA");
        this.put("A315", "ANTRODOCO");
        this.put("A316", "ANTRONAPIANA");
        this.put("A317", "ANTRONA SCHIERANCO");
        this.put("A317", "ANTRONA SCHIERANCO");
        this.put("A318", "ANVERSA");
        this.put("A318", "ANVERSA DEGLI ABRUZZI");
        this.put("A319", "ANZANO");
        this.put("A319", "ANZANO DEL PARCO");
        this.put("A320", "ANZANO");
        this.put("A320", "ANZANO DEGLI IRPINI");
        this.put("A320", "ANZANO DI PUGLIA");
        this.put("A321", "ANZI");
        this.put("A322", "ANZINO");
        this.put("A323", "ANZIO");
        this.put("A324", "ANZOLA");
        this.put("A324", "ANZOLA DELL'EMILIA");
        this.put("A325", "ANZOLA");
        this.put("A325", "ANZOLA D'OSSOLA");
        this.put("A325", "ANZOLA D'OSSOLA");
        this.put("A326", "AOSTA");
        this.put("A327", "APECCHIO");
        this.put("A328", "APICE");
        this.put("A329", "APIRO");
        this.put("A330", "APOLLOSA");
        this.put("A331", "APPARIZIONE");
        this.put("A332", "APPIANO * EPPAN");
        this.put("A332", "APPIANO SULLA STRADA DEL VINO * EPPAN AN DER WEINSTRASSE");
        this.put("A333", "APPIANO");
        this.put("A333", "APPIANO GENTILE");
        this.put("A334", "APPIGNANO");
        this.put("A335", "APPIGNANO DEL TRONTO");
        this.put("A335", "APPIGNANO DI OFFIDA");
        this.put("A336", "APRIANO");
        this.put("A337", "APRICA");
        this.put("A338", "APRICALE");
        this.put("A339", "APRICENA");
        this.put("A340", "APRIGLIANO");
        this.put("A341", "APRILIA");
        this.put("A342", "APUANIA");
        this.put("A342", "APUANIA");
        this.put("A342", "APUANIA");
        this.put("A343", "AQUARA");
        this.put("A344", "AQUILA");
        this.put("A344", "AQUILA D'ARROSCIA");
        this.put("A345", "AQUILA");
        this.put("A345", "AQUILA DEGLI ABRUZZI");
        this.put("A345", "L'AQUILA");
        this.put("A346", "AQUILEIA");
        this.put("A347", "AQUILONIA");
        this.put("A347", "CARBONARA");
        this.put("A348", "AQUINO");
        this.put("A349", "ARA");
        this.put("A350", "ARADEO");
        this.put("A351", "ARAGONA");
        this.put("A352", "ARAMENGO");
        this.put("A353", "ARANCO");
        this.put("A354", "ARBA");
        this.put("A355", "ARBATAX DI TORTOLI");
        this.put("A355", "TORTOLI'");
        this.put("A355", "TORTOLI'");
        this.put("A356", "ARBIZZO");
        this.put("A357", "ARBOREA");
        this.put("A357", "MUSSOLINIA");
        this.put("A357", "ARBOREA");
        this.put("A358", "ARBORIO");
        this.put("A359", "ARBUS");
        this.put("A359", "ARBUS");
        this.put("A360", "ARCADE");
        this.put("A361", "ARCAGNA");
        this.put("A362", "ARCAGNANO");
        this.put("A363", "ARCE");
        this.put("A364", "ARCELLASCO");
        this.put("A365", "ARCENE");
        this.put("A366", "ARCEVIA");
        this.put("A367", "ARCHI");
        this.put("A368", "ARCIDANO");
        this.put("A368", "SAN NICOLO' D'ARCIDANO");
        this.put("A368", "SAN NICOLO' D'ARCIDANO");
        this.put("A369", "ARCIDOSSO");
        this.put("A370", "ARCINAZZO ROMANO");
        this.put("A370", "PONZA");
        this.put("A370", "PONZA D'ARCINAZZO");
        this.put("A371", "ARCISATE");
        this.put("A372", "ARCO");
        this.put("A373", "ARCOLA");
        this.put("A374", "ARCOLE");
        this.put("A375", "ARCONATE");
        this.put("A376", "ARCORE");
        this.put("A376", "ARCORE");
        this.put("A377", "ARCUGNANO");
        this.put("A378", "ARCUMEGGIA");
        this.put("A379", "ARDARA");
        this.put("A380", "ARDAULI");
        this.put("A380", "ARDAULI");
        this.put("A381", "ARDENA");
        this.put("A382", "ARDENNO");
        this.put("A383", "ARDESIO");
        this.put("A384", "ARDOLE SAN MARINO");
        this.put("A385", "ARDORE");
        this.put("A386", "ARENA");
        this.put("A386", "ARENA");
        this.put("A387", "ARENA");
        this.put("A387", "ARENA PO");
        this.put("A388", "ARENZANO");
        this.put("A389", "ARESE");
        this.put("A390", "AREZZO");
        this.put("A391", "ARGEGNO");
        this.put("A392", "ARGELATO");
        this.put("A393", "ARGENTA");
        this.put("A394", "ARGENTERA");
        this.put("A395", "ARGINE");
        this.put("A395", "ARGINE PO");
        this.put("A395", "BRESSANA");
        this.put("A396", "ARGUELLO");
        this.put("A397", "ARGUSTO");
        this.put("A398", "ARI");
        this.put("A399", "ARIANO");
        this.put("A399", "ARIANO DI PUGLIA");
        this.put("A399", "ARIANO IRPINO");
        this.put("A400", "ARIANO");
        this.put("A400", "ARIANO NEL POLESINE");
        this.put("A401", "ARICCIA");
        this.put("A402", "ARIELLI");
        this.put("A403", "ARIENZO");
        this.put("A404", "ARIENZO SANFELICE");
        this.put("A404", "ARIENZO SANFELICE");
        this.put("A405", "ARIGNANO");
        this.put("A406", "ARISCHIA");
        this.put("A407", "ARITZO");
        this.put("A408", "ARIXI");
        this.put("A409", "ARIZZANO");
        this.put("A409", "ARIZZANO");
        this.put("A410", "ARIZZANO INFERIORE");
        this.put("A411", "ARIZZANO SUPERIORE");
        this.put("A412", "ARLENA");
        this.put("A412", "ARLENA DI CASTRO");
        this.put("A413", "ARLUNO");
        this.put("A414", "ARMENO");
        this.put("A415", "ARMENTO");
        this.put("A416", "ARMIO");
        this.put("A417", "ARMO");
        this.put("A418", "ARMO");
        this.put("A419", "ARMUNGIA");
        this.put("A420", "ARNAGO");
        this.put("A421", "ARNARA");
        this.put("A422", "ARNASCO");
        this.put("A423", "ARNATE");
        this.put("A424", "ARNAD");
        this.put("A424", "ARNAZ");
        this.put("A425", "ARNESANO");
        this.put("A426", "ARNO");
        this.put("A426", "BONDO BREGUZZO");
        this.put("A426", "BONDO BREGUZZO");
        this.put("A427", "AROLA");
        this.put("A427", "AROLA");
        this.put("A428", "AROLO");
        this.put("A429", "ARONA");
        this.put("A430", "AROSIO");
        this.put("A431", "ARPAIA");
        this.put("A432", "ARPAISE");
        this.put("A433", "ARPINO");
        this.put("A434", "ARQUA'");
        this.put("A434", "ARQUA' PETRARCA");
        this.put("A435", "ARQUA'");
        this.put("A435", "ARQUA' POLESINE");
        this.put("A436", "ARQUATA");
        this.put("A436", "ARQUATA SCRIVIA");
        this.put("A437", "ARQUATA");
        this.put("A437", "ARQUATA DEL TRONTO");
        this.put("A438", "ARRE");
        this.put("A439", "ARRONE");
        this.put("A440", "ARSAGO");
        this.put("A440", "ARZAGO D'ADDA");
        this.put("A441", "ARSAGO");
        this.put("A441", "ARSAGO SEPRIO");
        this.put("A442", "ARSIA");
        this.put("A443", "ARSIE'");
        this.put("A444", "ARSIERO");
        this.put("A445", "ARSITA");
        this.put("A445", "BACUCCO");
        this.put("A446", "ARSOLI");
        this.put("A447", "ARTA");
        this.put("A447", "ARTA TERME");
        this.put("A448", "ARTEGNA");
        this.put("A449", "ARTENA");
        this.put("A449", "MONFORTINO");
        this.put("A449", "MONTEFORTINO");
        this.put("A450", "ARTO");
        this.put("A451", "ARTOGNE");
        this.put("A452", "ARVIE");
        this.put("A452", "ARVIER");
        this.put("A453", "ARZACHENA");
        this.put("A453", "ARZACHENA");
        this.put("A454", "ARZANA");
        this.put("A454", "ARZANA");
        this.put("A455", "ARZANO");
        this.put("A456", "ARZENE");
        this.put("A457", "ARZENO D'ONEGLIA");
        this.put("A457", "ARZENO D'ONEGLIA");
        this.put("A457", "SAN BARTOLOMEO ED ARZENO");
        this.put("A458", "ARZERGRANDE");
        this.put("A459", "ARZIGNANO");
        this.put("A460", "ASCEA");
        this.put("A461", "ASCIANO");
        this.put("A462", "ASCOLI");
        this.put("A462", "ASCOLI PICENO");
        this.put("A463", "ASCOLI");
        this.put("A463", "ASCOLI SATRIANO");
        this.put("A464", "ASCREA");
        this.put("A465", "ASIAGO");
        this.put("A466", "ASIGLIANO");
        this.put("A466", "ASIGLIANO VERCELLESE");
        this.put("A467", "ASIGLIANO");
        this.put("A467", "ASIGLIANO VENETO");
        this.put("A468", "ASINALUNGA");
        this.put("A468", "SINALUNGA");
        this.put("A469", "ASNAGO");
        this.put("A469", "ASNAGO");
        this.put("A470", "ASOLA");
        this.put("A471", "ASOLO");
        this.put("A472", "ASPRA");
        this.put("A472", "ASPRA SABINA");
        this.put("A472", "CASPERIA");
        this.put("A473", "ASSAGO");
        this.put("A474", "ASSEMINI");
        this.put("A475", "ASSISI");
        this.put("A476", "ASSO");
        this.put("A477", "ASSOLO");
        this.put("A477", "ASSOLO NURECI");
        this.put("A477", "ASSOLO");
        this.put("A478", "ASSORO");
        this.put("A479", "ASTI");
        this.put("A480", "ASUNI");
        this.put("A480", "ASUNI");
        this.put("A481", "ATELETA");
        this.put("A482", "ATELLA");
        this.put("A483", "ATELLA DI NAPOLI");
        this.put("A483", "ATELLA DI NAPOLI");
        this.put("A483", "ATELLA DI NAPOLI");
        this.put("A484", "ATENA");
        this.put("A484", "ATENA LUCANA");
        this.put("A485", "ATESSA");
        this.put("A486", "ATINA");
        this.put("A487", "ATRANI");
        this.put("A487", "ATRANI");
        this.put("A488", "ATRI");
        this.put("A489", "ATRIPALDA");
        this.put("A490", "ATTIGLIANO");
        this.put("A491", "ATTIMIS");
        this.put("A492", "ATZARA");
        this.put("A493", "AUDITORE");
        this.put("A494", "AUGUSTA");
        this.put("A495", "AULETTA");
        this.put("A496", "AULLA");
        this.put("A497", "AURANO");
        this.put("A497", "AURANO");
        this.put("A498", "AUREMO DI SOPRA");
        this.put("A499", "AURIGO");
        this.put("A500", "AURISINA");
        this.put("A500", "NABRESINA");
        this.put("A501", "AURONZO");
        this.put("A501", "AURONZO DI CADORE");
        this.put("A502", "AUSONIA");
        this.put("A502", "FRATTE");
        this.put("A503", "AUSTIS");
        this.put("A504", "AUZATE");
        this.put("A505", "AUZZA");
        this.put("A506", "AVEGNO");
        this.put("A507", "AVELENGO * HAFLING");
        this.put("A507", "AVELIGNA * HAFLING");
        this.put("A508", "AVELLA");
        this.put("A509", "AVELLINO");
        this.put("A510", "AVENONE");
        this.put("A511", "AVERARA");
        this.put("A512", "AVERSA");
        this.put("A513", "AVESA");
        this.put("A514", "AVETRANA");
        this.put("A515", "AVEZZANO");
        this.put("A516", "AVIANO");
        this.put("A517", "AVIATICO");
        this.put("A518", "AVIGLIANA");
        this.put("A519", "AVIGLIANO");
        this.put("A520", "AVIO");
        this.put("A521", "AVISE");
        this.put("A522", "AVOLA");
        this.put("A523", "AVOLASCA");
        this.put("A524", "AVUGLIONE E VERNONE");
        this.put("A525", "AZEGLIO");
        this.put("A526", "AZZANELLO");
        this.put("A527", "AZZANO");
        this.put("A527", "AZZANO DEL TANARO");
        this.put("A527", "AZZANO D'ASTI");
        this.put("A528", "AZZANO");
        this.put("A528", "AZZANO SAN PAOLO");
        this.put("A529", "AZZANO");
        this.put("A529", "AZZANO MELLA");
        this.put("A530", "AZZANO DECIMO");
        this.put("A530", "AZZANO");
        this.put("A531", "AZZATE");
        this.put("A532", "AZZIO");
        this.put("A533", "AZZONE");
        this.put("A534", "BACENO");
        this.put("A534", "BACENO");
        this.put("A535", "BACOLI");
        this.put("A536", "BADALUCCO");
        this.put("A537", "BADIA * ABTEI");
        this.put("A538", "BADIA");
        this.put("A538", "BADIA PAVESE");
        this.put("A539", "BADIA");
        this.put("A539", "BADIA POLESINE");
        this.put("A540", "BADIA CALAVENA");
        this.put("A541", "BADIA TEDALDA");
        this.put("A542", "BADOLATO");
        this.put("A543", "BAGAGGERA");
        this.put("A544", "BAGALADI");
        this.put("A545", "BAGGIO");
        this.put("A546", "BAGHERIA");
        this.put("A547", "BAGNACAVALLO");
        this.put("A548", "BAGNAIA");
        this.put("A549", "BAGNARA");
        this.put("A549", "BAGNARA DI BENEVENTO");
        this.put("A550", "BAGNARA");
        this.put("A550", "BAGNARIA");
        this.put("A550", "BAGNARIA");
        this.put("A551", "BAGNARA");
        this.put("A551", "BAGNARA DI ROMAGNA");
        this.put("A552", "BAGNARA");
        this.put("A552", "BAGNARA CALABRA");
        this.put("A553", "BAGNARIA");
        this.put("A553", "BAGNARIA ARSA");
        this.put("A554", "BAGNAROLO");
        this.put("A555", "BAGNASCO");
        this.put("A556", "BAGNASCO D'ASTI");
        this.put("A557", "BAGNATICA");
        this.put("A558", "BAGNI DELLA PORRETTA");
        this.put("A558", "PORRETTA");
        this.put("A558", "PORRETTA TERME");
        this.put("A559", "BAGNI DI CASCIANA");
        this.put("A559", "CASCIANA TERME");
        this.put("A560", "BAGNI DI LUCCA");
        this.put("A560", "BAGNO A CORSENA");
        this.put("A561", "BAGNI DI MONTECATINI");
        this.put("A561", "MONTECATINI TERME");
        this.put("A562", "BAGNI SAN GIULIANO");
        this.put("A562", "SAN GIULIANO TERME");
        this.put("A563", "BAGNO");
        this.put("A564", "BAGNO A RIPOLI");
        this.put("A565", "BAGNO DI ROMAGNA");
        this.put("A566", "BAGNOLI");
        this.put("A566", "BAGNOLI IRPINO");
        this.put("A567", "BAGNOLI");
        this.put("A567", "BAGNOLI DEL TRIGNO");
        this.put("A568", "BAGNOLI");
        this.put("A568", "BAGNOLI DI SOPRA");
        this.put("A569", "BAGNOLO");
        this.put("A569", "BAGNOLO MELLA");
        this.put("A570", "BAGNOLO");
        this.put("A570", "BAGNOLO CREMASCO");
        this.put("A571", "BAGNOLO");
        this.put("A571", "BAGNOLO PIEMONTE");
        this.put("A572", "BAGNOLO");
        this.put("A572", "BAGNOLO DEL SALENTO");
        this.put("A573", "BAGNOLO");
        this.put("A573", "BAGNOLO IN PIANO");
        this.put("A574", "BAGNOLO");
        this.put("A574", "BAGNOLO DI PO");
        this.put("A575", "BAGNOLO SAN VITO");
        this.put("A576", "BAGNONE");
        this.put("A577", "BAGNOREA");
        this.put("A577", "BAGNOREGIO");
        this.put("A578", "BAGOLINO");
        this.put("A579", "BAIA E LATINA");
        this.put("A580", "BAIANO");
        this.put("A581", "BAIARDO");
        this.put("A582", "BAIEDO");
        this.put("A583", "BAIO");
        this.put("A583", "BAIO DORA");
        this.put("A584", "BAIRO");
        this.put("A585", "BAIRO TORRE");
        this.put("A585", "BAIRO TORRE");
        this.put("A586", "BAISO");
        this.put("A587", "BALANGERO");
        this.put("A588", "BALDICHIERI D'ASTI");
        this.put("A589", "BALDISSERO");
        this.put("A589", "BALDISSERO D'ALBA");
        this.put("A590", "BALDISSERO");
        this.put("A590", "BALDISSERO CANAVESE");
        this.put("A591", "BALDISSERO");
        this.put("A591", "BALDISSERO TORINESE");
        this.put("A592", "BALESTRATE");
        this.put("A593", "BALESTRINO");
        this.put("A594", "BALLABIO");
        this.put("A594", "BALLABIO");
        this.put("A595", "BALLABIO INFERIORE");
        this.put("A596", "BALLABIO SUPERIORE");
        this.put("A597", "BALLAO");
        this.put("A598", "BOSCO");
        this.put("A598", "BOSCO DI GAVIRATE");
        this.put("A598", "BALLARATE");
        this.put("A599", "BALME");
        this.put("A600", "BALMUCCIA");
        this.put("A601", "BALOCCO");
        this.put("A602", "BALSAMO");
        this.put("A603", "BALSORANO");
        this.put("A604", "BALVANO");
        this.put("A605", "BALZOLA");
        this.put("A606", "BANARI");
        this.put("A607", "BANCHETTE");
        this.put("A608", "BANCO");
        this.put("A609", "BANNARI");
        this.put("A609", "BANNARI DI USELLUS");
        this.put("A609", "VILLA VERDE");
        this.put("A609", "VILLA VERDE");
        this.put("A610", "BANNIO");
        this.put("A610", "BANNIO ANZINO");
        this.put("A610", "BANNIO ANZINO");
        this.put("A611", "BANTINE");
        this.put("A612", "BANZI");
        this.put("A613", "BAONE");
        this.put("A614", "BARADILI");
        this.put("A614", "BARADILI");
        this.put("A615", "BARAGIANO");
        this.put("A616", "BARANELLO");
        this.put("A617", "BARANO");
        this.put("A617", "BARANO D'ISCHIA");
        this.put("A618", "BARANZATE");
        this.put("A618", "BARANZATE");
        this.put("A619", "BARASSO");
        this.put("A620", "BARATE");
        this.put("A621", "BARATILI");
        this.put("A621", "BARATILI SAN PIETRO");
        this.put("A621", "BARATILI SAN PIETRO");
        this.put("A622", "BARATONIA");
        this.put("A623", "BARBAIANA");
        this.put("A624", "BARBANA D'ISTRIA");
        this.put("A625", "BARBANIA");
        this.put("A626", "BARBARA");
        this.put("A627", "BARBARANO");
        this.put("A627", "BARBARANO VICENTINO");
        this.put("A628", "BARBARANO");
        this.put("A628", "BARBARANO ROMANO");
        this.put("A629", "BARBARESCO");
        this.put("A630", "BARBARIGA");
        this.put("A631", "BARBATA");
        this.put("A632", "BARBERINO DI MUGELLO");
        this.put("A633", "BARBERINO VAL D'ELSA");
        this.put("A634", "BARBIANELLO");
        this.put("A635", "BARBIANO * BARBIAN");
        this.put("A636", "BARBISELLE");
        this.put("A637", "BARBONA");
        this.put("A638", "BARCELLONA POZZO DI GOTTO");
        this.put("A639", "BARCHI");
        this.put("A640", "BARCIS");
        this.put("A641", "BARCO");
        this.put("A642", "BARCONE");
        this.put("A643", "BARD");
        this.put("A644", "BARDASSANO");
        this.put("A645", "BARDELLO");
        this.put("A646", "BARDI");
        this.put("A647", "BARDINETO");
        this.put("A648", "BARDINO NUOVO");
        this.put("A649", "BARDINO VECCHIO");
        this.put("A650", "BARDOLINO");
        this.put("A651", "BARDONECCHIA");
        this.put("A652", "BAREGGIO");
        this.put("A653", "BARENGO");
        this.put("A654", "BARESI");
        this.put("A655", "BARESSA");
        this.put("A655", "BARESSA");
        this.put("A656", "BARETE");
        this.put("A657", "BARGA");
        this.put("A658", "BARGAGLI");
        this.put("A659", "BARGANO");
        this.put("A660", "BARGE");
        this.put("A661", "BARGHE");
        this.put("A662", "BARI");
        this.put("A662", "BARI DELLE PUGLIE");
        this.put("A663", "BARI");
        this.put("A663", "BARI SARDO");
        this.put("A663", "BARI SARDO");
        this.put("A664", "BARIANO");
        this.put("A665", "BARICELLA");
        this.put("A666", "BARILE");
        this.put("A667", "BARISCIANO");
        this.put("A668", "BARLASSINA");
        this.put("A668", "BARLASSINA");
        this.put("A669", "BARLETTA");
        this.put("A669", "BARLETTA");
        this.put("A670", "BARNI");
        this.put("A671", "BAROLO");
        this.put("A672", "BARONA");
        this.put("A673", "BARONE CANAVESE");
        this.put("A674", "BARONISSI");
        this.put("A675", "BARRA");
        this.put("A676", "BARRAFRANCA");
        this.put("A677", "BARRALI");
        this.put("A678", "BARREA");
        this.put("A679", "BARZIZZA");
        this.put("A680", "BARTESATE");
        this.put("A681", "BARUMINI");
        this.put("A681", "BARUMINI");
        this.put("A682", "BARZA");
        this.put("A683", "BARZAGO");
        this.put("A683", "BARZAGO");
        this.put("A684", "BARZANA");
        this.put("A685", "BARZANIGA");
        this.put("A686", "BARZANO'");
        this.put("A686", "BARZANO'");
        this.put("A687", "BARZIO");
        this.put("A687", "BARZIO");
        this.put("A688", "BARZOLA");
        this.put("A689", "BASALUZZO");
        this.put("A690", "BASCAPE'");
        this.put("A691", "BASCHI");
        this.put("A692", "BASCIANO");
        this.put("A693", "BASELGA");
        this.put("A693", "BASELGA DI VEZZANO");
        this.put("A694", "BASELGA DI PINE'");
        this.put("A695", "BASELICA BOLOGNA");
        this.put("A696", "BASELICE");
        this.put("A697", "BASIANO");
        this.put("A698", "BASICO'");
        this.put("A698", "CASALNUOVO");
        this.put("A699", "BASIGLIO");
        this.put("A700", "BASILIANO");
        this.put("A700", "PASIAN SCHIAVONESCO");
        this.put("A701", "BASSANELLO");
        this.put("A701", "VASANELLO");
        this.put("A702", "BASSANO");
        this.put("A702", "BASSANO BRESCIANO");
        this.put("A703", "BASSANO");
        this.put("A703", "BASSANO DEL GRAPPA");
        this.put("A704", "BASSANO DI SUTRI");
        this.put("A704", "BASSANO ROMANO");
        this.put("A705", "BASSANO DI TRONZANO");
        this.put("A705", "TRONZANO");
        this.put("A705", "TRONZANO LAGO MAGGIORE");
        this.put("A706", "BASSANO IN TEVERINA");
        this.put("A707", "BASSIANO");
        this.put("A708", "BASSIGNANA");
        this.put("A709", "BASTIA");
        this.put("A709", "BASTIA MONDOVI'");
        this.put("A710", "BASTIA UMBRA");
        this.put("A711", "BASTIDA DE' DOSSI");
        this.put("A712", "BASTIDA PANCARANA");
        this.put("A713", "BASTIGLIA");
        this.put("A714", "BATTAGLIA");
        this.put("A714", "BATTAGLIA TERME");
        this.put("A715", "BATTAGLIA DELLA BAINSIZZA");
        this.put("A716", "BATTIFOLLO");
        this.put("A717", "BATTIPAGLIA");
        this.put("A718", "BATTUDA");
        this.put("A719", "BAUCINA");
        this.put("A720", "BAUCO");
        this.put("A720", "BOVILLE ERNICA");
        this.put("A721", "BAULADU");
        this.put("A721", "BAULADU");
        this.put("A722", "BAUNEI");
        this.put("A722", "BAUNEI");
        this.put("A723", "BAUSO");
        this.put("A724", "BAVARI");
        this.put("A725", "BAVENO");
        this.put("A725", "BAVENO");
        this.put("A726", "BAZZANO");
        this.put("A727", "BEAULARD");
        this.put("A728", "BEDERO VALCUVIA");
        this.put("A729", "BEDIZZOLE");
        this.put("A730", "BEDOLLO");
        this.put("A731", "BEDONIA");
        this.put("A732", "BEDULITA");
        this.put("A733", "BEE");
        this.put("A733", "BEE");
        this.put("A734", "BEINASCO");
        this.put("A735", "BEINETTE");
        this.put("A736", "BELCASTRO");
        this.put("A737", "BELFIORE");
        this.put("A737", "BELFIORE DI PORCILE");
        this.put("A738", "BELFORTE");
        this.put("A738", "BELFORTE MONFERRATO");
        this.put("A739", "BELFORTE");
        this.put("A739", "BELFORTE DEL CHIENTI");
        this.put("A739", "BELFORTE DEL CHIENTO");
        this.put("A740", "BELFORTE");
        this.put("A740", "BELFORTE ALL'ISAURO");
        this.put("A741", "BELGIOIOSO");
        this.put("A742", "BELGIRATE");
        this.put("A742", "BELGIRATE");
        this.put("A743", "BELLA");
        this.put("A744", "BELLAGIO");
        this.put("A745", "BELLANO");
        this.put("A745", "BELLANO");
        this.put("A746", "BELLANTE");
        this.put("A747", "BELLARIA-IGEA MARINA");
        this.put("A747", "BELLARIA-IGEA MARINA");
        this.put("A748", "BELLEDO");
        this.put("A749", "BELLEGRA");
        this.put("A749", "CIVITELLA");
        this.put("A749", "CIVITELLA SAN SISTO");
        this.put("A750", "BELLINO");
        this.put("A751", "BELLINZAGO LOMBARDO");
        this.put("A751", "BELLINZAGO");
        this.put("A752", "BELLINZAGO");
        this.put("A752", "BELLINZAGO NOVARESE");
        this.put("A753", "BELLIZZI");
        this.put("A753", "BELLIZZI IRPINO");
        this.put("A754", "BELLOMBRA");
        this.put("A755", "BELLONA");
        this.put("A756", "BELLOSGUARDO");
        this.put("A757", "BELLUNO");
        this.put("A758", "BELLUNO VERONESE");
        this.put("A759", "BELLUSCO");
        this.put("A759", "BELLUSCO");
        this.put("A760", "BELMONTE");
        this.put("A760", "BELMONTE PICENO");
        this.put("A760", "BELMONTE PICENO");
        this.put("A761", "BELMONTE");
        this.put("A761", "BELMONTE DEL SANNIO");
        this.put("A762", "BELMONTE");
        this.put("A762", "BELMONTE CALABRO");
        this.put("A763", "BELMONTE");
        this.put("A763", "BELMONTE CASTELLO");
        this.put("A764", "BELMONTE");
        this.put("A764", "BELMONTE MEZZAGNO");
        this.put("A765", "BELMONTE");
        this.put("A765", "BELMONTE IN SABINA");
        this.put("A766", "BELPASSO");
        this.put("A767", "BEL PRATO");
        this.put("A767", "PRATO");
        this.put("A768", "BELSITO");
        this.put("A769", "BELVEDERE");
        this.put("A769", "BELVEDERE OSTRENSE");
        this.put("A770", "BELVEDERE");
        this.put("A770", "BELVEGLIO");
        this.put("A771", "BELVEDERE");
        this.put("A771", "LIZZANO IN BELVEDERE");
        this.put("A772", "BELVEDERE");
        this.put("A772", "BELVEDERE DI SPINELLO");
        this.put("A772", "BELVEDERE DI SPINELLO");
        this.put("A773", "BELVEDERE");
        this.put("A773", "BELVEDERE MARITTIMO");
        this.put("A774", "BELVEDERE");
        this.put("A774", "BELVEDERE LANGHE");
        this.put("A775", "BELVEDERE");
        this.put("A775", "BELVEDERE AL PO");
        this.put("A776", "BELVI");
        this.put("A777", "BEMA");
        this.put("A778", "BENE");
        this.put("A778", "BENE LARIO");
        this.put("A779", "BENE");
        this.put("A779", "BENE VAGIENNA");
        this.put("A780", "BENESTARE");
        this.put("A781", "BENETUTTI");
        this.put("A782", "BENEVELLO");
        this.put("A783", "BENEVENTO");
        this.put("A784", "BENNA");
        this.put("A784", "BENNA");
        this.put("A785", "BENTIVOGLIO");
        this.put("A785", "SANTA MARIA IN DUNO");
        this.put("A786", "BERBENNO");
        this.put("A787", "BERBENNO");
        this.put("A787", "BERBENNO DI VALTELLINA");
        this.put("A788", "BERCETO");
        this.put("A789", "BERCHIDDA");
        this.put("A789", "BERCHIDDA");
        this.put("A790", "BERDO SAN GIOVANNI");
        this.put("A791", "BEREGAZZO");
        this.put("A791", "BEREGAZZO CON FIGLIARO");
        this.put("A792", "BEREGUARDO");
        this.put("A793", "BERGAMASCO");
        this.put("A794", "BERGAMO");
        this.put("A795", "BERGANTINO");
        this.put("A796", "BERGEGGI");
        this.put("A797", "BERGOGNA");
        this.put("A798", "BERGOLO");
        this.put("A799", "BERLINGO");
        this.put("A800", "BERNAGA");
        this.put("A801", "BERNALDA");
        this.put("A802", "BERNAREGGIO");
        this.put("A802", "BERNAREGGIO");
        this.put("A803", "BERNATE");
        this.put("A803", "BERNATE DI COMO");
        this.put("A803", "BERNATE ROSALES");
        this.put("A804", "BERNATE");
        this.put("A804", "BERNATE TICINO");
        this.put("A805", "BERNEZZO");
        this.put("A806", "BERRA");
        this.put("A807", "BERSEZIO");
        this.put("A808", "BERSONE");
        this.put("A809", "BERTINORO");
        this.put("A810", "BERTIOLO");
        this.put("A811", "BERTONICO");
        this.put("A811", "BERTONICO");
        this.put("A812", "BERZANO");
        this.put("A812", "BERZANO DI SAN PIETRO");
        this.put("A813", "BERZANO");
        this.put("A813", "BERZANO DI TORTONA");
        this.put("A815", "BERZO");
        this.put("A815", "BERZO SAN FERMO");
        this.put("A816", "BERZO DEMO");
        this.put("A817", "BERZO INFERIORE");
        this.put("A818", "BESANA");
        this.put("A818", "BESANA IN BRIANZA");
        this.put("A818", "BESANA IN BRIANZA");
        this.put("A819", "BESANO");
        this.put("A820", "BESATE");
        this.put("A821", "BESENELLO");
        this.put("A822", "BESENO");
        this.put("A822", "BESENO");
        this.put("A823", "BESENZONE");
        this.put("A824", "BERSEZIO DEL QUARNARO");
        this.put("A825", "BESNATE");
        this.put("A826", "BESOZZO");
        this.put("A827", "BESSUDE");
        this.put("A828", "BESTAGNO");
        this.put("A829", "BESTAZZO");
        this.put("A830", "BETTENESCO");
        this.put("A831", "BETTOLA");
        this.put("A831", "BORGONURE");
        this.put("A832", "BETTONA");
        this.put("A833", "BEURA");
        this.put("A834", "BEURA-CARDEZZA");
        this.put("A834", "BEURA-CARDEZZA");
        this.put("A835", "BEVAGNA");
        this.put("A836", "BEVERINO");
        this.put("A837", "BEVILACQUA");
        this.put("A838", "BEVILACQUA BOSCHI");
        this.put("A838", "BEVILACQUA BOSCHI");
        this.put("A839", "BEZZECCA");
        this.put("A840", "BIACESA");
        this.put("A841", "BIANCAVILLA");
        this.put("A842", "BIANCHI");
        this.put("A843", "BIANCO");
        this.put("A844", "BIANDRATE");
        this.put("A845", "BIANDRONNO");
        this.put("A846", "BIANZANO");
        this.put("A846", "BIANZANO");
        this.put("A847", "BIANZE'");
        this.put("A848", "BIANZONE");
        this.put("A849", "BIASSONO");
        this.put("A849", "BIASSONO");
        this.put("A850", "BIBBIANO");
        this.put("A851", "BIBBIENA");
        this.put("A852", "BIBBONA");
        this.put("A853", "BIBIANA");
        this.put("A854", "BICCARI");
        this.put("A855", "BICINICCO");
        this.put("A856", "BIDONI'");
        this.put("A856", "BIDONI'");
        this.put("A857", "BIEDA");
        this.put("A857", "BLERA");
        this.put("A858", "BIEGNO");
        this.put("A859", "BIELLA");
        this.put("A859", "BIELLA");
        this.put("A860", "BIENATE");
        this.put("A861", "BIENNO");
        this.put("A862", "BIENO");
        this.put("A863", "BIENO");
        this.put("A864", "BIENTINA");
        this.put("A865", "BIESTRO");
        this.put("A866", "BIGARELLO");
        this.put("A867", "BIGLIA");
        this.put("A868", "BIGLIANA");
        this.put("A869", "BIGLIO");
        this.put("A870", "BINAGO");
        this.put("A871", "BINANUOVA");
        this.put("A872", "BINASCO");
        this.put("A873", "BINDO");
        this.put("A874", "BINETTO");
        this.put("A875", "BINZAGO");
        this.put("A876", "BIOGLIO");
        this.put("A876", "BIOGLIO");
        this.put("A877", "BIONA");
        this.put("A877", "BIONAZ");
        this.put("A878", "BIONE");
        this.put("A879", "BIRAGO");
        this.put("A880", "BIRORI");
        this.put("A881", "BISACCIA");
        this.put("A882", "BISACQUINO");
        this.put("A883", "BISCEGLIE");
        this.put("A883", "BISCEGLIE");
        this.put("A884", "BISEGNA");
        this.put("A885", "BISENTI");
        this.put("A886", "BISENTRATE");
        this.put("A887", "BISIGNANO");
        this.put("A888", "BISIO");
        this.put("A889", "BISTAGNO");
        this.put("A890", "BISTERZA");
        this.put("A891", "BISUSCHIO");
        this.put("A892", "BITETTO");
        this.put("A893", "BITONTO");
        this.put("A894", "BITRITTO");
        this.put("A895", "BITTI");
        this.put("A896", "BIVONA");
        this.put("A897", "BIVONGI");
        this.put("A898", "BIZZARONE");
        this.put("A899", "BIZZOZERO");
        this.put("A900", "BLEGGIO");
        this.put("A900", "BLEGGIO");
        this.put("A901", "BLEGGIO INFERIORE");
        this.put("A902", "BLEGGIO SUPERIORE");
        this.put("A903", "BLELLO");
        this.put("A904", "BLESSAGNO");
        this.put("A905", "BLEVIO");
        this.put("A906", "BOARA");
        this.put("A906", "BOARA PISANI");
        this.put("A907", "BOARA");
        this.put("A907", "BOARA POLESINE");
        this.put("A908", "BOBBIATE");
        this.put("A909", "BOBBIO");
        this.put("A910", "BOBBIO PELLICE");
        this.put("A910", "PELLICE");
        this.put("A911", "BOCA");
        this.put("A912", "BOCCHIGLIERO");
        this.put("A913", "BOCCHIGNANO");
        this.put("A914", "BOCCIOLETO");
        this.put("A915", "BOCCOLO DEI TASSI");
        this.put("A915", "BOCCOLO DEI TASSI");
        this.put("A915", "BOCCOLO DEI TASSI");
        this.put("A915", "BOCCOLO DEI TASSI");
        this.put("A916", "BOCENAGO");
        this.put("A917", "BODIO");
        this.put("A918", "BODIO LOMNAGO");
        this.put("A918", "LOMNAGO");
        this.put("A919", "BOFFALORA D'ADDA");
        this.put("A919", "BOFFALORA");
        this.put("A919", "BOFFALORA D'ADDA");
        this.put("A920", "BOFFALORA");
        this.put("A920", "BOFFALORA SOPRA TICINO");
        this.put("A921", "BOFFETTO");
        this.put("A922", "BOGLIASCO");
        this.put("A923", "BOGLIASCO PIEVE");
        this.put("A923", "BOGLIASCO PIEVE");
        this.put("A924", "BOGLIUNO");
        this.put("A925", "BOGNANCO");
        this.put("A925", "BOGNANCO");
        this.put("A926", "BOGNANCO DENTRO");
        this.put("A927", "BOGNANCO FUORI");
        this.put("A928", "BOGNO");
        this.put("A929", "BOGOGNO");
        this.put("A930", "BOIANO");
        this.put("A931", "BOISSANO");
        this.put("A931", "BOISSANO");
        this.put("A932", "BOLANO");
        this.put("A933", "BOLBENO");
        this.put("A934", "BOLDINASCO");
        this.put("A935", "BOLENTINA");
        this.put("A936", "BOLETO");
        this.put("A937", "BOLGARE");
        this.put("A938", "BOLGIANO");
        this.put("A939", "BOLLADELLO");
        this.put("A940", "BOLLATE");
        this.put("A941", "BOLLENGO");
        this.put("A942", "BOLLITA");
        this.put("A942", "NOVA SIRI");
        this.put("A943", "BOLLONE");
        this.put("A944", "BOLOGNA");
        this.put("A945", "BOLOGNANO");
        this.put("A946", "BOLOGNETTA");
        this.put("A946", "OGLIASTRO");
        this.put("A946", "SANTA MARIA DI OGLIASTRO");
        this.put("A947", "BOLOGNOLA");
        this.put("A948", "BOLOTANA");
        this.put("A949", "BOLSENA");
        this.put("A950", "BOLTIERE");
        this.put("A951", "BOLZANETO");
        this.put("A952", "BOLZANO * BOZEN");
        this.put("A953", "BOLZANO");
        this.put("A953", "BOLZANO NOVARESE");
        this.put("A954", "BOLZANO");
        this.put("A954", "BOLZANO VICENTINO");
        this.put("A955", "BOMARZO");
        this.put("A956", "BOMBA");
        this.put("A957", "BOMPENSIERE");
        this.put("A958", "BOMPIETRO");
        this.put("A958", "BUOMPIETRO");
        this.put("A959", "BOMPORTO");
        this.put("A960", "BONARCADO");
        this.put("A960", "BONARCADO");
        this.put("A961", "BONASSOLA");
        this.put("A962", "BONATE SOTTO");
        this.put("A963", "BONATE SOPRA");
        this.put("A964", "BONAVIGO");
        this.put("A965", "BONDENO");
        this.put("A966", "BONDIONE");
        this.put("A967", "BONDO");
        this.put("A968", "BONDONE");
        this.put("A969", "BONDO PETELLO");
        this.put("A970", "BONEA");
        this.put("A971", "BONEFRO");
        this.put("A972", "BONEMERSE");
        this.put("A973", "BONIFATI");
        this.put("A974", "BONIROLA");
        this.put("A975", "BONITO");
        this.put("A976", "BONNANARO");
        this.put("A977", "BONO");
        this.put("A978", "BONORVA");
        this.put("A979", "BONVICINO");
        this.put("A980", "BONZO");
        this.put("A981", "BORBONA");
        this.put("A982", "BORCA");
        this.put("A982", "BORCA DI CADORE");
        this.put("A983", "BORDANO");
        this.put("A984", "BORDIGHERA");
        this.put("A985", "BORDOGNA");
        this.put("A986", "BORDOLANO");
        this.put("A987", "BORE");
        this.put("A987", "METTI E POZZOLO");
        this.put("A988", "BORETTO");
        this.put("A989", "BORGARELLO");
        this.put("A989", "BORGARELLO");
        this.put("A990", "BORGARO TORINESE");
        this.put("A991", "BORGETTO");
        this.put("A992", "BORGHETTO");
        this.put("A992", "BORGHETTO DI VARA");
        this.put("A993", "BORGHETTO");
        this.put("A993", "BORGHETTO D'ARROSCIA");
        this.put("A994", "BORGHETTO");
        this.put("A994", "BORGHETTO SAN NICOLO'");
        this.put("A995", "BORGHETTO LODIGIANO");
        this.put("A995", "BORGHETTO");
        this.put("A995", "BORGHETTO LODIGIANO");
        this.put("A996", "BORGHETTO");
        this.put("A996", "BORGO VELINO");
        this.put("A997", "BORGHETTO");
        this.put("A998", "BORGHETTO DI BORBERA");
        this.put("A999", "BORGHETTO SANTO SPIRITO");
    }

    public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }

}
